'use client';
import {FormEvent,useEffect,useState} from 'react';
import {runnerJson} from './runner-client';
type Row={assertion_id:string;ccn:string;chain:{publisher_chain_id:string|null;id_state:string;name:string|null;name_state:string;reported_facility_count_raw:string|null;reported_facility_count:number|null;count_state:string};observation:{publisher_processing_date_raw:string;observed_at:string|null;recovery_created_at:string|null};lineage:{source_id:string;source_release_sha256:string;source_row:number;source_record_id:string;selected_assertion_sha256:string|null};reconciliation:null|{retained_member_assertion_rows:number;publisher_reported_facility_counts:number[];name_variant_count:number;status:string};flags:string[]};
type View={filters:{publisher_chain_id:string|null;ccn:string|null};page:{offset:number;limit:number;total_matching_assertion_rows:number;next_offset:number|null};rows:Row[];conservation:{retained_assertion_rows:number;rows_missing_chain_id:number;rows_unresolved_chain_id:number;all_source_rows_preserved:boolean};semantics:{claim_boundary:string}};
export default function CmsNursingHomeChainReview(){
 const[chainInput,setChainInput]=useState(''),[ccnInput,setCcnInput]=useState(''),[filters,setFilters]=useState({chainId:'',ccn:''}),[offset,setOffset]=useState(0),[result,setResult]=useState<{key:string;value:View}|null>(null),[failure,setFailure]=useState<{key:string;message:string}|null>(null);const requestKey=JSON.stringify([filters,offset]);const view=result?.key===requestKey?result.value:null,error=failure?.key===requestKey?failure.message:'';
 useEffect(()=>{const controller=new AbortController(),params=new URLSearchParams({offset:String(offset),limit:'50'});if(filters.chainId)params.set('chain_id',filters.chainId);if(filters.ccn)params.set('ccn',filters.ccn);void runnerJson<View>(`/api/local-review/cms-nursing-home-chains?${params}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted){setResult({key:requestKey,value});setFailure(null);}}).catch(reason=>{if(!controller.signal.aborted&&reason?.name!=='AbortError')setFailure({key:requestKey,message:reason instanceof Error?reason.message:'Chain assertions are unavailable.'});});return()=>controller.abort();},[filters,offset,requestKey]);
 function submit(event:FormEvent){event.preventDefault();if(chainInput&&!/^\d{1,64}$/.test(chainInput)||ccnInput&&!/^[A-Za-z0-9]{6}$/.test(ccnInput)){setFailure({key:requestKey,message:'Use a 1–64 digit publisher chain ID and/or an exact six-character CCN.'});return;}setOffset(0);setFilters({chainId:chainInput,ccn:ccnInput});}
 return <section className="operations-builder" aria-labelledby="nursing-chain-review-title"><h3 id="nursing-chain-review-title">Nursing-home chain assertions · local review</h3><p className="operations-note">Publisher-reported shared ownership, officers, or management is not proof of legal parenthood, network identity, a unique business, a physical site, or current operation. No export or download is available.</p><form className="operations-options" onSubmit={submit}><label>Opaque publisher chain ID <input value={chainInput} maxLength={64} inputMode="numeric" onChange={event=>setChainInput(event.target.value)}/></label><label>Exact CCN <input value={ccnInput} maxLength={6} onChange={event=>setCcnInput(event.target.value)}/></label><button type="submit" className="ghost-button">Review assertions</button></form>{!view&&!error&&<p role="status">Verifying the fixed retained release…</p>}{error&&<p role="alert">{error}</p>}{view&&<><p className="operations-note">{view.page.total_matching_assertion_rows.toLocaleString()} matching assertion rows · {view.conservation.retained_assertion_rows.toLocaleString()} retained in all, including {view.conservation.rows_missing_chain_id.toLocaleString()} missing and {view.conservation.rows_unresolved_chain_id.toLocaleString()} unresolved chain IDs.</p><div className="business-name-list">{view.rows.map(row=><article key={row.assertion_id}><div><strong>{row.chain.name??'Chain name missing'}</strong><span>Chain ID {row.chain.publisher_chain_id??`not available (${row.chain.id_state})`} · CCN {row.ccn}</span><span>Publisher count {row.chain.reported_facility_count_raw??`not available (${row.chain.count_state})`} · reconciliation {row.reconciliation?.status??'not applicable without a resolved chain ID'}</span><small>Processing date {row.observation.publisher_processing_date_raw||'not supplied'} · observed {row.observation.observed_at??'not supplied'} · source row {row.lineage.source_row} · source release {row.lineage.source_release_sha256.slice(0,12)}…</small><small>Assertion {row.assertion_id.slice(0,12)}… · source record {row.lineage.source_record_id} · selected evidence {row.lineage.selected_assertion_sha256?.slice(0,12)??'not supplied'}…</small><small>{row.flags.length?`Flags: ${row.flags.join(', ')}`:'No row reconciliation flags'} · publisher chain ID remains opaque</small></div></article>)}</div><div className="operations-actions"><button type="button" className="ghost-button" disabled={view.page.offset===0} onClick={()=>setOffset(Math.max(0,view.page.offset-view.page.limit))}>Previous</button><button type="button" className="ghost-button" disabled={view.page.next_offset===null} onClick={()=>setOffset(view.page.next_offset??0)}>Next</button></div></>}</section>;
}
