'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { runnerJson } from './runner-client';
type View = { available: true; release: { release_id: string; manifest_sha256: string; artifact_sha256: string; created_at: string }; census_polygon_completeness: { complete_for_declared_layers_and_vintages: boolean; coordinate_reference_system: string; generalized_geometry: boolean; nation_polygon_products: number; state_equivalents: number; states_and_district_of_columbia: number; county_equivalents: number; zcta_2020_polygons: number }; temporal_vintage: { aligned: boolean; state_and_county_vintage: string; zcta_vintage: string; limitation: string }; overlay_diagnostics: { zctas_complete_within_tolerance: number; zctas_partial_or_overlapping: number; zctas_unmatched: number; counties_without_zcta_intersection: number; zctas_materially_crossing_state_boundaries: number; zctas_materially_crossing_county_boundaries: number }; usps_operational_denominator: { complete: boolean; verified: boolean; registry_zip5_keys: number; unverified_registry_zip5_keys: number; same_code_census_zcta: number; source_reported_without_same_code_zcta: number; denominator_only_without_same_code_zcta: number; explicit_00000_placeholder_count: number; limitation: string }; zip4: { stored_separately_from_zip5: boolean; geometric: boolean; limitation: string }; claim_boundaries: Record<string, boolean>; execution: { network_requests: number; production_pointer_changes: boolean; current_pointer_present: boolean; read_only: boolean } };
const endpoint = '/api/data-operations/national-geography-goal-status';
export default function NationalGeographyGoalStatus() {
  const [view, setView] = useState<View | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const sequence = useRef(0); const active = useRef<AbortController | null>(null);
  const load = useCallback(async () => { active.current?.abort(); const controller = new AbortController(); active.current = controller; const current = ++sequence.current; try { const result = await runnerJson<View>(endpoint, { signal: controller.signal }); if (controller.signal.aborted || current !== sequence.current) return; setView(result); setError(false); } catch { if (!controller.signal.aborted && current === sequence.current) { setView(null); setError(true); } } finally { if (!controller.signal.aborted && current === sequence.current) setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => { window.clearTimeout(timer); sequence.current += 1; active.current?.abort(); }; }, [load]);
  return <section className="operations-builder" aria-labelledby="national-geography-goal-title"><h3 id="national-geography-goal-title">National geography goal status</h3><p className="operations-note">Verified aggregate-only geography status. Each measure has its own scope; there is no overall completion percentage.</p><button type="button" className="ghost-button" onClick={() => { setView(null); setError(false); setLoading(true); void load(); }}>Recheck retained geography status</button>
    {loading && <p role="status">Independently verifying retained geography, overlay, and ZIP summary evidence…</p>}{error && <p role="alert">The national geography goal status is unavailable or failed verification. No cached details or actions are available.</p>}
    {view && <><article className="operation-record"><h4>Census polygon completeness</h4><p>{`${view.census_polygon_completeness.nation_polygon_products} nation products · ${view.census_polygon_completeness.state_equivalents} state equivalents (${view.census_polygon_completeness.states_and_district_of_columbia} states/DC) · ${view.census_polygon_completeness.county_equivalents} county equivalents · ${view.census_polygon_completeness.zcta_2020_polygons} 2020 ZCTA polygons`}</p><p>{view.census_polygon_completeness.coordinate_reference_system} generalized geometry; complete only for the declared layers and vintages.</p></article>
      <article className="operation-record"><h4>Temporal vintage mismatch</h4><p>{`${view.temporal_vintage.state_and_county_vintage} states/counties · ${view.temporal_vintage.zcta_vintage} ZCTAs · aligned: ${view.temporal_vintage.aligned ? 'yes' : 'no'}`}</p></article>
      <article className="operation-record"><h4>Overlay diagnostics</h4><p>{`${view.overlay_diagnostics.zctas_complete_within_tolerance} within tolerance · ${view.overlay_diagnostics.zctas_partial_or_overlapping} partial/overlapping · ${view.overlay_diagnostics.counties_without_zcta_intersection} counties with no ZCTA intersection · ${view.overlay_diagnostics.zctas_materially_crossing_state_boundaries} materially cross-state · ${view.overlay_diagnostics.zctas_materially_crossing_county_boundaries} materially cross-county`}</p></article>
      <article className="operation-record"><h4>USPS operational denominator — incomplete and unverified</h4><p>{`${view.usps_operational_denominator.registry_zip5_keys} registry ZIP5 keys · ${view.usps_operational_denominator.unverified_registry_zip5_keys} unverified · ${view.usps_operational_denominator.same_code_census_zcta} same-code ZCTA · ${view.usps_operational_denominator.source_reported_without_same_code_zcta} source-reported without same-code ZCTA · ${view.usps_operational_denominator.denominator_only_without_same_code_zcta} denominator-only without same-code ZCTA · ${view.usps_operational_denominator.explicit_00000_placeholder_count} explicit 00000 placeholder`}</p></article>
      <article className="operation-record"><h4>ZIP+4 boundary</h4><p>{`${view.zip4.limitation} Stored separately: ${view.zip4.stored_separately_from_zip5 ? 'yes' : 'no'} · geometric: ${view.zip4.geometric ? 'yes' : 'no'}.`}</p></article>
      <details><summary>Verified immutable lineage</summary><dl><dt>Release</dt><dd>{view.release.release_id}</dd><dt>Manifest SHA-256</dt><dd><code>{view.release.manifest_sha256}</code></dd><dt>Artifact SHA-256</dt><dd><code>{view.release.artifact_sha256}</code></dd></dl><p>No network requests, current pointer, production pointer change, record rows, ZIP lists, or execution control.</p></details></>}
  </section>;
}
