'use client';
import { useEffect, useRef, useState } from 'react';
import { runnerJson } from './runner-client';
type View={available:true;release:{release_id:string};industry:{label:string;taxonomy_code:string;taxonomy_system:'NUCC'};coverage:{accepted_organization_rows:number;reported_address_count:number;positive_zip5_rows:number;zero_count_denominator_rows:number;state_dc_rows:number;territory_rows:number;unassigned_rows:number};supplementary_secondary_addresses:{rows:number;distinct_npis:number;distinct_zip5:number;secondary_only_zip5:number;additive_to_primary_counts:false;row_publication:false};inclusion:{generic_business_totals:false;generic_category_totals:false;production_enrollment:false;status:string}};
const endpoint='/api/data-operations/national-pharmacy-industry-coverage-status';
export default function NationalPharmacyIndustryCoverageStatus(){
  const[view,setView]=useState<View|null>(null),[error,setError]=useState(false);const sequence=useRef(0);
  useEffect(()=>{const controller=new AbortController(),current=++sequence.current;void runnerJson<View>(endpoint,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted&&current===sequence.current){setView(result);setError(false)}}).catch(()=>{if(!controller.signal.aborted&&current===sequence.current){setView(null);setError(true)}});return()=>{controller.abort();sequence.current+=1}},[]);
  return <section className="operations-builder" aria-label="National pharmacy industry coverage status"><h3>National pharmacy industry coverage</h3>{error?<p role="alert">Verified pharmacy coverage is unavailable. No cached evidence or action is shown.</p>:!view?<p role="status">Verifying retained pharmacy aggregates…</p>:<><p className="operations-note"><strong>{view.industry.label}</strong> · {view.industry.taxonomy_system} taxonomy {view.industry.taxonomy_code} · release {view.release.release_id}.</p><dl><dt>Retained organization rows</dt><dd>{view.coverage.accepted_organization_rows.toLocaleString()}</dd><dt>Reported primary addresses</dt><dd>{view.coverage.reported_address_count.toLocaleString()}</dd><dt>ZIP5 with positive evidence</dt><dd>{view.coverage.positive_zip5_rows.toLocaleString()}</dd><dt>ZIP5 denominator-only rows</dt><dd>{view.coverage.zero_count_denominator_rows.toLocaleString()}</dd><dt>State and D.C. rows</dt><dd>{view.coverage.state_dc_rows.toLocaleString()}</dd><dt>Territory rows</dt><dd>{view.coverage.territory_rows.toLocaleString()}</dd><dt>Unassigned rows</dt><dd>{view.coverage.unassigned_rows.toLocaleString()}</dd></dl><article className="operation-record"><h4>Excluded, non-additive coverage</h4><p>Secondary reported addresses: {view.supplementary_secondary_addresses.rows.toLocaleString()} rows across {view.supplementary_secondary_addresses.distinct_npis.toLocaleString()} NPIs and {view.supplementary_secondary_addresses.distinct_zip5.toLocaleString()} ZIP5 values; {view.supplementary_secondary_addresses.secondary_only_zip5.toLocaleString()} ZIP5 values are secondary-only.</p><p>Not added to primary pharmacy counts, generic business totals, generic category totals, or production enrollment. Aggregate local review only; no current-operation, physical-site, unique-business, licensed-pharmacy, or nationwide-completeness claim.</p></article></>}</section>
}
