"use client";

import { useEffect, useState } from "react";
import { runnerJson } from "./runner-client";

type View={schema_version:"non-zcta-source-geography-context-summary-view@1.0.0";status:"retained-nonblocking-context";summary:{rows:14402;source_contributed_outside_zcta:14361;denominator_only_outside_zcta:41;relationship_keys:8871;no_relationship_keys:5531;one_reported_code_keys:8673;multiple_reported_code_keys:198;one_code_census_state_dc_keys:8456;one_code_census_territory_keys:126;one_code_outside_census_roster_keys:91;point_keys:336;point_profile_rows:441;point_agreement_keys:335;point_conflict_keys:1};release:{release_id:string;manifest_sha256:string;summary_sha256:string};claims:{zip_to_state_assignment:false;cardinal_or_central_grouping:null;polygon:null;centroid:null;usps_class:null;usps_validity:null;park_status:null;tribal_or_native_status:null;private_land_status:null;population:null;business_completeness:null;map_blocked:false;heatmap_integration:false;state_denominator_integration:false;network_requests:0;current_pointer_written:false;production_enrollment:false}};
const hash=(value:unknown)=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value);
export function validNonZctaGeographyStatus(input:unknown):input is View{if(!input||typeof input!=='object'||Array.isArray(input))return false;const value=input as View,summary=value.summary,release=value.release,claims=value.claims;return Object.keys(value).sort().join('|')==='claims|release|schema_version|status|summary'&&value.schema_version==='non-zcta-source-geography-context-summary-view@1.0.0'&&value.status==='retained-nonblocking-context'&&!!summary&&JSON.stringify(summary)===JSON.stringify({rows:14402,source_contributed_outside_zcta:14361,denominator_only_outside_zcta:41,relationship_keys:8871,no_relationship_keys:5531,one_reported_code_keys:8673,multiple_reported_code_keys:198,one_code_census_state_dc_keys:8456,one_code_census_territory_keys:126,one_code_outside_census_roster_keys:91,point_keys:336,point_profile_rows:441,point_agreement_keys:335,point_conflict_keys:1})&&!!release&&/^non-zcta-source-geography-context-[a-f0-9]{64}$/.test(release.release_id)&&hash(release.manifest_sha256)&&hash(release.summary_sha256)&&!!claims&&JSON.stringify(claims)===JSON.stringify({zip_to_state_assignment:false,cardinal_or_central_grouping:null,polygon:null,centroid:null,usps_class:null,usps_validity:null,park_status:null,tribal_or_native_status:null,private_land_status:null,population:null,business_completeness:null,map_blocked:false,heatmap_integration:false,state_denominator_integration:false,network_requests:0,current_pointer_written:false,production_enrollment:false});}
export default function NonZctaGeographyStatus(){const[view,setView]=useState<View|null>(null),[error,setError]=useState(false);useEffect(()=>{const controller=new AbortController();void runnerJson<unknown>('/api/business-map/non-zcta-source-geography-summary',{signal:controller.signal}).then(value=>{if(controller.signal.aborted)return;if(!validNonZctaGeographyStatus(value))throw Error('invalid');setView(value)}).catch(()=>{if(!controller.signal.aborted)setError(true)});return()=>controller.abort()},[]);return <section className="supporting-evidence" aria-label="Non-ZCTA special ZIP context"><strong>Special and unresolved ZIP context</strong>{error?<p role="status">Retained special-ZIP context is unavailable. This does not block the state/ZCTA map.</p>:!view?<p role="status">Loading retained special-ZIP context…</p>:<><p><strong>{view.summary.rows.toLocaleString()}</strong> ZIP5 keys sit outside the selected Census ZCTA overlay. Retained business profiles provide source-reported location context for <strong>{view.summary.relationship_keys.toLocaleString()}</strong>; <strong>{view.summary.no_relationship_keys.toLocaleString()}</strong> remain without profile context.</p><p className="operations-note">These may include private or organization-specific ZIPs and other non-ZCTA cases. Co*Tive does not infer park, Native/tribal, private-property, population, state, polygon, centroid, or cardinal-region status from absence. They are excluded from state denominators and never block the map or industry reporting.</p></>}</section>}
