'use client';

import {useState} from 'react';
import {runnerJson} from './runner-client';

export type RetainedBusinessRefreshPlan={planId:string;sourceId:string;mode:string;status:'HOLD';allocationCount:0;networkRequestCount:0;operationCreated:false;steps:string[];unresolvedGates:string[]};
export type RetainedBusinessRefreshStatus={sourceId:'co-business-registry'|'ct-business-registry'|'de-business-licenses'|'fl-business-registry'|'pa-business-registry';state:string;label:string;readinessStatus:'HOLD';dispatchAvailable:false;freshAcquisitionAuthorized:false;autonomousAcquisitionAuthorized:false;productionPointerChangeAuthorized:false;retainedRelease:{releaseId:string;sourceReleaseId:string;sourceObservedAt:string;metrics:Array<{label:string;value:number}>;artifactCount:number};observedAssessment:{assessmentId:string;observedAt:string;decision:string;retainedReleaseId:string;catalogRetainedReleaseMatchesAssessment:boolean;currentRetainedReleaseMatchesAssessment:boolean};plan:RetainedBusinessRefreshPlan;nextAction:string};

export default function RetainedBusinessRefreshStatusCard({status}:{status?:RetainedBusinessRefreshStatus}){
  const [plan,setPlan]=useState<RetainedBusinessRefreshPlan|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false); if(!status)return null;
  const preview=async()=>{setBusy(true);setError('');try{setPlan(await runnerJson<RetainedBusinessRefreshPlan>('/api/data-operations/source-refresh-plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceId:status.sourceId})}));}catch(reason){setError(reason instanceof Error?reason.message:`${status.state} refresh plan is unavailable.`);}finally{setBusy(false);}};
  return <section className="operations-builder" aria-labelledby={`${status.state.toLowerCase()}-business-refresh-title`}><h3 id={`${status.state.toLowerCase()}-business-refresh-title`}>{status.label}</h3><p className="operations-note">Read-only readiness for a governed retained full-snapshot source. Registration or license evidence is not proof of current operation or a verified physical site.</p><p role="status"><strong>Refresh {status.readinessStatus}</strong> · retained source observed {status.retainedRelease.sourceObservedAt.slice(0,10)} · {status.retainedRelease.metrics[1]?.value.toLocaleString()} retained records</p><dl>{status.retainedRelease.metrics.map(metric=><div key={metric.label}><dt>{metric.label}</dt><dd>{metric.value.toLocaleString()}</dd></div>)}<dt>Fresh acquisition</dt><dd>Not authorized</dd><dt>Production pointer change</dt><dd>Not authorized</dd><dt>Assessment</dt><dd>{status.observedAssessment.assessmentId}</dd></dl><div className="operations-actions"><button className="ghost-button" disabled={busy} onClick={()=>void preview()}>Preview refresh plan</button><button className="primary-button" disabled aria-disabled="true" title="ACQUISITION_NOT_AUTHORIZED">Start {status.state} refresh</button></div>{error&&<p role="alert" className="operations-error">{error}</p>}{plan&&<div className="operations-plan" aria-live="polite"><strong>{plan.status} · no operation created</strong><p className="operations-note">{plan.networkRequestCount} network requests · {plan.allocationCount} allocations</p><ol>{plan.steps.map(step=><li key={step}>{step}</li>)}</ol><p className="operations-note">Open gates: {plan.unresolvedGates.join(', ')}</p></div>}<p className="operations-note">{status.nextAction}</p></section>;
}
