'use client';

import {useEffect, useState} from 'react';
import {runnerJson} from './runner-client';
import CensusZbpIndustryHeatmap from './census-zbp-industry-heatmap';
import CensusNonemployerCountyHeatmap from './census-nonemployer-county-heatmap';
import {StateAvailabilityChoropleth} from './business-intelligence';

export const workspaceTabs = ['Coverage', 'Industries', 'ZIP Economy', 'Jobs', 'Collection', 'Evidence', 'Connectors'] as const;
export type WorkspaceTab = typeof workspaceTabs[number];
export function WorkspaceTabs({value,onChange}:{value:WorkspaceTab;onChange:(value:WorkspaceTab)=>void}) {
  return <div className="workspace-tabs" role="tablist" aria-label="Collector workspaces">{workspaceTabs.map((name,index)=><button key={name} id={`workspace-tab-${index}`} role="tab" aria-selected={value===name} aria-controls="workspace-panel" tabIndex={value===name?0:-1} onClick={()=>onChange(name)} onKeyDown={event=>{const next=event.key==='Home'?0:event.key==='End'?workspaceTabs.length-1:event.key==='ArrowRight'?(index+1)%workspaceTabs.length:event.key==='ArrowLeft'?(index+workspaceTabs.length-1)%workspaceTabs.length:null;if(next!==null){event.preventDefault();onChange(workspaceTabs[next]);document.getElementById(`workspace-tab-${next}`)?.focus();}}}>{name}</button>)}</div>;
}

type MatrixRow={code:string;name:string;available:number;measured:number;unmeasured:number;denominator:number;percent:number|null;measurement_status:string;broad_layer_gap:boolean};
type Matrix={available:boolean;status:string;release_id:string|null;denominator?:{version:string};categories?:string[];jurisdictions:MatrixRow[];selected:null|{code:string;category:{datasets:Array<{dataset_id:string;label:string;availability_status:string;state_record_count:number|null;gap_reason:string|null}>}}};
type Shares={available:boolean;categories:Array<{id:string;label:string}>;national_category_counts:Record<string,number>;national_category_percent_of_collected_evidence:Record<string,number|null>;states:Array<{postal_abbreviation:string;state_name:string;category_counts:Record<string,number>;percent_of_category_nationwide:Record<string,number|null>}>};
const percent=(value:number|null|undefined)=>value==null?'Unmeasured':`${value.toFixed(1)}%`;
const count=(value:number|null|undefined)=>value==null?'Unmeasured':value.toLocaleString();
const CATEGORY_LABELS:Record<string,string>={
  'general-business':'Broad state organization layer',
  'retail-consumer':'Retail and consumer',
  'health-care':'Health care',
  'financial-services':'Financial services',
  'tax-exempt-organizations':'Tax-exempt organizations',
  'regulated-meat-poultry-egg-establishments':'Regulated meat, poultry and egg establishments',
  'cross-industry-regulated-facilities':'Cross-industry regulated facilities',
  transportation:'Transportation',
};
const categoryLabel=(id:string)=>CATEGORY_LABELS[id]??id.replaceAll('-',' ');

export function CoverageWorkspace({industries=false}:{industries?:boolean}) {
  const [category,setCategory]=useState('general-business'),[state,setState]=useState(''),[view,setView]=useState<Matrix|null>(null),[shares,setShares]=useState<Shares|null>(null),[error,setError]=useState('');
  function chooseState(value:string){setState(value);setError('');}
  function chooseCategory(value:string){setCategory(value);setView(null);setError('');}
  useEffect(()=>{const controller=new AbortController();const query=new URLSearchParams({category});if(state)query.set('state',state);void runnerJson<Matrix>(`/api/business-map/goal-completion?${query}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setView(value);}).catch(()=>{if(!controller.signal.aborted)setError('Verified coverage evidence is unavailable. No older result or zero is substituted.');});return()=>controller.abort();},[state,category]);
  useEffect(()=>{if(!industries)return;const controller=new AbortController();void runnerJson<Shares>('/api/business-map/state-summary?include_territories=false',{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setShares(value);}).catch(()=>{if(!controller.signal.aborted)setShares(null);});return()=>controller.abort();},[industries]);
  const selected=view?.jurisdictions?.find(row=>row.code===state);
  const selectedCategoryLabel=categoryLabel(category);
  return <section className="panel focused-workspace"><h2>{industries?'Industries':'Coverage'}</h2><p>Governed dataset availability — not completeness of all businesses. Availability is available ÷ measured datasets; unmeasured members remain separately visible.</p>
    <label>{industries?'Reporting industry':'Coverage category'} <select aria-label={industries?'Reporting industry':'Coverage category'} value={category} onChange={event=>chooseCategory(event.target.value)}>{(view?.categories??[category]).map(id=><option key={id} value={id}>{categoryLabel(id)}</option>)}</select></label>
    {error&&<p role="alert">{error}</p>}{!view&&!error&&<p role="status">Verifying local coverage…</p>}{view&&!view.available&&<p role="status">{view.status.replaceAll('-',' ')}. Completion is unmeasured.</p>}
    {view?.available&&<><div className="coverage-focus-layout"><div><h3>50 states and D.C. · {selectedCategoryLabel} availability</h3><StateAvailabilityChoropleth rows={view.jurisdictions} selected={state} categoryLabel={selectedCategoryLabel} onSelect={chooseState}/><details><summary>Accessible state tiles — same values as the map</summary><p>Alphabetical state tiles, not geographic polygons. Select a tile or use the state list. Text values are the same evidence as the colors.</p><div className="coverage-state-tiles">{view.jurisdictions.map(row=><button key={row.code} aria-pressed={state===row.code} aria-label={`${row.name}, ${selectedCategoryLabel}: ${percent(row.percent)}, ${row.available} of ${row.measured} measured, ${row.unmeasured} unmeasured`} onClick={()=>chooseState(row.code)} style={{backgroundColor:row.percent===null?'#263241':`hsl(${190+(row.percent/100)*35} 45% ${20+(row.percent/100)*20}%)`}}><strong>{row.code}</strong><span>{percent(row.percent)}</span><small>{row.available}/{row.measured} measured</small><small>{row.unmeasured} unmeasured</small></button>)}</div></details></div>
      <aside className="coverage-selected" aria-label="Selected state summary"><h3>Selected state</h3><p><strong>Scope:</strong> {selectedCategoryLabel}</p><label>State <select aria-label="Coverage state" value={state} onChange={event=>chooseState(event.target.value)}><option value="">Choose a state</option>{view.jurisdictions.map(row=><option key={row.code} value={row.code}>{row.name}</option>)}</select></label>{selected?<><h4>{selected.name}</h4><p><strong>{percent(selected.percent)}</strong> {selectedCategoryLabel} dataset availability</p><p>{selected.available} available / {selected.measured} measured · {selected.unmeasured} unmeasured / {selected.denominator} expected.</p><p>Broad state organization layer: {selected.broad_layer_gap?'Gap':'Available'}. All-business completeness: Unknown.</p><ul>{view.selected?.code===state&&view.selected.category.datasets.map(row=><li key={row.dataset_id}><strong>{row.label}</strong>: {row.availability_status.replaceAll('-',' ')} · {count(row.state_record_count)} state records{row.gap_reason&&` · ${row.gap_reason}`}</li>)}</ul></>:<p>Select a state to see measured availability, missing evidence and source counts here.</p>}</aside></div><p className="entity-method-note">Selected reporting scope: {selectedCategoryLabel}. Versioned denominator: {view.denominator?.version}. Release: {view.release_id}. A measured zero is not an unmeasured value; 100% availability applies only to the selected category and does not establish complete industry or business collection.</p></>}
    {industries&&<><h3>National and state industry evidence shares</h3><p>These source-category shares are separate from dataset availability above. Categories may overlap; they are not GDP allocations or shares of all businesses.</p>{shares?.available?<div className="representation-table"><table><thead><tr><th>Source category</th><th>National evidence rows</th><th>Share of all collected national category evidence</th><th>{state||'Selected state'} evidence rows</th><th>State share of this category nationwide</th></tr></thead><tbody>{shares.categories.map(row=>{const local=shares.states.find(item=>item.postal_abbreviation===state);return <tr key={row.id}><th>{row.label}</th><td>{count(shares.national_category_counts[row.id])}</td><td>{percent(shares.national_category_percent_of_collected_evidence[row.id])}</td><td>{count(local?.category_counts[row.id])}</td><td>{percent(local?.percent_of_category_nationwide[row.id])}</td></tr>;})}</tbody></table><p>Scope: 50 states and D.C.; only evidence with the governed state assignment. Ambiguous/unmatched geography is excluded. Null denominators remain unmeasured.</p></div>:<p>National share evidence is unavailable or loading; no percentage is inferred.</p>}<details><summary>Census employer industry aggregates</summary><CensusZbpIndustryHeatmap/></details><details><summary>Census nonemployer county industry aggregates</summary><CensusNonemployerCountyHeatmap/></details></>}
  </section>;
}

type ZipEvidence={zip5:string;evidence_status:string;governed_zcta:{status:string;geoid:string|null};counts:null|{physical_sites:number;establishments:number;employer_establishments:number|null};bindings:Record<string,string|null>};
export function ZipEconomyWorkspace(){
  const [input,setInput]=useState(''),[zip,setZip]=useState(''),[view,setView]=useState<ZipEvidence|null>(null),[error,setError]=useState(''),[dimension,setDimension]=useState('Race');
  useEffect(()=>{if(!zip)return;const controller=new AbortController();void runnerJson<ZipEvidence>(`/api/business-map/zip-inspector?zip=${zip}&category=all`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted&&value.zip5===zip)setView(value);}).catch(()=>{if(!controller.signal.aborted)setError('Exact ZIP evidence is unavailable. No estimates were substituted.');});return()=>controller.abort();},[zip]);
  return <section className="panel focused-workspace"><h2>ZIP Economy</h2><p>Look up retained ZIP evidence. Source-reported ZIP5 and Census ZCTA polygons are different geographies; ZIP+4 is not a polygon.</p><form onSubmit={event=>{event.preventDefault();if(/^\d{5}$/.test(input)){setError('');if(input!==zip){setView(null);setZip(input);}}else setError('Enter exactly five ZIP digits, including leading zeros.');}}><label>ZIP5 <input aria-label="Economy ZIP5" inputMode="numeric" maxLength={5} value={input} onChange={event=>setInput(event.target.value)}/></label><button type="submit">View ZIP</button></form>{error&&<p role="alert">{error}</p>}{zip&&!view&&!error&&<p role="status">Loading {zip}…</p>}{view&&<div><h3>ZIP {view.zip5}</h3><p>Observed evidence status: {view.evidence_status.replaceAll('-',' ')}. Same-code ZCTA: {view.governed_zcta.geoid??'Not evidenced'}.</p><dl><dt>Observed physical-site evidence</dt><dd>{count(view.counts?.physical_sites)}</dd><dt>Provisional establishments</dt><dd>{count(view.counts?.establishments)}</dd><dt>Published Census employer baseline</dt><dd>{count(view.counts?.employer_establishments)}</dd></dl><details><summary>Evidence releases</summary>{Object.entries(view.bindings).map(([key,value])=><p key={key}>{key.replaceAll('_',' ')}: {value??'Unavailable'}</p>)}</details></div>}
    <div className="economy-evidence-grid"><article><h3>Total extrapolated ZIP GDP</h3><strong>Unavailable — no governed model</strong><p>Existing BEA current-dollar GDP estimates are joined only to exact state/county GEOIDs. The current contract explicitly prohibits ZIP/ZCTA allocation. No ZIP GDP total is computed here.</p></article><article><h3>Business-segment GDP allocations</h3><strong>Unavailable — no governed allocation</strong><p>Industry evidence counts and Census establishments are not output or GDP weights. No segment allocation or false precision is inferred.</p></article></div>
    <h3>Demographic views</h3><label>Demographic dimension <select aria-label="Demographic dimension" value={dimension} onChange={event=>setDimension(event.target.value)}>{['Race','Lineage / ancestry','Sex','Age'].map(value=><option key={value}>{value}</option>)}</select></label><p><strong>{dimension}: unavailable in the current ZIP economy contract.</strong> No demographic population breakdown or demographic GDP estimate is fabricated. Population/housing context in the Evidence map is not a substitute for these dimensions.</p><p className="entity-method-note">Observed source records, published statistical estimates and modeled allocations are distinct. This view performs no acquisition and publishes no economic model.</p>
  </section>;
}
