'use client';

import {useEffect, useState} from 'react';
import {runnerJson} from './runner-client';
import CensusZbpIndustryHeatmap from './census-zbp-industry-heatmap';
import CensusNonemployerCountyHeatmap from './census-nonemployer-county-heatmap';
import {StateAvailabilityChoropleth} from './business-intelligence';
import {RetainedCountyWorkspace} from './retained-county-panel';

export const workspaceTabs = ['Coverage', 'Industries', 'ZIP Economy', 'Jobs', 'Collection', 'Evidence', 'Connectors'] as const;
export type WorkspaceTab = typeof workspaceTabs[number];
export function WorkspaceTabs({value,onChange}:{value:WorkspaceTab;onChange:(value:WorkspaceTab)=>void}) {
  return <div className="workspace-tabs" role="tablist" aria-label="Collector workspaces">{workspaceTabs.map((name,index)=><button key={name} id={`workspace-tab-${index}`} role="tab" aria-selected={value===name} aria-controls="workspace-panel" tabIndex={value===name?0:-1} onClick={()=>onChange(name)} onKeyDown={event=>{const next=event.key==='Home'?0:event.key==='End'?workspaceTabs.length-1:event.key==='ArrowRight'?(index+1)%workspaceTabs.length:event.key==='ArrowLeft'?(index+workspaceTabs.length-1)%workspaceTabs.length:null;if(next!==null){event.preventDefault();onChange(workspaceTabs[next]);document.getElementById(`workspace-tab-${next}`)?.focus();}}}>{name}</button>)}</div>;
}

type MatrixRow={code:string;name:string;available:number;measured:number;unmeasured:number;denominator:number;percent:number|null;measurement_status:string;broad_layer_gap:boolean};
type ScopeComparison={available:boolean;denominator_version:string|null;configuration:null|{path:string;version:number;sha256:string};catalog:null|{path:string;schema_version:string;denominator_version:string;predecessor_sha256:string};industries:null|Array<{id:string;sources:Array<{id:string;scope:string;publisher_states:string[]|'all';manual_selection_required:boolean}>}>};
type Matrix={available:boolean;status:string;release_id:string|null;denominator?:{version:string};categories?:string[];scope_comparison?:ScopeComparison;jurisdictions:MatrixRow[];selected:null|{code:string;category:{datasets:Array<{dataset_id:string;label:string;availability_status:string;state_record_count:number|null;gap_reason:string|null}>}}};
type Shares={available:boolean;categories:Array<{id:string;label:string}>;national_category_counts:Record<string,number>;national_category_percent_of_collected_evidence:Record<string,number|null>;states:Array<{postal_abbreviation:string;state_name:string;category_counts:Record<string,number>;percent_of_category_nationwide:Record<string,number|null>}>};
const percent=(value:number|null|undefined)=>value==null?'Unmeasured':`${value.toFixed(1)}%`;
const count=(value:number|null|undefined)=>value==null?'Unmeasured':value.toLocaleString();
const CATEGORY_LABELS:Record<string,string>={
  'general-business':'Broad state organization layer',
  'retail-consumer':'Retail and consumer',
  'health-care':'Health care',
  'financial-services':'Financial services',
  'tax-exempt-organizations':'Tax-exempt organizations',
  'regulated-meat-poultry-egg-establishments':'Regulated meat, poultry and egg establishments',
  'cross-industry-regulated-facilities':'Cross-industry regulated facilities',
  transportation:'Transportation',
};
const categoryLabel=(id:string)=>CATEGORY_LABELS[id]??id.replaceAll('-',' ');

export function OutsideNationalReporting({comparison}:{comparison?:ScopeComparison}) {
  const ready=comparison?.available&&comparison.configuration&&comparison.catalog&&Array.isArray(comparison.industries);
  return <section aria-label="Outside national reporting denominator"><h3>Outside national reporting denominator</h3>
    <p>Configured industries below are excluded from the national reporting denominator. State-only configuration is not evidence of acquisition or nationwide coverage. Expected, measured and unmeasured matrix totals above are unchanged; no completeness percentage is inferred.</p>
    {!ready?<p role="status">Scope comparison unavailable. Missing or unverified inputs are not an empty gap list or zero coverage.</p>:<>
      <p>Compared denominator: {comparison.denominator_version}.</p>
      {comparison.industries!.length?<div className="representation-table" role="region" aria-label="Excluded configured industry sources" tabIndex={0}><table><caption>Configuration only — not acquired records or measured coverage</caption><thead><tr><th scope="col">Configured industry</th><th scope="col">Source configuration</th><th scope="col">Publisher scope</th></tr></thead><tbody>{comparison.industries!.flatMap(industry=>industry.sources.map(source=><tr key={`${industry.id}:${source.id}`}><th scope="row">{categoryLabel(industry.id)}</th><td>{source.id}{source.manual_selection_required&&' · manual selection required'}</td><td>{source.scope==='state'?`State-only: ${Array.isArray(source.publisher_states)?source.publisher_states.join(', '):'Unknown'}`:'National configuration only'}</td></tr>))}</tbody></table></div>:<p>No excluded configured industry groups were found in this validated comparison. This is not a completeness claim.</p>}
      <details><summary>Scope comparison identities</summary><p>Configuration: {comparison.configuration!.path} · version {comparison.configuration!.version}</p><p>Configuration SHA-256: <code style={{overflowWrap:'anywhere'}}>{comparison.configuration!.sha256}</code></p><p>Catalog: {comparison.catalog!.path} · {comparison.catalog!.schema_version} · {comparison.catalog!.denominator_version}</p><p>Validated base catalog SHA-256: <code style={{overflowWrap:'anywhere'}}>{comparison.catalog!.predecessor_sha256}</code></p></details>
    </>}
  </section>;
}

export function summarizeAvailability(rows:MatrixRow[]){
  const available=rows.reduce((sum,row)=>sum+row.available,0),measured=rows.reduce((sum,row)=>sum+row.measured,0),expected=rows.reduce((sum,row)=>sum+row.denominator,0),unmeasured=rows.reduce((sum,row)=>sum+row.unmeasured,0),connected=rows.filter(row=>row.available>0).length;
  return {available,measured,expected,unmeasured,connected,jurisdictions:rows.length,availabilityPercent:measured?available/measured*100:null,connectivityPercent:rows.length?connected/rows.length*100:null};
}

export function CoverageWorkspace({industries=false,stateCode,categoryCode,onStateChange,onCategoryChange,onNavigate}:{industries?:boolean;stateCode?:string;categoryCode?:string;onStateChange?:(code:string)=>void;onCategoryChange?:(code:string)=>void;onNavigate?:(tab:WorkspaceTab)=>void}) {
  const [localCategory,setCategory]=useState('general-business'),[localState,setState]=useState(''),[view,setView]=useState<Matrix|null>(null),[shares,setShares]=useState<Shares|null>(null),[error,setError]=useState('');
  const category=categoryCode??localCategory;
  const state=stateCode??localState;
  function chooseState(value:string){setState(value);onStateChange?.(value);setError('');}
  function chooseCategory(value:string){setCategory(value);onCategoryChange?.(value);setView(null);setError('');}
  useEffect(()=>{const controller=new AbortController();const query=new URLSearchParams({category});if(state)query.set('state',state);void runnerJson<Matrix>(`/api/business-map/goal-completion?${query}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setView(value);}).catch(()=>{if(!controller.signal.aborted){setView(null);setError('Verified coverage evidence is unavailable. No older result or zero is substituted.');}});return()=>controller.abort();},[state,category]);
  useEffect(()=>{if(!industries)return;const controller=new AbortController();void runnerJson<Shares>('/api/business-map/state-summary?include_territories=false',{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setShares(value);}).catch(()=>{if(!controller.signal.aborted)setShares(null);});return()=>controller.abort();},[industries]);
  const selected=view?.jurisdictions?.find(row=>row.code===state);
  const selectedCategoryLabel=categoryLabel(category);
  const national=view?.available?summarizeAvailability(view.jurisdictions):null;
  return <section className="panel focused-workspace"><h2>{industries?'Industries':'Coverage'}</h2><p>Governed dataset availability — not completeness of all businesses. Availability is available ÷ measured datasets; unmeasured members remain separately visible.</p>
    <label>{industries?'Reporting industry':'Coverage category'} <select aria-label={industries?'Reporting industry':'Coverage category'} value={category} onChange={event=>chooseCategory(event.target.value)}>{(view?.categories??[category]).map(id=><option key={id} value={id}>{categoryLabel(id)}</option>)}</select></label>
    {error&&<p role="alert">{error}</p>}{!view&&!error&&<p role="status">Verifying local coverage…</p>}{view&&!view.available&&<p role="status">{view.status.replaceAll('-',' ')}. Completion is unmeasured.</p>}
    {national&&<><div className="coverage-national-metrics" aria-label="National dataset expectations"><article><span>Expected dataset × state cells</span><strong>{count(national.expected)}</strong><small>Version {view?.denominator?.version}</small></article><article><span>Available / measured cells</span><strong>{count(national.available)} / {count(national.measured)}</strong><small>{percent(national.availabilityPercent)} of measured cells · not business completeness</small></article><article><span>Unmeasured expected cells</span><strong>{count(national.unmeasured)}</strong><small>Unknown, not zero and not omitted from expectations</small></article><article><span>States/DC with positive dataset evidence</span><strong>{national.connected} / {national.jurisdictions}</strong><small>{percent(national.connectivityPercent)} of listed jurisdictions · at least one available dataset, not full industry coverage</small></article></div><p>National expectation counts sum the selected reporting category across listed states/DC. They count dataset–state relationships, not distinct datasets, businesses, or GDP.</p></>}
    {onNavigate&&<div className="workspace-path"><span>{state?`Selected state: ${state}`:'Select a state on the map'}</span><button onClick={()=>onNavigate(industries?'Coverage':'Industries')}>{industries?'View state coverage':'View industry summary'}</button><button onClick={()=>onNavigate('ZIP Economy')}>Explore ZIP economy</button></div>}
    {view?.available&&<><div className="coverage-focus-layout"><div><h3>50 states and D.C. · {selectedCategoryLabel} availability</h3><StateAvailabilityChoropleth rows={view.jurisdictions} selected={state} categoryLabel={selectedCategoryLabel} onSelect={chooseState}/><details><summary>Accessible state tiles — same values as the map</summary><p>Alphabetical state tiles, not geographic polygons. Select a tile or use the state list. Text values are the same evidence as the colors.</p><div className="coverage-state-tiles">{view.jurisdictions.map(row=><button key={row.code} aria-pressed={state===row.code} aria-label={`${row.name}, ${selectedCategoryLabel}: ${percent(row.percent)}, ${row.available} of ${row.measured} measured, ${row.unmeasured} unmeasured`} onClick={()=>chooseState(row.code)} style={{backgroundColor:row.percent===null?'#263241':`hsl(${190+(row.percent/100)*35} 45% ${20+(row.percent/100)*20}%)`}}><strong>{row.code}</strong><span>{percent(row.percent)}</span><small>{row.available}/{row.measured} measured</small><small>{row.unmeasured} unmeasured</small></button>)}</div></details></div>
      <aside className="coverage-selected" aria-label="Selected state summary"><h3>Selected state</h3><p><strong>Scope:</strong> {selectedCategoryLabel}</p><label>State <select aria-label="Coverage state" value={state} onChange={event=>chooseState(event.target.value)}><option value="">Choose a state</option>{view.jurisdictions.map(row=><option key={row.code} value={row.code}>{row.name}</option>)}</select></label>{selected?<><h4>{selected.name}</h4><p><strong>{percent(selected.percent)}</strong> {selectedCategoryLabel} dataset availability</p><p>{selected.available} available / {selected.measured} measured · {selected.unmeasured} unmeasured / {selected.denominator} expected.</p><p>Broad state organization layer: {selected.broad_layer_gap?'Gap':'Available'}. All-business completeness: Unknown.</p><ul>{view.selected?.code===state&&view.selected.category.datasets.map(row=><li key={row.dataset_id}><strong>{row.label}</strong>: {row.availability_status.replaceAll('-',' ')} · {count(row.state_record_count)} state records{row.gap_reason&&` · ${row.gap_reason}`}</li>)}</ul></>:<p>Select a state to see measured availability, missing evidence and source counts here.</p>}</aside></div><p className="entity-method-note">Selected reporting scope: {selectedCategoryLabel}. Versioned denominator: {view.denominator?.version}. Release: {view.release_id}. A measured zero is not an unmeasured value; 100% availability applies only to the selected category and does not establish complete industry or business collection.</p></>}
    {industries&&<><h3>National and state industry evidence shares</h3><p>These source-category shares are separate from dataset availability above. Categories may overlap; they are not GDP allocations or shares of all businesses.</p>{shares?.available?<div className="representation-table"><table><thead><tr><th>Source category</th><th>National evidence rows</th><th>Share of all collected national category evidence</th><th>{state||'Selected state'} evidence rows</th><th>State share of this category nationwide</th></tr></thead><tbody>{shares.categories.map(row=>{const local=shares.states.find(item=>item.postal_abbreviation===state);return <tr key={row.id}><th>{row.label}</th><td>{count(shares.national_category_counts[row.id])}</td><td>{percent(shares.national_category_percent_of_collected_evidence[row.id])}</td><td>{count(local?.category_counts[row.id])}</td><td>{percent(local?.percent_of_category_nationwide[row.id])}</td></tr>;})}</tbody></table><p>Scope: 50 states and D.C.; only evidence with the governed state assignment. Ambiguous/unmatched geography is excluded. Null denominators remain unmeasured.</p></div>:<p>National share evidence is unavailable or loading; no percentage is inferred.</p>}<details><summary>Census employer industry aggregates</summary><CensusZbpIndustryHeatmap/></details><details><summary>Census nonemployer county industry aggregates</summary><CensusNonemployerCountyHeatmap/></details></>}
    <OutsideNationalReporting comparison={view?.scope_comparison}/>
    <RetainedCountyWorkspace stateCode={state}/>
  </section>;
}

type ZipEvidence={zip5:string;evidence_status:string;governed_zcta:{status:string;geoid:string|null};counts:null|{physical_sites:number;establishments:number;employer_establishments:number|null};bindings:Record<string,string|null>;category_evidence?:{category_id:string;category_label:string;status:string;semantics:string;positive_source_contributions:Array<{source_id:string;source_release_id:string|null;positive_counts:Record<string,number>}>}};
const economyTabs=['Overview','Business segments','Demographics'] as const;
const segments=[['all','All source categories'],['retail-consumer','Retail and consumer'],['health-care','Health care'],['financial-services','Financial services'],['tax-exempt-organizations','Tax-exempt organizations'],['food-production','Food production'],['environmental-facilities','Environmental facilities'],['transportation','Transportation']];
export function ZipEconomyWorkspace({stateCode=''}:{stateCode?:string}={}){
  const [input,setInput]=useState(''),[zip,setZip]=useState(''),[view,setView]=useState<ZipEvidence|null>(null),[error,setError]=useState(''),[dimension,setDimension]=useState('Race'),[section,setSection]=useState<typeof economyTabs[number]>('Overview'),[segment,setSegment]=useState('all'),[attempt,setAttempt]=useState(0);
  const segmentName=segments.find(([id])=>id===segment)?.[1]??segment;
  useEffect(()=>{if(!zip)return;const controller=new AbortController();void runnerJson<ZipEvidence>(`/api/business-map/zip-inspector?zip=${zip}&category=${encodeURIComponent(segment)}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted&&value.zip5===zip&&value.category_evidence?.category_id===segment)setView(value);else if(!controller.signal.aborted)setError('Returned ZIP/category evidence did not match the requested scope.');}).catch(()=>{if(!controller.signal.aborted)setError('Exact ZIP evidence is unavailable. No estimates were substituted.');});return()=>controller.abort();},[zip,segment,attempt]);
  function changeSegment(value:string){setSegment(value);setView(null);setError('');}
  return <section className="panel focused-workspace"><h2>ZIP Economy</h2><p>Observed ZIP evidence and modeled-economy readiness in one place. Source-reported ZIP5 and Census ZCTA polygons are different geographies; ZIP+4 is not a polygon.</p>
    {stateCode&&<p>Navigation context: {stateCode}. A ZIP is not inferred from the selected state; enter an exact ZIP below.</p>}
    <form onSubmit={event=>{event.preventDefault();if(/^\d{5}$/.test(input)){setError('');setView(null);setZip(input);setAttempt(attempt+1);}else setError('Enter exactly five ZIP digits, including leading zeros.');}}><label>ZIP5 <input aria-label="Economy ZIP5" inputMode="numeric" maxLength={5} value={input} onChange={event=>setInput(event.target.value)}/></label><label>Business segment <select aria-label="Economy business segment" value={segment} onChange={event=>changeSegment(event.target.value)}>{segments.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button type="submit">{error&&zip?'Retry ZIP':'View ZIP'}</button></form>
    <p className="economy-context"><strong>{zip?`ZIP ${zip}`:'No ZIP selected'}</strong> · {segmentName} · observed evidence only; modeled GDP unavailable</p>
    <div className="workspace-tabs" role="tablist" aria-label="ZIP economy views">{economyTabs.map((name,index)=><button key={name} id={`economy-tab-${index}`} role="tab" aria-selected={section===name} aria-controls="economy-panel" tabIndex={section===name?0:-1} onClick={()=>setSection(name)} onKeyDown={event=>{const next=event.key==='Home'?0:event.key==='End'?2:event.key==='ArrowRight'?(index+1)%3:event.key==='ArrowLeft'?(index+2)%3:null;if(next!==null){event.preventDefault();setSection(economyTabs[next]);document.getElementById(`economy-tab-${next}`)?.focus();}}}>{name}</button>)}</div>
    {error&&<p role="alert">{error}</p>}{zip&&!view&&!error&&<p role="status">Loading {zip} · {segmentName}…</p>}
    <div id="economy-panel" role="tabpanel" aria-labelledby={`economy-tab-${economyTabs.indexOf(section)}`} tabIndex={0}>
    {section==='Overview'&&<><div className="economy-evidence-grid"><article><h3>Total extrapolated ZIP GDP</h3><strong>Unavailable — no governed model</strong><p>Existing BEA current-dollar GDP estimates are joined only to exact state/county GEOIDs. The current contract explicitly prohibits ZIP/ZCTA allocation. No ZIP GDP total is computed here.</p></article><article><h3>Business-segment GDP allocations</h3><strong>Unavailable — no governed allocation</strong><p>Industry evidence counts and Census establishments are not output or GDP weights. No segment allocation or false precision is inferred.</p></article></div>{view&&<><h3>Observed evidence · ZIP {view.zip5}</h3><p>{view.evidence_status.replaceAll('-',' ')}. Same-code ZCTA: {view.governed_zcta.geoid??'Not evidenced'}.</p><dl><dt>All-category physical-site evidence</dt><dd>{count(view.counts?.physical_sites)}</dd><dt>All-category provisional establishments</dt><dd>{count(view.counts?.establishments)}</dd><dt>Published Census employer baseline (statistical aggregate)</dt><dd>{count(view.counts?.employer_establishments)}</dd></dl><p>These baseline counts are not filtered by the business segment. Open Business segments for scoped source evidence.</p></>}</>}
    {section==='Business segments'&&<><h3>{segmentName} · ZIP {zip||'not selected'}</h3><p>Selected-segment extrapolated GDP: <strong>Unavailable</strong>. GDP share: <strong>Unmeasured</strong>. Observed source contributions below are not GDP allocations, additive business totals or a completeness percentage.</p>{view?.category_evidence?.status==='positive-source-contribution'?<div className="representation-table"><table><caption>Observed source evidence for the selected ZIP and segment</caption><thead><tr><th>Source / release</th><th>Source-defined count</th><th>Modeled GDP</th></tr></thead><tbody>{view.category_evidence.positive_source_contributions.flatMap(source=>Object.entries(source.positive_counts).map(([unit,value])=><tr key={`${source.source_id}:${unit}`}><th>{source.source_id}<small>{source.source_release_id??'Release unavailable'}</small></th><td>{count(value)} · {unit.replaceAll('_',' ')}</td><td>Unavailable</td></tr>))}</tbody></table></div>:<p>{zip?'No verified positive segment evidence available. This is not a measured zero.':'Enter a ZIP to inspect segment evidence.'}</p>}{view?.category_evidence&&<p>{view.category_evidence.semantics}</p>}</>}
    {section==='Demographics'&&<><h3>Demographic GDP cross-view</h3><label>Demographic dimension <select aria-label="Demographic dimension" value={dimension} onChange={event=>setDimension(event.target.value)}>{['Race','Lineage / ancestry','Sex','Age'].map(value=><option key={value}>{value}</option>)}</select></label><p><strong>{dimension}: unavailable in the current ZIP economy contract.</strong> No demographic population breakdown or demographic GDP estimate is fabricated. Population/housing context in the Evidence map is not a substitute for these dimensions.</p><div className="representation-table"><table><caption>{zip?`ZIP ${zip}`:'No ZIP selected'} × {segmentName} × {dimension}</caption><thead><tr><th>Required input / output</th><th>Value</th><th>Evidence class</th></tr></thead><tbody><tr><th>ZIP GDP baseline</th><td>Unavailable</td><td>No governed extrapolation model</td></tr><tr><th>{dimension} population weights</th><td>Unknown</td><td>No governed demographic input in this contract</td></tr><tr><th>Segment allocation weights</th><td>Unknown</td><td>No governed economic weighting</td></tr><tr><th>Extrapolated demographic GDP</th><td>Unavailable</td><td>Modeled output withheld; not observed</td></tr></tbody></table></div><p>No demographic categories or shares are inferred from names, addresses, establishment counts, or ancestry proxies. Missing inputs prevent modeling; they do not imply zero economic activity.</p></>}
    </div>
    {view&&<details><summary>Evidence releases</summary>{Object.entries(view.bindings).map(([key,value])=><p key={key}>{key.replaceAll('_',' ')}: {value??'Unavailable'}</p>)}</details>}
    <p className="entity-method-note">Observed source records, published statistical estimates and modeled allocations are distinct. This view performs no acquisition and publishes no economic model.</p>
  </section>;
}
