'use client';

import {useEffect, useState} from 'react';
import {runnerJson} from './runner-client';
import CensusZbpIndustryHeatmap from './census-zbp-industry-heatmap';
import CensusNonemployerCountyHeatmap from './census-nonemployer-county-heatmap';
import {StateAvailabilityChoropleth} from './business-intelligence';
import {RetainedCountyWorkspace} from './retained-county-panel';
import ZipEvidenceQualificationPanel from './zip-evidence-qualification-panel';
import type {QualificationView} from './zip-evidence-qualification-panel';
import CensusZbpZipProfile, {type CensusZbpZipProfileView} from './census-zbp-zip-profile';
import ZipSourceNativeStatus, {type SourceNativeStatusView} from './zip-source-native-status';

export const workspaceTabs = ['Coverage', 'Industries', 'ZIP Economy', 'Operations'] as const;
export type WorkspaceTab = typeof workspaceTabs[number];
export function WorkspaceTabs({value,onChange}:{value:WorkspaceTab;onChange:(value:WorkspaceTab)=>void}) {
  return <div className="workspace-tabs" role="tablist" aria-label="Collector workspaces">{workspaceTabs.map((name,index)=><button key={name} id={`workspace-tab-${index}`} role="tab" aria-selected={value===name} aria-controls="workspace-panel" tabIndex={value===name?0:-1} onClick={()=>onChange(name)} onKeyDown={event=>{const next=event.key==='Home'?0:event.key==='End'?workspaceTabs.length-1:event.key==='ArrowRight'?(index+1)%workspaceTabs.length:event.key==='ArrowLeft'?(index+workspaceTabs.length-1)%workspaceTabs.length:null;if(next!==null){event.preventDefault();onChange(workspaceTabs[next]);document.getElementById(`workspace-tab-${next}`)?.focus();}}}>{name}</button>)}</div>;
}

export const operationsTabs = ['Jobs', 'Collection', 'Evidence', 'Connectors'] as const;
export type OperationsTab = typeof operationsTabs[number];
export function OperationsTabs({value,onChange}:{value:OperationsTab;onChange:(value:OperationsTab)=>void}) {
  return <div className="workspace-tabs operations-tabs" role="tablist" aria-label="Operations views">{operationsTabs.map((name,index)=><button key={name} id={`operations-tab-${index}`} role="tab" aria-selected={value===name} aria-controls="operations-panel" tabIndex={value===name?0:-1} onClick={()=>onChange(name)} onKeyDown={event=>{const next=event.key==='Home'?0:event.key==='End'?operationsTabs.length-1:event.key==='ArrowRight'?(index+1)%operationsTabs.length:event.key==='ArrowLeft'?(index+operationsTabs.length-1)%operationsTabs.length:null;if(next!==null){event.preventDefault();onChange(operationsTabs[next]);document.getElementById(`operations-tab-${next}`)?.focus();}}}>{name}</button>)}</div>;
}

type MatrixRow={code:string;name:string;available:number;measured:number;unmeasured:number;denominator:number;percent:number|null;measurement_status:string;broad_layer_gap:boolean};
type ScopeComparison={available:boolean;denominator_version:string|null;configuration:null|{path:string;version:number;sha256:string};catalog:null|{path:string;schema_version:string;denominator_version:string;predecessor_sha256:string};industries:null|Array<{id:string;sources:Array<{id:string;scope:string;publisher_states:string[]|'all';manual_selection_required:boolean}>}>};
type AdjacentEvidence={dataset_id:string;evidence_kind:string;included_in_broad_layer:false;included_in_dataset_availability:false;release_id:string;source_release_id:string;source_date:string;state:string;row_semantics:string;organization_count:number;record_zcta_count:number;record_nonpolygon_count:number;limitations:string[]};
type Matrix={available:boolean;status:string;release_id:string|null;denominator?:{version:string};categories?:string[];scope_comparison?:ScopeComparison;jurisdictions:MatrixRow[];selected:null|{code:string;category:{datasets:Array<{dataset_id:string;label:string;availability_status:string;state_record_count:number|null;gap_reason:string|null}>};adjacent_evidence?:AdjacentEvidence[]}};
type Shares={available:boolean;categories:Array<{id:string;label:string}>;national_category_counts:Record<string,number>;national_category_percent_of_collected_evidence:Record<string,number|null>;states:Array<{postal_abbreviation:string;state_name:string;category_counts:Record<string,number>;percent_of_category_nationwide:Record<string,number|null>}>};
const percent=(value:number|null|undefined)=>value==null?'Unmeasured':`${value.toFixed(1)}%`;
const count=(value:number|null|undefined)=>value==null?'Unmeasured':value.toLocaleString();
const CATEGORY_LABELS:Record<string,string>={
  'general-business':'Broad state organization layer',
  'retail-consumer':'Retail and consumer',
  'health-care':'Health care',
  'financial-services':'Financial services',
  'tax-exempt-organizations':'Tax-exempt organizations',
  'regulated-meat-poultry-egg-establishments':'Regulated meat, poultry and egg establishments',
  'cross-industry-regulated-facilities':'Cross-industry regulated facilities',
  transportation:'Transportation',
};
const categoryLabel=(id:string)=>CATEGORY_LABELS[id]??id.replaceAll('-',' ');

export function OutsideNationalReporting({comparison}:{comparison?:ScopeComparison}) {
  const ready=comparison?.available&&comparison.configuration&&comparison.catalog&&Array.isArray(comparison.industries);
  return <section aria-label="Outside national reporting denominator"><h3>Outside national reporting denominator</h3>
    <p>Configured industries below are excluded from the national reporting denominator. State-only configuration is not evidence of acquisition or nationwide coverage. Expected, measured and unmeasured matrix totals above are unchanged; no completeness percentage is inferred.</p>
    {!ready?<p role="status">Scope comparison unavailable. Missing or unverified inputs are not an empty gap list or zero coverage.</p>:<>
      <p>Compared denominator: {comparison.denominator_version}.</p>
      {comparison.industries!.length?<div className="representation-table" role="region" aria-label="Excluded configured industry sources" tabIndex={0}><table><caption>Configuration only — not acquired records or measured coverage</caption><thead><tr><th scope="col">Configured industry</th><th scope="col">Source configuration</th><th scope="col">Publisher scope</th></tr></thead><tbody>{comparison.industries!.flatMap(industry=>industry.sources.map(source=><tr key={`${industry.id}:${source.id}`}><th scope="row">{categoryLabel(industry.id)}</th><td>{source.id}{source.manual_selection_required&&' · manual selection required'}</td><td>{source.scope==='state'?`State-only: ${Array.isArray(source.publisher_states)?source.publisher_states.join(', '):'Unknown'}`:'National configuration only'}</td></tr>))}</tbody></table></div>:<p>No excluded configured industry groups were found in this validated comparison. This is not a completeness claim.</p>}
      <details><summary>Scope comparison identities</summary><p>Configuration: {comparison.configuration!.path} · version {comparison.configuration!.version}</p><p>Configuration SHA-256: <code style={{overflowWrap:'anywhere'}}>{comparison.configuration!.sha256}</code></p><p>Catalog: {comparison.catalog!.path} · {comparison.catalog!.schema_version} · {comparison.catalog!.denominator_version}</p><p>Validated base catalog SHA-256: <code style={{overflowWrap:'anywhere'}}>{comparison.catalog!.predecessor_sha256}</code></p></details>
    </>}
  </section>;
}

export function summarizeAvailability(rows:MatrixRow[]){
  const available=rows.reduce((sum,row)=>sum+row.available,0),measured=rows.reduce((sum,row)=>sum+row.measured,0),expected=rows.reduce((sum,row)=>sum+row.denominator,0),unmeasured=rows.reduce((sum,row)=>sum+row.unmeasured,0),connected=rows.filter(row=>row.available>0).length;
  return {available,measured,expected,unmeasured,connected,jurisdictions:rows.length,availabilityPercent:measured?available/measured*100:null,connectivityPercent:rows.length?connected/rows.length*100:null};
}

export function CoverageWorkspace({industries=false,stateCode,categoryCode,onStateChange,onCategoryChange,onNavigate}:{industries?:boolean;stateCode?:string;categoryCode?:string;onStateChange?:(code:string)=>void;onCategoryChange?:(code:string)=>void;onNavigate?:(tab:WorkspaceTab)=>void}) {
  const [localCategory,setCategory]=useState('general-business'),[localState,setState]=useState(''),[view,setView]=useState<Matrix|null>(null),[shares,setShares]=useState<Shares|null>(null),[error,setError]=useState('');
  const category=categoryCode??localCategory;
  const state=stateCode??localState;
  function chooseState(value:string){setState(value);onStateChange?.(value);setError('');}
  function chooseCategory(value:string){setCategory(value);onCategoryChange?.(value);setView(null);setError('');}
  useEffect(()=>{const controller=new AbortController();const query=new URLSearchParams({category});if(state)query.set('state',state);void runnerJson<Matrix>(`/api/business-map/goal-completion?${query}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setView(value);}).catch(()=>{if(!controller.signal.aborted){setView(null);setError('Verified coverage evidence is unavailable. No older result or zero is substituted.');}});return()=>controller.abort();},[state,category]);
  useEffect(()=>{if(!industries)return;const controller=new AbortController();void runnerJson<Shares>('/api/business-map/state-summary?include_territories=false',{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setShares(value);}).catch(()=>{if(!controller.signal.aborted)setShares(null);});return()=>controller.abort();},[industries]);
  const selected=view?.jurisdictions?.find(row=>row.code===state);
  const selectedCategoryLabel=categoryLabel(category);
  const national=view?.available?summarizeAvailability(view.jurisdictions):null;
  const industryCategory=shares?.categories.find(row=>row.id===category);
  const industryState=shares?.states.find(row=>row.postal_abbreviation===state);
  const industrySummary=industries&&shares?.available?<section className="industry-summary" aria-label="Industry summary"><h3>Industry summary</h3><p>Observed source-category evidence only. Categories can overlap and do not represent deduplicated businesses, GDP allocation, or all-business completeness.</p><div className="coverage-national-metrics"><article><span>Selected industry</span><strong>{industryCategory?.label??selectedCategoryLabel}</strong><small>Reporting category, not a complete industry census</small></article><article><span>National evidence rows</span><strong>{count(shares.national_category_counts[category])}</strong><small>{percent(shares.national_category_percent_of_collected_evidence[category])} of collected category evidence</small></article><article><span>{state||'Selected state'} evidence rows</span><strong>{count(industryState?.category_counts[category])}</strong><small>{percent(industryState?.percent_of_category_nationwide[category])} of this category nationwide</small></article></div></section>:null;
  return <section className="panel focused-workspace"><h2>{industries?'Industries':'Coverage'}</h2><p>Governed dataset availability — not completeness of all businesses. Availability is available ÷ measured datasets; unmeasured members remain separately visible.</p>
    <label>{industries?'Reporting industry':'Coverage category'} <select aria-label={industries?'Reporting industry':'Coverage category'} value={category} onChange={event=>chooseCategory(event.target.value)}>{(view?.categories??[category]).map(id=><option key={id} value={id}>{categoryLabel(id)}</option>)}</select></label>
    {error&&<p role="alert">{error}</p>}{!view&&!error&&<p role="status">Verifying local coverage…</p>}{view&&!view.available&&<p role="status">{view.status.replaceAll('-',' ')}. Completion is unmeasured.</p>}
    {industrySummary}
    {industries&&<><h3>National and state industry evidence shares</h3><p>These source-category shares are separate from dataset availability below. Categories may overlap; they are not GDP allocations or shares of all businesses.</p>{shares?.available?<div className="representation-table"><table><thead><tr><th>Source category</th><th>National evidence rows</th><th>Share of all collected national category evidence</th><th>{state||'Selected state'} evidence rows</th><th>State share of this category nationwide</th></tr></thead><tbody>{shares.categories.map(row=><tr key={row.id}><th>{row.label}</th><td>{count(shares.national_category_counts[row.id])}</td><td>{percent(shares.national_category_percent_of_collected_evidence[row.id])}</td><td>{count(industryState?.category_counts[row.id])}</td><td>{percent(industryState?.percent_of_category_nationwide[row.id])}</td></tr>)}</tbody></table><p>Scope: 50 states and D.C.; only evidence with the governed state assignment. Ambiguous/unmatched geography is excluded. Null denominators remain unmeasured.</p></div>:<p>National share evidence is unavailable or loading; no percentage is inferred.</p>}<details><summary>Census employer industry aggregates</summary><CensusZbpIndustryHeatmap/></details><details><summary>Census nonemployer county industry aggregates</summary><CensusNonemployerCountyHeatmap/></details></>}
    {national&&<><div className="coverage-national-metrics" aria-label="National dataset expectations"><article><span>Expected dataset × state cells</span><strong>{count(national.expected)}</strong><small>Version {view?.denominator?.version}</small></article><article><span>Available / measured cells</span><strong>{count(national.available)} / {count(national.measured)}</strong><small>{percent(national.availabilityPercent)} of measured cells · not business completeness</small></article><article><span>Unmeasured expected cells</span><strong>{count(national.unmeasured)}</strong><small>Unknown, not zero and not omitted from expectations</small></article><article><span>States/DC with positive dataset evidence</span><strong>{national.connected} / {national.jurisdictions}</strong><small>{percent(national.connectivityPercent)} of listed jurisdictions · at least one available dataset, not full industry coverage</small></article></div><p>National expectation counts sum the selected reporting category across listed states/DC. They count dataset–state relationships, not distinct datasets, businesses, or GDP.</p></>}
    {onNavigate&&<div className="workspace-path"><span>{state?`Selected state: ${state}`:'Select a state on the map'}</span><button onClick={()=>onNavigate(industries?'Coverage':'Industries')}>{industries?'View state coverage':'View industry summary'}</button><button onClick={()=>onNavigate('ZIP Economy')}>Explore ZIP economy</button></div>}
    {view?.available&&<><div className="coverage-focus-layout"><div><h3>50 states and D.C. · {selectedCategoryLabel} availability</h3><StateAvailabilityChoropleth rows={view.jurisdictions} selected={state} categoryLabel={selectedCategoryLabel} onSelect={chooseState}/><details><summary>Accessible state tiles — same values as the map</summary><p>Alphabetical state tiles, not geographic polygons. Select a tile or use the state list. Text values are the same evidence as the colors.</p><div className="coverage-state-tiles">{view.jurisdictions.map(row=><button key={row.code} aria-pressed={state===row.code} aria-label={`${row.name}, ${selectedCategoryLabel}: ${percent(row.percent)}, ${row.available} of ${row.measured} measured, ${row.unmeasured} unmeasured`} onClick={()=>chooseState(row.code)} style={{backgroundColor:row.percent===null?'#263241':`hsl(${190+(row.percent/100)*35} 45% ${20+(row.percent/100)*20}%)`}}><strong>{row.code}</strong><span>{percent(row.percent)}</span><small>{row.available}/{row.measured} measured</small><small>{row.unmeasured} unmeasured</small></button>)}</div></details></div>
      <aside className="coverage-selected" aria-label={industries?'Selected industry and state summary':'Selected state summary'}><h3>{industries?'Industry and state summary':'Selected state'}</h3><p><strong>Scope:</strong> {selectedCategoryLabel}</p><label>State <select aria-label="Coverage state" value={state} onChange={event=>chooseState(event.target.value)}><option value="">Choose a state</option>{view.jurisdictions.map(row=><option key={row.code} value={row.code}>{row.name}</option>)}</select></label>{industries&&<dl className="summary-stats"><dt>National source evidence rows</dt><dd>{count(shares?.available?shares.national_category_counts[category]:null)}</dd><dt>{state||'Selected state'} source evidence rows</dt><dd>{count(shares?.available?industryState?.category_counts[category]:null)}</dd></dl>}{selected?<><h4>{selected.name}</h4><p><strong>{percent(selected.percent)}</strong> {selectedCategoryLabel} dataset availability</p><p>{selected.available} available / {selected.measured} measured · {selected.unmeasured} unmeasured / {selected.denominator} expected.</p><p>Broad state organization layer: {selected.broad_layer_gap?'Gap':'Available'}. All-business completeness: Unknown.</p><ul>{view.selected?.code===state&&view.selected.category.datasets.map(row=><li key={row.dataset_id}><strong>{row.label}</strong>: {row.availability_status.replaceAll('-',' ')} · {count(row.state_record_count)} state records{row.gap_reason&&` · ${row.gap_reason}`}</li>)}</ul>{view.selected?.code===state&&view.selected.adjacent_evidence?.map(item=><article key={item.dataset_id} aria-label="Retained adjacent organization evidence"><h5>Adjacent retained evidence — outside availability</h5><p><strong>{count(item.organization_count)}</strong> IRS tax-exempt organization records grouped by reported filing-address state.</p><dl><dt>Source date</dt><dd>{item.source_date}</dd><dt>Coverage release</dt><dd>{item.release_id}</dd><dt>Same-code ZCTA records</dt><dd>{count(item.record_zcta_count)}</dd><dt>Nonpolygon records</dt><dd>{count(item.record_nonpolygon_count)}</dd></dl><p>{item.row_semantics}.</p><ul>{item.limitations.map(text=><li key={text}>{text}</li>)}</ul></article>)}</>:<p>Select a state to see measured availability, missing evidence and source counts here.</p>}</aside></div><p className="entity-method-note">Selected reporting scope: {selectedCategoryLabel}. Versioned denominator: {view.denominator?.version}. Release: {view.release_id}. A measured zero is not an unmeasured value; 100% availability applies only to the selected category and does not establish complete industry or business collection.</p></>}
    <OutsideNationalReporting comparison={view?.scope_comparison}/>
    <RetainedCountyWorkspace stateCode={state}/>
  </section>;
}

type ZipEvidence={source_native_status_distribution?:SourceNativeStatusView|null;census_zbp_industry_profile?:CensusZbpZipProfileView;qualification?:QualificationView;operational_admission?:{status:string;production_admission:boolean|null;blockers:string[]};zip5:string;evidence_status:string;coverage_status?:string|null;classification?:{class:string;ordinary_zip5_eligible?:boolean}|null;governed_zcta:{status:string;geoid:string|null};selected_coverage_geography?:{zcta_status:string|null;zcta_geoid:string|null;spatial_zip_polygon_membership_status:string|null;material_county_count:number|null;county_assignment:string|null}|null;zip_quality?:{status?:string;usps_operational_status?:string;usps_operational_evidence?:{evidence_status:string;operational_status?:string|null;reason?:string};unresolved_proof_gap_codes?:string[]};coverage_gap_codes?:string[];counts:null|{physical_sites:number;establishments:number;employer_establishments:number|null};bindings:Record<string,string|null>;category_evidence?:{category_id:string;category_label:string;status:string;semantics:string;positive_source_contributions:Array<{source_id:string;source_release_id:string|null;positive_counts:Record<string,number>}>}};
export type ZctaEconomicReadiness={schema_version:string;zcta:string;available:boolean;status:string;readiness:null|{population_2020:number;housing_units_2020:number;zbp_publication_status:string;relationship_count:number;material_relationship_count:number;state_fips:string[];county_geoids:string[];direct_county_gdp_count:number;missing_county_gdp_geoids:string[];direct_gdp_relationship_coverage:number|null;model_status:string;blockers:string[]};provenance:{release_id:string;manifest_sha256:string;artifact_sha256:string;created_at:string;geography_release_id:string;input_releases:Array<{dataset_id:string;release_id:string;manifest_sha256:string}>};limitations:string[];claims:{official_zip_code:false;active_businesses:false;numeric_gdp_or_demographic_allocation:false}};
const evidenceLabel=(value:string|null|undefined)=>value?value.replaceAll('-',' '):'Unknown — not evidenced';
const machine=(value:string|null|undefined)=>value??'unavailable';
const exactKeys=(value:unknown,keys:string[])=>{if(!value||typeof value!=='object'||Array.isArray(value))return false;const actual=Object.keys(value).sort(),expected=[...keys].sort();return actual.length===expected.length&&actual.every((key,index)=>key===expected[index]);};
const unique=(values:unknown[])=>new Set(values).size===values.length;
const canonicalIso=(value:string)=>{const time=Date.parse(value);return Number.isFinite(time)&&new Date(time).toISOString()===value;};
export function validZctaEconomicReadiness(value:unknown,zcta:string=(value as {zcta?:string})?.zcta??''):value is ZctaEconomicReadiness{
  if(!exactKeys(value,['schema_version','zcta','available','status','readiness','provenance','limitations','claims']))return false;
  const view=value as ZctaEconomicReadiness;
  if(view.schema_version!=='zcta-economic-readiness-view@1.0.0'||!/^[0-9]{5}$/.test(zcta)||view.zcta!==zcta||typeof view.available!=='boolean'||!['found','not-found'].includes(view.status)||view.available!==(view.status==='found')||!Array.isArray(view.limitations)||!view.limitations.every(item=>typeof item==='string'))return false;
  if(!exactKeys(view.claims,['official_zip_code','active_businesses','numeric_gdp_or_demographic_allocation'])||Object.values(view.claims).some(item=>item!==false))return false;
  if(!exactKeys(view.provenance,['release_id','manifest_sha256','artifact_sha256','created_at','geography_release_id','input_releases'])||![view.provenance.release_id,view.provenance.geography_release_id].every(item=>typeof item==='string'&&item.length>0)||typeof view.provenance.created_at!=='string'||!canonicalIso(view.provenance.created_at)||![view.provenance.manifest_sha256,view.provenance.artifact_sha256].every(item=>typeof item==='string'&&/^[a-f0-9]{64}$/.test(item))||!Array.isArray(view.provenance.input_releases)||!view.provenance.input_releases.every(item=>exactKeys(item,['dataset_id','release_id','manifest_sha256'])&&typeof item.dataset_id==='string'&&item.dataset_id.length>0&&typeof item.release_id==='string'&&item.release_id.length>0&&/^[a-f0-9]{64}$/.test(item.manifest_sha256)))return false;
  if(!view.available)return view.readiness===null;
  const row=view.readiness;
  if(!exactKeys(row,['population_2020','housing_units_2020','zbp_publication_status','relationship_count','material_relationship_count','state_fips','county_geoids','direct_county_gdp_count','missing_county_gdp_geoids','direct_gdp_relationship_coverage','model_status','blockers'])||!row)return false;
  if(row.model_status!=='withheld'||!Number.isSafeInteger(row.population_2020)||row.population_2020<0||!Number.isSafeInteger(row.housing_units_2020)||row.housing_units_2020<0||!['zbp-and-zcta','zcta-without-published-zbp'].includes(row.zbp_publication_status)||!Number.isSafeInteger(row.relationship_count)||row.relationship_count<0||!Number.isSafeInteger(row.material_relationship_count)||row.material_relationship_count<0||row.material_relationship_count>row.relationship_count||!Number.isSafeInteger(row.direct_county_gdp_count)||row.direct_county_gdp_count<0||row.direct_county_gdp_count>row.relationship_count)return false;
  if(!Array.isArray(row.state_fips)||!unique(row.state_fips)||!row.state_fips.every(item=>/^\d{2}$/.test(item))||!Array.isArray(row.county_geoids)||!unique(row.county_geoids)||row.county_geoids.length!==row.relationship_count||!row.county_geoids.every(item=>/^\d{5}$/.test(item))||!Array.isArray(row.missing_county_gdp_geoids)||!unique(row.missing_county_gdp_geoids)||!row.missing_county_gdp_geoids.every(item=>row.county_geoids.includes(item))||row.direct_county_gdp_count+row.missing_county_gdp_geoids.length!==row.relationship_count||!Array.isArray(row.blockers)||!unique(row.blockers)||!row.blockers.every(item=>typeof item==='string'&&item.length>0))return false;
  return row.direct_gdp_relationship_coverage===(row.relationship_count?row.direct_county_gdp_count/row.relationship_count:null);
}
export function ZctaEconomicReadinessPanel({view}:{view:ZctaEconomicReadiness}){
  const row=view.readiness,lineage=view.provenance.input_releases;
  return <section aria-label={`ZCTA ${view.zcta} economic-model readiness`} style={{minWidth:0,overflowWrap:'anywhere'}}>
    <h3>Economic-model readiness · Census ZCTA {view.zcta}</h3>
    <p>This is readiness metadata for a Census statistical area, not an official USPS ZIP, current-operation finding, or economic estimate.</p>
    {!view.available||!row?<p role="status"><code>{machine(view.status)}</code>. No retained readiness row was found; this does not make the ZIP invalid or establish zero population, housing, businesses, or GDP.</p>:<dl><dt>model_status</dt><dd><code>{machine(row.model_status)}</code></dd><dt>blockers</dt><dd>{row.blockers.length?<ul>{row.blockers.map(value=><li key={value}><code>{value}</code></li>)}</ul>:<code>none-reported</code>}</dd><dt>County relationships</dt><dd>{count(row.relationship_count)} total · {count(row.material_relationship_count)} material</dd><dt>Direct county GDP coverage</dt><dd>{count(row.direct_county_gdp_count)} / {count(row.relationship_count)} relationships · {row.direct_gdp_relationship_coverage==null?'Unavailable':`${(row.direct_gdp_relationship_coverage*100).toFixed(1)}%`}</dd><dt>Missing direct-county GDP GEOIDs</dt><dd>{row.missing_county_gdp_geoids.length?row.missing_county_gdp_geoids.map(value=><code key={value}>{value} </code>):'None reported'}</dd><dt>2020 Census population</dt><dd>{count(row.population_2020)} · aggregate context, not a current estimate or allocation weight</dd><dt>2020 Census housing units</dt><dd>{count(row.housing_units_2020)} · aggregate context, not a current estimate or allocation weight</dd><dt>ZIP Business Patterns status</dt><dd><code>{machine(row.zbp_publication_status)}</code></dd></dl>}
    <details><summary>Readiness release and source lineage</summary><p>Readiness release: <code>{view.provenance.release_id}</code> · created {view.provenance.created_at}</p><p>Census geography release: <code>{view.provenance.geography_release_id}</code></p><p>Manifest SHA-256: <code>{view.provenance.manifest_sha256}</code> · artifact SHA-256: <code>{view.provenance.artifact_sha256}</code></p>{lineage.length?<ul>{lineage.map(source=><li key={`${source.dataset_id}:${source.release_id}`}><code>{source.dataset_id}</code> · <code>{source.release_id}</code> · manifest <code>{source.manifest_sha256}</code></li>)}</ul>:<p>Source lineage was not supplied.</p>}</details>
    <details><summary>Readiness limitations ({view.limitations.length})</summary>{view.limitations.length?<ul>{view.limitations.map(value=><li key={value}>{value}</li>)}</ul>:<p>No limitations were supplied; this is not evidence that limitations are absent.</p>}</details>
    <p>No ZIP/ZCTA GDP or demographic allocation is produced. County GDP is direct county evidence only and is not allocated to this ZCTA.</p>
  </section>;
}
export function ZipGeographySummary({view}:{view:ZipEvidence}){
  const geography=view.selected_coverage_geography,quality=view.zip_quality;
  const gaps=Array.from(new Set([...(quality?.unresolved_proof_gap_codes??[]),...(view.coverage_gap_codes??[])]));
  // The API's absent-registry fallback also says not-in-denominator; it is not a verified nonmember.
  const membership=view.governed_zcta?.status==='not-in-denominator'?(view.classification?'Not in the selected governed ZCTA denominator':'Unknown — no registry classification'):evidenceLabel(view.governed_zcta?.status);
  return <section aria-label="Shared ZIP geography evidence" style={{fontSize:'1rem',lineHeight:1.5,minWidth:0,overflowWrap:'anywhere'}}>
    <h3>Geography evidence · ZIP {view.zip5}</h3>
    <p>ZIP-wide context, not segment-filtered. A same-code Census ZCTA does not verify USPS operation, business operations or membership in the selected navigation state.</p>
    <dl><dt>Registry classification</dt><dd>{evidenceLabel(view.classification?.class)}</dd><dt>Selected coverage status</dt><dd>{evidenceLabel(view.coverage_status)}</dd><dt>Same-code governed ZCTA status</dt><dd>{membership}</dd><dt>Same-code ZCTA GEOID</dt><dd>{view.governed_zcta?.geoid??'Unknown — not evidenced'}</dd><dt>Selected coverage ZCTA status / GEOID</dt><dd>{evidenceLabel(geography?.zcta_status)} · {geography?.zcta_geoid??'Unknown — not evidenced'}</dd><dt>Selected spatial polygon status</dt><dd>{evidenceLabel(geography?.spatial_zip_polygon_membership_status)}</dd><dt>Material county intersections</dt><dd>{geography?.material_county_count??'Unknown — not measured'}</dd><dt>County assignment</dt><dd>{evidenceLabel(geography?.county_assignment)}</dd><dt>USPS operational evidence</dt><dd>{evidenceLabel(quality?.usps_operational_evidence?.evidence_status??quality?.usps_operational_status)}. Current USPS operation is not verified by this view.</dd></dl>
    <details><summary>Geography proof gaps ({gaps.length?`${gaps.length} reported`:'none reported; not proof of completeness'})</summary>{gaps.length?<ul>{gaps.map(gap=><li key={gap}>{evidenceLabel(gap)}</li>)}</ul>:<p>No proof gap codes were supplied. This does not verify geography or postal operation.</p>}</details>
    <p>Business segments contains independently bound source contributions and temporal review qualification; neither resolves these geography gaps.</p>
  </section>;
}
const economyTabs=['Overview','Business segments','Demographics'] as const;
const segments=[['all','All source categories'],['retail-consumer','Retail and consumer'],['health-care','Health care'],['financial-services','Financial services'],['tax-exempt-organizations','Tax-exempt organizations'],['food-production','Food production'],['environmental-facilities','Environmental facilities'],['transportation','Transportation'],['childcare','Childcare'],['licensed-businesses','Licensed business evidence'],['registrations-nonprofits','Organization registrations and nonprofits']];
export function ZipEconomyWorkspace({stateCode=''}:{stateCode?:string}={}){
  const [input,setInput]=useState(''),[zip,setZip]=useState(''),[view,setView]=useState<ZipEvidence|null>(null),[error,setError]=useState(''),[dimension,setDimension]=useState('Race'),[section,setSection]=useState<typeof economyTabs[number]>('Overview'),[segment,setSegment]=useState('all'),[attempt,setAttempt]=useState(0),[readiness,setReadiness]=useState<ZctaEconomicReadiness|null>(null),[readinessError,setReadinessError]=useState(false);
  const segmentName=segments.find(([id])=>id===segment)?.[1]??segment;
  useEffect(()=>{if(!zip)return;const controller=new AbortController();void runnerJson<ZipEvidence>(`/api/business-map/zip-inspector?zip=${zip}&category=${encodeURIComponent(segment)}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted&&value.zip5===zip&&value.category_evidence?.category_id===segment)setView(value);else if(!controller.signal.aborted)setError('Returned ZIP/category evidence did not match the requested scope.');}).catch(()=>{if(!controller.signal.aborted)setError('Exact ZIP evidence is unavailable. No estimates were substituted.');});return()=>controller.abort();},[zip,segment,attempt]);
  const governedZcta=view?.governed_zcta;
  let matchedZcta:string|null=null;
  if(view&&governedZcta?.geoid===view.zip5&&governedZcta.status==='included')matchedZcta=governedZcta.geoid;
  useEffect(()=>{if(!matchedZcta)return;const controller=new AbortController();void Promise.resolve().then(()=>{if(!controller.signal.aborted){setReadiness(null);setReadinessError(false);}});void runnerJson<ZctaEconomicReadiness>(`/api/business-map/zcta-economic-readiness?zcta=${encodeURIComponent(matchedZcta)}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted&&validZctaEconomicReadiness(value,matchedZcta))setReadiness(value);else if(!controller.signal.aborted)setReadinessError(true);}).catch(reason=>{if(!controller.signal.aborted&&reason?.name!=='AbortError')setReadinessError(true);});return()=>controller.abort();},[matchedZcta]);
  function changeSegment(value:string){setSegment(value);setView(null);setReadiness(null);setReadinessError(false);setError('');}
  return <section className="panel focused-workspace"><h2>ZIP Economy</h2><p>Observed ZIP evidence and modeled-economy readiness in one place. Source-reported ZIP5 and Census ZCTA polygons are different geographies; ZIP+4 is not a polygon.</p>
    {stateCode&&<p>Navigation context: {stateCode}. A ZIP is not inferred from the selected state; enter an exact ZIP below.</p>}
    <form onSubmit={event=>{event.preventDefault();if(/^\d{5}$/.test(input)){setError('');setView(null);setReadiness(null);setReadinessError(false);setZip(input);setAttempt(attempt+1);}else setError('Enter exactly five ZIP digits, including leading zeros.');}}><label>ZIP5 <input aria-label="Economy ZIP5" inputMode="numeric" maxLength={5} value={input} onChange={event=>setInput(event.target.value)}/></label><label>Business segment <select aria-label="Economy business segment" value={segment} onChange={event=>changeSegment(event.target.value)}>{segments.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button type="submit">{error&&zip?'Retry ZIP':'View ZIP'}</button></form>
    <p className="economy-context"><strong>{zip?`ZIP ${zip}`:'No ZIP selected'}</strong> · {segmentName} · observed evidence only; modeled GDP unavailable</p>
    <p>Segments are source-evidence categories, not mutually exclusive industries. Licenses and organization registrations do not establish current operations or physical business sites. Aggregate Census baselines remain separate context in Overview, not a business segment. Ordinary ZIP contributions and review qualification use separate source mappings; missing contributions do not mean qualification is unsupported or zero.</p>
    <div className="workspace-tabs" role="tablist" aria-label="ZIP economy views">{economyTabs.map((name,index)=><button key={name} id={`economy-tab-${index}`} role="tab" aria-selected={section===name} aria-controls="economy-panel" tabIndex={section===name?0:-1} onClick={()=>setSection(name)} onKeyDown={event=>{const next=event.key==='Home'?0:event.key==='End'?2:event.key==='ArrowRight'?(index+1)%3:event.key==='ArrowLeft'?(index+2)%3:null;if(next!==null){event.preventDefault();setSection(economyTabs[next]);document.getElementById(`economy-tab-${next}`)?.focus();}}}>{name}</button>)}</div>
    {error&&<p role="alert">{error}</p>}{zip&&!view&&!error&&<p role="status">Loading {zip} · {segmentName}…</p>}
    {view&&<ZipGeographySummary view={view}/>}
    {view&&<ZipSourceNativeStatus view={view.source_native_status_distribution}/>}
    <div id="economy-panel" role="tabpanel" aria-labelledby={`economy-tab-${economyTabs.indexOf(section)}`} tabIndex={0}>
    {section==='Overview'&&<>{view&&<CensusZbpZipProfile view={view.census_zbp_industry_profile} onRetry={()=>{setView(null);setReadiness(null);setReadinessError(false);setError('');setAttempt(attempt+1);}}/>}{view&&<><h3>Observed evidence · ZIP {view.zip5}</h3><p>{evidenceLabel(view.evidence_status)}.</p><dl><dt>All-category physical-site evidence</dt><dd>{count(view.counts?.physical_sites)}</dd><dt>All-category provisional establishments</dt><dd>{count(view.counts?.establishments)}</dd><dt>Published Census employer baseline (statistical aggregate)</dt><dd>{count(view.counts?.employer_establishments)}</dd></dl><p>These baseline counts are not filtered by the business segment. Open Business segments for scoped source evidence.</p></>}{view&&(matchedZcta?(readiness?<ZctaEconomicReadinessPanel view={readiness}/>:<p role="status">{readinessError?'Economic-model readiness is unavailable. No status or estimate was substituted.':`Loading economic-model readiness for Census ZCTA ${matchedZcta}…`}</p>):<p role="status">Economic-model readiness: not applicable. This ZIP has no same-code governed Census ZCTA match, so no readiness lookup was made.</p>)}<div className="economy-evidence-grid"><article><h3>Total extrapolated ZIP GDP</h3><strong>Unavailable — no governed model</strong><p>Existing BEA current-dollar GDP estimates are joined only to exact state/county GEOIDs. The current contract explicitly prohibits ZIP/ZCTA allocation. No ZIP GDP total is computed here.</p></article><article><h3>Business-segment GDP allocations</h3><strong>Unavailable — no governed allocation</strong><p>Industry evidence counts and Census establishments are not output or GDP weights. No segment allocation or false precision is inferred.</p></article></div></>}
    {section==='Business segments'&&<><h3>{segmentName} · ZIP {zip||'not selected'}</h3><p>Selected-segment extrapolated GDP: <strong>Unavailable</strong>. GDP share: <strong>Unmeasured</strong>. Observed source contributions below are not GDP allocations, additive business totals or a completeness percentage.</p><h4>Observed source contributions</h4>{view?.category_evidence?.status==='positive-source-contribution'?<div className="representation-table" role="region" aria-label="Ordinary ZIP source contributions" tabIndex={0}><table><caption>Observed source evidence for the selected ZIP and segment</caption><thead><tr><th scope="col">Source / release</th><th scope="col">Source-defined count</th><th scope="col">Modeled GDP</th></tr></thead><tbody>{view.category_evidence.positive_source_contributions.flatMap(source=>Object.entries(source.positive_counts).map(([unit,value])=><tr key={`${source.source_id}:${unit}`}><th scope="row">{source.source_id}<small>{source.source_release_id??'Release unavailable'}</small></th><td>{count(value)} · {unit.replaceAll('_',' ')}</td><td>Unavailable</td></tr>))}</tbody></table></div>:<p>{!zip?'Enter a ZIP to inspect segment evidence.':error?'Ordinary source contributions are unavailable. Retry ZIP above; absence has not been established.':!view?'Ordinary source contributions are loading; absence has not been established.':view.category_evidence?.status==='no-selected-positive-evidence'?'No verified positive segment evidence in the selected release. This is not a measured zero.':'Ordinary source contribution status is unknown. Absence has not been established.'}</p>}{view?.category_evidence&&<p>{view.category_evidence.semantics}</p>}</>}
    {section==='Demographics'&&<><h3>Demographic GDP cross-view</h3><label>Demographic dimension <select aria-label="Demographic dimension" value={dimension} onChange={event=>setDimension(event.target.value)}>{['Race','Lineage / ancestry','Sex','Age'].map(value=><option key={value}>{value}</option>)}</select></label>{readiness?.readiness&&<><h4>Governed ZCTA readiness inputs</h4><dl><dt>2020 Census population</dt><dd>{count(readiness.readiness.population_2020)} · aggregate context only</dd><dt>2020 Census housing units</dt><dd>{count(readiness.readiness.housing_units_2020)} · aggregate context only</dd><dt>ZIP Business Patterns status</dt><dd><code>{readiness.readiness.zbp_publication_status}</code></dd><dt>model_status</dt><dd><code>{readiness.readiness.model_status}</code></dd></dl></>}<p><strong>{dimension}: unavailable in the current ZIP economy contract.</strong> No demographic population breakdown or demographic GDP estimate is fabricated. Population/housing context is not a current estimate, demographic weight, or official USPS ZIP measure.</p><div className="representation-table"><table><caption>{zip?`ZIP ${zip}`:'No ZIP selected'} × {segmentName} × {dimension}</caption><thead><tr><th>Required input / output</th><th>Value</th><th>Evidence class</th></tr></thead><tbody><tr><th>ZIP GDP baseline</th><td>Unavailable</td><td>No governed extrapolation model</td></tr><tr><th>{dimension} population weights</th><td>Unknown</td><td>No governed demographic input in this contract</td></tr><tr><th>Segment allocation weights</th><td>Unknown</td><td>No governed economic weighting</td></tr><tr><th>Extrapolated demographic GDP</th><td>Unavailable</td><td>Modeled output withheld; not observed</td></tr></tbody></table></div><p>No demographic categories or shares are inferred from names, addresses, establishment counts, or ancestry proxies. Missing inputs prevent modeling; they do not imply zero economic activity.</p></>}
    {view?.operational_admission&&<aside aria-label="USPS operational admission"><h3>USPS operational evidence</h3><p>{view.operational_admission.status.replaceAll('-',' ')}. Candidate configuration is not admission or proof of current ZIP operation or address deliverability.</p><ul>{view.operational_admission.blockers.map(code=><li key={code}>{code.replaceAll('-',' ')}</li>)}</ul></aside>}
    {section==='Business segments'&&<ZipEvidenceQualificationPanel navigationState={stateCode} zip={zip} categoryId={segment} coverageReleaseId={view?.bindings.coverage_release_id??''} registryReleaseId={view?.bindings.registry_release_id??''} supplied={{view:view?.qualification??null,error:!!error||!!view&&!view.qualification}} onRetry={()=>{setView(null);setReadiness(null);setReadinessError(false);setError('');setAttempt(attempt+1);}}/>}
    </div>
    {view&&<details><summary>Evidence releases</summary>{Object.entries(view.bindings).map(([key,value])=><p key={key}>{key.replaceAll('_',' ')}: {value??'Unavailable'}</p>)}</details>}
    <p className="entity-method-note">Observed source records, published statistical estimates and modeled allocations are distinct. This view performs no acquisition and publishes no economic model.</p>
  </section>;
}
