'use client';
import {useEffect,useState} from 'react';
import {runnerJson} from './runner-client';

type Row={source_key:string;source_release_id:string;source_kind:string;evidence_type:string;qualification:string;temporal_status:{status:string;source_reference_field:string|null;source_reference_date:string|null;review_due_date:string|null};source_semantics:{classification:string;source_status_term:string;cohort_scope:string;jurisdiction_scope:string;policy_sha256:string};review_clock:{source_reference_at:string|null;age_days:number|null;review_after_days:number|null;cadence_class:string};observation_window:{first_seen:string|null;last_seen:string|null;meaning:string};retained_source_observation:{observed_at:string;meaning:string}|null;evidence_counts_by_unit:Record<string,number>;eligible_evidence_counts_by_unit:Record<string,number|null>};
export type QualificationView={schema_version:string;available:boolean;status:string;zip5:string;category_id:string;selection_status:string;export_policy:string|null;assessment_as_of:string|null;semantic_compatibility:string|null;semantic_provenance:Record<string,string>|null;review_scope_summary?:{assessment_as_of:string;qualification_sources:number;zip_cohort_members:number;source_zip_pair_unit:string;within_review_window:{source_count:number;source_zip_pairs:number;positive_source_zip_pairs:number;positive_zip_union:number};stale_review_due:{source_count:number;source_zip_pairs:number;positive_source_zip_pairs:number;positive_zip_union:number};unmeasured:{source_count:number;source_zip_pairs:number;positive_source_zip_pairs:number;positive_zip_union:number};within_window_semantics:{source_defined_current_membership:{source_count:number;positive_source_zip_pairs:number;positive_zip_union:number};non_active_reporting_membership:{source_count:number;positive_source_zip_pairs:number;positive_zip_union:number}}};review_qualification_gap:null|{status:string;positive_source_count:number;source_keys:string[]};release:null|{id:string;manifest_sha256:string;as_of:string;created_at:string;temporal_policy_version:string};bindings:null|{coverage_release_id:string;coverage_manifest_sha256:string;registry_release_id:string;registry_manifest_sha256:string;mapping_version:string;mapping_sha256:string;taxonomy_version:string};rows:Row[]};
type Request=(path:string,options:{signal:AbortSignal})=>Promise<QualificationView>;
const qualificationLabel=(value:string)=>value==='measured-within-review-window'?'Within internal review window':value==='measured-stale-review-due'?'Review overdue — does not mean closed':'Unmeasured — reference does not support qualification';

/** Supplied mode renders the server-composed envelope without a second request. */
export default function ZipEvidenceQualificationPanel({zip,categoryId,coverageReleaseId,registryReleaseId,navigationState='',request=runnerJson,supplied,onRetry}:{zip:string;categoryId:string;coverageReleaseId:string;registryReleaseId:string;navigationState?:string;request?:Request;supplied?:{view:QualificationView|null;error:boolean};onRetry?:()=>void}){
 const [attempt,setAttempt]=useState(0),[result,setResult]=useState<{scope:string;view:QualificationView|null;error:boolean}|null>(null);
 const scope=JSON.stringify([zip,categoryId,coverageReleaseId,registryReleaseId,navigationState,attempt]);
 const current=supplied??(result?.scope===scope?result:null);
 useEffect(()=>{
  if(supplied!==undefined||!/^\d{5}$/.test(zip)||!coverageReleaseId||!registryReleaseId)return;
  const controller=new AbortController(),query=new URLSearchParams({zip,category:categoryId});
  void request(`/api/business-map/zip-evidence-qualification?${query}`,{signal:controller.signal}).then(view=>{
   if(controller.signal.aborted)return;
    const mismatch=view.schema_version!=='zip-evidence-qualification-view@1.1.0'||view.zip5!==zip||view.category_id!==categoryId||view.available&&(!coverageReleaseId||!registryReleaseId||view.bindings?.coverage_release_id!==coverageReleaseId||view.bindings?.registry_release_id!==registryReleaseId);
   setResult({scope,view:mismatch?null:view,error:!!mismatch});
  }).catch(()=>{if(!controller.signal.aborted)setResult({scope,view:null,error:true});});
  return()=>controller.abort();
 },[zip,categoryId,coverageReleaseId,registryReleaseId,navigationState,attempt,scope,request,supplied]);
 const view=current?.view;
 return <section aria-label="Source evidence review qualification" style={{fontSize:'1rem',lineHeight:1.5,minWidth:0,overflowWrap:'anywhere'}}>
  <h3>Source evidence review qualification</h3>
  <p>Internal temporal review only. Current operations are not verified; active-business counts and all-business completeness remain unknown. Source units overlap and must not be added.</p>
  {!/^\d{5}$/.test(zip)?<p>Enter an exact ZIP5 to inspect qualification.</p>:!coverageReleaseId||!registryReleaseId?<p role="status">Qualification waits for compatible ordinary ZIP evidence release identities. No assessment is inferred.</p>:<>
   <p>ZIP {zip} · {categoryId.replaceAll('-',' ')}</p>
   {(!current||!current.view&&!current.error)&&<p role="status">Loading qualification evidence…</p>}
   {current?.error&&<p role="alert">Qualification evidence is unavailable or does not match the selected ZIP, category or evidence releases. Ordinary ZIP evidence is unchanged.</p>}
   {view&&!view.available&&<p role="status">Qualification release unavailable: {view.status.replaceAll('-',' ')}. No assessment was rebuilt; this is not zero evidence.</p>}
   {(current?.error||view&&!view.available)&&<button onClick={()=>onRetry?onRetry():setAttempt(attempt+1)}>Retry qualification</button>}
   {view?.available&&<>
    <p>Use restriction: <strong>{view.export_policy}</strong>. No public export is offered.</p>
    <p>Assessment as of {view.assessment_as_of}. This retained assessment clock is fixed; build time does not refresh source references. Review policy {view.release?.temporal_policy_version}. Semantic lineage: {view.semantic_compatibility?.replaceAll('-',' ')}.</p>
    {view.review_qualification_gap&&<p role="note">Positive evidence with {view.review_qualification_gap.status==='unknown-only'?'unmeasured':'stale'} review qualification only: {view.review_qualification_gap.source_keys.join(', ')}. This is a review gap, not a closure or invalid-ZIP finding.</p>}
    {view.review_scope_summary&&<details><summary>National retained review snapshot</summary><p>As of {view.review_scope_summary.assessment_as_of}, the ZIP cohort contains {view.review_scope_summary.zip_cohort_members.toLocaleString()} ZIPs and {view.review_scope_summary.qualification_sources} ZIP-bearing source cohorts. Units are {view.review_scope_summary.source_zip_pair_unit}; overlapping counts are nonadditive and do not measure businesses or operation.</p><ul><li>Within internal review window: {view.review_scope_summary.within_review_window.source_count} sources / {view.review_scope_summary.within_review_window.source_zip_pairs.toLocaleString()} source–ZIP pairs; {view.review_scope_summary.within_review_window.positive_source_zip_pairs.toLocaleString()} positive pairs across {view.review_scope_summary.within_review_window.positive_zip_union.toLocaleString()} ZIPs.</li><li>Review overdue: {view.review_scope_summary.stale_review_due.source_count} source / {view.review_scope_summary.stale_review_due.source_zip_pairs.toLocaleString()} pairs; {view.review_scope_summary.stale_review_due.positive_source_zip_pairs.toLocaleString()} positive pairs across {view.review_scope_summary.stale_review_due.positive_zip_union.toLocaleString()} ZIPs.</li><li>Unmeasured: {view.review_scope_summary.unmeasured.source_count} sources / {view.review_scope_summary.unmeasured.source_zip_pairs.toLocaleString()} pairs; {view.review_scope_summary.unmeasured.positive_source_zip_pairs.toLocaleString()} positive pairs across {view.review_scope_summary.unmeasured.positive_zip_union.toLocaleString()} ZIPs.</li><li>Within-window source-defined-current cohorts: {view.review_scope_summary.within_window_semantics.source_defined_current_membership.source_count}, {view.review_scope_summary.within_window_semantics.source_defined_current_membership.positive_source_zip_pairs.toLocaleString()} positive pairs across {view.review_scope_summary.within_window_semantics.source_defined_current_membership.positive_zip_union.toLocaleString()} ZIPs. Non-active reporting cohorts: {view.review_scope_summary.within_window_semantics.non_active_reporting_membership.source_count}, {view.review_scope_summary.within_window_semantics.non_active_reporting_membership.positive_source_zip_pairs.toLocaleString()} positive pairs across {view.review_scope_summary.within_window_semantics.non_active_reporting_membership.positive_zip_union.toLocaleString()} ZIPs. A review window never implies active operation.</li></ul></details>}
    {view.selection_status==='absent'&&<p>No retained matching ZIP/source pair. Absence is not measured zero or a finding of no businesses.</p>}
    {view.selection_status==='unsupported'&&<p>This category has no supported mapping in this release. Qualification is unavailable, not zero.</p>}
    {view.selection_status==='matched'&&<div role="region" aria-label="Source qualification rows" tabIndex={0} style={{overflowX:'auto',maxWidth:'100%'}}><table style={{fontSize:'inherit'}}><caption>ZIP {zip}: source-defined counts and review qualification</caption><thead><tr>{['Source semantics','Review clock and observation','Source unit','Observed count','Eligible under review rule'].map(label=><th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{view.rows.flatMap(row=>Object.entries(row.evidence_counts_by_unit).map(([unit,value])=><tr key={`${row.source_key}:${unit}`}><th scope="row">{row.source_key}<br/>{row.source_release_id}<br/>{row.source_semantics.source_status_term} · {row.source_semantics.classification}<br/>{row.source_semantics.jurisdiction_scope}: {row.source_semantics.cohort_scope}</th><td>{qualificationLabel(row.qualification)} · {row.temporal_status.status.replaceAll('-',' ')}<br/>Reference: {row.temporal_status.source_reference_date??'Unknown'} ({row.temporal_status.source_reference_field??'Unavailable'}); age: {row.review_clock.age_days??'Unknown'} days / {row.review_clock.review_after_days??'Unmeasured'}-day internal review threshold; cadence {row.review_clock.cadence_class}.<br/>Review due: {row.temporal_status.review_due_date??'Unknown'}. Record observation: {row.observation_window.first_seen??'Unknown'} — {row.observation_window.last_seen??'Unknown'}. {row.retained_source_observation&&`Retained source observed ${row.retained_source_observation.observed_at}; ${row.retained_source_observation.meaning}`}</td><td>{unit.replaceAll('_',' ')}</td><td>{value.toLocaleString()}</td><td>{row.eligible_evidence_counts_by_unit[unit]===null?'Unknown':row.eligible_evidence_counts_by_unit[unit]?.toLocaleString()}</td></tr>))}</tbody></table></div>}
    <details><summary>Qualification release and bindings</summary><p>Release {view.release?.id} · manifest {view.release?.manifest_sha256}</p>{Object.entries(view.semantic_provenance??{}).map(([key,value])=><p key={key}>Semantic {key.replaceAll('_',' ')}: {value}</p>)}{Object.entries(view.bindings??{}).map(([key,value])=><p key={key}>{key.replaceAll('_',' ')}: {value}</p>)}</details>
   </>}
  </>}
 </section>;
}
