'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { runnerJson } from './runner-client';
const endpoint='/api/data-operations/zip-denominator-delta-review';
type V={production:{key_count:number};prior_candidate:{key_count:number};delta:{added_count:number;removed_count:number;same_code_zcta_added:number;placeholder_added:number;usps_unverified_added:number};local_review_drilldown:Array<{zip5:string;zip4:null;source_provenance:Array<{source_id:string}>;zcta_membership:string;usps_status:string;review_disposition:string}>};
export default function ZipDenominatorDeltaReview(){
 const[v,setV]=useState<V|null>(null),[error,setError]=useState(false);const seq=useRef(0),active=useRef<AbortController|null>(null);
 const load=useCallback(async()=>{active.current?.abort();const c=new AbortController;active.current=c;const n=++seq.current;try{const x=await runnerJson<V>(endpoint,{signal:c.signal});if(!c.signal.aborted&&n===seq.current){setV(x);setError(false)}}catch{if(!c.signal.aborted&&n===seq.current){setV(null);setError(true)}}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>{window.clearTimeout(timer);seq.current+=1;active.current?.abort()}},[load]);
 return <section className="operations-builder"><h3>Registry ZIP evidence-key delta review</h3><p className="operations-note">These are registry ZIP evidence keys, never an operational USPS denominator. ZIP5 and ZIP+4 remain separate; no geometry, state, or invalidity is inferred.</p><button className="ghost-button" onClick={()=>void load()}>Recheck retained delta</button>{error&&<p role="alert">Verified delta review unavailable. No cached details or actions are available.</p>}{v&&<><p><strong>{v.production.key_count.toLocaleString()}</strong> current versus {v.prior_candidate.key_count.toLocaleString()} prior · {v.delta.added_count} added · {v.delta.removed_count} removed.</p><p>{v.delta.usps_unverified_added} USPS-unverified · {v.delta.same_code_zcta_added} same-code ZCTA · {v.delta.placeholder_added} placeholders.</p>{v.local_review_drilldown.map(r=><article className="operation-record" key={r.zip5}><h4>{r.zip5}</h4><p>{r.source_provenance.map(s=>s.source_id).join(', ')} · {r.zcta_membership==='not-in-denominator'?'no same-code governed 2020 Census ZCTA':r.zcta_membership} · USPS {r.usps_status} · {r.review_disposition}</p><p>ZIP+4: separate and null</p></article>)}</>}</section>;
}
