import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {APP_ROOT} from './paths.mjs';
import {expectedDemographicCells} from './acs-zcta-demographic-admission.mjs';
import {validateAuthorization,validateOfficialMetadata,validateOfflinePackageManifest} from './acs-zcta-demographic-offline-admission.mjs';

const config=JSON.parse(await fs.readFile(path.join(APP_ROOT,'config/acs-zcta-demographic-admission.json'),'utf8'));
function metadata(){const variables=expectedDemographicCells(config),groups={};for(const group of Object.keys(config.required_tables)){groups[group]={concept:`${group} concept`,universe:`${group} universe`,variables:Object.fromEntries(variables.filter(v=>v.startsWith(group)).map(base=>[base,{label:`${base} label`,estimate:`${base}E`,margin_of_error:`${base}M`,estimate_annotation:`${base}EA`,margin_of_error_annotation:`${base}MA`}]))};}return{schema_version:'acs-zcta-official-metadata@1.0.0',publisher:'United States Census Bureau',dataset:'acs/acs5',vintage:2024,geography:'zip code tabulation area',groups,sentinels:[{value:'-666666666',meaning:'publisher-defined unavailable value'}]};}
const authorization=()=>({schema_version:'acs-zcta-offline-authorization@1.0.0',authorization_id:'fixture-authorization',authorized_at:'2026-10-03T00:00:00.000Z',authorized_by:'synthetic-test-fixture',source_files_supplied_offline:true,network_acquisition_authorized:false,production_enrollment_authorized:false,current_pointer_change_authorized:false});
test('closed official metadata preserves exact four-group E/M/EA/MA roster',()=>{const value=metadata();assert.equal(validateOfficialMetadata(value,config),value);delete value.groups.B02001.variables.B02001_010;assert.throws(()=>validateOfficialMetadata(value,config),/metadata roster/);});
test('authorization cannot grant network, production, or pointer mutation',()=>{assert.equal(validateAuthorization(authorization()).network_acquisition_authorized,false);for(const key of ['network_acquisition_authorized','production_enrollment_authorized','current_pointer_change_authorized']){const value=authorization();value[key]=true;assert.throws(()=>validateAuthorization(value),/authorization/);}});
test('package manifest is closed, bounded, and requires the national governed row count',()=>{const value={schema_version:'acs-zcta-offline-package@1.0.0',dataset:'acs/acs5',vintage:2024,geography:'zip code tabulation area',record_count:33791,artifacts:['authorization.json','data.jsonl','metadata.json'].map((p,i)=>({path:p,bytes:i+1,sha256:'a'.repeat(64)}))};assert.equal(validateOfflinePackageManifest(value),value);assert.throws(()=>validateOfflinePackageManifest({...value,record_count:1}),/package manifest/);assert.throws(()=>validateOfflinePackageManifest({...value,artifacts:[...value.artifacts,{path:'extra',bytes:1,sha256:'a'.repeat(64)}]}),/package manifest/);});
test('implementation contains no network API and managed route remains protected',async()=>{const code=await fs.readFile(new URL('./acs-zcta-demographic-offline-admission.mjs',import.meta.url),'utf8'),server=await fs.readFile(new URL('./server.mjs',import.meta.url),'utf8');assert.doesNotMatch(code,/\bfetch\s*\(|https?:\/\//);assert.ok(server.indexOf('controlPlane.authorize(request)')<server.indexOf("endpoint === 'source-admissions'"));assert.match(server,/startAcsZctaDemographicAdmission/);});
