import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {readAdjacentExactZipEvidenceCatalog as readCatalog} from './adjacent-exact-zip-evidence-catalog.mjs';

const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
async function tamperedRoot(change){const root=await mkdtemp(path.join(tmpdir(),'adjacent-catalog-'));await mkdir(path.join(root,'config/datasets'),{recursive:true});const source=JSON.parse(await readFile(new URL('../config/datasets/adjacent-exact-zip-evidence-catalog.json',import.meta.url),'utf8'));change(source);const bytes=Buffer.from(`${JSON.stringify(source,null,2)}\n`);await writeFile(path.join(root,'config/datasets/adjacent-exact-zip-evidence-catalog.json'),bytes);await writeFile(path.join(root,'config/datasets/adjacent-exact-zip-evidence-catalog-registration.json'),`${JSON.stringify({schema_version:'adjacent-exact-zip-evidence-catalog-registration@1.0.0',dataset_id:'adjacent-exact-zip-evidence-catalog',catalog_path:'config/datasets/adjacent-exact-zip-evidence-catalog.json',catalog_sha256:sha(bytes),status:'registered-local-review-only-read-model',production_enrollment:false,mutable_pointer:false},null,2)}\n`);return root;}

test('replays every registered catalog entry and conserves rows',async()=>{const view=await readCatalog();assert.equal(view.entries.length,2);const mn=view.entries.find(row=>row.id==='mn-residential-construction-credentials');assert.deepEqual(mn.counts,{source_rows:11456,zip5_bearing_rows:11455,missing_zip5_rows:1,zip4_rows:0,positive_zip5_keys:961,projected_rows:11455});const pharmacy=view.entries.find(row=>row.id==='national-pharmacy-nonprimary-addresses');assert.deepEqual(pharmacy.counts,{source_rows:420,zip5_bearing_rows:420,missing_zip5_rows:0,zip4_rows:369,positive_zip5_keys:377,projected_rows:420});for(const row of view.entries){assert.equal(row.counts.source_rows,row.counts.zip5_bearing_rows+row.counts.missing_zip5_rows);assert.equal(row.claims.current_operations_verified,false);assert.equal(row.claims.matrix_admission_performed,false);}});
test('rejects catalog hash tamper',async()=>{const root=await mkdtemp(path.join(tmpdir(),'adjacent-catalog-hash-'));await mkdir(path.join(root,'config/datasets'),{recursive:true});await writeFile(path.join(root,'config/datasets/adjacent-exact-zip-evidence-catalog-registration.json'),await readFile(new URL('../config/datasets/adjacent-exact-zip-evidence-catalog-registration.json',import.meta.url)));await writeFile(path.join(root,'config/datasets/adjacent-exact-zip-evidence-catalog.json'),'{}\n');await assert.rejects(()=>readCatalog({root}));});
test('rejects duplicate IDs and broken conservation before entry replay',async()=>{const duplicate=await tamperedRoot(value=>value.entries.push(structuredClone(value.entries[0])));await assert.rejects(()=>readCatalog({root:duplicate}));const broken=await tamperedRoot(value=>{value.entries[0].expected_counts.missing_zip5_rows=2;});await assert.rejects(()=>readCatalog({root:broken}));});
test('rejects an unknown entry verifier without inventing unavailable counts',async()=>{const root=await tamperedRoot(value=>{value.entries[0].verifier_id='unknown-exact-zip-projector@1.0.0';});await assert.rejects(()=>readCatalog({root}));});
test('honors cancellation before catalog work',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(()=>readCatalog({signal:controller.signal}),error=>error?.name==='AbortError');});
