import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import {stateAccessIndustrySummary} from './state-access-view.mjs';

const require=createRequire(import.meta.url),source=await readFile(new URL('../app/administration.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const jsx=(type,props)=>({type,props:props??{}}),nodes=tree=>!tree||typeof tree!=='object'?[]:Array.isArray(tree)?tree.flatMap(nodes):[tree,...nodes(tree.props?.children)],text=tree=>tree==null||typeof tree==='boolean'?'':typeof tree!=='object'?String(tree):Array.isArray(tree)?tree.map(text).join(''):text(tree.props?.children),flush=()=>new Promise(resolve=>setImmediate(resolve));
function moduleWith({request=async()=>{throw Error('unexpected')}}={}){const exports={},states=[],setters=[];let cursor=0,mounted=false,effects=[];const react={useState(initial){const i=cursor++;if(!(i in states))states[i]=initial;const set=value=>{states[i]=typeof value==='function'?value(states[i]):value};setters[i]=set;return[states[i],set]},useEffect(effect){if(!mounted)effects.push(effect)}};runInNewContext(`${code}`,{exports,module:{exports},require:id=>id==='react'?react:id==='react/jsx-runtime'?{jsx,jsxs:jsx,Fragment:'fragment'}:id==='./runner-client'?{runnerJson:request}:require(id),AbortController,Blob,URL,document:{createElement:()=>({click(){}})}});const render=()=>{cursor=0;return exports.default()};const mount=async()=>{const tree=render();mounted=true;for(const effect of effects)effect();effects=[];await flush();await flush();return tree};return{exports,states,setters,render,mount};}
const settings=(maintained=['construction'])=>({industries:['childcare','construction','financial-services','health-care','local-business-licenses','retail-consumer','sales-tax-outlets','tax-exempt-organizations','transportation'].map(id=>({id,label:id})),maintainedIndustries:maintained,revision:7,semantics:'Intent only.'});

test('Administration summary validator enforces pin, exact 9x51 conservation, vocabularies and claims',async()=>{const h=moduleWith(),value=await stateAccessIndustrySummary();assert.equal(h.exports.validAdministrationIndustryEvidence(value),true);for(const mutate of [v=>{v.report_sha256='0'.repeat(64)},v=>{v.industry_cells=458},v=>{v.industries.pop()},v=>{v.industries[1].id=v.industries[0].id},v=>{v.industries[0].states.pop()},v=>{v.industries[0].states[0].access_status='invented'},v=>{v.industries[0].access_status_counts['unsupported-missing']++;v.industries[0].access_status_counts['unsupported-evidence-not-measured']--},v=>{v.claims.nationwide_industry_completeness=100},v=>{v.extra=true}]){const changed=structuredClone(value);mutate(changed);assert.equal(h.exports.validAdministrationIndustryEvidence(changed),false)}});

test('Administration renders all nine validated status rows with draft and authorization boundaries',async()=>{const evidence=await stateAccessIndustrySummary(),view=settings(),backlog={schema_version:'state-access-maintenance-backlog@1.1.0',report_sha256:'a977e9477c9db453c394100b859bdf8dda839fc33ddc0a9761c9195d10d586af',backlog_sha256:'a'.repeat(64),maintenance_revision:7,maintained_industries:['construction'],total_attention_cells:0,batch_limit:10,next_batch:[],remaining_after_batch:0,claims:{acquisition_authorized:false,dispatch_performed:false,production_change:false,business_completeness:null}},h=moduleWith({request:async url=>url.includes('state-access-industry-summary')?evidence:url.includes('industry-backlog')?backlog:view});await h.mount();let tree=h.render(),rendered=text(tree);assert.equal(nodes(tree).filter(node=>node.type==='input'&&node.props?.type==='checkbox').length,9);assert.match(rendered,/Displayed selection is persisted/);assert.match(rendered,/Authorization not represented by this ledger; maintenance selection grants none/);assert.match(rendered,/of jurisdictions \(/);assert.match(rendered,/Temporal status:/);nodes(tree).find(node=>node.type==='input'&&node.props?.type==='checkbox'&&!node.props.checked).props.onChange();tree=h.render();assert.match(text(tree),/Unsaved draft — persisted selection is unchanged/)});

test('failed or stale save refetches and renders only the persisted selection',async()=>{const evidence=await stateAccessIndustrySummary(),durable=settings(['construction']);let put=false;const h=moduleWith({request:async(url,options={})=>{if(url.includes('state-access-industry-summary'))return evidence;if(url.includes('industry-backlog'))throw Error('not needed');if(options.method==='PUT'){put=true;throw Error('stale revision')}return durable}});await h.mount();let tree=h.render();const childcare=nodes(tree).find(node=>node.type==='input'&&node.props?.type==='checkbox'&&!node.props.checked);childcare.props.onChange();tree=h.render();assert.match(text(tree),/Unsaved draft/);const save=nodes(tree).find(node=>node.type==='button'&&text(node).includes('Save maintenance selection'));await save.props.onClick();assert.equal(put,true);tree=h.render();assert.match(text(tree),/Save failed or was stale. Reloaded the persisted maintenance selection/);assert.match(text(tree),/Displayed selection is persisted/);assert.equal(nodes(tree).filter(node=>node.type==='input'&&node.props?.checked).length,1)});

test('malformed settings fail closed and show no selector',async()=>{const h=moduleWith({request:async url=>url.includes('state-access')?{}:{...settings(),extra:true}});await h.mount();const tree=h.render();assert.match(text(tree),/Administration settings are unavailable. No selection was inferred/);assert.equal(nodes(tree).some(node=>node.type==='input'&&node.props?.type==='checkbox'),false)});
