import assert from "node:assert/strict";
import test from "node:test";
import {loadArkansasBusinessSourceReassessment,validateArkansasBusinessSourceReassessment} from "./arkansas-business-source-reassessment.mjs";
import {loadStateBusinessSourceValidationAssessment} from "./state-business-source-validation-wave.mjs";
import {APP_ROOT} from "./paths.mjs";
import path from "node:path";

test("current Arkansas reassessment records paid products without widening authority",async()=>{const value=await loadArkansasBusinessSourceReassessment();assert.equal(value.decision,"hold");assert.equal(value.connector_candidate,false);assert.match(value.access.bulk,/\$2,000 per month/);assert.match(value.access.list_builder,/\$0.10 per record/);assert.match(value.access.subscriber_account,/\$150 per year/);assert.equal(value.fields.published,false);assert.match(value.statewide_completeness,/not established/);for(const [key,expected]of Object.entries({record_requests:0,downloads:0,accounts_created:0,terms_accepted:0,fees_paid:0,contacts_made:0,portal_automation:false,production_changes:0}))assert.equal(value.controls[key],expected);});
test("historical September Arkansas assessment remains independently loadable",async()=>{const historical=await loadStateBusinessSourceValidationAssessment(path.join(APP_ROOT,"config","state-business-source-ar-2026-09-22.json"),"AR");assert.equal(historical.assessment_id,"state-business-source-ar-20260922-v1");assert.equal(historical.observed_at,"2026-09-22");assert.match(historical.access.fees,/no stable public statewide price/);});
test("Arkansas reassessment rejects authority, readiness, and evidence escalation",async()=>{const original=await loadArkansasBusinessSourceReassessment();for(const mutate of [value=>{value.connector_candidate=true;},value=>{value.decision="connector-candidate";},value=>{value.controls.accounts_created=1;},value=>{value.controls.fees_paid=2000;},value=>{value.fields.published=true;},value=>{value.statewide_completeness="Statewide complete.";},value=>{value.supersedes_assessment_id="other";}]){const value=structuredClone(original);mutate(value);assert.throws(()=>validateArkansasBusinessSourceReassessment(value));}});
