import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {readBusinessIntelligenceReadiness} from './business-intelligence-readiness.mjs';

test('projects pinned non-additive pharmacy and FMCSA memberships plus ZIP blockers',async()=>{const view=await readBusinessIntelligenceReadiness();assert.equal(view.schema_version,'business-intelligence-readiness-view@1.1.0');assert.equal(view.source_replay_performed,false);assert.equal(view.pharmacy_overlay.summary.pharmacy_rows,89077);assert.equal(view.pharmacy_overlay.summary.generic_business_additivity_delta,0);assert.equal(view.fmcsa_transportation_membership.summary.fmcsa_rows,2195563);assert.equal(view.fmcsa_transportation_membership.summary.exact_usdot_membership_matches,2195563);assert.equal(view.fmcsa_transportation_membership.summary.generic_business_additivity_delta,0);assert.equal(view.fmcsa_transportation_membership.claims.unique_business,false);assert.equal(view.fmcsa_transportation_membership.claims.current_operation_beyond_source,false);assert.equal(view.fmcsa_transportation_membership.claims.nationwide_completeness,false);assert.equal(view.fmcsa_transportation_membership.claims.authoritative_current_usps_zip_denominator,null);assert.equal(view.zip_denominator.status,'blocked-on-authorized-authoritative-input');assert.deepEqual(view.zip_denominator.blockers,['missing-authorized-authoritative-usps-zip-artifact','missing-governed-production-eligible-usps-permission-evidence','authoritative-current-usps-denominator-unverified']);assert.equal(view.zip_denominator.retained_zip_evidence.usps_unverified,48194);});

const sourceRoot=fileURLToPath(new URL('..',import.meta.url));
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'bi-readiness-'));for(const relative of ['config/datasets/national-nppes-pharmacy-registry-overlay.json','config/datasets/national-fmcsa-registry-industry-overlay.json','config/datasets/zip-denominator-admission-readiness.json']){await fs.mkdir(path.dirname(path.join(root,relative)),{recursive:true});await fs.copyFile(path.join(sourceRoot,relative),path.join(root,relative));}for(const dataset of ['national-nppes-pharmacy-registry-overlay','national-fmcsa-registry-industry-overlay','zip-denominator-admission-readiness'])await fs.cp(path.join(sourceRoot,'data',dataset),path.join(root,'data',dataset),{recursive:true});return root;}
const rejects=root=>assert.rejects(readBusinessIntelligenceReadiness({root}),/unavailable or incompatible/);
test('rejects bad pins, unsafe paths, manifest identity drift, malformed and oversized registrations',async t=>{for(const mutation of [async root=>{const file=path.join(root,'config/datasets/national-nppes-pharmacy-registry-overlay.json'),v=JSON.parse(await fs.readFile(file));v.retained_release.manifest_sha256='0'.repeat(64);await fs.writeFile(file,JSON.stringify(v));},async root=>{const file=path.join(root,'config/datasets/national-nppes-pharmacy-registry-overlay.json'),v=JSON.parse(await fs.readFile(file));v.retained_release.manifest='../escape.json';await fs.writeFile(file,JSON.stringify(v));},async root=>{const registration=path.join(root,'config/datasets/national-nppes-pharmacy-registry-overlay.json'),v=JSON.parse(await fs.readFile(registration)),manifest=path.join(root,v.retained_release.manifest),m=JSON.parse(await fs.readFile(manifest));m.release_id='national-nppes-pharmacy-registry-overlay-'+'0'.repeat(64);const raw=Buffer.from(JSON.stringify(m));await fs.writeFile(manifest,raw);v.retained_release.manifest_sha256=createHash('sha256').update(raw).digest('hex');await fs.writeFile(registration,JSON.stringify(v));},async root=>fs.writeFile(path.join(root,'config/datasets/national-nppes-pharmacy-registry-overlay.json'),'{bad'),async root=>fs.writeFile(path.join(root,'config/datasets/national-nppes-pharmacy-registry-overlay.json'),' '.repeat(64001))]){const root=await fixture();t.after(()=>fs.rm(root,{recursive:true,force:true}));await mutation(root);await rejects(root);}});
test('honors pre-abort and rejects linked ancestry',async t=>{const root=await fixture();t.after(()=>fs.rm(root,{recursive:true,force:true}));const controller=new AbortController();controller.abort();await assert.rejects(readBusinessIntelligenceReadiness({root,signal:controller.signal}),error=>error.name==='AbortError');const linked=await fs.mkdtemp(path.join(os.tmpdir(),'bi-readiness-link-'));t.after(()=>fs.rm(linked,{recursive:true,force:true}));await fs.rename(path.join(root,'config'),path.join(linked,'config'));try{await fs.symlink(path.join(linked,'config'),path.join(root,'config'),process.platform==='win32'?'junction':'dir');}catch(error){if(['EPERM','EACCES','UNKNOWN'].includes(error.code)){t.skip('link creation unavailable');return;}throw error;}await rejects(root);});
test('rejects stale or malformed FMCSA registration and manifest evidence',async t=>{const registrationMutation=(key,value)=>async root=>{const file=path.join(root,'config/datasets/national-fmcsa-registry-industry-overlay.json'),v=JSON.parse(await fs.readFile(file));v.retained_release[key]=value;await fs.writeFile(file,JSON.stringify(v));};const manifestMutation=change=>async root=>{const registration=path.join(root,'config/datasets/national-fmcsa-registry-industry-overlay.json'),v=JSON.parse(await fs.readFile(registration)),manifest=path.join(root,v.retained_release.manifest),m=JSON.parse(await fs.readFile(manifest));change(m);const raw=Buffer.from(JSON.stringify(m));await fs.writeFile(manifest,raw);v.retained_release.manifest_sha256=createHash('sha256').update(raw).digest('hex');await fs.writeFile(registration,JSON.stringify(v));};for(const mutate of [registrationMutation('release_id','national-fmcsa-registry-industry-overlay-stale'),registrationMutation('membership_rows',-1),registrationMutation('jurisdiction_rows','56'),registrationMutation('zip5_denominator_rows',Number.MAX_SAFE_INTEGER+1),registrationMutation('positive_zip5_rows',48195),manifestMutation(m=>{m.claims.current_operation_beyond_source=true;}),manifestMutation(m=>{m.summary.exact_site_identity_matches='2195563';}),manifestMutation(m=>{m.summary.extra_identities=-1;}),manifestMutation(m=>{m.summary.fmcsa_rows=Number.MAX_SAFE_INTEGER+1;}),manifestMutation(m=>{m.claims.source_defined_active_fmcsa_registration_as_of='2026-08-30';})]){const root=await fixture();t.after(()=>fs.rm(root,{recursive:true,force:true}));await mutate(root);await rejects(root);}});
