import assert from 'node:assert/strict';
import test from 'node:test';
import {CA_CHILDCARE_RESOURCES,CA_CHILDCARE_SELECTED_FIELDS} from './ca-childcare-acquisition.mjs';
import {CA_CHILDCARE_NORMALIZATION_VERSION,normalizeCaChildcarePages,normalizeCaChildcareRecord} from './ca-childcare-normalization.mjs';

const resource=CA_CHILDCARE_RESOURCES[0].id;
function row(overrides={}){return Object.assign(Object.fromEntries(CA_CHILDCARE_SELECTED_FIELDS.map(key=>[key,null])),{_id:1,facility_type:'CHILD CARE CENTER',facility_number:'01234567',facility_name:'Example Center',facility_address:'10 Main St',facility_city:'Sacramento',facility_state:'CA',facility_zip:'95814-1234',county_name:'Sacramento',regional_office:'SACRAMENTO',facility_capacity:'42',facility_status:'LICENSED',license_first_date:'01/02/2020',closed_date:null,file_date:'05/25/2025'},overrides)}
const context={resourceId:resource,sourceReleaseId:'ca-acquired-fixture',ingestRunId:'ca-normalize-fixture',observedAt:'2026-10-07T10:00:00.000Z',processedAt:'2026-10-07T11:00:00.000Z'};

test('normalizes California publisher evidence without promoting it to a current business or site',()=>{const value=normalizeCaChildcareRecord(row(),context);assert.equal(value.schema_version,'ca-childcare-normalized-record@1.0.0');assert.equal(value.business_name,'Example Center');assert.deepEqual(value.reported_address,{street:'10 Main St',city:'Sacramento',state:'CA',state_source:'CA',country:'US',county_source:'Sacramento',zip_code:'95814',postal_code:'95814',zip4:'1234',address_role:'publisher-reported-facility-address-not-independently-verified'});assert.deepEqual(value.geocode,{latitude:null,longitude:null,crs:null,status:'not-provided-by-selected-source',inferred:false});assert.equal(value.source_status.status_source,'LICENSED');assert.equal(value.source_status.active_business_verified,false);assert.equal(value.temporal.license_first_date.iso_date,'2020-01-02');assert.equal(value.temporal.file_date.iso_date,'2025-05-25');assert.equal(value.capacity.value,42);assert.equal(value.external_identifiers[0].value,'01234567');assert.equal(value.claims.current_operations_verified,false);assert.equal(value.claims.physical_site_verified,false);assert.equal(value.claims.zip_validity_verified,false);assert.equal(value.claims.zcta_membership_verified,false);assert.equal(value.claims.ownership_inferred,false);assert.equal(value.claims.network_affiliation_inferred,false);assert.equal(value.export_policy,'internal');assert.equal(value.provenance.transformation_version,CA_CHILDCARE_NORMALIZATION_VERSION)});

test('preserves missing and invalid geography as gaps and keeps ZIP4 separate',()=>{const missing=normalizeCaChildcareRecord(row({_id:2,facility_zip:null,facility_address:null,facility_city:null,facility_state:null,facility_capacity:'unknown',license_first_date:'unknown'}),context);assert.equal(missing.reported_address.zip_code,null);assert.equal(missing.reported_address.postal_code,null);assert.equal(missing.reported_address.zip4,null);assert.equal(missing.quality.zip_unavailable_reason,'missing-source-zip');assert.equal(missing.quality.address_unavailable_reason,'missing-source-address');assert.equal(missing.quality.state_scope_conflict,false);assert.equal(missing.capacity.value,null);assert.equal(missing.temporal.license_first_date.iso_date,null);const foreign=normalizeCaChildcareRecord(row({_id:3,facility_state:'NV',facility_zip:'89101'}),context);assert.equal(foreign.reported_address.state,'NV');assert.equal(foreign.quality.state_scope_conflict,true);const invalid=normalizeCaChildcareRecord(row({_id:4,facility_zip:'95814 1234'}),context);assert.equal(invalid.reported_address.zip_code,null);assert.equal(invalid.quality.zip_unavailable_reason,'invalid-source-zip-format')});

test('batch normalization conserves source rows, resource identity, statuses and cancellation',async()=>{const pages=[{resource_id:resource,offset:0,observed_at:context.observedAt,records:[row(),row({_id:2,facility_status:'CLOSED',facility_zip:null})]}],value=await normalizeCaChildcarePages(pages,{sourceReleaseId:context.sourceReleaseId,ingestRunId:context.ingestRunId,processedAt:context.processedAt});assert.equal(value.summary.source_records,2);assert.equal(value.summary.accepted_records,2);assert.equal(value.summary.quarantined_records,0);assert.equal(value.summary.accepted_with_zip5,1);assert.equal(value.summary.accepted_with_zip4,1);assert.equal(value.summary.accepted_with_points,0);assert.deepEqual(value.summary.status_counts,{CLOSED:1,LICENSED:1});assert.deepEqual(value.summary.zip_gap_counts,{'missing-source-zip':1});assert.equal(value.records.length+value.quarantine.length,2);await assert.rejects(normalizeCaChildcarePages(pages,{sourceReleaseId:context.sourceReleaseId,ingestRunId:context.ingestRunId,processedAt:context.processedAt},{signal:AbortSignal.abort()}));await assert.rejects(normalizeCaChildcarePages([{resource_id:resource,offset:0,observed_at:context.observedAt,records:[row()]},{resource_id:resource,offset:500,observed_at:context.observedAt,records:[row()]}],{sourceReleaseId:context.sourceReleaseId,ingestRunId:context.ingestRunId,processedAt:context.processedAt}),/duplicate source key/)});

test('rejects private fields, invalid resource identity and unsafe selected scalars',async()=>{assert.throws(()=>normalizeCaChildcareRecord({...row(),licensee:'private'},context),/selected fields/);assert.throws(()=>normalizeCaChildcareRecord(row(),{...context,resourceId:'foreign'}),/context/);assert.throws(()=>normalizeCaChildcareRecord(row({facility_name:'bad\nname'}),context),/selected row/);await assert.rejects(normalizeCaChildcarePages([{resource_id:'foreign',offset:0,observed_at:context.observedAt,records:[row()]}],{sourceReleaseId:context.sourceReleaseId,ingestRunId:context.ingestRunId,processedAt:context.processedAt}),/page/)});
