import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {APP_ROOT} from './paths.mjs';
import {CA_CHILDCARE_RESOURCES,CA_CHILDCARE_SELECTED_FIELDS} from './ca-childcare-acquisition.mjs';
import {buildCaChildcareAcquiredReleaseWithTransport} from './ca-childcare-acquired-release.mjs';
import {buildCaChildcareNormalizedRelease,verifyCaChildcareNormalizedRelease} from './ca-childcare-normalized-release.mjs';

function transport(){return async url=>{const parsed=new URL(String(url)),id=parsed.searchParams.get('resource_id'),resource=CA_CHILDCARE_RESOURCES.find(row=>row.id===id),limit=Number(parsed.searchParams.get('limit'));let result;if(limit===0)result={resource_id:id,total:resource.total,records:[]};else{const offset=Number(parsed.searchParams.get('offset')),count=Math.min(500,resource.total-offset);result={resource_id:id,records:Array.from({length:count},(_,index)=>Object.fromEntries(CA_CHILDCARE_SELECTED_FIELDS.map(key=>[key,key==='_id'?offset+index+1:key==='facility_state'?'CA':key==='facility_zip'?'90001':key==='facility_status'?(index%2?'LICENSED':'CLOSED'):key==='facility_capacity'?'12':key==='license_first_date'?'01/02/2020':key==='closed_date'?null:key==='file_date'?'05/25/2025':`${key}-${offset+index+1}`])))}}return new Response(JSON.stringify({success:true,result}),{headers:{'content-type':'application/json'}})}}

test('publishes and independently replays the complete California normalized release',async()=>{const root=await mkdtemp(path.join(APP_ROOT,'data/tmp/ca-normalized-release-'));try{const acquired=await buildCaChildcareAcquiredReleaseWithTransport({outputRoot:path.join(root,'acquired'),fetchImpl:transport(),runId:'11111111-2222-4333-8444-555555555555',now:()=>new Date('2026-10-07T10:00:00.000Z')}),verification=await buildCaChildcareNormalizedRelease(acquired.manifest_path,{outputRoot:path.join(root,'normalized'),runId:'22222222-2222-4333-8444-555555555555',processedAt:'2026-10-07T11:00:00.000Z'});assert.equal(verification.source_record_count,39184);assert.equal(verification.accepted_record_count,39184);assert.equal(verification.quarantine_count,0);const read=await verifyCaChildcareNormalizedRelease(verification.manifest_path);assert.equal(read.summary.accepted_with_zip5,39184);assert.equal(read.summary.accepted_with_points,0);assert.equal(read.manifest.claims.current_operations_verified,false);assert.equal(read.manifest.claims.physical_site_verified,false);assert.equal(read.manifest.claims.zcta_membership_verified,false);const recordsPath=path.join(path.dirname(verification.manifest_path),'normalized.jsonl'),bytes=await readFile(recordsPath);await writeFile(recordsPath,Buffer.concat([bytes,Buffer.from('{}\n')]));await assert.rejects(verifyCaChildcareNormalizedRelease(verification.manifest_path),/artifact integrity/);await writeFile(recordsPath,bytes);await verifyCaChildcareNormalizedRelease(verification.manifest_path)}finally{await rm(root,{recursive:true,force:true})}});

test('normalization cancellation and invalid output never publish a final manifest',async()=>{const root=await mkdtemp(path.join(APP_ROOT,'data/tmp/ca-normalized-cancel-'));try{const acquired=await buildCaChildcareAcquiredReleaseWithTransport({outputRoot:path.join(root,'acquired'),fetchImpl:transport(),runId:'33333333-2222-4333-8444-555555555555'});await assert.rejects(buildCaChildcareNormalizedRelease(acquired.manifest_path,{outputRoot:path.join(root,'normalized'),signal:AbortSignal.abort(),runId:'44444444-2222-4333-8444-555555555555'}));await assert.rejects(readFile(path.join(root,'normalized','ca-childcare-normalized-44444444-2222-4333-8444-555555555555','manifest.json')));await assert.rejects(buildCaChildcareNormalizedRelease(acquired.manifest_path,{outputRoot:APP_ROOT,runId:'55555555-2222-4333-8444-555555555555'}))}finally{await rm(root,{recursive:true,force:true})}});
