import assert from 'node:assert/strict';
import {mkdtemp,readFile,readdir,rm,writeFile} from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {APP_ROOT} from './paths.mjs';
import {CA_CHILDCARE_RESOURCES,CA_CHILDCARE_SELECTED_FIELDS} from './ca-childcare-acquisition.mjs';
import {runCaChildcareApp,runCaChildcareAppWithTransport,verifyCaChildcareAppReceipt} from './ca-childcare-app.mjs';

function transport(hook=()=>{}){let calls=0;return async url=>{calls++;await hook(calls);const parsed=new URL(String(url)),id=parsed.searchParams.get('resource_id'),resource=CA_CHILDCARE_RESOURCES.find(row=>row.id===id),limit=Number(parsed.searchParams.get('limit'));let result;if(limit===0)result={resource_id:id,total:resource.total,fields:[],records:[]};else{const offset=Number(parsed.searchParams.get('offset')),count=Math.min(500,resource.total-offset);result={resource_id:id,records:Array.from({length:count},(_,index)=>Object.fromEntries(CA_CHILDCARE_SELECTED_FIELDS.map(key=>[key,key==='_id'?offset+index+1:key==='facility_state'?'CA':key==='facility_zip'?'90001':key==='facility_status'?'LICENSED':`${key}-${offset+index+1}`])))}}return new Response(JSON.stringify({success:true,result}),{headers:{'content-type':'application/json'}})}}

test('California app publishes durable verified receipts and reuses retained acquisition without fetching',async()=>{const root=await mkdtemp(path.join(APP_ROOT,'data/tmp/ca-app-test-'));try{const result=await runCaChildcareAppWithTransport({outputRoot:path.join(root,'first'),fetchImpl:transport(),industryRunId:'childcare-ca'});assert.equal(result.receipt.status,'SUCCEEDED');assert.equal(result.receipt.claims.provider_rows_acquired,true);assert.equal(result.receipt.claims.normalization_performed,false);assert.equal(result.receipt.acquired.record_count,39184);await verifyCaChildcareAppReceipt(result.receipt_path);const manifestBytes=await readFile(result.receipt.acquired.manifest_path),oldFetch=globalThis.fetch;globalThis.fetch=()=>assert.fail('retained reuse must not fetch');try{const reused=await runCaChildcareApp({outputRoot:path.join(root,'reuse'),acquiredManifestPath:result.receipt.acquired.manifest_path});assert.equal(reused.receipt.execution_mode,'retained-local-verification');assert.equal(reused.receipt.acquired.manifest_sha256,result.receipt.acquired.manifest_sha256);await verifyCaChildcareAppReceipt(reused.receipt_path)}finally{globalThis.fetch=oldFetch}assert.deepEqual(await readFile(result.receipt.acquired.manifest_path),manifestBytes);const bytes=await readFile(result.receipt_path),changed=JSON.parse(bytes);changed.claims.production_admission=true;await writeFile(result.receipt_path,`${JSON.stringify(changed)}\n`);await assert.rejects(verifyCaChildcareAppReceipt(result.receipt_path));await writeFile(result.receipt_path,bytes)}finally{await rm(root,{recursive:true,force:true})}});

test('California app excludes concurrent ownership and preserves failed and cancelled terminal evidence',async()=>{const root=await mkdtemp(path.join(APP_ROOT,'data/tmp/ca-app-lifecycle-'));try{let release,arrive;const gate=new Promise(resolve=>{release=resolve}),entered=new Promise(resolve=>{arrive=resolve}),fetch=transport(async call=>{if(call===1){arrive();await gate}}),running=runCaChildcareAppWithTransport({outputRoot:path.join(root,'locked'),fetchImpl:fetch});await entered;await assert.rejects(runCaChildcareAppWithTransport({outputRoot:path.join(root,'locked'),fetchImpl:transport()}));release();await running;const failedRoot=path.join(root,'failed');await assert.rejects(runCaChildcareAppWithTransport({outputRoot:failedRoot,fetchImpl:transport(call=>{if(call===4)throw Error('private failure')})}));const [failedId]=await readdir(path.join(failedRoot,'operations')),failed=JSON.parse(await readFile(path.join(failedRoot,'operations',failedId,'receipt.json')));assert.equal(failed.status,'FAILED');assert.equal(failed.claims.provider_rows_acquired,false);const cancelledRoot=path.join(root,'cancelled'),controller=new AbortController();await assert.rejects(runCaChildcareAppWithTransport({outputRoot:cancelledRoot,signal:controller.signal,fetchImpl:transport(call=>{if(call===3)controller.abort()})}));const [cancelledId]=await readdir(path.join(cancelledRoot,'operations')),cancelled=JSON.parse(await readFile(path.join(cancelledRoot,'operations',cancelledId,'receipt.json')));assert.equal(cancelled.status,'CANCELLED');assert.equal(cancelled.output_state,'inspection-required')}finally{await rm(root,{recursive:true,force:true})}});
