import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {readFile,writeFile,rm,unlink,lstat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {APP_ROOT} from './paths.mjs';
import {runCensusGeocoderDemoFixture as run,verifyCensusGeocoderDemoFixture as verify,verifyCensusGeocoderDemo as nativeVerify} from './census-geocoder-demo-prerequisite.mjs';
const base=path.join(APP_ROOT,'data/tmp/census-geocoder-demo'),lease=path.join(base,'.source-lease'),catalog=Buffer.from(JSON.stringify({benchmarks:[{id:'8',benchmarkName:'Public_AR_ACS2025',isDefault:false}]}));
async function gone(file){await assert.rejects(lstat(file),{code:'ENOENT'});}
async function cleanup(result){const d=result.directory;assert.equal(path.dirname(d),path.join(base,'jobs'));assert.match(path.basename(d),/^[a-f0-9-]{36}$/);await rm(d,{recursive:true,force:true});}
function transport(change){let count=0;const calls=[];const fetch=async(url,opts)=>{count++;calls.push({url,opts});let bytes=catalog;if(opts.method==='POST'){const body=Buffer.from(opts.body).toString(),id=body.match(/[a-f0-9]{8}-[a-f0-9-]{27}/)[0];assert.match(body,/"4600 Silver Hill Rd","Washington","DC","20233"/);assert.ok(body.includes('name="benchmark"\r\n\r\n8'));bytes=Buffer.from(`"${id}","4600 Silver Hill Rd Washington DC 20233",Match,Exact,"4600 SILVER HILL RD WASHINGTON DC 20233","-76.92,38.84",123,L\n`);}return change?.(count,url,opts,bytes)??new Response(bytes,{status:200,headers:{'content-type':opts.method==='POST'?'text/csv':'application/json'}});};return {fetch,calls};}
test('fixed demo fixture publishes manifest last, independent replay and native rejection',async()=>{const t=transport();const r=await run(t.fetch);try{assert.equal(t.calls.length,3);assert.deepEqual(t.calls.map(c=>c.opts.method),['GET','POST','GET']);for(const c of t.calls){assert.equal(c.opts.credentials,'omit');assert.equal(c.opts.redirect,'manual');}const m=await verify(r.manifestPath,r.manifestSha256);assert.equal(m.claims.nativeTransportObserved,false);assert.equal(m.claims.allResponseVariantsVerified,false);assert.equal(m.observation.fieldCount,8);await assert.rejects(nativeVerify(r.manifestPath,r.manifestSha256));await gone(lease);const csv=path.join(r.directory,'response.csv');await writeFile(csv,'bad');await assert.rejects(verify(r.manifestPath,r.manifestSha256));}finally{await cleanup(r);}});
test('missing explicit benchmark fails before POST with durable failure',async()=>{const t=transport(()=>new Response('{"benchmarks":[{"id":"4","benchmarkName":"Public_AR_Current"}]}'));let recovery;try{await run(t.fetch);assert.fail('reject');}catch(e){recovery=e.recovery;}try{const failure=JSON.parse(await readFile(path.join(recovery.directory,'failure.json')));assert.equal(t.calls.length,1);assert.equal(failure.requests.length,1);assert.equal(failure.submissionOrCleanupUnresolved,false);await gone(lease);}finally{await cleanup(recovery);}});
test('complete invalid response preserves raw evidence and releases settled lease',async()=>{const t=transport((i,u,o,b)=>new Response(i===2?'private-unrecognized-value':b));let recovery;try{await run(t.fetch);assert.fail('must reject');}catch(e){recovery=e.recovery;}try{const failure=JSON.parse(await readFile(path.join(recovery.directory,'failure.json')));assert.equal(failure.requests.length,3);assert.equal(failure.submissionOrCleanupUnresolved,false);assert.ok(failure.artifacts.some(a=>a.path==='response.csv'));await gone(path.join(recovery.directory,'manifest.json'));await gone(lease);}finally{await cleanup(recovery);}});
test('redirect and response cap reject without retry and preserve uncertain POST ownership',async()=>{for(const kind of ['redirect','cap']){const t=transport((i,u,o,b)=>i===2?new Response(kind==='cap'?Buffer.alloc(65537):'',{status:kind==='redirect'?302:200}):new Response(b));let r;try{await run(t.fetch);assert.fail('reject');}catch(e){r=e.recovery;}try{assert.equal(t.calls.length,2);const failure=JSON.parse(await readFile(path.join(r.directory,'failure.json')));if(kind==='cap'){assert.equal(failure.submissionOrCleanupUnresolved,true);assert.ok(await lstat(lease));await unlink(lease);}else await gone(lease);}finally{await cleanup(r);}}});
test('post-publication error retains descriptor and immutable manifest',async()=>{const t=transport();let r;try{await run(t.fetch,{},phase=>{if(phase==='after-publication')throw Error('test');});assert.fail('reject');}catch(e){r=e.recovery;}try{assert.equal(r.inspectionRequired,true);await verify(r.manifestPath,r.manifestSha256);await gone(lease);}finally{await cleanup(r);}});
test('shared provider lease prevents parallel fixture sessions',async()=>{let unblock,started;const ready=new Promise(r=>started=r),pause=new Promise(r=>unblock=r),t=transport(async(i,u,o,b)=>{if(i===1){started();await pause;}return new Response(b);});const first=run(t.fetch);await ready;await assert.rejects(run(()=>assert.fail('second request')),/lease unavailable/);unblock();const r=await first;await cleanup(r);await gone(lease);});
test('noncooperative POST abort returns bounded uncertain receipt and retained lease',async()=>{const c=new AbortController(),t=transport((i,u,o,b)=>{if(i===2){setTimeout(()=>c.abort(),5);return new Promise(()=>{});}return new Response(b);}),start=Date.now();let r;try{await run(t.fetch,{signal:c.signal});assert.fail('reject');}catch(e){r=e.recovery;}try{assert.ok(Date.now()-start<5000);assert.equal(r.sourceLeaseRetained,true);assert.ok(await lstat(lease));assert.equal(t.calls.length,2);}finally{await unlink(lease);await cleanup(r);}});
test('lease cleanup uncertainty preserves published identity without deleting changed owner',async()=>{const t=transport();let r;try{await run(t.fetch,{},async(phase,ctx)=>{if(phase==='before-lease-cleanup'){await unlink(ctx.leasePath);await writeFile(ctx.leasePath,'foreign',{flag:'wx'});}});assert.fail('reject');}catch(e){r=e.recovery;}try{assert.equal(r.inspectionRequired,true);assert.equal(r.leaseCleanupFailed,true);assert.equal(await readFile(lease,'utf8'),'foreign');await verify(r.manifestPath,r.manifestSha256);}finally{await unlink(lease);await cleanup(r);}});
test('malformed CLI and closed API reject before source transport',async()=>{await assert.rejects(run(()=>assert.fail('network'),{address:'other'}));await assert.rejects(run(()=>assert.fail('network'),{signal:AbortSignal.abort()}),{name:'AbortError'});const child=spawnSync(process.execPath,['scripts/preflight-census-geocoder-demo.mjs','--address','other'],{cwd:APP_ROOT,encoding:'utf8',windowsHide:true,timeout:10000});assert.equal(child.status,1);assert.match(child.stderr,/did not complete/);});
test('rehashed impossible request receipt fails independent replay',async()=>{const r=await run(transport().fetch);try{const m=JSON.parse(await readFile(r.manifestPath));m.requests[1].status=500;const bytes=Buffer.from(JSON.stringify(m)+'\n');await writeFile(r.manifestPath,bytes);await assert.rejects(verify(r.manifestPath,createHash('sha256').update(bytes).digest('hex')));}finally{await cleanup(r);}});
test('policy drift rejects before any transport and restores exact owned policy bytes',async()=>{const file=path.join(APP_ROOT,'config/source-policies/census-geocoder-demo-prerequisite.json'),before=await readFile(file);try{await writeFile(file,'{}');await assert.rejects(run(()=>assert.fail('network')));await gone(lease);}finally{await writeFile(file,before);}});
test('oversized content-type retains completed raw response with safe diagnostic',async()=>{const t=transport((i,u,o,b)=>new Response(b,{headers:{'content-type':i===2?'x'.repeat(257):'application/json'}}));let recovery;try{await run(t.fetch);assert.fail('reject');}catch(e){recovery=e.recovery;}try{const failure=JSON.parse(await readFile(path.join(recovery.directory,'failure.json')));assert.equal(failure.requests[1].responseContentType,'[over-limit]');assert.equal(failure.requests[1].responseContentTypeOverLimit,true);const a=failure.artifacts.find(a=>a.path==='response.csv');assert.equal(createHash('sha256').update(await readFile(path.join(recovery.directory,a.path))).digest('hex'),a.sha256);assert.equal(failure.submissionOrCleanupUnresolved,false);await gone(lease);}finally{await cleanup(recovery);}});
test('same-inode changed lease payload is retained for inspection',async()=>{let recovery;try{await run(transport().fetch,{},async(phase,ctx)=>{if(phase==='before-lease-cleanup')await writeFile(ctx.leasePath,'another-owner');});assert.fail('reject');}catch(e){recovery=e.recovery;}try{assert.equal(recovery.leaseCleanupFailed,true);assert.equal(await readFile(lease,'utf8'),'another-owner');await verify(recovery.manifestPath,recovery.manifestSha256);}finally{await unlink(lease);await cleanup(recovery);}});
test('noncooperative body read and cancellation retain uncertain POST lease',async()=>{const c=new AbortController(),t=transport((i,u,o,b)=>i===2?{status:200,redirected:false,headers:new Headers(),body:{getReader(){return {read(){setTimeout(()=>c.abort(),5);return new Promise(()=>{});},cancel(){return new Promise(()=>{});},releaseLock(){}};}}}:new Response(b));let recovery;const start=Date.now();try{await run(t.fetch,{signal:c.signal});assert.fail('reject');}catch(e){recovery=e.recovery;}try{assert.ok(Date.now()-start<5000);assert.equal(recovery.sourceLeaseRetained,true);assert.equal(t.calls.length,2);}finally{await unlink(lease);await cleanup(recovery);}});
test('actual thirty-second request timer bounds a noncooperative fetch',{timeout:35000},async()=>{const start=Date.now();let recovery;try{await run(()=>new Promise(()=>{}));assert.fail('reject');}catch(e){recovery=e.recovery;}try{const elapsed=Date.now()-start;assert.ok(elapsed>=29500&&elapsed<34000,`elapsed ${elapsed}`);assert.equal(recovery.sourceLeaseRetained,true);const failure=JSON.parse(await readFile(path.join(recovery.directory,'failure.json')));assert.equal(failure.requests.length,1);assert.equal(failure.submissionOrCleanupUnresolved,true);}finally{await unlink(lease);await cleanup(recovery);}});
