import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { gzipSync } from "node:zlib";
import { createCensusZbpIndustryView } from "./census-zbp-industry-view.mjs";
import { censusZbpIndustryHttp } from "./census-zbp-industry-http.mjs";

const sha256=value=>createHash("sha256").update(value).digest("hex");
async function fixture(){
 const root=await mkdtemp(path.join(os.tmpdir(),"zbp-industry-")),release=path.join(root,"releases","zbp");await mkdir(path.join(release,"derived","zip-naics"),{recursive:true});
 const artifacts=[];async function put(relative,body,type,extra={}){const target=path.join(release,relative);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,body);artifacts.push({path:relative,bytes:body.length,sha256:sha256(body),artifact_type:type,...extra});}
 const coverage=[{zip_code:"12345",geography:{status:"2020-zcta-polygon-available",geoid:"12345"}},{zip_code:"54321",geography:{status:"no-2020-zcta-polygon",geoid:null}},{zip_code:"99999",geography:{status:"no-2020-zcta-polygon",geoid:null}}].map(JSON.stringify).join("\n")+"\n";
 await put("derived/zip-coverage.jsonl",Buffer.from(coverage),"zip-coverage-union-jsonl");await put("derived/naics-coverage.jsonl",Buffer.from(JSON.stringify({naics_code:"23----"})+"\n"),"naics-coverage-jsonl");
 const header="zip_code,naics_code,establishments,preferred_city,preferred_state,county_name\n";
 for(let i=0;i<10;i++){const rows=i===1?"12345,23----,7,Town,NY,County\n":i===5?"54321,23----,0,Town,CA,County\n":i===9?"99999,23----,4,,,\n":"";await put(`derived/zip-naics/prefix=${i}.csv.gz`,gzipSync(header+rows),"normalized-zbp-naics-csv-gzip",{partition:String(i)});}
 const manifest={dataset_id:"census-zbp-baseline",release_id:"zbp",reference_year:2023,complete_national_release:true,artifacts};await writeFile(path.join(release,"manifest.json"),JSON.stringify(manifest));await writeFile(path.join(root,"current.json"),JSON.stringify({dataset_id:manifest.dataset_id,release_id:"zbp",manifest:"releases/zbp/manifest.json"}));return{root,release,pointer:path.join(root,"current.json")};
}
test("serves one exact code with zero, absence, ZIP5/ZCTA, and unassigned semantics",async()=>{const f=await fixture(),result=await createCensusZbpIndustryView({pointerPath:f.pointer}).get({naics:"23----"});assert.equal(result.total,3);assert.equal(result.records.find(r=>r.zip5==="54321").establishments,0);assert.equal(result.records.find(r=>r.zip5==="54321").zcta_geoid,null);assert.equal(result.records.find(r=>r.zip5==="99999").state,null);assert.equal(result.absent_row_semantics,"not-published-not-zero");assert.equal(result.hierarchical_aggregation_permitted,false);});
test("cooperatively cancels an in-flight scan and closes without accepting more work",async()=>{const f=await fixture(),view=createCensusZbpIndustryView({pointerPath:f.pointer}),controller=new AbortController(),pending=view.get({naics:"23----"},{signal:controller.signal});controller.abort();await assert.rejects(pending,{name:"AbortError"});assert.deepEqual(await view.close(),{active_queries:0});await assert.rejects(view.get({naics:"23----"}),/closed/);});
test("rejects hierarchy lists, bounds, tampering, and escaping manifests",async()=>{let f=await fixture(),view=createCensusZbpIndustryView({pointerPath:f.pointer});await assert.rejects(view.get({naics:"23----,31----"}),/exact six-character/);await assert.rejects(view.get({naics:"23----",limit:35001}),/limit/);f=await fixture();await writeFile(path.join(f.release,"derived/zip-naics/prefix=1.csv.gz"),Buffer.from("tamper"));await assert.rejects(createCensusZbpIndustryView({pointerPath:f.pointer}).get({naics:"23----"}),/integrity/);f=await fixture();await writeFile(f.pointer,JSON.stringify({dataset_id:"census-zbp-baseline",release_id:"zbp",manifest:"../outside.json"}));await assert.rejects(createCensusZbpIndustryView({pointerPath:f.pointer}).get({naics:"23----"}),/escapes/);});
test("bounded HTTP contract rejects duplicates and delegates an abort signal",async()=>{const calls=[],view={get:async(q,o)=>(calls.push([q,o.signal instanceof AbortSignal]),{ok:true})};const invoke=async(method,query)=>{let result;await censusZbpIndustryHttp({method},{},new URL(`http://local/api/census-zbp-industry${query}`),view,(_r,status,value)=>{result={status,value};});return result;};assert.equal((await invoke("POST","?naics=23----")).status,405);assert.equal((await invoke("GET","?naics=23----&extra=x")).status,400);assert.equal((await invoke("GET","?naics=23----&naics=11----")).status,400);assert.equal((await invoke("GET","?naics=23----&limit=10")).status,200);assert.deepEqual(calls,[[{naics:"23----",limit:10},true]]);});
test("UI keeps Census aggregates separate from business and credential modes",async()=>{const ui=await readFile(new URL("../app/business-intelligence.tsx",import.meta.url),"utf8"),panel=await readFile(new URL("../app/census-zbp-industry-heatmap.tsx",import.meta.url),"utf8");assert.match(ui,/Census employer industry · annual aggregate/);assert.match(ui,/mode==='credentials'.*mode==='census-industry'/s);assert.match(panel,/Absent ZIP5 × NAICS rows are unavailable, not zero/);assert.match(panel,/hierarchical NAICS rows are never added together/);assert.match(panel,/ZIP 99999 remains unassigned/);});
