import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {readFile} from 'node:fs/promises';
import {cmsRetainedDirectoryZipHttp} from './cms-retained-directory-zip-http.mjs';
import {readCmsRetainedDirectoryZipEvidence} from './cms-retained-directory-zip-evidence.mjs';
function fixture(){const request=Object.assign(new EventEmitter(),{method:'GET',headers:{}}),response=Object.assign(new EventEmitter(),{writableEnded:false,setHeader(){}}),out=[];return {request,response,out,json:(_r,status,value)=>out.push({status,value})};}
test('same-ZIP malicious reader envelopes are rejected',async()=>{const base=await readCmsRetainedDirectoryZipEvidence({zip5:'00000'});for(const mutate of [v=>{v.claims.business_count=2;},v=>{v.status='retained-directory-evidence-present';},v=>{v.extra=true;},v=>{v.manifest_sha256='0'.repeat(64);},v=>{v.bindings.sources.hospital.extra=true;},v=>{v.denominators.hospital.directory_rows++;},v=>{v.row={zip5:'00000',zip4:null,hospital:{directory_rows:0,reported_states:{}},nursing_home:{directory_rows:0,reported_states:{}}};},v=>{v.available=false;}]){const value=structuredClone(base);mutate(value);const f=fixture();await cmsRetainedDirectoryZipHttp(f.request,f.response,new URL('http://local/?zip=00000'),{authorize:()=>true,reader:async()=>value},f.json);assert.equal(f.out[0].status,503);}});
test('protected exact ZIP empty GET rejects unauthorized, duplicates, extra options and body before reading',async()=>{for(const mode of ['auth','duplicate','extra','body','zip4']){const f=fixture();if(mode==='body')f.request.headers['content-length']='1';let calls=0;await cmsRetainedDirectoryZipHttp(f.request,f.response,new URL(`http://local/?zip=${mode==='zip4'?'00501-0001':'00501'}${mode==='duplicate'?'&zip=00501':mode==='extra'?'&build=1':''}`),{authorize:()=>mode!=='auth',reader:async()=>{calls++;} },f.json);assert.equal(calls,0);assert.equal(f.out[0].status,mode==='auth'?401:400);}});
test('returns source-bound ZIP and applies deadline/disconnect without late success',async t=>{const f=fixture();await cmsRetainedDirectoryZipHttp(f.request,f.response,new URL('http://local/?zip=00501'),{authorize:()=>true,reader:async({zip5,signal})=>{assert.ok(signal);return readCmsRetainedDirectoryZipEvidence({zip5,signal});}},f.json);assert.equal(f.out[0].status,200);
 t.mock.timers.enable({apis:['setTimeout']});const timeout=fixture();let signal;const pending=cmsRetainedDirectoryZipHttp(timeout.request,timeout.response,new URL('http://local/?zip=00501'),{authorize:()=>true,reader:async o=>{signal=o.signal;return new Promise(resolve=>o.signal.addEventListener('abort',()=>resolve({zip5:'00501'})));}},timeout.json);await Promise.resolve();await Promise.resolve();t.mock.timers.tick(30000);await pending;assert.equal(signal.aborted,true);assert.equal(timeout.out[0].status,503);assert.equal(timeout.request.listenerCount('aborted'),0);
});
test('runner wires the exact ZIP route only after the shared control-plane guard',async()=>{const source=await readFile(new URL('./server.mjs',import.meta.url),'utf8'),guard=source.indexOf('controlPlane.authorize(request);'),route=source.indexOf("url.pathname === '/api/business-map/cms-retained-directory-zip-evidence'");assert.ok(guard>=0&&route>guard);assert.match(source,/cmsRetainedDirectoryZipHttp\(request,response,url,\{authorize:\(\)=>true\},json\)/);});
