import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {readFile,writeFile,lstat,unlink,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {APP_ROOT} from './paths.mjs';
import {geocodeCmsHospitalsFixture as run,verifyCmsHospitalGeocodingFixture as verify,verifyCmsHospitalGeocoding as nativeVerify} from './cms-hospital-census-geocoding.mjs';
import {runCensusGeocoderDemoFixture as demo} from './census-geocoder-demo-prerequisite.mjs';
const root=path.join(APP_ROOT,`data/tmp/cms-hospital-census-geocoding-${process.pid}/jobs`),lease=path.join(APP_ROOT,`data/tmp/census-geocoder-demo-${process.pid}/.source-lease`),catalog=Buffer.from('{"benchmarks":[{"id":"8","benchmarkName":"Public_AR_ACS2025"}]}');
const source=()=>({nativeSourceVerified:false,evidence:{test:'retained-fixture'},demo:{test:'demo-fixture'},rows:[{sourceRecordId:'PRIVATE_ID_A',reportedAddress:{street:'10 Public Rd',city:'Town',state:'MD',postal:{zip5:'00123',zip4:'4567'}}},{sourceRecordId:'PRIVATE_ID_B',reportedAddress:{street:'20 Public Rd',city:'Town',state:'GU',postal:{zip5:'96910',zip4:null}}}]});
async function clean(r){assert.equal(path.dirname(r.directory),root);await rm(r.directory,{recursive:true,force:true});}
async function absent(file){await assert.rejects(lstat(file),{code:'ENOENT'});}
function transport(change){const calls=[];return {calls,fetch:async(url,opts)=>{calls.push({url,opts});let raw=catalog;if(opts.method==='POST'){const body=Buffer.from(opts.body).toString();assert.ok(!body.includes('PRIVATE_ID')&&!body.includes('"4567"'));const ids=[...body.matchAll(/"([a-f0-9-]{36})",/g)].map(m=>m[1]);raw=Buffer.from(ids.reverse().map(id=>`"${id}",echo,Match,Exact,matched,"-76,38",123,L\n`).join(''));}return change?.(calls.length,opts,raw)??new Response(raw);}};}
test('bounded three-request lifecycle replays all rows and native verifier rejects fixtures',async()=>{const t=transport(),r=await run(t.fetch,source);try{assert.deepEqual(t.calls.map(c=>c.opts.method),['GET','POST','GET']);const m=await verify(r.manifestPath,r.manifestSha256,source);assert.equal(m.counts.planned,2);assert.equal(m.counts.matched,1);assert.equal(m.counts.ineligible,1);assert.equal(m.claims.nativeTransportObserved,false);await assert.rejects(nativeVerify(r.manifestPath,r.manifestSha256));const rows=(await readFile(path.join(r.directory,'geocodes.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);assert.equal(rows[0].originalAddress.zip4,'4567');assert.equal(rows[1].status,'ineligible');await absent(lease);}finally{await clean(r);}});
test('source drift before POST blocks disclosure, preserving GET evidence',async()=>{let reads=0;const f=()=>{const s=source();if(++reads>1)s.evidence.test='changed';return s;},t=transport();let r;try{await run(t.fetch,f);assert.fail('reject');}catch(e){r=e.recovery;}try{assert.equal(t.calls.length,1);const m=JSON.parse(await readFile(path.join(r.directory,'failure.json')));assert.ok(m.artifacts.some(a=>a.path==='catalog-before.json'));await absent(lease);}finally{await clean(r);}});
test('settled unknown response retains raw and mapping without false success or permanent lock',async()=>{const t=transport((i,o,b)=>new Response(i===2?'unknown':b));let r;try{await run(t.fetch,source);assert.fail('reject');}catch(e){r=e.recovery;}try{const m=JSON.parse(await readFile(path.join(r.directory,'failure.json')));assert.equal(m.submissionOrCleanupUnresolved,false);assert.ok(m.artifacts.some(a=>a.path==='mapping.json'));assert.ok(m.artifacts.some(a=>a.path==='response.csv'));await absent(path.join(r.directory,'manifest.json'));await absent(lease);}finally{await clean(r);}});
test('noncooperative POST abort leaves bounded uncertain submission and owned lease',async()=>{const c=new AbortController(),t=transport((i,o,b)=>{if(i===2){setTimeout(()=>c.abort(),5);return new Promise(()=>{});}return new Response(b);});let r;const start=Date.now();try{await run(t.fetch,source,{signal:c.signal});assert.fail('reject');}catch(e){r=e.recovery;}try{assert.ok(Date.now()-start<5000);assert.equal(r.sourceLeaseRetained,true);assert.equal(t.calls.length,2);await assert.rejects(run(()=>assert.fail('second transport'),source),/lease unavailable/);}finally{await unlink(lease);await clean(r);}});
test('unchanged public-demo worker and hospital worker share the same physical provider lease',async()=>{const r=await run(transport().fetch,source,{},async phase=>{if(phase==='before-post')await assert.rejects(demo(()=>assert.fail('demo must not fetch')),/lease unavailable/);});await clean(r);await absent(lease);});
test('publication and same-inode lease errors retain successful manifest identity',async()=>{for(const kind of ['published','lease']){let r;try{await run(transport().fetch,source,{},async(phase,ctx)=>{if(kind==='published'&&phase==='after-publication')throw Error('test');if(kind==='lease'&&phase==='before-lease-cleanup')await writeFile(ctx.leasePath,'other-owner');});assert.fail('reject');}catch(e){r=e.recovery;}try{assert.equal(r.inspectionRequired,true);await verify(r.manifestPath,r.manifestSha256,source);if(kind==='lease'){assert.equal(await readFile(lease,'utf8'),'other-owner');await unlink(lease);}else await absent(lease);}finally{await clean(r);}}});
test('rehashed derived output and source-linkage tampering fail independent replay',async()=>{const r=await run(transport().fetch,source);try{const m=JSON.parse(await readFile(r.manifestPath)),file=path.join(r.directory,'geocodes.jsonl'),raw=Buffer.from((await readFile(file,'utf8')).replace('00123','99999'));await writeFile(file,raw);Object.assign(m.artifacts.find(a=>a.path==='geocodes.jsonl'),{bytes:raw.length,sha256:createHash('sha256').update(raw).digest('hex')});const b=Buffer.from(JSON.stringify(m)+'\n');await writeFile(r.manifestPath,b);await assert.rejects(verify(r.manifestPath,createHash('sha256').update(b).digest('hex'),source));}finally{await clean(r);}});
test('closed API and malformed CLI reject before retained source/network access',async()=>{await assert.rejects(run(()=>assert.fail('network'),source,{address:'other'}));await assert.rejects(run(()=>assert.fail('network'),source,{signal:AbortSignal.abort()}),{name:'AbortError'});const c=spawnSync(process.execPath,['scripts/geocode-cms-hospitals.mjs','--source','other'],{cwd:APP_ROOT,encoding:'utf8',windowsHide:true,timeout:10000});assert.equal(c.status,1);});
test('response cap and noncooperative body cancel retain uncertain submission',async()=>{for(const kind of ['cap','body']){const c=new AbortController(),t=transport((i,o,b)=>{if(i!==2)return new Response(b);if(kind==='cap')return new Response(Buffer.alloc(4194305));return {status:200,headers:new Headers(),body:{getReader(){return {read(){setTimeout(()=>c.abort(),5);return new Promise(()=>{});},cancel(){return new Promise(()=>{});},releaseLock(){}};}}};});let r;try{await run(t.fetch,source,{signal:c.signal});assert.fail('reject');}catch(e){r=e.recovery;}try{assert.equal(r.sourceLeaseRetained,true);assert.equal(t.calls.length,2);}finally{await unlink(lease);await clean(r);}}});
test('policy drift rejects before any GET or source loading',async()=>{const file=path.join(APP_ROOT,'config/source-policies/cms-hospital-census-geocoding.json'),before=await readFile(file);try{await writeFile(file,'{}');await assert.rejects(run(()=>assert.fail('GET'),()=>assert.fail('source')));await absent(lease);}finally{await writeFile(file,before);}});
test('policy and source changes after local preparation are rejected immediately before POST',async()=>{for(const kind of ['policy','source']){const file=path.join(APP_ROOT,'config/source-policies/cms-hospital-census-geocoding.json'),before=await readFile(file),t=transport();let changed=false,r;const f=()=>{const s=source();if(changed&&kind==='source')s.rows[0].reportedAddress.street='altered';return s;};try{try{await run(t.fetch,f,{},async phase=>{if(phase==='before-post'){changed=true;if(kind==='policy')await writeFile(file,'{}');}});assert.fail('reject');}catch(e){r=e.recovery;}assert.equal(t.calls.length,1);const failed=JSON.parse(await readFile(path.join(r.directory,'failure.json')));assert.equal(failed.submissionOrCleanupUnresolved,false);await absent(lease);}finally{if(kind==='policy')await writeFile(file,before);await clean(r);}}});
test('actual thirty-second GET deadline returns uncertain bounded failure',{timeout:35000},async()=>{let r;const started=Date.now();try{await run(()=>new Promise(()=>{}),source);assert.fail('reject');}catch(e){r=e.recovery;}try{const elapsed=Date.now()-started;assert.ok(elapsed>=29500&&elapsed<34000);assert.equal(r.sourceLeaseRetained,true);}finally{await unlink(lease);await clean(r);}});
