import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {mkdir,readdir,readFile,writeFile,rm,unlink,rmdir,open} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {fileURLToPath} from 'node:url';
import {APP_ROOT} from './paths.mjs';
import {acquireCmsNursingHomes,acquireCmsNursingHomesWithTestTransport as run,verifyCmsNursingHomeAcquisitionWithTestInput as verify,verifyCmsNursingHomeAcquisition as nativeVerify,CMS_NURSING_HOME_BUDGET_LOCKS} from './cms-nursing-home-acquisition.mjs';
import {CMS_NURSING_HOME_SELECTED_HEADERS} from './cms-nursing-home-prerequisite.mjs';
const LEASE=CMS_NURSING_HOME_BUDGET_LOCKS.fixture;
const ROOT=path.join(APP_ROOT,'data/tmp/cms-nursing-home-acquisition'),sha=v=>createHash('sha256').update(v).digest('hex');
const exec=promisify(execFile);
const m={identifier:'4pq5-n9py',title:'Provider Information',description:'General information on currently active nursing homes, including number of certified beds, quality measure scores, staffing and other information used in the Five-Star Rating System. Data are presented as one row per nursing home.',accessLevel:'public',publisher:{name:'Centers for Medicare & Medicaid Services (CMS)'},landingPage:'https://data.cms.gov/provider-data/dataset/4pq5-n9py',issued:'2026-02-01',modified:'2026-08-01',released:'2026-08-26',distribution:[{mediaType:'text/csv',downloadURL:'https://data.cms.gov/provider-data/sites/default/files/resources/328596835e6db31b2564cd733c3795f4_1786724150/NH_ProviderInfo_Aug2026.csv',describedBy:'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/nursing_home/NH_Data_Dictionary.pdf',describedByType:'application/pdf'}]};
const csv=[...CMS_NURSING_HOME_SELECTED_HEADERS,'Telephone Number'].join(',')+'\n00123A,Fixture Home,1 Street,City,AL,00501-0012,County,Future ownership,Future type,Source Legal,30,-85,22,08/01/2026,PRIVATE CONTACT\n';
const response=(body,type)=>new Response(body,{status:200,headers:{'content-type':type}});
async function track(t){await mkdir(ROOT,{recursive:true});const before=new Set(await readdir(ROOT));t.after(async()=>{for(const name of await readdir(ROOT)){if(before.has(name))continue;assert.match(name,/^[a-f0-9-]{36}$/);const target=path.join(ROOT,name);assert.equal(path.dirname(target),ROOT);await rm(target,{recursive:true,force:true});}});}
function transport(edit){let calls=0;const urls=[];const fn=async(url,opts)=>{calls++;urls.push(url);assert.equal(opts.redirect,'manual');assert.equal(opts.credentials,'omit');assert.equal(opts.method,'GET');const directories=await readdir(ROOT);assert.ok(directories.length);assert.ok((await Promise.all(directories.map(d=>readFile(path.join(ROOT,d,'intent.json')).catch(()=>null)))).some(Boolean));
 const body=calls===2?Buffer.from('%PDF-SYNTHETIC-NURSING-HOME-DICTIONARY'):calls===3?Buffer.from('%PDF-SYNTHETIC-CMS-REUSE-NOTICE'):calls===4?csv:JSON.stringify(m),type=calls===2||calls===3?'application/pdf':calls===4?'text/csv':'application/json';return edit?.(calls,url,opts,body,type)??response(body,type);};fn.calls=()=>calls;fn.urls=urls;return fn;}
test('one immutable national source passes five sequential fixture requests and independent source-to-selected replay',async t=>{await track(t);const fetch=transport(),out=await run(fetch),manifest=await verify(out.manifestPath,out.manifestSha256);assert.equal(fetch.calls(),5);assert.equal(fetch.urls[0],fetch.urls[4]);assert.equal(manifest.sourceRows,1);assert.equal(manifest.observedHeaderColumns,15);assert.equal(manifest.claims.nativeTransportVerified,false);assert.equal(manifest.claims.csvRecordConservationVerified,true);assert.equal(manifest.claims.allNursingHomeCompletenessPercent,null);const directory=path.dirname(out.manifestPath),selected=await readFile(path.join(directory,'selected.jsonl'),'utf8');assert.doesNotMatch(selected,/PRIVATE CONTACT|Telephone Number/);assert.match(await readFile(path.join(directory,'source.csv'),'utf8'),/PRIVATE CONTACT/);const row=JSON.parse(selected);assert.equal(row.reportedAddress.postal.zip4,'0012');assert.equal(row.provenance.policyProfile,'cms-nursing-home-acquisition@1.0.0');assert.equal(manifest.artifacts.find(a=>a.path==='source.csv').exportPolicy,'internal');await assert.rejects(nativeVerify(out.manifestPath,out.manifestSha256));});
test('dictionary and notice hash/type/signature mismatch or redirect stop before CSV',async t=>{await track(t);for(const step of [2,3])for(const edit of [(n,u,o,b,type)=>n===step?response('%PDF-not-reviewed',type):response(b,type),(n,u,o,b,type)=>n===step?response(b,'text/html'):response(b,type),(n,u,o,b,type)=>n===step?new Response(null,{status:302,headers:{location:'https://example.com/SECRET'}}):response(b,type)]){const fetch=transport(edit);let recovery;await assert.rejects(run(fetch),e=>{recovery=e.recovery;assert.equal(e.message,'CMS nursing-home acquisition failed.');return true;});assert.equal(fetch.calls(),step);const names=await readdir(recovery.directory);assert.ok(names.includes('metadata-before.json'));assert.ok(!names.includes('source.csv')&&!names.includes('manifest.json'));const failure=JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8'));assert.ok(failure.completedRestrictedSourceArtifacts.every(a=>a.exportPolicy==='internal'));}});

test('same exclusive path as unchanged hospital makes CMS budget exclusion bidirectional',async t=>{await track(t);assert.equal(CMS_NURSING_HOME_BUDGET_LOCKS.native,path.join(APP_ROOT,'data/business-sources/cms-hospital-general-information/jobs/.source-lease'));assert.equal(LEASE,path.join(APP_ROOT,'data/tmp/cms-hospital-acquisition/.source-lease'));await mkdir(path.dirname(LEASE),{recursive:true});const hospital=await open(LEASE,'wx');try{await assert.rejects(run(()=>assert.fail('hospital lease must block requests')),/lease unavailable/);}finally{await hospital.close();await unlink(LEASE);}let checked=false;await run(transport(),{},async stage=>{if(stage==='before-publication'){await assert.rejects(open(LEASE,'wx'),{code:'EEXIST'});const lease=JSON.parse(await readFile(LEASE,'utf8'));assert.equal(lease.ownerProfile,'cms-nursing-home-acquisition@1.0.0');assert.equal(lease.budgetKey,'cms-provider-data-catalog');checked=true;}});assert.equal(checked,true);});

test('actual internal 30-second metadata deadline bounds a noncooperative fetch', {timeout:36000},async t=>{await track(t);let recovery;const began=Date.now();await assert.rejects(run(()=>new Promise(()=>{})),error=>{recovery=error.recovery;return true;});assert.ok(Date.now()-began>=29000&&Date.now()-began<35000);assert.equal(recovery.sourceLeaseRetained,true);assert.equal(JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8')).requestAttempts,1);await unlink(LEASE);});

test('policy drift rejects before network or lease, and malformed CLI arguments never import acquisition',async t=>{await track(t);const childRoot=path.join(ROOT,randomUUID()),config=path.join(childRoot,'config/source-policies');await mkdir(config,{recursive:true});const policy=JSON.parse(await readFile(new URL('../config/source-policies/cms-nursing-home-acquisition.json',import.meta.url),'utf8'));policy.publicExportAuthorized=true;await writeFile(path.join(config,'cms-nursing-home-acquisition.json'),JSON.stringify(policy));const env={...process.env,DATAHUB_ROOT:childRoot},moduleUrl=new URL('./cms-nursing-home-acquisition.mjs',import.meta.url).href;const code=`globalThis.fetch=()=>{throw Error('NETWORK CALLED');};const m=await import(${JSON.stringify(moduleUrl)});try{await m.acquireCmsNursingHomes();process.exitCode=2;}catch(e){if(e.message!=='CMS nursing-home acquisition evidence rejected.')throw e;console.log('policy-rejected-before-network');}`;const result=await exec(process.execPath,['--input-type=module','-e',code],{env,timeout:10000});assert.match(result.stdout,/policy-rejected-before-network/);assert.deepEqual(await readdir(childRoot),['config']);await assert.rejects(exec(process.execPath,[fileURLToPath(new URL('../scripts/acquire-cms-nursing-homes.mjs',import.meta.url)),'--unsupported'],{env,timeout:10000}),e=>e.code===1&&e.stderr.includes('no automatic retry'));assert.deepEqual(await readdir(childRoot),['config']);});
test('metadata drift and duplicate facility IDs preserve completed internal source without publication or retry',async t=>{await track(t);for(const edit of [(n,u,o,b,type)=>response(n===5?JSON.stringify({...m,modified:'2026-07-23'}):b,type),(n,u,o,b,type)=>response(n===4?csv+csv.split('\n')[1]+'\n':b,type)]){const fetch=transport(edit);let recovery;await assert.rejects(run(fetch),e=>{recovery=e.recovery;return true;});assert.equal(fetch.calls(),5);const names=await readdir(recovery.directory);assert.ok(names.includes('source.csv'));assert.ok(!names.includes('manifest.json')&&!names.includes('selected.jsonl'));const failure=JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8'));const a=failure.completedRestrictedSourceArtifacts.find(a=>a.path==='source.csv');assert.equal(a.sha256,sha(await readFile(path.join(recovery.directory,'source.csv'))));}});
test('rehashed selected tampering still fails replay and wrong artifact hash fails',async t=>{await track(t);const out=await run(transport()),directory=path.dirname(out.manifestPath),file=path.join(directory,'selected.jsonl'),changed=(await readFile(file,'utf8')).replace('Fixture Home','Different Home');await writeFile(file,changed);const manifest=JSON.parse(await readFile(out.manifestPath,'utf8'));Object.assign(manifest.artifacts.find(a=>a.path==='selected.jsonl'),{bytes:Buffer.byteLength(changed),sha256:sha(changed)});const raw=JSON.stringify(manifest)+'\n';await writeFile(out.manifestPath,raw);await assert.rejects(verify(out.manifestPath,sha(raw)));});
test('preabort sends no request; cancellation during CSV request preserves cancelled intent and completed notice',async t=>{await track(t);const before=new AbortController();before.abort();await assert.rejects(acquireCmsNursingHomes({signal:before.signal}),{name:'AbortError'});const controller=new AbortController(),fetch=transport((n,u,o,b,type)=>{if(n===4){controller.abort();o.signal.throwIfAborted();}return response(b,type);});let recovery;await assert.rejects(run(fetch,{signal:controller.signal}),e=>{recovery=e.recovery;return true;});assert.equal(fetch.calls(),4);const receipt=JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8'));assert.equal(receipt.status,'CANCELLED');assert.equal(receipt.published,false);assert.deepEqual((await readdir(recovery.directory)).sort(),['dictionary.pdf','failure.json','intent.json','metadata-before.json','request-1.json','request-2.json','request-3.json','request-4.json','reuse-notice.pdf']);});
test('response byte cap and invalid options reject without retries or arbitrary URL overrides',async t=>{await track(t);const fetch=transport((n,u,o,b,type)=>response(n===2?Buffer.alloc(5242881):b,type));await assert.rejects(run(fetch));assert.equal(fetch.calls(),2);await assert.rejects(run(()=>assert.fail('must not fetch'),{url:'https://example.com'}));});

test('manifest-last publication and late cancellation or failure preserve explicit uncertain recovery',async t=>{await track(t);for(const cancellation of [false,true]){const controller=new AbortController();let recovery;await assert.rejects(run(transport(),{signal:controller.signal},async(stage,{directory})=>{if(stage==='before-publication'){assert.ok((await readdir(directory)).includes('manifest.pending'));assert.ok(!(await readdir(directory)).includes('manifest.json'));}if(stage==='after-publication'){if(cancellation)controller.abort();else throw Error('PRIVATE injected failure');}}),e=>{assert.equal(e.code,'CMS_NURSING_HOME_PUBLICATION_UNCERTAIN');assert.doesNotMatch(e.message,/PRIVATE/);recovery=e.recovery;return true;});assert.equal(recovery.inspectionRequired,true);const m=await verify(recovery.manifestPath,recovery.manifestSha256);assert.equal(m.sourceRows,1);assert.ok((await readdir(path.dirname(recovery.manifestPath))).includes('source.csv'));}});

test('shared source lease excludes simultaneous jobs and never takes over an existing lease',async t=>{await track(t);let entered,release;const began=new Promise(r=>entered=r),held=new Promise(r=>release=r),normal=transport();const first=run(async(...args)=>{entered();await held;return normal(...args);});await began;let secondCalls=0;await assert.rejects(run(()=>{secondCalls++;}),/lease unavailable/);assert.equal(secondCalls,0);release();await first;const file=LEASE;await writeFile(file,'FOREIGN LEASE');try{await assert.rejects(run(()=>assert.fail('must not request')),/lease unavailable/);assert.equal(await readFile(file,'utf8'),'FOREIGN LEASE');}finally{await unlink(file);}});

test('noncooperative transport abort is bounded, retains exclusion and disposes a late response',async t=>{await track(t);const controller=new AbortController();let resolve,entered,cancelled=false;const begun=new Promise(r=>entered=r);const pending=run(()=>{entered();return new Promise(r=>resolve=r);},{signal:controller.signal});await begun;controller.abort();await assert.rejects(pending,e=>e.recovery.sourceLeaseRetained===true);await assert.rejects(run(()=>assert.fail('unresolved owner must exclude new work')),/lease unavailable/);resolve({body:{cancel:async()=>{cancelled=true;}}});await new Promise(r=>setImmediate(r));assert.equal(cancelled,true);await unlink(LEASE);});

test('nonsettling body reads and cleanup cannot hang cancellation or rejection',async t=>{await track(t);for(const stalledRead of [true,false]){const controller=new AbortController();const began=Date.now();let timer;const request=run(()=>{if(stalledRead)timer=setTimeout(()=>controller.abort(),20);return {status:200,redirected:false,headers:new Headers({'content-type':stalledRead?'application/json':'text/html'}),body:{getReader:()=>({read:()=>new Promise(()=>{}),cancel:()=>new Promise(()=>{}),releaseLock(){}}),cancel:()=>new Promise(()=>{})}};},{signal:controller.signal});await assert.rejects(request,e=>e.recovery.sourceLeaseRetained===true);clearTimeout(timer);assert.ok(Date.now()-began<3000);await unlink(LEASE);}});

test('lease cleanup failure preserves publication or original failed run identity with redacted inspection recovery',async t=>{await track(t);for(const successful of [true,false]){let recovery;await assert.rejects(run(transport((n,u,o,b,type)=>response(!successful&&n===2?'invalid notice':b,type)),{},async(stage)=>{if(stage==='before-lease-cleanup')throw Error('PRIVATE cleanup failure');}),e=>{recovery=e.recovery;assert.equal(e.code,successful?'CMS_NURSING_HOME_PUBLICATION_UNCERTAIN':'CMS_NURSING_HOME_ACQUISITION_FAILED');assert.doesNotMatch(e.message,/PRIVATE/);return true;});assert.equal(recovery.inspectionRequired,true);assert.equal(recovery.sourceLeaseRetained,true);assert.equal(recovery.leaseCleanupFailed,true);assert.ok(recovery.runId);if(successful)assert.equal((await verify(recovery.manifestPath,recovery.manifestSha256)).sourceRows,1);else assert.equal(JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8')).runId,recovery.runId);await unlink(LEASE);}});

test('changed-owner lease is never removed and published recovery is preserved',async t=>{await track(t);await assert.rejects(run(transport(),{},async(stage,{leasePath})=>{if(stage==='before-lease-cleanup'){await unlink(leasePath);await mkdir(leasePath);}}),e=>e.code==='CMS_NURSING_HOME_PUBLICATION_UNCERTAIN'&&e.recovery.inspectionRequired===true);const lease=LEASE;assert.deepEqual(await readdir(lease),[]);await rmdir(lease);});
