import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {CMS_HOSPITAL_SELECTED_HEADERS as HEADERS,CMS_HOSPITAL_PREREQUISITE_CONTRACT as CONTRACT,inspectCmsHospitalMetadata as metadata,inspectCmsHospitalCsvForConformance as inspect} from './cms-hospital-prerequisite.mjs';
const opts={observedAt:'2026-09-12T13:00:00.000Z'};
function source(){return {identifier:'xubh-q36u',title:'Hospital General Information',accessLevel:'public',publisher:{name:'Centers for Medicare & Medicaid Services (CMS)'},landingPage:'https://data.cms.gov/provider-data/dataset/xubh-q36u',issued:'2025-01-08',modified:'2026-07-22',released:'2026-08-13',distribution:[{mediaType:'text/csv',downloadURL:'https://data.cms.gov/provider-data/sites/default/files/resources/893c372430d9d71a1c52737d01239d47_1785189955/Hospital_General_Information.csv',describedBy:'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/hospital/HOSPITAL_Data_Dictionary.pdf',describedByType:'application/pdf'}]};}
const meta=()=>metadata(Buffer.from(JSON.stringify(source())),opts);
function record(changes={}){return {'Facility ID':'010001','Facility Name':'Fixture, Hospital','Address':'123 Fixture St','City/Town':'Fixture','State':'AL','ZIP Code':'00501-0012','County/Parish':'Fixture County','Hospital Type':'Unknown future type','Hospital Ownership':'Unknown category','Emergency Services':'Unknown source value',...changes};}
const quoted=v=>'"'+v.replaceAll('"','""')+'"';
function csv(rows=[record()],headers=HEADERS){return Buffer.from('\ufeff'+headers.map(quoted).join(',')+'\r\n'+rows.map(row=>headers.map(key=>quoted(row[key]??'')).join(',')).join('\r\n')+'\r\n');}
test('metadata confirms only fixed CMS byte/schema contract, never transport or acquisition readiness',()=>{const raw=Buffer.from(JSON.stringify(source())),m=metadata(raw,opts);assert.equal(m.metadataSha256,createHash('sha256').update(raw).digest('hex'));assert.equal(m.modified,'2026-07-22');assert.equal(m.released,'2026-08-13');assert.equal(m.transportAuthenticityVerified,false);assert.equal(m.acquisitionReady,false);assert.equal(m.fullHeaderOrderVerified,false);assert.equal(CONTRACT.metadata.maxBytes,1048576);assert.throws(()=>{m.csvUrl='changed';});});
test('metadata rejects redirected-style URLs, wrong source, access drift, malformed dates and invalid UTF8',()=>{for(const edit of [m=>m.identifier='other',m=>m.publisher.name='Other',m=>m.accessLevel='restricted',m=>m.title='Other',m=>m.modified='2026-02-30',m=>m.released='2027-01-01',m=>m.distribution.push(m.distribution[0]),m=>m.distribution[0].downloadURL=m.distribution[0].downloadURL.replace('data.cms.gov','example.com'),m=>m.distribution[0].downloadURL+='?token=secret',m=>m.distribution[0].describedBy='https://example.com/dict']){const m=source();edit(m);assert.throws(()=>metadata(Buffer.from(JSON.stringify(m)),opts));}assert.throws(()=>metadata(Buffer.from([0xff]),opts));assert.throws(()=>metadata(Buffer.alloc(1048577),opts));});
test('selected CSV projection preserves identifiers and split postal values without inferred identity/status',async()=>{const raw=csv(),r=await inspect(raw,meta()),row=r.rows[0];assert.equal(row.identifier.raw,'010001');assert.deepEqual(row.reportedAddress.postal,{raw:'00501-0012',zip5:'00501',zip4:'0012',status:'format-only-usps-unverified'});assert.equal(row.facilityName,'Fixture, Hospital');assert.equal(row.emergencyServicesSource,'Unknown source value');assert.equal(row.npi,null);assert.equal(row.parentCompany,null);assert.equal(row.currentOperatingStatus,null);assert.deepEqual(row.geocode,{latitude:null,longitude:null});assert.equal(r.nativeAcquisitionVerified,false);assert.equal(r.acquisitionReady,false);assert.equal(r.csvSha256,createHash('sha256').update(raw).digest('hex'));assert.equal((await inspect(raw,meta())).csvSha256,r.csvSha256);});
test('only documented selected headers required; arbitrary order and additional columns are not full-schema proof',async()=>{const headers=['Telephone Number','Unverified extra',...HEADERS.toReversed()],r=await inspect(csv([record({'Telephone Number':'PRIVATE CONTACT','Unverified extra':'PRIVATE VALUE'})],headers),meta());assert.equal(r.headerColumns,12);assert.equal(r.unselectedHeaderCount,2);assert.equal(r.fullHeaderOrderVerified,false);assert.doesNotMatch(JSON.stringify(r),/PRIVATE|Telephone Number|Unverified extra/);await assert.rejects(inspect(csv([record()],HEADERS.slice(1)),meta()));await assert.rejects(inspect(csv([record()],[...HEADERS,HEADERS[0]]),meta()));});
test('missing and unresolved postal values remain unknown; raw state is not silently filtered',async()=>{const r=await inspect(csv([record({'ZIP Code':'','State':'PR'}),record({'Facility ID':'010002','ZIP Code':'invalid'}),record({'Facility ID':'010003','ZIP Code':'005010012'})]),meta());assert.equal(r.rows[0].reportedAddress.postal.zip5,null);assert.equal(r.rows[0].reportedAddress.state,'PR');assert.equal(r.rows[1].reportedAddress.postal.raw,'invalid');assert.equal(r.rows[1].reportedAddress.postal.zip4,null);assert.equal(r.rows[2].reportedAddress.postal.zip4,'0012');assert.equal(r.sourceRows,3);});
test('duplicates/invalid IDs, missing names, record widths, text controls and malformed CSV reject the whole conformance',async()=>{for(const rows of [[record(),record()],[record({'Facility ID':''})],[record({'Facility ID':'10001'})],[record({'Facility Name':''})],[record({'Facility Name':'PRIVATE\nLINE'})]])await assert.rejects(inspect(csv(rows),meta()),error=>{assert.doesNotMatch(error.message,/PRIVATE/);return true;});await assert.rejects(inspect(Buffer.from(HEADERS.join(',')+'\nonly,two\n'),meta()));await assert.rejects(inspect(Buffer.from('"unterminated'),meta()));await assert.rejects(inspect(Buffer.from(HEADERS.join(',')+'\n'),meta()));});
test('bounds and cooperative cancellation reject without producing artifacts or partial success',async()=>{const m=meta(),controller=new AbortController();controller.abort();await assert.rejects(inspect(csv(),m,{signal:controller.signal}),{name:'AbortError'});await assert.rejects(inspect(Buffer.alloc(20971521),m));await assert.rejects(inspect(Buffer.from([0xff,10]),m));await assert.rejects(inspect(csv([record({'Address':'x'.repeat(66000)})]),m));const late=new AbortController();setImmediate(()=>late.abort());await assert.rejects(inspect(csv(Array.from({length:256},(_,i)=>record({'Facility ID':String(i+1).padStart(6,'0')}))),m,{signal:late.signal}),{name:'AbortError'});});
test('forged metadata and unsupported execution options cannot mint conformance',async()=>{await assert.rejects(inspect(csv(),{...meta()}));await assert.rejects(inspect(csv(),meta(),{url:'https://example.com'}));assert.throws(()=>metadata(Buffer.from(JSON.stringify(source())),{...opts,cookie:'secret'}));});
