import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs/promises';
import {existsSync,readdirSync} from 'node:fs';
import path from 'node:path';
import {APP_ROOT} from './paths.mjs';
import {publishCmsRetainedDirectoryZipEvidence,readCmsRetainedDirectoryZipEvidence} from './cms-retained-directory-zip-evidence.mjs';
const url=new URL('./cms-retained-directory-zip-evidence.mjs',import.meta.url),source=(await fs.readFile(url,'utf8')).replace(/from '(\.\/[^']+)'/g,(_,r)=>`from '${new URL(r,url).href}'`);
const {core}=await import(`data:text/javascript;base64,${Buffer.from(`${source}\nexport const core={publish,verify,lookup,project};`).toString('base64')}`);
const hash=b=>createHash('sha256').update(b).digest('hex'),bytes=v=>Buffer.from(`${JSON.stringify(v)}\n`),clock='2026-10-02T22:30:00.000Z';
test('both selected inputs remain identity-bound before rename and after install',async t=>{for(const kind of ['hospital','nursing_home'])for(const phase of ['before','after']){const c=await fixture(t);for(const k of ['hospital','nursing_home']){const dir=path.join(c.root,k);await fs.mkdir(dir);const raw=bytes({source:k});await fs.writeFile(path.join(dir,'selected.jsonl'),raw);Object.assign(c.binding.sources[k],{manifest_path:`${k}/manifest.json`,selected_artifact:{path:'selected.jsonl',bytes:raw.length,sha256:hash(raw)}});}const rename=fs.rename;let replaced=false;const stub=t.mock.method(fs,'rename',async(from,to)=>{if(from.includes('.staging')){const file=path.join(c.root,kind,'selected.jsonl');const replace=async()=>{const raw=await fs.readFile(file);await fs.unlink(file);await fs.writeFile(file,raw);replaced=true;};if(phase==='before')await replace();await rename(from,to);if(phase==='after')await replace();return;}return rename(from,to);});try{await assert.rejects(core.publish(c,clock),e=>{assert.equal(e.inspection_required,true);return /drift/.test(e.message);});assert.equal(replaced,true);}finally{stub.mock.restore();}}});
test('rehashed malformed bucket schemas cannot pass bounded lookup',async t=>{for(const mutate of [r=>{r.extra=true;},r=>{r.hospital.extra=true;},r=>{r.hospital.directory_rows=-1;},r=>{r.hospital.reported_states={'other:AL':1};},r=>{r.hospital.reported_states={'reported:AL':2};}]){const c=await fixture(t),r=await core.publish(c,clock),mf=path.join(r.directory,'manifest.json'),m=JSON.parse(await fs.readFile(mf)),a=m.artifacts[0],bf=path.join(r.directory,a.path),rows=JSON.parse(await fs.readFile(bf));mutate(rows[0]);const raw=bytes(rows);await fs.writeFile(bf,raw);Object.assign(a,{bytes:raw.length,sha256:hash(raw)});const {release_id,...body}=m;void release_id;m.release_id=`cms-retained-directory-zip-evidence-${hash(JSON.stringify(body))}`;const manifestRaw=bytes(m);await fs.writeFile(mf,manifestRaw);const dir=path.join(path.dirname(r.directory),m.release_id);await fs.rename(r.directory,dir);await assert.rejects(core.lookup(dir,hash(manifestRaw),'00501',c));}});
async function fixture(t){await fs.mkdir(path.join(APP_ROOT,'data/tmp'),{recursive:true});const root=await fs.mkdtemp(path.join(APP_ROOT,'data/tmp/cms-zip-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const row=(id,state,zip)=>({identifier:{value:id},sourceRecordId:id,reportedAddress:{state,postal:{zip5:zip,zip4:zip?'1234':null}}});const inputs={hospital:{nativeSourceVerified:true,rows:[row('h1','AL','00501'),row('h2','PR',null)]},nursing_home:{nativeSourceVerified:true,rows:[row('n1','AL','00501'),row('n2',null,'99999'),row('n3','CA','90210')]}};return {root,reads:[],binding:{sources:{hospital:{completed_at:'2026-10-01T00:00:00.000Z'},nursing_home:{completed_at:'2026-10-01T00:00:00.000Z',historical_failure_rewritten:false}}},load:async()=>inputs,inputs};}
test('immutable replay conserves separate cohorts, missing ZIP/state, territories and no business claims',async t=>{const c=await fixture(t),r=await core.publish(c,clock),v=await core.verify(r.directory,c);assert.equal(v.manifest.summary.hospital.directory_rows,2);assert.equal(v.manifest.summary.hospital.territory_rows,1);assert.equal(v.manifest.summary.hospital.missing_zip_rows,1);assert.equal(v.manifest.summary.nursing_home.unknown_state_rows,1);const found=await core.lookup(r.directory,r.manifest_sha256,'00501',c);assert.equal(found.row.hospital.directory_rows,1);assert.equal(found.row.nursing_home.directory_rows,1);assert.equal(found.row.zip4,null);assert.equal(found.claims.physical_site_count,null);assert.equal(found.source_replay_performed,false);assert.equal((await core.lookup(r.directory,r.manifest_sha256,'00000',c)).row,null);assert.equal((await core.publish(c,clock)).reused,true);assert.equal(existsSync(path.join(c.root,'data/cms-retained-directory-zip-evidence/current.json')),false);});
test('self-consistent rehashed aggregate tampering fails independent source reconstruction',async t=>{const c=await fixture(t),r=await core.publish(c,clock),file=path.join(r.directory,'manifest.json'),m=JSON.parse(await fs.readFile(file)),a=m.artifacts[0],bucket=path.join(r.directory,a.path),rows=JSON.parse(await fs.readFile(bucket));rows[0].hospital.directory_rows++;const raw=bytes(rows);await fs.writeFile(bucket,raw);a.bytes=raw.length;a.sha256=hash(raw);const {release_id,...body}=m;void release_id;m.release_id=`cms-retained-directory-zip-evidence-${hash(JSON.stringify(body))}`;await fs.writeFile(file,bytes(m));const dir=path.join(path.dirname(r.directory),m.release_id);await fs.rename(r.directory,dir);await assert.rejects(core.verify(dir,c));await assert.rejects(core.lookup(dir,r.manifest_sha256,'00501',c));});
test('duplicates, joined ZIPs and unverified snapshots reject before publication',async t=>{for(const mode of ['duplicate','postal','unverified']){const c=await fixture(t);if(mode==='duplicate')c.inputs.hospital.rows.push(c.inputs.hospital.rows[0]);if(mode==='postal')c.inputs.hospital.rows[0].reportedAddress.postal.zip5='00501-1234';if(mode==='unverified')c.inputs.hospital.nativeSourceVerified=false;await assert.rejects(core.publish(c,clock));}});
test('closed inventory, bad pins and links reject lookup',async t=>{for(const mode of ['extra','pin','link']){const c=await fixture(t),r=await core.publish(c,clock);if(mode==='extra')await fs.writeFile(path.join(r.directory,'extra.json'),'{}');if(mode==='link')await fs.link(path.join(r.directory,'zip-00.json'),path.join(c.root,'alias.json'));await assert.rejects(core.lookup(r.directory,mode==='pin'?'0'.repeat(64):r.manifest_sha256,'00501',c));}});
test('cancellation before/during staging and after install preserves ownership and inspectable release',async t=>{for(const phase of ['pre','stage','published']){const c=await fixture(t),controller=new AbortController(),base=path.join(c.root,'data/cms-retained-directory-zip-evidence');const original=controller.signal.throwIfAborted.bind(controller.signal);controller.signal.throwIfAborted=()=>{const dir=path.join(base,phase==='stage'?'.staging':'releases');if(phase==='pre'||existsSync(dir)&&readdirSync(dir).some(n=>phase==='published'||existsSync(path.join(dir,n,'zip-00.json'))))controller.abort();original();};await assert.rejects(core.publish(c,clock,controller.signal),e=>{if(phase==='published')assert.equal(e.inspection_required,true);return /abort/i.test(e.message);});if(existsSync(path.join(base,'.locks')))assert.deepEqual(await fs.readdir(path.join(base,'.locks')),[]);}});
test('concurrent owners cannot install different bytes at one release; public injection rejected',async t=>{const c=await fixture(t),r=await Promise.allSettled([core.publish(c,clock),core.publish(c,clock)]);assert.ok(r.some(v=>v.status==='fulfilled'));for(const e of r.filter(v=>v.status==='rejected'))assert.equal(e.reason.code,'EEXIST');await assert.rejects(publishCmsRetainedDirectoryZipEvidence({context:c}),/unsupported/);await assert.rejects(readCmsRetainedDirectoryZipEvidence({zip5:'00501',root:c.root}),/unsupported/);});
test('lookup never invokes source replay; cleanup failure preserves published release and owned lock',async t=>{
 const c=await fixture(t),r=await core.publish(c,clock);c.load=()=>{throw Error('must not replay');};assert.equal((await core.lookup(r.directory,r.manifest_sha256,'90210',c)).row.nursing_home.directory_rows,1);
 const other=await fixture(t),unlink=fs.unlink,lockDir=path.join(other.root,'data/cms-retained-directory-zip-evidence/.locks'),stub=t.mock.method(fs,'unlink',async(file,...args)=>{if(path.dirname(file)===lockDir)throw Error('injected');return unlink(file,...args);});
 try{await assert.rejects(core.publish(other,clock),e=>{assert.equal(e.code,'CMS_ZIP_INSPECTION_REQUIRED');assert.equal(e.recovery.publication_state,'published');return true;});}finally{stub.mock.restore();}assert.equal((await fs.readdir(lockDir)).length,1);
});
test('registered native lookup is bounded and preserves exact cohort pins without source replay',async()=>{
 const c=JSON.parse(await fs.readFile(path.join(APP_ROOT,'config/datasets/cms-retained-directory-zip-evidence.json'))),raw=await fs.readFile(path.join(APP_ROOT,c.retained_release.manifest)),m=JSON.parse(raw);assert.equal(hash(raw),c.retained_release.manifest_sha256);assert.equal(m.summary.hospital.directory_rows,5419);assert.equal(m.summary.nursing_home.directory_rows,14690);assert.equal(m.indexed_zip_count,9997);assert.equal(c.runtime_pointer,null);assert.equal(c.production_enrollment,false);
 const found=await readCmsRetainedDirectoryZipEvidence({zip5:'00000'});assert.equal(found.row,null);assert.equal(found.source_replay_performed,false);assert.equal(found.bindings.sources.nursing_home.historical_failed_run_id,'ffb1fac4-4eb4-4ea4-b11c-875ebff4de41');assert.equal(found.claims.business_count,null);
});
