import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {cmsNursingHomeChainFixture as fixture,loadCmsNursingHomeChainReportingInput as load} from './cms-nursing-home-chain-reporting-input.mjs';
const headers=['CMS Certification Number (CCN)','Chain Name','Chain ID','Number of Facilities in Chain','Processing Date'];
function input(values){const raw=Buffer.from([headers,...values.map((v,i)=>[String(i+1).padStart(6,'0'),...v,'08/01/2026'])].map(r=>r.map(v=>'"'+v.replaceAll('"','""')+'"').join(',')).join('\n')+'\n'),hash=createHash('sha256').update(raw).digest('hex');return [raw,values.map((v,i)=>({identifier:{value:String(i+1).padStart(6,'0')},provenance:{sourceRow:i+2,csvSha256:hash},sourceRecordId:`cms-pdc:4pq5-n9py:${hash}:row:${i+2}`}))];}
test('chain assertions conserve missing rows and preserve opaque numeric strings and exact names',async()=>{const r=await fixture(...input([['Example','001','2'],['Example','001','2'],['','','']]));assert.equal(r.nativeSourceVerified,false);assert.equal(r.rows.length,3);assert.equal(r.rows[0].chainId.raw,'001');assert.equal(r.groups[0].memberRows,2);assert.equal(r.groups[0].reportedCountReconciliation,'matches-retained-membership');assert.equal(r.summary.rowsMissingChainId,1);assert.equal(r.claims.legalParentVerified,false);assert.ok(Object.isFrozen(r.rows[0].chainId));});
test('contradictions and cardinality differences are retained, not forced into consistency',async()=>{const r=await fixture(...input([['A','1','9'],['B','1','8'],['B','2','9'],['X','','1'],['','3',''],['Z','unknown','?'],[' Q\t','4','0']]));assert.equal(r.rows.length,7);assert.equal(r.summary.groupsWithNameVariants,1);assert.equal(r.summary.namesAcrossMultipleIds,1);assert.equal(r.groups.find(g=>g.chainId==='1').reportedCountReconciliation,'contradictory-reported-counts');assert.equal(r.groups.find(g=>g.chainId==='2').reportedCountReconciliation,'differs-from-retained-membership');assert.equal(r.groups.find(g=>g.chainId==='3').reportedCountReconciliation,'unresolved');assert.equal(r.rows[6].chainName.raw,' Q\t');assert.ok(r.rows[3].flags.includes('count-without-chain-id'));assert.equal(r.summary.rowsUnresolvedChainId,1);assert.equal(r.summary.directoryRows,r.summary.rowsWithLexicallyValidChainId+r.summary.rowsMissingChainId+r.summary.rowsUnresolvedChainId);});
test('CSV/source-row/CCN tamper, duplicate headers, invalid UTF8 and sparse linkage reject without row leakage',async()=>{for(const mutation of ['ccn','row','hash','duplicate','sparse','utf8','quote']){const [raw,selected]=input([['SECRET_NAME','1','1']]);let bytes=raw;if(mutation==='ccn')selected[0].identifier.value='999999';if(mutation==='row')selected[0].provenance.sourceRow=3;if(mutation==='hash')selected[0].provenance.csvSha256='0'.repeat(64);if(mutation==='duplicate')bytes=Buffer.from(raw.toString().replace('Chain Name','Chain ID'));if(mutation==='sparse')delete selected[0];if(mutation==='utf8')bytes=Buffer.from([255]);if(mutation==='quote')bytes=Buffer.concat([raw,Buffer.from('"SECRET_NAME')]);await assert.rejects(fixture(bytes,selected),e=>!e.message.includes('SECRET_NAME'));}});
test('closed native options and caller cancellation reject; zero fixture remains honest',async()=>{await assert.rejects(load({path:'other'}));await assert.rejects(load({signal:AbortSignal.abort()}),{name:'AbortError'});const [raw,rows]=input(Array.from({length:1000},()=>['A','1','1000'])),c=new AbortController();setImmediate(()=>c.abort());await assert.rejects(fixture(raw,rows,{signal:c.signal}),{name:'AbortError'});const zero=await fixture(...input([]));assert.equal(zero.summary.directoryRows,0);assert.equal(zero.nativeSourceVerified,false);});
test('actual short timer is observed at a cooperative projection yield',async()=>{const [raw,rows]=input(Array.from({length:2000},()=>['A','1','2000'])),signal=AbortSignal.timeout(1);await assert.rejects(fixture(raw,rows,{signal}),{name:'TimeoutError'});assert.equal(signal.aborted,true);});
test('native retained chain replay conserves cohort without source calls or publication',{skip:process.env.DATAHUB_TEST_NURSING_RETAINED!=='1',timeout:180000},async t=>{t.mock.method(globalThis,'fetch',()=>assert.fail('No network'));const r=await load({signal:AbortSignal.timeout(180000)});assert.equal(r.nativeSourceVerified,true);assert.equal(r.summary.directoryRows,14690);assert.equal(r.summary.rowsWithLexicallyValidChainId,10116);assert.equal(r.summary.rowsMissingChainId,4574);assert.equal(r.summary.publisherGroupIds,610);assert.equal(r.summary.groupsMatchingReportedCount,610);assert.equal(r.summary.rowsWithFlags,0);console.info(JSON.stringify({proof:'retained-chain-read-only',summary:r.summary,csv:r.evidence.rawCsv,manifestSha256:r.evidence.manifestSha256,dictionary:r.evidence.dictionary,networkDisabled:true,publicationPerformed:false}));});
