import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {mkdir,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {APP_ROOT} from './paths.mjs';
import {CMS_HOSPITAL_REGISTRY_ARTIFACT as TYPE,CMS_HOSPITAL_REGISTRY_PATH as FILE,cmsHospitalRegistryDeclaration as declaration,cmsHospitalRegistryDependency as dependency,validateCmsHospitalRegistryEnvelope as envelope,validateCmsHospitalRegistryMembership as membership,verifyCmsHospitalRegistryExtension as verify,loadCmsHospitalRegistryInput as load} from './cms-hospital-registry-input.mjs';
function fixture(){const records=[{sourceRecordId:'synthetic-1',identifier:{type:'cms-pdc-hospital-facility-id',value:'A00001'}},{sourceRecordId:'synthetic-2',identifier:{type:'cms-pdc-hospital-facility-id',value:'000002'}}];const input={records,selection:{path:'config/cms-hospital-retained-selection.json',sha256:'a'.repeat(64)},source:{dataset_id:'cms-hospital-general-information',release_id:'synthetic-source',manifest_sha256:'b'.repeat(64),acquisition_completed_at:'2026-09-12T14:02:20.502Z',selected_artifact:{bytes:123,sha256:'c'.repeat(64)}},summary:{directory_rows:2}};const artifact={path:FILE,artifact_type:TYPE,record_count:2,bytes:123,sha256:'c'.repeat(64),export_policy:'local-review-only'};const manifest={dataset_id:'national-business-registry',publisher:{id:'national-business-registry',version:'2.15.0'},created_at:'2026-09-12T15:00:00.000Z',export_policy:'internal; local-review-only',coverage:{physical_sites:7,source_records:20,cms_hospital_directory_rows:2},artifacts:[artifact],dependencies:[dependency(input)],cms_hospital_directory_reporting:declaration(input)};return {input,artifact,manifest,meter:{bytes:123,sha256:'c'.repeat(64),records:2}};}
test('typed admission preserves independent canonical counts and not-yet-reconciled future identity possibility',()=>{const {input,manifest,artifact,meter}=fixture();assert.deepEqual(envelope(manifest,input),artifact);membership(input,input.records,meter,artifact);assert.equal(manifest.coverage.physical_sites,7);assert.equal(manifest.coverage.source_records,20);assert.equal(manifest.cms_hospital_directory_reporting.identity_reconciliation_status,'not-yet-reconciled');assert.equal(manifest.cms_hospital_directory_reporting.unique_business_count,null);assert.equal(manifest.cms_hospital_directory_reporting.physical_site_assertion_applied,false);});
test('optional envelope supports each existing reporting-capable base version without requiring unrelated source dependencies',()=>{for(const version of ['2.12.0','2.13.0','2.14.0','2.15.0']){const {input,manifest}=fixture();manifest.publisher.version=version;assert.ok(envelope(manifest,input));}});
test('absent option leaves historical base versions valid, but orphan count/artifact/dependency rejects',()=>{for(const version of ['1.0.0','2.12.0','2.15.0'])assert.equal(envelope({publisher:{version},artifacts:[],dependencies:[],coverage:{}}),null);for(const mutate of [m=>m.artifacts.push({path:FILE}),m=>m.artifacts.push({artifact_type:TYPE}),m=>m.dependencies.push({dataset_id:'cms-hospital-general-information'}),m=>m.coverage.cms_hospital_directory_rows=0]){const m={artifacts:[],dependencies:[],coverage:{}};mutate(m);assert.throws(()=>envelope(m));}});
test('dependency, source/selection lineage, artifact roster and row-count drift rejects',()=>{for(const change of [m=>m.dependencies=[],m=>m.dependencies.push(m.dependencies[0]),m=>m.dependencies[0].manifest_sha256='d'.repeat(64),m=>m.artifacts=[],m=>m.artifacts.push(m.artifacts[0]),m=>m.artifacts[0].path='other.jsonl',m=>m.artifacts[0].bytes++,m=>m.artifacts[0].sha256='e'.repeat(64),m=>m.coverage.cms_hospital_directory_rows++,m=>m.cms_hospital_directory_reporting.selection.sha256='f'.repeat(64),m=>m.cms_hospital_directory_reporting.source.release_id='different']){const {input,manifest}=fixture();const m=structuredClone(manifest);change(m);assert.throws(()=>envelope(m,input));}});
test('chronology, exact base version and policy/claim widening rejects',()=>{for(const change of [m=>m.created_at='2026-09-12T14:02:20.501Z',m=>m.created_at='invalid',m=>m.publisher.version='2.16.0',m=>m.export_policy='public',m=>m.artifacts[0].export_policy='public',m=>m.cms_hospital_directory_reporting.identity_matching_applied=true,m=>m.cms_hospital_directory_reporting.current_operations_verified=true]){const {input,manifest}=fixture();const m=structuredClone(manifest);change(m);assert.throws(()=>envelope(m,input));}});
test('exact membership rejects changed, missing, extra, reordered or duplicate rows and sparse arrays',()=>{const {input,artifact,meter}=fixture();for(const records of [[input.records[1],input.records[0]],[input.records[0]],[...input.records,input.records[0]],[input.records[0],input.records[0]],new Array(2)])assert.throws(()=>membership(input,records,meter,artifact));const changed=structuredClone(input.records);changed[0].identifier.value='DIFFERENT';assert.throws(()=>membership(input,changed,meter,artifact));assert.throws(()=>membership(input,input.records,{...meter,sha256:'d'.repeat(64)},artifact));});
test('absence verifier detects a physically undeclared typed artifact without requiring a native source',async t=>{const base=path.join(APP_ROOT,'data/tmp');await mkdir(base,{recursive:true});const directory=await mkdtemp(path.join(base,'cms-registry-test-'));t.after(()=>rm(directory,{recursive:true,force:true}));const manifest={artifacts:[],dependencies:[],coverage:{}};assert.equal(await verify(manifest,directory),null);await mkdir(path.dirname(path.join(directory,FILE)),{recursive:true});await writeFile(path.join(directory,FILE),'synthetic');await assert.rejects(verify(manifest,directory));});
test('preabort and noncanonical selection prevent native replay',async()=>{await assert.rejects(load('data/fake/manifest.json'));await assert.rejects(load(path.join(APP_ROOT,'config/cms-hospital-retained-selection.json'),{signal:AbortSignal.abort()}),{name:'AbortError'});await assert.rejects(verify({},APP_ROOT,{signal:AbortSignal.abort()}),{name:'AbortError'});});
