import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {mkdir,readFile,writeFile,readdir,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {APP_ROOT} from './paths.mjs';
import {CMS_NURSING_HOME_SELECTED_HEADERS as H} from './cms-nursing-home-prerequisite.mjs';
import {recoverCmsNursingHomesWithTestInput as recover} from './cms-nursing-home-recovery.mjs';
import {buildCmsNursingHomeAdoptionWithTestInput as build,verifyCmsNursingHomeAdoptionWithTestInput as verify,buildCmsNursingHomeAdoption as nativeBuild,CMS_NURSING_HOME_RETAINED_ADOPTION as source} from './cms-nursing-home-adoption.mjs';
import {ManagedOperations} from './managed-operations.mjs';
import {isolatedCmsAcquisitionFixture} from './isolated-cms-acquisition-fixture.mjs';
if(process.env.DATAHUB_CMS_ACQUISITION_SUITE!=='nursing-adoption')isolatedCmsAcquisitionFixture(fileURLToPath(import.meta.url),'nursing-adoption',7);
else {
const ROOT=path.join(APP_ROOT,'data/tmp/cms-nursing-home-recovery'),sha=v=>createHash('sha256').update(v).digest('hex'),json=v=>Buffer.from(JSON.stringify(v)+'\n');
async function fixture(t){await mkdir(path.join(ROOT,'sources'),{recursive:true});await mkdir(path.join(ROOT,'outputs'),{recursive:true});const old=new Set(await readdir(path.join(ROOT,'outputs'))),runId=randomUUID(),directory=path.join(ROOT,'sources',runId);await mkdir(directory);t.after(async()=>{await rm(directory,{recursive:true,force:true});for(const name of await readdir(path.join(ROOT,'outputs'))){if(old.has(name))continue;assert.match(name,/^[a-f0-9-]{36}$/);const target=path.join(ROOT,'outputs',name);assert.equal(path.dirname(target),path.join(ROOT,'outputs'));await rm(target,{recursive:true,force:true});}});
 const createdAt='2026-09-12T14:21:58.087Z',m={identifier:'4pq5-n9py',title:'Provider Information',accessLevel:'public',publisher:{name:'Centers for Medicare & Medicaid Services (CMS)'},landingPage:'https://data.cms.gov/provider-data/dataset/4pq5-n9py',description:'General information on currently active nursing homes, including number of certified beds, quality measure scores, staffing and other information used in the Five-Star Rating System. Data are presented as one row per nursing home.',issued:'2026-02-01',modified:'2026-08-01',released:'2026-08-26',distribution:[{mediaType:'text/csv',downloadURL:'https://data.cms.gov/provider-data/sites/default/files/resources/328596835e6db31b2564cd733c3795f4_1786724150/NH_ProviderInfo_Aug2026.csv',describedBy:'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/nursing_home/NH_Data_Dictionary.pdf',describedByType:'application/pdf'}]},limits={requests:5,metadataBytes:1048576,dictionaryBytes:5242880,noticeBytes:1048576,csvBytes:33554432,totalResponseBytes:41943040,rows:25000,jobDeadlineMs:240000,cleanupGraceMs:1000,parallelRequests:1,retries:0,redirects:0};
 const bodyNames=['metadata-before.json','dictionary.pdf','reuse-notice.pdf','source.csv','metadata-after.json'],parts=new Map([['metadata-before.json',json(m)],['metadata-after.json',json(m)],['dictionary.pdf',Buffer.from('%PDF-SYNTHETIC-NURSING-HOME-DICTIONARY')],['reuse-notice.pdf',Buffer.from('%PDF-SYNTHETIC-CMS-REUSE-NOTICE')],['source.csv',Buffer.from(H.join(',')+'\n00123A,Fixture Home,1\tStreet,City,PR,00901-0004,County,Owner,Provider,Legal,18,-66,22,08/01/2026\n000002,Other Home,2 Street,City,ZZ,,County,Owner,Provider,Legal,,,,08/01/2026\n')]]);
 parts.set('intent.json',json({schemaVersion:'cms-nursing-home-acquisition@1.0.0',runId,executionMode:'injected-fixture',createdAt,limits,policyProfile:'cms-nursing-home-acquisition@1.0.0'}));const urls=['https://data.cms.gov/provider-data/api/1/metastore/schemas/dataset/items/4pq5-n9py',m.distribution[0].describedBy,'https://data.cms.gov/sites/default/files/2022-12/API%20FAQ%20%20v1_1.pdf',m.distribution[0].downloadURL,'https://data.cms.gov/provider-data/api/1/metastore/schemas/dataset/items/4pq5-n9py'];for(let i=0;i<5;i++)parts.set('request-'+(i+1)+'.json',json({sequence:i+1,url:urls[i],method:'GET',credentials:'omit',maxBytes:i===3?33554432:i===1?5242880:1048576,timeoutMs:i===3?90000:30000}));
 parts.set('failure.json',json({schemaVersion:'cms-nursing-home-acquisition@1.0.0',runId,executionMode:'injected-fixture',status:'FAILED',requestAttempts:5,finishedAt:'2026-09-12T14:21:59.786Z',published:false,networkOwnershipUnresolved:false,completedRestrictedSourceArtifacts:bodyNames.map(p=>({path:p,bytes:parts.get(p).length,sha256:sha(parts.get(p)),exportPolicy:'internal'})),error:'Synthetic failed source'}));for(const [name,bytes]of parts)await writeFile(path.join(directory,name),bytes);return {directory,pin:{runId,rows:2,files:[...parts].map(([p,b])=>({path:p,bytes:b.length,sha256:sha(b)}))}};
}
async function input(t){const f=await fixture(t),recovery=await recover(f.pin);return{...f,source:{manifestPath:recovery.manifestPath,manifestSha256:recovery.manifestSha256,failedSourcePin:f.pin}};}
async function op(){const operationId=randomUUID();await mkdir(path.join(APP_ROOT,'data/tmp/cms-nursing-home-adoption',operationId),{recursive:true});return{operationId};}
test('verified recovery adoption keeps failure identity and clocks, typed counts and no source JSON',async t=>{const f=await input(t),id=await op(),d=await build(id,f.source),r=await verify(d,id,f.source);assert.equal(r.summary.directoryRows,2);assert.equal(r.summary.territoryRows,1);assert.equal(r.summary.unknownStateRows,1);assert.equal(r.summary.historicalAcquisitionStatus,'FAILED');assert.equal(r.summary.failedSourceRunId,f.pin.runId);assert.equal(r.summary.failedSourceReceiptSha256,f.pin.files.find(x=>x.path==='failure.json').sha256);assert.equal(r.claims.recoveryPerformedThisRun,false);assert.equal(r.claims.networkRequestsPerformed,0);assert.match(r.claims.jsonOutputPolicy,/metadata-only/);assert.doesNotMatch(JSON.stringify(r),/Fixture Home|Other Home|1\\tStreet|00123A/);for(const p of f.pin.files)assert.equal(sha(await readFile(path.join(f.directory,p.path))),p.sha256);await assert.rejects(verify(d,await op(),f.source));});
test('rehashed failure widening counts clocks and source drift reject',async t=>{const f=await input(t),id=await op(),d=await build(id,f.source),original=await readFile(d.manifestPath);for(const mutate of [r=>r.summary.historicalAcquisitionStatus='SUCCEEDED',r=>r.summary.directoryRows++,r=>r.summary.failedSourceReceiptSha256='0'.repeat(64),r=>r.claims.publicExportAuthorized=true,r=>r.startedAt='2000-01-01T00:00:00.000Z']){const r=JSON.parse(original);mutate(r);const bytes=json(r);await writeFile(d.manifestPath,bytes);await assert.rejects(verify({...d,manifestSha256:sha(bytes)},id,f.source));}await writeFile(d.manifestPath,original);await writeFile(path.join(f.directory,'source.csv'),'changed');await assert.rejects(verify(d,id,f.source));});
test('cancellation deadline and duplicate output retain truthful inspection',async t=>{const f=await input(t);await assert.rejects(build(await op(),f.source,{signal:AbortSignal.abort()}));const id=await op(),d=await build(id,f.source);await assert.rejects(build(id,f.source));await verify(d,id,f.source);let recovery;await assert.rejects(build(await op(),f.source,{testDeadlineMs:1000,hook:async stage=>{if(stage==='after-publication')await new Promise(r=>setTimeout(r,1100));}}),e=>{recovery=e.recovery;return true;});assert.equal(recovery.inspectionRequired,true);assert.throws(()=>nativeBuild(id,{testDeadlineMs:1}));});
const fake=id=>({operationId:id,executionMode:'verified-retained-source',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString(),summary:{sourceRunId:source.runId,sourceManifestSha256:source.manifestSha256,historicalAcquisitionStatus:'FAILED',failedSourceRunId:source.failedSourceRunId}});
async function settled(service,id){for(let n=0;n<100;n++){const r=await service.get(id);if(!['QUEUED','RUNNING'].includes(r.status))return r;await new Promise(r=>setTimeout(r,5));}throw Error('Did not settle');}
test('managed fixed dispatch, distinct source binding, duplicate exclusion and restart preserve metadata-only history',async()=>{let release,entered;const gate=new Promise(r=>release=r),began=new Promise(r=>entered=r);let id;const service=new ManagedOperations({executor:async req=>{assert.equal(req.script,'scripts/adopt-cms-nursing-homes.mjs');id=req.args[1];entered();await gate;return{code:0,stdout:'{}'};},adoptionVerifier:async()=>fake(id)});const record=await service.startSourceAdoption({sourceId:source.sourceId});await began;await assert.rejects(service.startSourceAdoption({sourceId:'cms-hospital-general-information'}),{statusCode:409});release();assert.equal((await settled(service,record.id)).status,'SUCCEEDED');await service.close();const reopened=new ManagedOperations({executor:()=>assert.fail('no retry')});const out=await reopened.get(id);assert.deepEqual(out.artifacts,[]);assert.equal(out.result.summary.historicalAcquisitionStatus,'FAILED');assert.equal(out.result.descriptor,undefined);assert.equal(await reopened.artifact(id,'selected.jsonl'),null);await reopened.close();});
test('wrong source or rewritten failure from verifier cannot succeed',async()=>{for(const change of [r=>r.summary.sourceRunId='wrong',r=>r.summary.historicalAcquisitionStatus='SUCCEEDED',r=>r.summary.failedSourceRunId=randomUUID()]){let id;const service=new ManagedOperations({executor:async req=>{id=req.args[1];return{code:0,stdout:'{}'};},adoptionVerifier:async()=>{const r=fake(id);change(r);return r;}});const record=await service.startSourceAdoption({sourceId:source.sourceId});assert.equal((await settled(service,record.id)).status,'FAILED');await service.close();}});
test('cooperative nursing verification cancellation withholds counts and artifacts',async()=>{let entered;const began=new Promise(r=>entered=r);const service=new ManagedOperations({executor:async()=>({code:0,stdout:'{}'}),adoptionVerifier:async(_d,_b,{signal})=>{entered();await new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));}});const r=await service.startSourceAdoption({sourceId:source.sourceId});await began;await service.cancel(r.id);const done=await settled(service,r.id);assert.equal(done.status,'CANCELLED');assert.equal(done.result.summary,undefined);assert.deepEqual(done.artifacts,[]);await service.close();});
test('noncooperative nursing verifier respects managed deadline and keeps UNKNOWN ownership',async()=>{let signal;const service=new ManagedOperations({executor:async()=>({code:0,stdout:'{}'}),adoptionVerifier:async(_d,_b,o)=>{signal=o.signal;return new Promise(()=>{});},adoptionTestTiming:{deadlineMs:30,childCleanupMs:20,verifierCleanupMs:20}});const r=await service.startSourceAdoption({sourceId:source.sourceId}),done=await settled(service,r.id);assert.equal(done.status,'UNKNOWN');assert.equal(signal.aborted,true);assert.equal(done.result.summary,undefined);assert.deepEqual(done.artifacts,[]);await assert.rejects(service.startSourceAdoption({sourceId:source.sourceId}),{statusCode:409});await service.close();});
}
