import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {mkdir,readFile,writeFile,readdir,rm,unlink} from 'node:fs/promises';
import {APP_ROOT} from './paths.mjs';
import {CMS_NURSING_HOME_SELECTED_HEADERS as H} from './cms-nursing-home-prerequisite.mjs';
import {recoverCmsNursingHomesWithTestInput as run,verifyCmsNursingHomeRecoveryWithTestInput as verify,verifyCmsNursingHomeRecovery as nativeVerify,recoverCmsNursingHomes as nativeRun} from './cms-nursing-home-recovery.mjs';
const ROOT=path.join(APP_ROOT,'data/tmp/cms-nursing-home-recovery'),sha=v=>createHash('sha256').update(v).digest('hex'),json=v=>Buffer.from(JSON.stringify(v)+'\n');
async function fixture(t){await mkdir(path.join(ROOT,'sources'),{recursive:true});await mkdir(path.join(ROOT,'outputs'),{recursive:true});const old=new Set(await readdir(path.join(ROOT,'outputs'))),runId=randomUUID(),directory=path.join(ROOT,'sources',runId);await mkdir(directory);t.after(async()=>{await rm(directory,{recursive:true,force:true});for(const name of await readdir(path.join(ROOT,'outputs'))){if(old.has(name))continue;assert.match(name,/^[a-f0-9-]{36}$/);const target=path.join(ROOT,'outputs',name);assert.equal(path.dirname(target),path.join(ROOT,'outputs'));await rm(target,{recursive:true,force:true});}});
 const createdAt='2026-09-12T14:21:58.087Z',m={identifier:'4pq5-n9py',title:'Provider Information',accessLevel:'public',publisher:{name:'Centers for Medicare & Medicaid Services (CMS)'},landingPage:'https://data.cms.gov/provider-data/dataset/4pq5-n9py',description:'General information on currently active nursing homes, including number of certified beds, quality measure scores, staffing and other information used in the Five-Star Rating System. Data are presented as one row per nursing home.',issued:'2026-02-01',modified:'2026-08-01',released:'2026-08-26',distribution:[{mediaType:'text/csv',downloadURL:'https://data.cms.gov/provider-data/sites/default/files/resources/328596835e6db31b2564cd733c3795f4_1786724150/NH_ProviderInfo_Aug2026.csv',describedBy:'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/nursing_home/NH_Data_Dictionary.pdf',describedByType:'application/pdf'}]},limits={requests:5,metadataBytes:1048576,dictionaryBytes:5242880,noticeBytes:1048576,csvBytes:33554432,totalResponseBytes:41943040,rows:25000,jobDeadlineMs:240000,cleanupGraceMs:1000,parallelRequests:1,retries:0,redirects:0};
 const bodyNames=['metadata-before.json','dictionary.pdf','reuse-notice.pdf','source.csv','metadata-after.json'],parts=new Map([['metadata-before.json',json(m)],['metadata-after.json',json(m)],['dictionary.pdf',Buffer.from('%PDF-SYNTHETIC-NURSING-HOME-DICTIONARY')],['reuse-notice.pdf',Buffer.from('%PDF-SYNTHETIC-CMS-REUSE-NOTICE')],['source.csv',Buffer.from(H.join(',')+'\n00123A,Fixture Home,1\tStreet,City,PR,00901-0004,County,Owner,Provider,Legal,18,-66,22,08/01/2026\n000002,Other Home,2 Street,City,ZZ,,County,Owner,Provider,Legal,,,,08/01/2026\n')]]);
 parts.set('intent.json',json({schemaVersion:'cms-nursing-home-acquisition@1.0.0',runId,executionMode:'injected-fixture',createdAt,limits,policyProfile:'cms-nursing-home-acquisition@1.0.0'}));const urls=['https://data.cms.gov/provider-data/api/1/metastore/schemas/dataset/items/4pq5-n9py',m.distribution[0].describedBy,'https://data.cms.gov/sites/default/files/2022-12/API%20FAQ%20%20v1_1.pdf',m.distribution[0].downloadURL,'https://data.cms.gov/provider-data/api/1/metastore/schemas/dataset/items/4pq5-n9py'];for(let i=0;i<5;i++)parts.set('request-'+(i+1)+'.json',json({sequence:i+1,url:urls[i],method:'GET',credentials:'omit',maxBytes:i===3?33554432:i===1?5242880:1048576,timeoutMs:i===3?90000:30000}));
 parts.set('failure.json',json({schemaVersion:'cms-nursing-home-acquisition@1.0.0',runId,executionMode:'injected-fixture',status:'FAILED',requestAttempts:5,finishedAt:'2026-09-12T14:21:59.786Z',published:false,networkOwnershipUnresolved:false,completedRestrictedSourceArtifacts:bodyNames.map(p=>({path:p,bytes:parts.get(p).length,sha256:sha(parts.get(p)),exportPolicy:'internal'})),error:'Synthetic failed source'}));for(const [name,bytes]of parts)await writeFile(path.join(directory,name),bytes);return {directory,pin:{runId,rows:2,files:[...parts].map(([p,b])=>({path:p,bytes:b.length,sha256:sha(b)}))}};
}
test('retained recovery conserves TAB and unknown points, leaves failed source byte-identical, and native verifier rejects fixture',async t=>{const f=await fixture(t),out=await run(f.pin),m=await verify(out.manifestPath,out.manifestSha256,f.pin);assert.equal(m.artifact.rows,2);assert.equal(m.claims.nativeSourceRetainedEvidenceVerified,false);assert.equal(m.claims.nativeTransportThisRun,false);const rows=(await readFile(path.join(path.dirname(out.manifestPath),'selected.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);assert.equal(rows[0].reportedAddress.street,'1\tStreet');assert.equal(rows[0].reportedAddress.textQuality.status,'source-tab-preserved');assert.equal(rows[0].sourceGeocode.facilityPointEligible,false);assert.equal(rows[1].sourceGeocode.status,'missing-coordinates');for(const p of f.pin.files)assert.equal(sha(await readFile(path.join(f.directory,p.path))),p.sha256);await assert.rejects(nativeVerify(out.manifestPath,out.manifestSha256));});
test('source tamper and injected-native mode fail before recovery publication',async t=>{for(const native of [false,true]){const f=await fixture(t);if(native){for(const name of ['intent.json','failure.json']){const p=path.join(f.directory,name),value=JSON.parse(await readFile(p));value.executionMode='native-fixed-fetch';const bytes=json(value);await writeFile(p,bytes);Object.assign(f.pin.files.find(v=>v.path===name),{bytes:bytes.length,sha256:sha(bytes)});}}else await writeFile(path.join(f.directory,'source.csv'),'changed');await assert.rejects(run(f.pin));}});
test('rehashed selected mutation still fails independent source projection replay',async t=>{const f=await fixture(t),out=await run(f.pin),file=path.join(path.dirname(out.manifestPath),'selected.jsonl'),bytes=Buffer.from((await readFile(file,'utf8')).replace('Fixture Home','Changed Home'));await writeFile(file,bytes);const m=JSON.parse(await readFile(out.manifestPath));m.artifact.bytes=bytes.length;m.artifact.sha256=sha(bytes);const manifest=json(m);await writeFile(out.manifestPath,manifest);await assert.rejects(verify(out.manifestPath,sha(manifest),f.pin));});
test('preabort and cancellation before publication leave source untouched and no success manifest',async t=>{const c=new AbortController();c.abort();await assert.rejects(nativeRun({signal:c.signal}),{name:'AbortError'});const f=await fixture(t),later=new AbortController();let recovery;await assert.rejects(run(f.pin,{signal:later.signal},stage=>{if(stage==='before-publication')later.abort();}),error=>{recovery=error.recovery;return true;});assert.equal(recovery.published,false);assert.deepEqual(await readdir(recovery.directory),[]);for(const p of f.pin.files)assert.equal(sha(await readFile(path.join(f.directory,p.path))),p.sha256);});
test('manifest last and postpublication cancellation preserve independent inspection recovery',async t=>{const f=await fixture(t),c=new AbortController();let recovery;await assert.rejects(run(f.pin,{signal:c.signal},async(stage,{directory})=>{if(stage==='before-publication'){assert.ok((await readdir(directory)).includes('manifest.pending'));assert.ok(!(await readdir(directory)).includes('manifest.json'));}else c.abort();}),error=>{recovery=error.recovery;return true;});assert.equal(recovery.inspectionRequired,true);assert.equal((await verify(recovery.manifestPath,recovery.manifestSha256,f.pin)).artifact.rows,2);});
test('changed output ownership is preserved rather than removed',async t=>{const f=await fixture(t);let recovery;await assert.rejects(run(f.pin,{},async(stage,{directory})=>{if(stage==='before-publication'){const p=path.join(directory,'selected.jsonl');await unlink(p);await mkdir(p);}}),error=>{recovery=error.recovery;return true;});assert.ok((await readdir(recovery.directory)).includes('selected.jsonl'));assert.deepEqual(await readdir(path.join(recovery.directory,'selected.jsonl')),[]);});

test('selected mutation after initial output read is caught before verifier success',async t=>{const f=await fixture(t),out=await run(f.pin);await assert.rejects(verify(out.manifestPath,out.manifestSha256,f.pin,{},async(stage,{directory})=>{assert.equal(stage,'after-output-read');await writeFile(path.join(directory,'selected.jsonl'),'changed after first read');}));});
