import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {readFile,realpath,lstat} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {APP_ROOT} from './paths.mjs';
import {pinCmsNursingHomeProductionInput as pin,cmsNursingHomeImplementationFiles as inventory} from './cms-nursing-home-production-input.mjs';
const selection='config/cms-nursing-home-retained-selection.json';
function assertReadiness(result){assert.equal(result.registryAdmissionImplemented,true);assert.equal(result.coverageProjectionImplemented,true);assert.equal(result.productionReleaseVerified,false);assert.equal(result.catalogPublication,false);assert.equal(result.productionDispatchPerformed,false);}
async function safe(root,file){const absolute=path.resolve(root,file),relative=path.relative(root,absolute);assert.ok(relative&&!relative.startsWith('..')&&!path.isAbsolute(relative));assert.equal(await realpath(absolute),absolute);return absolute;}
async function fileHash(file){const before=await lstat(file,{bigint:true});assert.ok(before.isFile()&&!before.isSymbolicLink()&&before.nlink===1n&&before.size<=33554432n);const raw=await readFile(file),after=await lstat(file,{bigint:true});for(const field of ['ino','dev','size','mtimeNs','ctimeNs'])assert.equal(after[field],before[field]);return {bytes:raw.length,sha256:createHash('sha256').update(raw).digest('hex')};}
test('nonnative root, unknown or accessor callbacks and preabort reject before reads',async()=>{const tools={safe:()=>assert.fail('no read'),fileHash:()=>assert.fail('no read')};await assert.rejects(pin(path.join(APP_ROOT,'data/tmp'),selection,tools));await assert.rejects(pin(APP_ROOT,selection,{...tools,source:'other'}));const getter={fileHash:tools.fileHash};Object.defineProperty(getter,'safe',{get(){assert.fail('accessor');}});await assert.rejects(pin(APP_ROOT,selection,getter));await assert.rejects(pin(APP_ROOT,selection,{...tools,signal:AbortSignal.abort()}),{name:'AbortError'});await assert.rejects(inventory(path.join(APP_ROOT,'data/tmp')));});
test('actual retained helper binds fifteen exact recovery and failed-source inputs without a production plan',{skip:process.env.DATAHUB_TEST_NURSING_RETAINED!=='1',timeout:180000},async t=>{t.mock.method(globalThis,'fetch',()=>assert.fail('No network'));const result=await pin(APP_ROOT,selection,{safe,fileHash,signal:AbortSignal.timeout(180000)});assertReadiness(result);assert.equal(result.evidencePins.length,15);assert.equal(new Set(result.evidencePins.map(p=>p.path)).size,15);assert.equal(result.declaration.summary.directory_rows,14690);assert.equal(result.declaration.source.failed_source.files.length,12);assert.equal(result.declaration.source.manifest_sha256,'89ee608067aa5b97833957b753be61003dc2efcfa22cfaedbb3b78f020396d7e');assert.equal(result.coverageProjectionImplemented,true);assert.equal(result.productionDispatchPerformed,false);assert.equal(result.sourceMode,'retained-native-source-recovery');for(const name of ['failure.json','request-5.json','dictionary.pdf','source.csv','selected.jsonl'])assert.ok(result.evidencePins.some(p=>p.path.endsWith('/'+name)));const modules=await inventory();for(const file of ['runner/cms-nursing-home-production-input.mjs','runner/cms-nursing-home-registry-input.mjs','runner/cms-nursing-home-reporting-input.mjs','runner/cms-nursing-home-recovery.mjs','runner/cms-nursing-home-recovery-pins.mjs','runner/cms-nursing-home-prerequisite.mjs','runner/mn-construction-retained-selection.mjs','config/cms-nursing-home-retained-selection.json','config/source-policies/cms-nursing-home-acquisition.json','package.json','package-lock.json'])assert.ok(modules.includes(file),file);assert.deepEqual(modules,[...new Set(modules)].sort());console.info(JSON.stringify({proof:'retained-production-helper-only',networkDisabled:true,evidencePins:result.evidencePins,directoryRows:14690,failedSourceFiles:12,implementationFileCount:modules.length,productionPlanCreated:false}));});
test('wrong or changing evidence hashes and mid-pin cancellation fail against actual retained input',{skip:process.env.DATAHUB_TEST_NURSING_RETAINED!=='1',timeout:180000},async t=>{t.mock.method(globalThis,'fetch',()=>assert.fail('No network'));await assert.rejects(pin(APP_ROOT,selection,{safe,fileHash:async()=>({bytes:1,sha256:'0'.repeat(64)})}));let calls=0;await assert.rejects(pin(APP_ROOT,selection,{safe,fileHash:async file=>{const h=await fileHash(file);calls++;return calls>15?{...h,sha256:'0'.repeat(64)}:h;}}));assert.equal(calls,16);const c=new AbortController();await assert.rejects(pin(APP_ROOT,selection,{safe,signal:c.signal,fileHash:async file=>{const h=await fileHash(file);c.abort();return h;}}),{name:'AbortError'});});
