import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import {readCmsRetainedDirectoryZipEvidence} from './cms-retained-directory-zip-evidence.mjs';
const require=createRequire(import.meta.url),source=await readFile(new URL('../app/workspace-views.tsx',import.meta.url),'utf8');
const text=value=>value==null||typeof value==='boolean'?'':typeof value!=='object'?String(value):Array.isArray(value)?value.map(text).join(''):text(value.props?.children);
function harness(request){const values=[],effects=[],cleanups=[],dependencies=[];let cursor=0,effectCursor=0;const exports={};runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,AbortController,URLSearchParams,document:{getElementById:()=>null},require:name=>name==='./runner-client'?{runnerJson:request}:name==='./business-intelligence'?{StateAvailabilityChoropleth:()=>null}:name.startsWith('./census-')?{default:()=>null}:name.startsWith('./')?{}:name==='react'?{useMemo:fn=>fn(),useState:initial=>{const index=cursor++;if(!(index in values))values[index]=initial;return[values[index],next=>values[index]=next];},useEffect:(effect,next)=>{const index=effectCursor++;if(!dependencies[index]||next.some((value,item)=>value!==dependencies[index][item])){dependencies[index]=next;effects.push(()=>{cleanups[index]?.();cleanups[index]=effect();});}}}:require(name)});return{render:(name,...args)=>{cursor=0;effectCursor=0;const tree=exports[name](...args);effects.splice(0).forEach(run=>run());return tree;},close:()=>cleanups.forEach(cleanup=>cleanup?.())};}
test('client accepts the protected endpoint native envelope',async()=>{const h=harness(()=>assert.fail()),value=await readCmsRetainedDirectoryZipEvidence({zip5:'00603'});assert.equal(h.render('validCmsDirectoryZipEvidence',value,'00603'),true);});
const flush=()=>new Promise(resolve=>setTimeout(resolve,0)),sha='a'.repeat(64),claims={export_policy:'local-review-only',production_enrollment:false,national_reporting_denominator_enrollment:false,current_pointer_written:false,network_requests:0,business_count:null,physical_site_count:null,current_operating_count:null,national_completeness_percent:null,coordinates_retained:false,county_assignment_performed:false,zcta_membership_inferred:false,zip4_aggregated:false,public_export_authorized:false};
const sourceBinding=(kind)=>({selection_path:`config/${kind}.json`,selection_sha256:sha,manifest_path:`data/${kind}/manifest.json`,manifest_sha256:sha,release_id:`${kind}-r1`,selected_artifact:{path:'selected.jsonl',bytes:10,sha256:sha,...(kind==='nursing_home'?{rows:1}:{}),exportPolicy:'local-review-only'},source_dates:{issued:'2026-01-01',modified:'2026-02-01',released:'2026-03-01'},observed_at:'2026-03-02T00:00:00.000Z',completed_at:'2026-03-02T00:01:00.000Z',provenance_mode:kind==='hospital'?'native-acquisition':'retained-native-source-recovery',...(kind==='nursing_home'?{historical_failed_run_id:'failed-r1',historical_failed_at:'2026-03-01T00:00:00.000Z',historical_failure_rewritten:false}:{})});
const denominator=(reported_states)=>{const total=Object.values(reported_states).reduce((sum,value)=>sum+value,0);return{directory_rows:total,state_dc_rows:total,territory_rows:0,unknown_state_rows:0,missing_zip_rows:0,zip_present_rows:total,reported_states};};
const response=(zip,status='retained-directory-evidence-present')=>({schema_version:'cms-retained-directory-zip-evidence@1.0.0',available:true,zip5:zip,status,row:status==='retained-directory-evidence-present'?{zip5:zip,zip4:null,hospital:{directory_rows:2,reported_states:{'reported:NY':1,'reported:NJ':1}},nursing_home:{directory_rows:1,reported_states:{'reported:NY':1}}}:null,release_id:`cms-retained-directory-zip-evidence-${'b'.repeat(64)}`,manifest_sha256:sha,created_at:'2026-03-03T00:00:00.000Z',bindings:{sources:{hospital:sourceBinding('hospital'),nursing_home:sourceBinding('nursing_home')}},denominators:{hospital:denominator({'reported:NY':1,'reported:NJ':1}),nursing_home:denominator({'reported:NY':1})},claims,source_replay_performed:false,semantics:'Separate dated directory-row evidence only; missing source/ZIP evidence is not zero businesses or closure.'});

test('strict CMS ZIP validator and panel preserve row, state, lineage and non-completeness semantics',()=>{const h=harness(()=>assert.fail()),valid=response('10001');assert.equal(h.render('validCmsDirectoryZipEvidence',valid,'10001'),true);for(const mutate of [value=>value.extra=true,value=>value.claims.business_count=3,value=>value.row.zip5='10002',value=>value.row.hospital.reported_states={'reported:NY':99},value=>value.bindings.sources.hospital.extra=true,value=>{delete value.denominators.hospital.reported_states['reported:NJ'];value.denominators.hospital.reported_states['reported:NY']=2;},value=>{value.row.hospital.reported_states={'reported:NY':2};value.denominators.hospital.reported_states={'reported:NY':1,'reported:NJ':1};},value=>value.bindings.sources.hospital.provenance_mode='retained-native-source-recovery',value=>value.bindings.sources.nursing_home.provenance_mode='native-acquisition',value=>value.bindings.sources.hospital.source_dates.issued='2026-02-30']){const bad=structuredClone(valid);mutate(bad);assert.equal(h.render('validCmsDirectoryZipEvidence',bad,'10001'),false);}const tree=h.render('CmsDirectoryZipPanel',{view:valid}),value=text(tree);assert.match(value,/Hospital directory rows2/);assert.match(value,/Nursing-home directory rows1/);assert.match(value,/Reported NY1/);assert.match(value,/Issued 2026-01-01/);assert.match(value,/not active-business counts, verified physical sites/);assert.match(value,/Local review only/);assert.equal(tree.props.style.minWidth,0);});
test('CMS absent and unavailable envelopes never imply zero or closure',()=>{const h=harness(()=>assert.fail()),absent=response('00501','absent-from-retained-directory-zip-evidence'),unavailable={available:false,zip5:'00501',status:'not-registered',claims};assert.equal(h.render('validCmsDirectoryZipEvidence',absent,'00501'),true);assert.match(text(h.render('CmsDirectoryZipPanel',{view:absent})),/not zero businesses, closure, ZIP invalidity/);assert.equal(h.render('validCmsDirectoryZipEvidence',unavailable,'00501'),true);assert.match(text(h.render('CmsDirectoryZipPanel',{view:unavailable})),/No absence, zero, or closure is inferred/);});
test('CMS ZIP loader aborts stale exact-ZIP reads and rejects malformed late responses',async()=>{const pending=[],h=harness((url,{signal})=>new Promise(resolve=>pending.push({url,signal,resolve})));h.render('CmsDirectoryZipLoader',{zip:'10001',attempt:0});let tree=h.render('CmsDirectoryZipLoader',{zip:'10002',attempt:0});assert.equal(pending[0].signal.aborted,true);assert.match(pending[1].url,/zip=10002$/);pending[1].resolve(response('10002'));await flush();tree=h.render('CmsDirectoryZipLoader',{zip:'10002',attempt:0});assert.equal(tree.type.name,'CmsDirectoryZipPanel');assert.equal(tree.props.view.zip5,'10002');pending[0].resolve(response('10001'));await flush();tree=h.render('CmsDirectoryZipLoader',{zip:'10002',attempt:0});assert.equal(tree.props.view.zip5,'10002');h.close();});
