import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {cmsHospitalReportingFixture as fixture,summarizeCmsHospitalReporting as summarize,validateCmsHospitalRetainedSelection as validate,loadCmsHospitalReportingInput as load} from './cms-hospital-reporting-input.mjs';
const hash='a'.repeat(64);
function row(i,state='ME',zip5='00123',zip4=null){return {sourceRecordId:`cms-pdc:xubh-q36u:${hash}:row:${i+2}`,identifier:{type:'cms-pdc-hospital-facility-id',raw:`A${String(i).padStart(5,'0')}`,value:`A${String(i).padStart(5,'0')}`},facilityName:'Synthetic facility',reportedAddress:{state,postal:{raw:zip5===null?null:zip5+(zip4===null?'':`-${zip4}`),zip5,zip4,status:zip5===null?'missing':'format-only-usps-unverified'},addressVerified:false},npi:null,parentCompany:null,currentOperatingStatus:null,geocode:{latitude:null,longitude:null},provenance:{datasetId:'xubh-q36u',csvSha256:hash,sourceRow:i+2,policyProfile:'cms-hospital-acquisition@1.0.0'},claims:{recordUnit:'publisher-hospital-facility-directory-row',uniqueBusinessIdentityVerified:false,physicalCampusIdentityVerified:false,currentOperationsVerified:false,exportPolicy:'local-review-only'}};}
test('closed exact native selection rejects future, fixture, path and hash overrides',async()=>{const p=JSON.parse(await readFile(new URL('../config/cms-hospital-retained-selection.json',import.meta.url),'utf8'));assert.deepEqual(validate(p),p);for(const changed of [{...p,extra:true},{...p,manifestSha256:'b'.repeat(64)},{...p,manifestPath:'data/tmp/cms-hospital-acquisition/fixture/manifest.json'},{...p,schemaVersion:'future'}])assert.throws(()=>validate(changed));const accessor={...p};Object.defineProperty(accessor,'manifestPath',{get(){assert.fail('must not invoke accessor');},enumerable:true});assert.throws(()=>validate(accessor));});
test('synthetic snapshot preserves source IDs and separate postal values but never claims native proof',()=>{const r=row(0,'ME','00123','0004'),input=fixture([r]);assert.equal(input.nativeSourceVerified,false);assert.equal(input.rows[0].identifier.value,'A00000');assert.equal(input.rows[0].reportedAddress.postal.zip4,'0004');r.identifier.value='CHANGED';assert.equal(input.rows[0].identifier.value,'A00000');assert.ok(Object.isFrozen(input.rows[0].provenance));assert.throws(()=>summarize({...input}));});
test('all-source and stateDC denominators remain fixed through state and ZIP filters with territories and unknowns conserved',()=>{const input=fixture([row(0),row(1),row(2,'DC','20001'),row(3,'PR','00901'),row(4,null,null)]),all=summarize(input);assert.deepEqual(all.denominators,{allRetainedDirectoryRows:5,stateDCRetainedDirectoryRows:3,territoryRetainedDirectoryRows:1,unknownReportedStateRows:1});assert.equal(all.filteredRowsMissingZip5,1);assert.equal(all.stateZips.reduce((n,g)=>n+g.directoryRows,0),5);const me=summarize(input,{states:['ME'],zip5s:['00123']});assert.deepEqual(me.denominators,all.denominators);assert.equal(me.filteredDirectoryRows,2);assert.equal(me.states[0].percentOfAllRetainedDirectoryRows,40);assert.equal(me.states[0].percentOfRetainedStateDCDirectoryRows,2/3*100);assert.equal(all.states.find(s=>s.reportedState==='PR').percentOfRetainedStateDCDirectoryRows,null);assert.equal(all.claims.businessCount,null);assert.equal(all.claims.nationalCompletenessPercent,null);});
test('zero matching filter is empty not an unknown or a new denominator',()=>{const s=summarize(fixture([row(0,'PR')]),{states:[]});assert.equal(s.filteredDirectoryRows,0);assert.equal(s.denominators.allRetainedDirectoryRows,1);assert.equal(s.denominators.stateDCRetainedDirectoryRows,0);assert.deepEqual(s.states,[]);assert.equal(summarize(fixture([row(0,'PR')])).states[0].percentOfRetainedStateDCDirectoryRows,null);});
test('membership, duplicate identifiers, coercion and eligibility widening reject',()=>{for(const edit of [rows=>rows.push(row(0)),rows=>rows[0].identifier.value=123456,rows=>rows[0].sourceRecordId='other',rows=>rows[0].provenance.sourceRow=3,rows=>rows[0].reportedAddress.postal.zip5=12345,rows=>rows[0].geocode.latitude=1,rows=>rows[0].claims.exportPolicy='public']){const rows=[row(0)];edit(rows);assert.throws(()=>fixture(rows));}});
test('filters and source arrays reject holes, accessors, inherited iterators, extra properties and invalid states',()=>{const input=fixture([row(0)]);for(const v of [new Array(1),Object.assign(['ME'],{extra:true}),['ME','ME'],['ZZ'],[12]])assert.throws(()=>summarize(input,{states:v}));const a=['ME'];Object.defineProperty(a,'0',{get(){assert.fail('accessor');}});assert.throws(()=>summarize(input,{states:a}));const b=['ME'];Object.setPrototypeOf(b,{[Symbol.iterator]:Array.prototype[Symbol.iterator]});assert.throws(()=>summarize(input,{states:b}));assert.throws(()=>fixture(new Array(1)));assert.throws(()=>summarize(input,{unknown:true}));});
test('preabort refuses native reads and pure aggregation; arbitrary source or verifier injection rejected',async()=>{const c=new AbortController();c.abort();await assert.rejects(load({signal:c.signal}),{name:'AbortError'});await assert.rejects(load({manifestPath:'arbitrary'}));await assert.rejects(load({verify:()=>{}}));assert.throws(()=>summarize(fixture([row(0)]),{signal:c.signal}),{name:'AbortError'});});
test('all-zero ZIP filter is rejected rather than presented as an empty valid ZIP',()=>{assert.throws(()=>summarize(fixture([row(0)]),{zip5s:['00000']}));});
