import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {CMS_SNF_PECOS_HEADERS as H,CMS_SNF_PECOS_OFFLINE_POLICY as P,inspectCmsSnfPecosCsv as inspect,inspectCmsSnfDirectoryLinkRows as directory,linkCmsSnfPecos as link} from './cms-snf-pecos-prerequisite.mjs';
const E='O00000000000001',E2='O00000000000002',E3='O00000000000003',PAC='0000000001',OWNER='0000000002';
const opts={referencePeriodRaw:'May 2026'};
const row=(kind,changes={})=>Object.fromEntries(H[kind].map(h=>[h,changes[h]??({'ENROLLMENT ID':E,'ASSOCIATE ID':PAC,'CCN':'001234','NPI':'0123456789','MULTIPLE NPI FLAG':'Y','PROVIDER TYPE CODE':'00-18','TYPE - OWNER':'O','ASSOCIATE ID - OWNER':OWNER,'ROLE CODE - OWNER':'34','ROLE TEXT - OWNER':'DIRECT','ORGANIZATION NAME - OWNER':'Fixture organization'}[h]??'')]));
const csv=(kind,rows,extra=[])=>Buffer.from([ [...H[kind],...extra],...rows.map(r=>[...H[kind],...extra].map(h=>r[h]??''))].map(r=>r.map(v=>'"'+v.replaceAll('"','""')+'"').join(',')).join('\r\n')+'\r\n');
const snap=(kind,rows,extra)=>inspect(kind,csv(kind,rows,extra),opts);
const dir=rows=>directory(rows??[{sourceRow:2,ccnRaw:'001234'}],{sourceArtifactSha256:'a'.repeat(64),...opts});

test('policy matches compiled offline boundary; no download budget or fabricated native pins',async()=>{assert.deepEqual(JSON.parse(await readFile(new URL('../config/source-policies/cms-snf-pecos.json',import.meta.url))),P);assert.equal(P.approvedDownloadBudgetBytes,0);assert.equal(P.acquisitionReady,false);});
test('exact CCN linkage preserves multiple applications, PAC and NPI strings and source identities',async()=>{
 const e=await snap('enrollments',[row('enrollments'),row('enrollments',{'ENROLLMENT ID':E2}),row('enrollments',{'ENROLLMENT ID':E3,'CCN':'009999'})]),o=await snap('owners',[row('owners'),row('owners',{'ROLE CODE - OWNER':'43'})]),n=await snap('additionalNpis',[row('additionalNpis',{'NPI':'0000000003'}),row('additionalNpis',{'NPI':'0000000004'})]);
 const result=await link(dir([{sourceRow:2,ccnRaw:'001234'},{sourceRow:3,ccnRaw:'1234'},{sourceRow:4,ccnRaw:'999999999999999'}]),e,o,n);
 assert.deepEqual(result.directoryLinks.map(r=>r.enrollmentRecordIds.length),[2,0,0]);assert.equal(result.counts.pecosOnlyEnrollmentRows,1);assert.equal(result.counts.multiEnrollmentDirectoryRows,1);assert.equal(result.organizationOwnerLinks.length,2);assert.equal(e.rows[0].associateId.value,PAC);assert.equal(e.rows[0].npi.value,'0123456789');assert.equal(result.npiCoverage[0].additionalNpiRecordIds.length,2);assert.notEqual(o.rows[0].sourceRecordId,o.rows[1].sourceRecordId);assert.equal(result.acquisitionReady,false);assert.equal(result.nativeSchemaObserved,false);assert.ok(Object.isFrozen(result.directoryLinks));
});
test('individual and unknown owner rows conserved without personal identifiers, names or addresses',async()=>{
 const rows=[row('owners',{'TYPE - OWNER':'I','FIRST NAME - OWNER':'SECRET PERSON','ASSOCIATE ID - OWNER':'1234567890'}),row('owners',{'TYPE - OWNER':'?','ORGANIZATION NAME - OWNER':'PRIVATE UNKNOWN'}),row('owners',{'ADDRESS LINE 1 - OWNER':'SECRET STREET'})];const o=await snap('owners',rows,['FIRST NAME - OWNER','ADDRESS LINE 1 - OWNER']);
 const result=await link(dir(),await snap('enrollments',[row('enrollments')]),o);assert.equal(result.counts.ownerRows,3);assert.equal(result.counts.organizationOwnerRows,1);assert.equal(result.counts.individualOwnerRows,1);assert.equal(result.counts.unknownTypeOwnerRows,1);for(const secret of ['SECRET PERSON','SECRET STREET','PRIVATE UNKNOWN','1234567890'])assert.ok(!JSON.stringify(o).includes(secret));assert.equal(result.npiCoverage[0].status,'companion-not-supplied');
});
test('duplicate enrollment and owner rows retained with ambiguity; orphan/PAC contradictions explicit',async()=>{
 const e=await snap('enrollments',[row('enrollments'),row('enrollments')]),r=row('owners',{'ASSOCIATE ID':'0000000099'}),o=await snap('owners',[r,r,row('owners',{'ENROLLMENT ID':E3})]),n=await snap('additionalNpis',[row('additionalNpis',{'ENROLLMENT ID':E3})]);const result=await link(dir(),e,o,n);assert.equal(result.counts.duplicateEnrollmentIdRows,1);assert.equal(result.counts.duplicateOrganizationRelationRows,1);assert.equal(result.counts.orphanOrganizationRelationRows,1);assert.equal(result.organizationOwnerLinks[0].providerPacStatus,'contradiction');assert.equal(result.organizationOwnerLinks[0].status,'ambiguous-enrollment-id');assert.equal(result.additionalNpiLinks[0].status,'orphan');
});
test('raw dates, flags, percentages and affiliations are not normalized into facts',async()=>{
 const e=await snap('enrollments',[row('enrollments',{'INCORPORATION DATE':'not a date','AFFILIATION ENTITY ID':'0007'})]),o=await snap('owners',[row('owners',{'ASSOCIATION DATE - OWNER':'20269999','PERCENTAGE OWNERSHIP':'140','PARENT COMPANY - OWNER':'Y','OWNED BY ANOTHER ORG OR IND - OWNER':'maybe'})]);const result=await link(dir(),e,o,await snap('additionalNpis',[]));assert.deepEqual(o.rows[0].associationDate,{raw:'20269999',parsed:null,status:'unverified-source-date-format'});assert.equal(o.rows[0].percentage.value,null);assert.equal(o.rows[0].parentCompanyFlag.value,true);assert.equal(o.rows[0].canonicalParent,null);assert.equal(o.rows[0].ownedByAnotherFlag.value,null);assert.equal(e.rows[0].affiliation.type,'pecos-publisher-affiliation-id');assert.equal(result.npiCoverage[0].status,'flag-without-companion-rows');
});
test('period disagreement and empty inputs stay honest; a zero-row CSV is valid',async()=>{const e=await snap('enrollments',[]),o=await inspect('owners',csv('owners',[]),{referencePeriodRaw:'August 2026'});const result=await link(dir([]),e,o);assert.equal(result.dateAlignment,'different-raw-labels');assert.equal(result.counts.ownerRows,0);assert.equal(result.counts.directoryRows,0);assert.equal(result.counts.additionalNpiRows,null);});
test('snapshot forging and hostile directory options/arrays reject',async()=>{const e=await snap('enrollments',[]),o=await snap('owners',[]);await assert.rejects(link(dir(),structuredClone(e),o));assert.throws(()=>dir(new Array(1)));class Rows extends Array{}assert.throws(()=>dir(new Rows()));const rows=[{sourceRow:2,ccnRaw:'001234'}];Object.defineProperty(rows,'0',{get(){throw Error('must not invoke');}});assert.throws(()=>dir(rows),/contract rejected/);assert.throws(()=>dir([{sourceRow:2,ccnRaw:'001234'},{sourceRow:2,ccnRaw:'001234'}]));await assert.rejects(inspect('owners',csv('owners',[]),{...opts,acquisitionReady:true}));});
test('bounded UTF-8/CSV/schema conformance rejects invalid bytes, controls, headers and over-limit rows',async()=>{await assert.rejects(inspect('owners',Buffer.from([255]),opts));await assert.rejects(inspect('owners',Buffer.alloc(8388609),opts));await assert.rejects(inspect('owners',Buffer.from('ENROLLMENT ID,ENROLLMENT ID\n'),opts));await assert.rejects(snap('enrollments',[row('enrollments',{'CCN':'00\t123'})]));await assert.rejects(snap('enrollments',[row('enrollments',{'ENROLLMENT ID':'bad'})]));await assert.rejects(snap('additionalNpis',Array.from({length:10001},()=>row('additionalNpis'))));});
test('actual short timer interrupts decoding; preabort and mid-link cancellation honored',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(inspect('owners',csv('owners',[]),{...opts,signal:controller.signal}));const buffer=csv('additionalNpis',Array.from({length:10000},()=>row('additionalNpis')));await assert.rejects(inspect('additionalNpis',buffer,{...opts,signal:AbortSignal.timeout(1)}));const e=await snap('enrollments',[row('enrollments')]),o=await snap('owners',[]),d=dir(Array.from({length:20000},(_,i)=>({sourceRow:i+2,ccnRaw:'001234'})));await assert.rejects(link(d,e,o,null,{signal:AbortSignal.timeout(1)}));});
test('raw change changes source identity and native-looking metadata cannot promote a fixture',async()=>{const a=await snap('enrollments',[row('enrollments')]),b=await snap('enrollments',[row('enrollments',{'NPI':'0000000000'})]);assert.notEqual(a.sourceArtifactSha256,b.sourceArtifactSha256);assert.notEqual(a.rows[0].sourceRecordId,b.rows[0].sourceRecordId);assert.equal(b.sourceTransportVerified,false);const result=await link(dir(),b,await snap('owners',[]));assert.equal(result.uniqueBusinessCount,null);assert.equal(result.publicExportAuthorized,false);});
test('duplicate IDs expand links up to the explicit reference cap, never silently truncate',async()=>{const e=await snap('enrollments',Array.from({length:100},()=>row('enrollments'))),o=await snap('owners',[]),d=dir([]),n=await snap('additionalNpis',Array.from({length:1000},()=>row('additionalNpis')));const result=await link(d,e,o,n);assert.equal(result.counts.linkReferences,100000);assert.equal(result.additionalNpiLinks.length,1000);assert.equal(result.additionalNpiLinks[0].enrollmentRecordIds.length,100);assert.equal(result.counts.duplicateEnrollmentIdRows,99);const oversized=await snap('additionalNpis',Array.from({length:1001},()=>row('additionalNpis')));await assert.rejects(link(d,e,o,oversized),/contract rejected/);});
