import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {mkdtemp,mkdir,rm,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {APP_ROOT} from './paths.mjs';
import {cmsNursingHomeSharedViewPolicy} from './cms-nursing-home-coverage-extension.mjs';
import {cmsNursingHomeCoverageIndex as index,applyCmsNursingHomeCoverage as apply,verifyCmsNursingHomeCoverageExtension as verify,CMS_NURSING_HOME_COVERAGE_PATH as FILE,CMS_NURSING_HOME_COVERAGE_TYPE as TYPE} from './cms-nursing-home-coverage-extension.mjs';
const FIELD='cms_nursing_home_directory_reporting';
test('CMS preserves pre-existing shared-view policy for childcare and credentials',()=>{assert.equal(cmsNursingHomeSharedViewPolicy({}),'local-review-only');assert.equal(cmsNursingHomeSharedViewPolicy({retained_childcare_reporting:{}}),'internal');assert.equal(cmsNursingHomeSharedViewPolicy({mn_construction_credential_reporting:{}}),'local-review-only');assert.equal(cmsNursingHomeSharedViewPolicy({retained_childcare_reporting:{},mn_construction_credential_reporting:{}}),'local-review-only');});
const row=(id,state,zip)=>({identifier:{type:'cms-certification-number',value:String(id).padStart(6,'0')},sourceRecordId:`synthetic-${id}`,reportedAddress:{state,postal:{zip5:zip,zip4:'0001'}},sourceGeocode:{facilityPointEligible:false}});
const input=()=>({records:[row(1,'AL','00123'),row(2,'DC','20001'),row(3,'PR','00901'),row(4,null,null),row(5,'ZZ','99999'),row(6,'AL',null)],source:{},selection:{},summary:{}});
const views=()=>({national:['registry-union','50-states-and-dc','all-census-us-areas'].map(scope=>({scope})),states:[{postal_abbreviation:'AL'},{postal_abbreviation:'DC'},{postal_abbreviation:'AK'}],counties:[{county_geoid:'01001'}],zips:[{zip_code:'00123'},{zip_code:'00001'}]});
test('source stateDC territory unknown and nullZIP buckets conserve entire input with fixed denominators',()=>{const result=index(input().records);assert.equal(result.all.directory_rows,6);assert.equal(result.stateDC.directory_rows,3);assert.equal(result.territories.directory_rows,1);assert.equal(result.unknown.directory_rows,2);assert.equal(result.all.rows_without_reported_zip5,2);assert.equal(result.stateZips.reduce((n,r)=>n+r.directory_rows,0),6);assert.equal(result.states.get('PR').percent_of_state_dc_retained_directory_rows,null);assert.equal(result.states.get('AL').percent_of_all_retained_directory_rows,2/6*100);assert.equal(result.states.get('AL').percent_of_state_dc_retained_directory_rows,2/3*100);assert.equal(result.all.business_count,null);assert.equal(result.all.zip4_aggregated,false);});
test('existing view gaps remain explicit and full stateZIP artifact preserves rows absent from old views',()=>{const i=input(),v=views(),declaration=apply(i,v);assert.equal(declaration.counts.rows_without_existing_state_view,3);assert.equal(declaration.counts.rows_without_existing_zip_view,5);assert.equal(declaration.counts.missing_reported_zip5_rows,2);assert.equal(v.national[0][FIELD].directory_rows,6);assert.equal(v.national[1][FIELD].directory_rows,3);assert.equal(v.national[2][FIELD].directory_rows,3);assert.equal(v.states[2][FIELD].directory_rows,0);assert.equal(v.zips[1][FIELD].directory_rows,0);assert.equal(v.counties[0][FIELD].directory_rows,null);assert.equal(v.counties[0][FIELD].geographic_assignment_performed,false);assert.deepEqual(v.states[0][FIELD].denominators,v.national[0][FIELD].denominators);assert.equal(declaration.state_zip_artifact.record_count,6);});
test('duplicate IDs, source IDs, sparse rows and malformed ZIP values reject',()=>{for(const mutate of [r=>r.push(r[0]),r=>r[1].sourceRecordId=r[0].sourceRecordId,r=>r[0].reportedAddress.postal.zip5='00000',r=>r[0].reportedAddress.postal.zip5=12345]){const rows=input().records;mutate(rows);assert.throws(()=>index(rows));}assert.throws(()=>index(new Array(1)));});
test('duplicate or missing scope views reject rather than double count',()=>{for(const mutate of [v=>v.states.push(v.states[0]),v=>v.zips.push(v.zips[0]),v=>v.counties.push(v.counties[0]),v=>v.national.pop()]){const v=views();mutate(v);assert.throws(()=>apply(input(),v));}});
test('historical absence and preabort work but orphan aggregate type or physical file rejects',async t=>{const base=path.join(APP_ROOT,'data/tmp');await mkdir(base,{recursive:true});const directory=await mkdtemp(path.join(base,'cms-coverage-'));t.after(()=>rm(directory,{recursive:true,force:true}));assert.equal(await verify({artifacts:[]},directory),null);await assert.rejects(verify({artifacts:[{path:FILE,artifact_type:TYPE}]},directory));await mkdir(path.dirname(path.join(directory,FILE)),{recursive:true});await writeFile(path.join(directory,FILE),'synthetic');await assert.rejects(verify({artifacts:[]},directory));await assert.rejects(verify({},directory,{signal:AbortSignal.abort()}),{name:'AbortError'});});

test('eligible facility point assertions reject instead of authorizing geography',()=>{const r=input().records;r[0].sourceGeocode.facilityPointEligible=true;assert.throws(()=>index(r));});
test('native verifier accepts only a closed cancellation option',async()=>{let invoked=false;const accessor={};Object.defineProperty(accessor,'signal',{get(){invoked=true;return undefined;}});for(const options of [{hook:()=>{}},{source:'other'},{signal:{}},accessor,null])await assert.rejects(verify({},'unused',options));assert.equal(invoked,false);});

test('retained-copy native source coverage fixture conserves cohort and detects final-output mutation',{skip:process.env.DATAHUB_TEST_NURSING_COVERAGE!=='1',timeout:180000},async t=>{
 const native=await import('./cms-nursing-home-registry-input.mjs'),extension=await import('./cms-nursing-home-coverage-extension.mjs'),signal=AbortSignal.timeout(175000),originalFetch=globalThis.fetch;globalThis.fetch=()=>assert.fail('No network');t.after(()=>{globalThis.fetch=originalFetch;});
 const base=path.join(APP_ROOT,'data/tmp');await mkdir(base,{recursive:true});const root=await mkdtemp(path.join(base,'nursing-coverage-native-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const source=await native.loadCmsNursingHomeRegistryInput(path.join(APP_ROOT,'config/cms-nursing-home-retained-selection.json'),{signal}),registryDir=path.join(root,'registry'),output=path.join(root,'coverage');await mkdir(output,{recursive:true});
 const sha=v=>createHash('sha256').update(v).digest('hex'),json=v=>JSON.stringify(v)+'\n',lines=rows=>rows.map(json).join('');
 async function artifact(directory,name,raw,type,count,policy){const file=path.join(directory,name);await mkdir(path.dirname(file),{recursive:true});await writeFile(file,raw);return{path:name,artifact_type:type,bytes:Buffer.byteLength(raw),sha256:sha(raw),record_count:count,export_policy:policy};}
 const registryArtifact=await artifact(registryDir,native.CMS_NURSING_HOME_REGISTRY_PATH,lines(source.records),native.CMS_NURSING_HOME_REGISTRY_ARTIFACT,source.records.length,'local-review-only'),registry={dataset_id:'national-business-registry',release_id:'synthetic-registry-with-native-retained-source',publisher:{id:'national-business-registry',version:'2.12.0'},created_at:new Date().toISOString(),export_policy:'local-review-only',dependencies:[native.cmsNursingHomeRegistryDependency(source)],coverage:{cms_nursing_home_directory_rows:source.records.length},artifacts:[registryArtifact],[FIELD]:native.cmsNursingHomeRegistryDeclaration(source)};
 const registryRaw=json(registry),registryPath=path.join(registryDir,'manifest.json');await writeFile(registryPath,registryRaw);const v=views(),declaration={...apply(source,v),registry_manifest_path:path.relative(APP_ROOT,registryPath).replaceAll('\\','/'),registry_manifest_sha256:sha(registryRaw)},artifacts=[];
 for(const [key,kind]of[['national','national'],['states','state'],['counties','county'],['zips','zip']])artifacts.push(await artifact(output,`views/${key}.jsonl`,lines(v[key]),`${kind}-coverage-view-jsonl`,v[key].length,'local-review-only'));
 const grouped=index(source.records);artifacts.push(await artifact(output,FILE,lines(grouped.stateZips),TYPE,grouped.stateZips.length,'local-review-only'));artifacts.push(await artifact(output,'evidence/registry-manifest.json',registryRaw,'retained-registry-manifest-json',1,'internal'));
 const manifest={created_at:new Date().toISOString(),dependencies:[{dataset_id:'national-business-registry',release_id:registry.release_id,manifest_sha256:sha(registryRaw)}],artifacts,[FIELD]:declaration};await verify(manifest,output,{signal});
 assert.equal(declaration.counts.all_retained_directory_rows,14690);assert.equal(declaration.counts.state_dc_retained_directory_rows,14680);assert.equal(declaration.counts.territory_retained_directory_rows,10);assert.equal(grouped.stateZips.reduce((n,r)=>n+r.directory_rows,0),14690);assert.ok(v.counties.every(r=>r[FIELD].directory_rows===null));
 for(const name of ['evidence/registry-manifest.json',FILE]){const file=path.join(output,name),raw=await readFile(file);let reached=false;try{await assert.rejects(extension.verifyCmsNursingHomeCoverageWithTestHook(manifest,output,async stage=>{assert.equal(stage,'before-final-rechecks');reached=true;await writeFile(file,'{}\n');}));assert.equal(reached,true);}finally{await writeFile(file,raw);}}
 const groupedPath=path.join(output,FILE),raw=await readFile(groupedPath),changed=structuredClone(grouped.stateZips);changed[0].directory_rows++;const body=lines(changed),forged=structuredClone(manifest),a=forged.artifacts.find(a=>a.path===FILE);a.bytes=Buffer.byteLength(body);a.sha256=sha(body);try{await writeFile(groupedPath,body);await assert.rejects(verify(forged,output,{signal}));}finally{await writeFile(groupedPath,raw);}
 await verify(manifest,output,{signal});
});
