import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {cmsNursingHomeReportingFixture as fixture,summarizeCmsNursingHomeReporting as summarize,validateCmsNursingHomeRetainedSelection as validate,loadCmsNursingHomeReportingInput as load} from './cms-nursing-home-reporting-input.mjs';
const hash='a'.repeat(64);
function row(i,state='ME',zip5='00123',zip4=null){return {sourceRecordId:`cms-pdc:4pq5-n9py:${hash}:row:${i+2}`,identifier:{type:'cms-certification-number',raw:`A${String(i).padStart(5,'0')}`,value:`A${String(i).padStart(5,'0')}`},facilityName:'Synthetic facility',reportedAddress:{street:'Synthetic street',textQuality:{status:'no-controls-observed',controlCodePoints:[],normalizationPerformed:false},state,postal:{raw:zip5===null?null:zip5+(zip4===null?'':`-${zip4}`),zip5,zip4,status:zip5===null?'missing':'format-only-usps-unverified'},addressVerified:false},npi:null,parentCompany:null,currentOperatingStatus:null,sourceGeocode:{latitudeRaw:null,longitudeRaw:null,footnoteRaw:null,status:'missing-coordinates',facilityPointEligible:false,independentlyVerified:false,coordinateReferenceSystem:null},publisherStatusAssertion:{value:'currently-active',basis:'publisher-dataset-description',sourceModified:'2026-08-01',sourceReleased:'2026-08-26'},provenance:{datasetId:'4pq5-n9py',csvSha256:hash,sourceRow:i+2,policyProfile:'cms-nursing-home-acquisition@1.0.0',sourceProjectionVersion:'cms-nursing-home-prerequisite@1.0.1',sourceModified:'2026-08-01',sourceReleased:'2026-08-26'},claims:{recordUnit:'publisher-nursing-home-directory-row',uniqueBusinessIdentityVerified:false,physicalCampusIdentityVerified:false,currentOperationsVerified:false,exportPolicy:'local-review-only'}};}
test('closed exact native selection rejects future, fixture, path and hash overrides',async()=>{const p=JSON.parse(await readFile(new URL('../config/cms-nursing-home-retained-selection.json',import.meta.url),'utf8'));assert.deepEqual(validate(p),p);for(const changed of [{...p,extra:true},{...p,manifestSha256:'b'.repeat(64)},{...p,manifestPath:'data/tmp/cms-nursing-home-acquisition/fixture/manifest.json'},{...p,schemaVersion:'future'}])assert.throws(()=>validate(changed));const accessor={...p};Object.defineProperty(accessor,'manifestPath',{get(){assert.fail('must not invoke accessor');},enumerable:true});assert.throws(()=>validate(accessor));});
test('synthetic snapshot preserves source IDs and separate postal values but never claims native proof',()=>{const r=row(0,'ME','00123','0004'),input=fixture([r]);assert.equal(input.nativeSourceVerified,false);assert.equal(input.rows[0].identifier.value,'A00000');assert.equal(input.rows[0].reportedAddress.postal.zip4,'0004');r.identifier.value='CHANGED';assert.equal(input.rows[0].identifier.value,'A00000');assert.ok(Object.isFrozen(input.rows[0].provenance));assert.throws(()=>summarize({...input}));});
test('all-source and stateDC denominators remain fixed through state and ZIP filters with territories and unknowns conserved',()=>{const input=fixture([row(0),row(1),row(2,'DC','20001'),row(3,'PR','00901'),row(4,null,null)]),all=summarize(input);assert.deepEqual(all.denominators,{allRetainedDirectoryRows:5,stateDCRetainedDirectoryRows:3,territoryRetainedDirectoryRows:1,unknownReportedStateRows:1});assert.equal(all.filteredRowsMissingZip5,1);assert.equal(all.stateZips.reduce((n,g)=>n+g.directoryRows,0),5);const me=summarize(input,{states:['ME'],zip5s:['00123']});assert.deepEqual(me.denominators,all.denominators);assert.equal(me.filteredDirectoryRows,2);assert.equal(me.states[0].percentOfAllRetainedDirectoryRows,40);assert.equal(me.states[0].percentOfRetainedStateDCDirectoryRows,2/3*100);assert.equal(all.states.find(s=>s.reportedState==='PR').percentOfRetainedStateDCDirectoryRows,null);assert.equal(all.claims.businessCount,null);assert.equal(all.claims.nationalCompletenessPercent,null);});
test('zero matching filter is empty not an unknown or a new denominator',()=>{const s=summarize(fixture([row(0,'PR')]),{states:[]});assert.equal(s.filteredDirectoryRows,0);assert.equal(s.denominators.allRetainedDirectoryRows,1);assert.equal(s.denominators.stateDCRetainedDirectoryRows,0);assert.deepEqual(s.states,[]);assert.equal(summarize(fixture([row(0,'PR')])).states[0].percentOfRetainedStateDCDirectoryRows,null);});
test('membership, duplicate identifiers, coercion and eligibility widening reject',()=>{for(const edit of [rows=>rows.push(row(0)),rows=>rows[0].identifier.value=123456,rows=>rows[0].sourceRecordId='other',rows=>rows[0].provenance.sourceRow=3,rows=>rows[0].reportedAddress.postal.zip5=12345,rows=>rows[0].sourceGeocode.facilityPointEligible=true,rows=>rows[0].claims.exportPolicy='public']){const rows=[row(0)];edit(rows);assert.throws(()=>fixture(rows));}});
test('filters and source arrays reject holes, accessors, inherited iterators, extra properties and invalid states',()=>{const input=fixture([row(0)]);for(const v of [new Array(1),Object.assign(['ME'],{extra:true}),['ME','ME'],['ZZ'],[12]])assert.throws(()=>summarize(input,{states:v}));const a=['ME'];Object.defineProperty(a,'0',{get(){assert.fail('accessor');}});assert.throws(()=>summarize(input,{states:a}));const b=['ME'];Object.setPrototypeOf(b,{[Symbol.iterator]:Array.prototype[Symbol.iterator]});assert.throws(()=>summarize(input,{states:b}));assert.throws(()=>fixture(new Array(1)));assert.throws(()=>summarize(input,{unknown:true}));});
test('preabort refuses native reads and pure aggregation; arbitrary source or verifier injection rejected',async()=>{const c=new AbortController();c.abort();await assert.rejects(load({signal:c.signal}),{name:'AbortError'});await assert.rejects(load({manifestPath:'arbitrary'}));await assert.rejects(load({verify:()=>{}}));assert.throws(()=>summarize(fixture([row(0)]),{signal:c.signal}),{name:'AbortError'});});
test('all-zero ZIP filter is rejected rather than presented as an empty valid ZIP',()=>{assert.throws(()=>summarize(fixture([row(0)]),{zip5s:['00000']}));});

test('source TAB quality, dated-active assertion and raw coordinate quality survive immutable snapshot',()=>{const r=row(0);r.reportedAddress.street='1\tStreet';r.reportedAddress.textQuality={status:'source-tab-preserved',controlCodePoints:['U+0009'],normalizationPerformed:false};Object.assign(r.sourceGeocode,{latitudeRaw:'30',longitudeRaw:'-85',footnoteRaw:'22',status:'publisher-zip-based-estimate'});const input=fixture([r]);assert.equal(input.rows[0].reportedAddress.street,'1\tStreet');assert.equal(input.rows[0].sourceGeocode.footnoteRaw,'22');assert.equal(input.rows[0].publisherStatusAssertion.sourceModified,'2026-08-01');assert.equal(input.rows[0].currentOperatingStatus,null);const summary=summarize(input);assert.equal(summary.filteredSourceTabRows,1);assert.deepEqual(summary.filteredCoordinateQuality,{'publisher-zip-based-estimate':1});assert.equal(summary.eligibleFacilityPoints,0);const changed=structuredClone(r);changed.reportedAddress.textQuality.normalizationPerformed=true;assert.throws(()=>fixture([changed]));});

test('same ZIP in different states stays distinct; filtered quality and fixed denominators conserve independently',()=>{const input=fixture([row(0,'ME','00123'),row(1,'VT','00123'),row(2,'GU',null)]),all=summarize(input),me=summarize(input,{states:['ME'],zip5s:['00123']});assert.equal(all.stateZips.length,3);assert.equal(me.filteredDirectoryRows,1);assert.deepEqual(me.denominators,all.denominators);assert.equal(Object.values(me.filteredCoordinateQuality).reduce((n,v)=>n+v,0),1);assert.equal(me.states[0].percentOfAllRetainedDirectoryRows,1/3*100);});
