import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {CMS_NURSING_HOME_SELECTED_HEADERS as HEADERS,CMS_NURSING_HOME_PREREQUISITE_CONTRACT as CONTRACT,inspectCmsNursingHomeMetadata as metadata,inspectCmsNursingHomeCsvForConformance as inspect} from './cms-nursing-home-prerequisite.mjs';
const opts={observedAt:'2026-09-12T16:00:00.000Z'};
function source(){return {identifier:'4pq5-n9py',title:'Provider Information',accessLevel:'public',publisher:{name:'Centers for Medicare & Medicaid Services (CMS)'},landingPage:'https://data.cms.gov/provider-data/dataset/4pq5-n9py',description:'General information on currently active nursing homes, including number of certified beds, quality measure scores, staffing and other information used in the Five-Star Rating System.\nData are presented as one row per nursing home.',issued:'2026-02-01',modified:'2026-08-01',released:'2026-08-26',distribution:[{mediaType:'text/csv',downloadURL:'https://data.cms.gov/provider-data/sites/default/files/resources/328596835e6db31b2564cd733c3795f4_1786724150/NH_ProviderInfo_Aug2026.csv',describedBy:'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/nursing_home/NH_Data_Dictionary.pdf',describedByType:'application/pdf'}]};}
const meta=()=>metadata(Buffer.from(JSON.stringify(source())),opts);
function row(changes={}){return {'CMS Certification Number (CCN)':'00123A','Provider Name':'Synthetic, "Home"','Provider Address':'123 Fixture Street','City/Town':'Fixture','State':'PR','ZIP Code':'00901-0004','County/Parish':'Source label','Ownership Type':'Future category','Provider Type':'Source type','Legal Business Name':'Synthetic legal name','Latitude':'18.2','Longitude':'-66.1','Geocoding Footnote':'','Processing Date':'08/01/2026',...changes};}
const quote=v=>'"'+v.replaceAll('"','""')+'"';
function csv(rows=[row()],headers=HEADERS){return Buffer.from('\ufeff'+headers.map(quote).join(',')+'\r\n'+rows.map(r=>headers.map(k=>quote(r[k]??'')).join(',')).join('\r\n')+'\r\n');}
test('fixed metadata, dates and status are immutable conformance not native evidence',()=>{const raw=Buffer.from(JSON.stringify(source())),m=metadata(raw,opts);assert.equal(m.metadataSha256,createHash('sha256').update(raw).digest('hex'));assert.equal(m.released,'2026-08-26');assert.equal(m.publisherStatusAssertion.value,'currently-active');assert.equal(m.publisherStatusAssertion.sourceModified,'2026-08-01');assert.equal(m.transportAuthenticityVerified,false);assert.equal(m.acquisitionReady,false);assert.throws(()=>{m.publisherStatusAssertion.value='verified';});});
test('source, access, description, date, distribution and malformed metadata fail closed',()=>{for(const edit of [m=>m.identifier='xubh-q36u',m=>m.title='Other',m=>m.publisher.name='Other',m=>m.accessLevel='restricted',m=>m.description='Former providers',m=>m.modified='2026-02-30',m=>m.issued='2027-01-01',m=>m.released='2027-01-01',m=>m.distribution.push(m.distribution[0]),m=>m.distribution[0].downloadURL+='?x=y',m=>m.distribution[0].downloadURL=m.distribution[0].downloadURL.replace('data.cms.gov','elsewhere.example'),m=>m.distribution[0].describedBy='other']){const s=source();edit(s);assert.throws(()=>metadata(Buffer.from(JSON.stringify(s)),opts));}assert.throws(()=>metadata(Buffer.from([255]),opts));assert.throws(()=>metadata(Buffer.alloc(1048577),opts));});
test('typed CCN, original address, source status and separate ZIP strings conserved',async()=>{const raw=csv(),r=await inspect(raw,meta()),p=r.rows[0];assert.deepEqual(p.identifier,{type:'cms-certification-number',raw:'00123A',value:'00123A'});assert.equal(p.reportedAddress.postal.zip5,'00901');assert.equal(p.reportedAddress.postal.zip4,'0004');assert.equal(p.facilityName,'Synthetic, "Home"');assert.equal(p.publisherStatusAssertion.value,'currently-active');assert.equal(p.currentOperatingStatus,null);assert.equal(p.npi,null);assert.equal(p.processingDateSource,'08/01/2026');assert.equal(p.provenance.sourceRow,2);assert.equal(r.sourceRows,r.projectedRows);assert.equal(r.csvSha256,createHash('sha256').update(raw).digest('hex'));assert.equal(r.acquisitionReady,false);assert.equal(r.nativeAcquisitionVerified,false);assert.ok(Object.isFrozen(p.sourceGeocode));});
test('all coordinate conditions preserve raw evidence, never grant facility-point eligibility',async()=>{const inputs=[{}, {'Geocoding Footnote':'22'},{'Geocoding Footnote':'999'},{Latitude:'',Longitude:'','Geocoding Footnote':'22'},{Latitude:'',Longitude:'1'},{Latitude:'91'},{Longitude:'NaN'},{Latitude:'Infinity'},{Latitude:'0',Longitude:'0'}],r=await inspect(csv(inputs.map((v,i)=>row({'CMS Certification Number (CCN)':String(i).padStart(6,'0'),...v}))),meta());assert.deepEqual(r.rows.map(p=>p.sourceGeocode.status),['publisher-estimate-quality-unspecified','publisher-zip-based-estimate','unresolved-footnote','missing-coordinates','invalid-coordinate-pair','invalid-coordinate-pair','invalid-coordinate-pair','invalid-coordinate-pair','publisher-estimate-quality-unspecified']);assert.equal(r.rows[3].sourceGeocode.footnoteStatus,'zip-based-fallback');assert.equal(r.rows[6].sourceGeocode.longitudeRaw,'NaN');assert.equal(r.rows[6].sourceGeocode.latitude,null);assert.equal(r.rows[8].sourceGeocode.latitude,0);assert.equal(Object.values(r.coordinateStatuses).reduce((a,b)=>a+b,0),inputs.length);for(const p of r.rows){assert.equal(p.sourceGeocode.facilityPointEligible,false);assert.equal(p.sourceGeocode.coordinateReferenceSystem,null);}});
test('missing/unknown state and postal records remain in cohort',async()=>{const r=await inspect(csv([row({'State':'','ZIP Code':''}),row({'CMS Certification Number (CCN)':'000002','State':'ZZ','ZIP Code':'bad'}),row({'CMS Certification Number (CCN)':'000003','ZIP Code':'005010012'})]),meta());assert.equal(r.sourceRows,3);assert.equal(r.rows[0].reportedAddress.state,null);assert.equal(r.rows[1].reportedAddress.postal.status,'unresolved-source-format');assert.equal(r.rows[1].reportedAddress.state,'ZZ');assert.equal(r.rows[2].reportedAddress.postal.zip4,'0012');});
test('selected exact headers reordered with unknown fields only counted, never disclosed',async()=>{const r=await inspect(csv([row({'Telephone Number':'PRIVATE CONTACT','Unknown header':'PRIVATE VALUE'})],['Telephone Number','Unknown header',...HEADERS.toReversed()]),meta());assert.equal(r.unselectedHeaderCount,2);assert.doesNotMatch(JSON.stringify(r),/PRIVATE|Telephone Number|Unknown header/);assert.equal(r.fullHeaderOrderVerified,false);for(const headers of [HEADERS.slice(1),[...HEADERS,HEADERS[0]],['Wrong CCN',...HEADERS.slice(1)]])await assert.rejects(inspect(csv([row()],headers),meta()));});
test('duplicates, invalid IDs, widths, controls, blanks and empty files reject without source diagnostics',async()=>{for(const rows of [[row(),row()],[row({'CMS Certification Number (CCN)':'12345'})],[row({'Provider Name':''})],[row({'Provider Address':'SECRET\nCONTROL'})]])await assert.rejects(inspect(csv(rows),meta()),e=>{assert.doesNotMatch(e.message,/SECRET/);return true;});for(const raw of [Buffer.from('"unterminated'),Buffer.from(HEADERS.join(',')+'\n'),Buffer.from(HEADERS.join(',')+'\nshort,row\n'),Buffer.from([255,10])])await assert.rejects(inspect(raw,meta()));});
test('byte, record, column and row bounds enforced',async()=>{const m=meta();await assert.rejects(inspect(Buffer.alloc(CONTRACT.csv.maxBytes+1),m));await assert.rejects(inspect(csv([row({'Provider Address':'x'.repeat(66000)})]),m));await assert.rejects(inspect(csv([row()],[...HEADERS,...Array.from({length:115},(_,i)=>`extra${i}`)]),m));await assert.rejects(inspect(csv(Array.from({length:25001},(_,i)=>row({'CMS Certification Number (CCN)':String(i).padStart(6,'0')}))),m));});
test('preabort and cooperative decoding cancellation yield no partial success',async()=>{const c=new AbortController();c.abort();assert.throws(()=>metadata(Buffer.from(JSON.stringify(source())),{...opts,signal:c.signal}),{name:'AbortError'});await assert.rejects(inspect(csv(),meta(),{signal:c.signal}),{name:'AbortError'});const late=new AbortController();setImmediate(()=>late.abort());await assert.rejects(inspect(csv(Array.from({length:256},(_,i)=>row({'CMS Certification Number (CCN)':String(i).padStart(6,'0')}))),meta(),{signal:late.signal}),{name:'AbortError'});});
test('forged snapshots and accessor/unknown execution controls reject; policy stays offline',async()=>{await assert.rejects(inspect(csv(),{...meta()}));await assert.rejects(inspect(csv(),meta(),{url:'other'}));const accessor={};Object.defineProperty(accessor,'signal',{get(){assert.fail('must not run accessor');}});await assert.rejects(inspect(csv(),meta(),accessor));const policy=JSON.parse(await readFile(new URL('../config/source-policies/cms-nursing-home-provider-information.json',import.meta.url),'utf8'));assert.equal(`${policy.policy_id}@${policy.version}`,CONTRACT.policyProfile);assert.equal(policy.acquisition_authorized,false);assert.equal(policy.public_export_authorized,false);assert.equal(policy.outbound_address_submission_authorized,false);});
