import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {CMS_SNF_PECOS_AUGUST_SELECTION as S,CMS_SNF_PECOS_CURRENT_DOCUMENTS as D,CMS_SNF_PECOS_PLAN_POLICY as P,inspectCmsSnfPecosMetadataPlan as inspect} from './cms-snf-pecos-metadata-prerequisite.mjs';
const endpoint=v=>'https://data.cms.gov/data-api/v1/dataset-resources/'+v;
const entry=p=>({name:p.name,fileSize:p.bytes,downloadURL:p.url});
function fixture(){const records=kind=>{const p=S[kind],common={temporal:'2026-08-01/2026-08-31',modified:'2026-08-17',title:p.title+' : 2026-08-01',resourcesAPI:endpoint(p.version)};return {title:p.title,identifier:'https://data.cms.gov/data-api/v1/dataset/'+p.typeId+'/data-viewer',accessLevel:'public',accessRights:'Open',license:P.sourceLicense,publisher:{name:'Centers for Medicare & Medicaid Services'},describedBy:D[kind].url,references:[D.guidance.url],distribution:[{...common,format:'CSV',mediaType:'text/csv',downloadURL:p.url},{...common,format:'API',accessURL:'https://data.cms.gov/data-api/v1/dataset/'+p.version+'/data'}]};};const resource=(kind,extra)=>({meta:{success:true},links:{self:{href:endpoint(S[kind].version)}},data:[entry(S[kind]),entry(D[kind]),entry(D.guidance),...extra]});return {catalog:{dataset:[records('enrollments'),records('owners')]},enrollmentResources:resource('enrollments',[entry(S.additionalNpis)]),ownerResources:resource('owners',[{name:'Unselected ADP',fileSize:128182,downloadURL:'https://data.cms.gov/sites/default/files/2026-07/SNF_ADP_Supplemental_Data_Dictionary.pdf'}])};}
const bytes=f=>Object.fromEntries(Object.entries(f).map(([k,v])=>[k,Buffer.from(JSON.stringify(v))]));
test('policy is exactly proposed/unapproved, fixed monthly metadata resolves without issuing transport',async()=>{assert.deepEqual(JSON.parse(await readFile(new URL('../config/source-policies/cms-snf-pecos-august-plan.json',import.meta.url))),P);const r=await inspect(bytes(fixture()));assert.equal(r.declaredDataBytes,57529084);assert.equal(r.unselectedResourceCount,1);assert.equal(r.currentDocumentsReplayed,false);assert.equal(r.approvedDownloadBudgetBytes,0);assert.equal(r.acquisitionReady,false);assert.ok(r.data.every(d=>!d.bodyObserved&&d.bodySha256===null));assert.ok(Object.isFrozen(r.selection));});
test('missing/duplicate dataset or companion rejects',async()=>{for(const mutate of [f=>f.catalog.dataset.pop(),f=>f.catalog.dataset.push(f.catalog.dataset[0]),f=>f.enrollmentResources.data.pop(),f=>f.enrollmentResources.data.push(f.enrollmentResources.data[3])]){const f=fixture();mutate(f);await assert.rejects(inspect(bytes(f)));}});
test('catalog identifiers bind both dataset types without following data-viewer',async()=>{for(const index of [0,1]){const f=fixture();f.catalog.dataset[index].identifier='https://data.cms.gov/data-api/v1/dataset/'+S[index===0?'owners':'enrollments'].typeId+'/data-viewer';await assert.rejects(inspect(bytes(f)));}const f=fixture();delete f.catalog.dataset[0].identifier;await assert.rejects(inspect(bytes(f)));});
test('fixed month, version, latest aliases, and resource URL binding reject disagreement',async()=>{for(const mutate of [f=>f.catalog.dataset[0].distribution[0].temporal='2026-07-01/2026-07-31',f=>f.catalog.dataset[0].distribution[1].description='latest',f=>f.catalog.dataset[0].distribution[0].resourcesAPI=endpoint(S.enrollments.typeId),f=>f.enrollmentResources.links.self.href=endpoint(S.owners.version),f=>f.ownerResources.data[0].downloadURL=S.enrollments.url]){const f=fixture();mutate(f);await assert.rejects(inspect(bytes(f)));}});
test('resource host/credentials/query/size and dictionary drift fail before plan',async()=>{for(const value of ['https://example.com/file.pdf','https://user@data.cms.gov/file.pdf','https://data.cms.gov/file.pdf?x=1']){const f=fixture();f.ownerResources.data[3].downloadURL=value;await assert.rejects(inspect(bytes(f)));}for(const size of [0,-1,Infinity,268435457]){const f=fixture();f.enrollmentResources.data[3].fileSize=size;await assert.rejects(inspect(bytes(f)));}const f=fixture();f.ownerResources.data[1].fileSize++;await assert.rejects(inspect(bytes(f)));});
test('pinned document presence requires actual bytes, no fabricated document replay',async()=>{const f=bytes(fixture());f.documents={enrollments:Buffer.from('%PDF-fake'),owners:Buffer.from('%PDF-fake'),guidance:Buffer.from('%PDF-fake')};await assert.rejects(inspect(f));});
test('metadata hashes bind all supplied bytes; malformed/oversize/cancel/options reject',async()=>{const f=bytes(fixture()),a=await inspect(f);f.catalog=Buffer.concat([f.catalog,Buffer.from(' ')]);const b=await inspect(f);assert.notEqual(a.metadataPins.catalog.sha256,b.metadataPins.catalog.sha256);await assert.rejects(inspect({...f,catalog:Buffer.from([255])}));await assert.rejects(inspect({...f,catalog:Buffer.alloc(8388609)}));await assert.rejects(inspect(f,{native:true}));const c=new AbortController();c.abort();await assert.rejects(inspect(f,{signal:c.signal}));});
test('standalone CLI rejects source/URL overrides before retained reads',()=>{const r=spawnSync(process.execPath,['scripts/plan-cms-snf-pecos.mjs','--url=https://example.com'],{cwd:new URL('..',import.meta.url),encoding:'utf8',timeout:5000});assert.equal(r.status,1);assert.equal(r.stdout,'');assert.match(r.stderr,/no source requests/);});
