import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {mkdir,readdir,readFile,writeFile,rm,unlink,rmdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {APP_ROOT} from './paths.mjs';
import {acquireCmsHospitals,acquireCmsHospitalsWithTestTransport as run,verifyCmsHospitalAcquisitionWithTestInput as verify,verifyCmsHospitalAcquisition as nativeVerify} from './cms-hospital-acquisition.mjs';
import {CMS_HOSPITAL_SELECTED_HEADERS} from './cms-hospital-prerequisite.mjs';
import {fileURLToPath} from 'node:url';
import {isolatedCmsAcquisitionFixture} from './isolated-cms-acquisition-fixture.mjs';
if(process.env.DATAHUB_CMS_ACQUISITION_SUITE!=='hospital')isolatedCmsAcquisitionFixture(fileURLToPath(import.meta.url),'hospital',12);
else {
const ROOT=path.join(APP_ROOT,'data/tmp/cms-hospital-acquisition'),sha=v=>createHash('sha256').update(v).digest('hex');
const m={identifier:'xubh-q36u',title:'Hospital General Information',accessLevel:'public',publisher:{name:'Centers for Medicare & Medicaid Services (CMS)'},landingPage:'https://data.cms.gov/provider-data/dataset/xubh-q36u',issued:'2025-01-08',modified:'2026-07-22',released:'2026-08-13',distribution:[{mediaType:'text/csv',downloadURL:'https://data.cms.gov/provider-data/sites/default/files/resources/893c372430d9d71a1c52737d01239d47_1785189955/Hospital_General_Information.csv',describedBy:'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/hospital/HOSPITAL_Data_Dictionary.pdf',describedByType:'application/pdf'}]};
const csv=[...CMS_HOSPITAL_SELECTED_HEADERS,'Telephone Number'].join(',')+'\n010001,Fixture Hospital,1 Street,City,AL,00501-0012,County,Future type,Future ownership,Unknown,PRIVATE CONTACT\n';
const response=(body,type)=>new Response(body,{status:200,headers:{'content-type':type}});
async function track(t){await mkdir(ROOT,{recursive:true});const before=new Set(await readdir(ROOT));t.after(async()=>{for(const name of await readdir(ROOT)){if(before.has(name))continue;assert.match(name,/^[a-f0-9-]{36}$/);const target=path.join(ROOT,name);assert.equal(path.dirname(target),ROOT);await rm(target,{recursive:true,force:true});}});}
function transport(edit){let calls=0;const urls=[];const fn=async(url,opts)=>{calls++;urls.push(url);assert.equal(opts.redirect,'manual');assert.equal(opts.credentials,'omit');assert.equal(opts.method,'GET');const directories=await readdir(ROOT);assert.ok(directories.length);assert.ok((await Promise.all(directories.map(d=>readFile(path.join(ROOT,d,'intent.json')).catch(()=>null)))).some(Boolean));
 const body=calls===2?Buffer.from('%PDF-SYNTHETIC-CMS-REUSE-NOTICE'):calls===3?csv:JSON.stringify(m),type=calls===2?'application/pdf':calls===3?'text/csv':'application/json';return edit?.(calls,url,opts,body,type)??response(body,type);};fn.calls=()=>calls;fn.urls=urls;return fn;}
test('one immutable national source passes four sequential fixture requests and independent source-to-selected replay',async t=>{await track(t);const fetch=transport(),out=await run(fetch),manifest=await verify(out.manifestPath,out.manifestSha256);assert.equal(fetch.calls(),4);assert.equal(fetch.urls[0],fetch.urls[3]);assert.equal(manifest.sourceRows,1);assert.equal(manifest.observedHeaderColumns,11);assert.equal(manifest.claims.nativeTransportVerified,false);assert.equal(manifest.claims.csvRecordConservationVerified,true);assert.equal(manifest.claims.allHospitalCompletenessPercent,null);const directory=path.dirname(out.manifestPath),selected=await readFile(path.join(directory,'selected.jsonl'),'utf8');assert.doesNotMatch(selected,/PRIVATE CONTACT|Telephone Number/);assert.match(await readFile(path.join(directory,'source.csv'),'utf8'),/PRIVATE CONTACT/);const row=JSON.parse(selected);assert.equal(row.reportedAddress.postal.zip4,'0012');assert.equal(row.provenance.policyProfile,'cms-hospital-acquisition@1.0.0');assert.equal(manifest.artifacts.find(a=>a.path==='source.csv').exportPolicy,'internal');await assert.rejects(nativeVerify(out.manifestPath,out.manifestSha256));});
test('notice hash/type/signature mismatch and redirect stop before CSV with restricted completed evidence',async t=>{await track(t);for(const edit of [(n,u,o,b,type)=>n===2?response('%PDF-not-reviewed',type):response(b,type),(n,u,o,b,type)=>n===2?response(b,'text/html'):response(b,type),(n,u,o,b,type)=>n===2?new Response(null,{status:302,headers:{location:'https://example.com/SECRET'}}):response(b,type)]){const fetch=transport(edit);let recovery;await assert.rejects(run(fetch),e=>{recovery=e.recovery;assert.equal(e.message,'CMS hospital acquisition failed.');return true;});assert.equal(fetch.calls(),2);const names=await readdir(recovery.directory);assert.ok(names.includes('metadata-before.json'));assert.ok(!names.includes('source.csv')&&!names.includes('manifest.json'));const failure=JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8'));assert.ok(failure.completedRestrictedSourceArtifacts.every(a=>a.exportPolicy==='internal'));}});
test('metadata drift and duplicate facility IDs preserve completed internal source without publication or retry',async t=>{await track(t);for(const edit of [(n,u,o,b,type)=>response(n===4?JSON.stringify({...m,modified:'2026-07-23'}):b,type),(n,u,o,b,type)=>response(n===3?csv+csv.split('\n')[1]+'\n':b,type)]){const fetch=transport(edit);let recovery;await assert.rejects(run(fetch),e=>{recovery=e.recovery;return true;});assert.equal(fetch.calls(),4);const names=await readdir(recovery.directory);assert.ok(names.includes('source.csv'));assert.ok(!names.includes('manifest.json')&&!names.includes('selected.jsonl'));const failure=JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8'));const a=failure.completedRestrictedSourceArtifacts.find(a=>a.path==='source.csv');assert.equal(a.sha256,sha(await readFile(path.join(recovery.directory,'source.csv'))));}});
test('rehashed selected tampering still fails replay and wrong artifact hash fails',async t=>{await track(t);const out=await run(transport()),directory=path.dirname(out.manifestPath),file=path.join(directory,'selected.jsonl'),changed=(await readFile(file,'utf8')).replace('Fixture Hospital','Different Hospital');await writeFile(file,changed);const manifest=JSON.parse(await readFile(out.manifestPath,'utf8'));Object.assign(manifest.artifacts.find(a=>a.path==='selected.jsonl'),{bytes:Buffer.byteLength(changed),sha256:sha(changed)});const raw=JSON.stringify(manifest)+'\n';await writeFile(out.manifestPath,raw);await assert.rejects(verify(out.manifestPath,sha(raw)));});
test('preabort sends no request; cancellation during CSV request preserves cancelled intent and completed notice',async t=>{await track(t);const before=new AbortController();before.abort();await assert.rejects(acquireCmsHospitals({signal:before.signal}),{name:'AbortError'});const controller=new AbortController(),fetch=transport((n,u,o,b,type)=>{if(n===3){controller.abort();o.signal.throwIfAborted();}return response(b,type);});let recovery;await assert.rejects(run(fetch,{signal:controller.signal}),e=>{recovery=e.recovery;return true;});assert.equal(fetch.calls(),3);const receipt=JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8'));assert.equal(receipt.status,'CANCELLED');assert.equal(receipt.published,false);assert.deepEqual((await readdir(recovery.directory)).sort(),['failure.json','intent.json','metadata-before.json','request-1.json','request-2.json','request-3.json','reuse-notice.pdf']);});
test('response byte cap and invalid options reject without retries or arbitrary URL overrides',async t=>{await track(t);const fetch=transport((n,u,o,b,type)=>response(n===2?Buffer.alloc(1048577):b,type));await assert.rejects(run(fetch));assert.equal(fetch.calls(),2);await assert.rejects(run(()=>assert.fail('must not fetch'),{url:'https://example.com'}));});

test('manifest-last publication and late cancellation or failure preserve explicit uncertain recovery',async t=>{await track(t);for(const cancellation of [false,true]){const controller=new AbortController();let recovery;await assert.rejects(run(transport(),{signal:controller.signal},async(stage,{directory})=>{if(stage==='before-publication'){assert.ok((await readdir(directory)).includes('manifest.pending'));assert.ok(!(await readdir(directory)).includes('manifest.json'));}if(stage==='after-publication'){if(cancellation)controller.abort();else throw Error('PRIVATE injected failure');}}),e=>{assert.equal(e.code,'CMS_HOSPITAL_PUBLICATION_UNCERTAIN');assert.doesNotMatch(e.message,/PRIVATE/);recovery=e.recovery;return true;});assert.equal(recovery.inspectionRequired,true);const m=await verify(recovery.manifestPath,recovery.manifestSha256);assert.equal(m.sourceRows,1);assert.ok((await readdir(path.dirname(recovery.manifestPath))).includes('source.csv'));}});

test('shared source lease excludes simultaneous jobs and never takes over an existing lease',async t=>{await track(t);let entered,release;const began=new Promise(r=>entered=r),held=new Promise(r=>release=r),normal=transport();const first=run(async(...args)=>{entered();await held;return normal(...args);});await began;let secondCalls=0;await assert.rejects(run(()=>{secondCalls++;}),/lease unavailable/);assert.equal(secondCalls,0);release();await first;const file=path.join(ROOT,'.source-lease');await writeFile(file,'FOREIGN LEASE');try{await assert.rejects(run(()=>assert.fail('must not request')),/lease unavailable/);assert.equal(await readFile(file,'utf8'),'FOREIGN LEASE');}finally{await unlink(file);}});

test('noncooperative transport abort is bounded, retains exclusion and disposes a late response',async t=>{await track(t);const controller=new AbortController();let resolve,entered,cancelled=false;const begun=new Promise(r=>entered=r);const pending=run(()=>{entered();return new Promise(r=>resolve=r);},{signal:controller.signal});await begun;controller.abort();await assert.rejects(pending,e=>e.recovery.sourceLeaseRetained===true);await assert.rejects(run(()=>assert.fail('unresolved owner must exclude new work')),/lease unavailable/);resolve({body:{cancel:async()=>{cancelled=true;}}});await new Promise(r=>setImmediate(r));assert.equal(cancelled,true);await unlink(path.join(ROOT,'.source-lease'));});

test('nonsettling body reads and cleanup cannot hang cancellation or rejection',async t=>{await track(t);for(const stalledRead of [true,false]){const controller=new AbortController();const began=Date.now();let timer;const request=run(()=>{if(stalledRead)timer=setTimeout(()=>controller.abort(),20);return {status:200,redirected:false,headers:new Headers({'content-type':stalledRead?'application/json':'text/html'}),body:{getReader:()=>({read:()=>new Promise(()=>{}),cancel:()=>new Promise(()=>{}),releaseLock(){}}),cancel:()=>new Promise(()=>{})}};},{signal:controller.signal});await assert.rejects(request,e=>e.recovery.sourceLeaseRetained===true);clearTimeout(timer);assert.ok(Date.now()-began<3000);await unlink(path.join(ROOT,'.source-lease'));}});

test('lease cleanup failure preserves publication or original failed run identity with redacted inspection recovery',async t=>{await track(t);for(const successful of [true,false]){let recovery;await assert.rejects(run(transport((n,u,o,b,type)=>response(!successful&&n===2?'invalid notice':b,type)),{},async(stage)=>{if(stage==='before-lease-cleanup')throw Error('PRIVATE cleanup failure');}),e=>{recovery=e.recovery;assert.equal(e.code,successful?'CMS_HOSPITAL_PUBLICATION_UNCERTAIN':'CMS_HOSPITAL_ACQUISITION_FAILED');assert.doesNotMatch(e.message,/PRIVATE/);return true;});assert.equal(recovery.inspectionRequired,true);assert.equal(recovery.sourceLeaseRetained,true);assert.equal(recovery.leaseCleanupFailed,true);assert.ok(recovery.runId);if(successful)assert.equal((await verify(recovery.manifestPath,recovery.manifestSha256)).sourceRows,1);else assert.equal(JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8')).runId,recovery.runId);await unlink(path.join(ROOT,'.source-lease'));}});

test('changed-owner lease is never removed and published recovery is preserved',async t=>{await track(t);await assert.rejects(run(transport(),{},async(stage,{leasePath})=>{if(stage==='before-lease-cleanup'){await unlink(leasePath);await mkdir(leasePath);}}),e=>e.code==='CMS_HOSPITAL_PUBLICATION_UNCERTAIN'&&e.recovery.inspectionRequired===true);const lease=path.join(ROOT,'.source-lease');assert.deepEqual(await readdir(lease),[]);await rmdir(lease);});
}
