import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {open,mkdir,readFile,writeFile,readdir,rm,lstat} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {acquireCmsSnfPecos as native,acquireCmsSnfPecosWithTestTransport as acquire,verifyCmsSnfPecosAcquisition as verifyNative,verifyCmsSnfPecosAcquisitionWithTestInput as verify,PECOS_ACQUISITION_LEASES as leases,PECOS_ACQUISITION_POLICY as policy} from './cms-snf-pecos-acquisition.mjs';
import {CMS_NURSING_HOME_BUDGET_LOCKS} from './cms-nursing-home-acquisition.mjs';
import {CMS_SNF_PECOS_AUGUST_SELECTION as S,CMS_SNF_PECOS_CURRENT_DOCUMENTS as D} from './cms-snf-pecos-metadata-prerequisite.mjs';
import {CMS_SNF_PECOS_HEADERS as H} from './cms-snf-pecos-prerequisite.mjs';
const json=v=>Buffer.from(JSON.stringify(v)+'\n'),sha=b=>createHash('sha256').update(b).digest('hex');
const resourceUrl=v=>'https://data.cms.gov/data-api/v1/dataset-resources/'+v;
function bodies(){const entry=p=>({name:p.name,fileSize:p.bytes,downloadURL:p.url}),records=kind=>{const p=S[kind],common={temporal:'2026-08-01/2026-08-31',modified:'2026-08-17',title:p.title+' : 2026-08-01',resourcesAPI:resourceUrl(p.version)};return {title:p.title,identifier:'https://data.cms.gov/data-api/v1/dataset/'+p.typeId+'/data-viewer',accessLevel:'public',accessRights:'Open',license:policy.sourceLicense,publisher:{name:'Centers for Medicare & Medicaid Services'},describedBy:D[kind].url,references:[D.guidance.url],distribution:[{...common,format:'CSV',mediaType:'text/csv',downloadURL:p.url},{...common,format:'API',accessURL:'https://data.cms.gov/data-api/v1/dataset/'+p.version+'/data'}]};};const resource=kind=>({meta:{success:true},links:{self:{href:resourceUrl(S[kind].version)}},data:[entry(S[kind]),entry(D[kind]),entry(D.guidance),...(kind==='enrollments'?[entry(S.additionalNpis)]:[])]});const values={'ENROLLMENT ID':'O00000000000001','ASSOCIATE ID':'0000000001','CCN':'001234','NPI':'0123456789','MULTIPLE NPI FLAG':'Y','PROVIDER TYPE CODE':'00-18','TYPE - OWNER':'O','ASSOCIATE ID - OWNER':'0000000002'};return [json({dataset:[records('enrollments'),records('owners')]}),json(resource('enrollments')),json(resource('owners')),...['enrollments','owners','additionalNpis'].map(k=>Buffer.from(H[k].join(',')+'\n'+H[k].map(h=>values[h]??'').join(',')+'\n'))];}
function transport(edit){const data=bodies();let i=0;return async(url,init)=>{const index=i++;assert.equal(init.method,'GET');assert.equal(init.redirect,'manual');const b=Buffer.from(data[index<6?index:index-6]);const r=await edit?.({index,b,data,url,init});return r??new Response(b,{status:200,headers:{'content-type':index>=3&&index<=5?'text/csv':'application/json'}});};}
async function clean(directory){if(!directory)return;const root=path.dirname(leases.fixture);assert.ok(path.resolve(directory).startsWith(root+path.sep));await rm(directory,{recursive:true,force:true});}
async function leaseClear(){const s=await lstat(leases.fixture).catch(()=>null);if(s){assert.ok(s.isFile()&&!s.isSymbolicLink());await rm(leases.fixture);}}
test('policy+native dispatch hold and malformed CLI reject before transport',async()=>{assert.deepEqual(JSON.parse(await readFile(new URL('../config/source-policies/cms-snf-pecos-acquisition.json',import.meta.url))),policy);assert.equal(leases.native,CMS_NURSING_HOME_BUDGET_LOCKS.native);await assert.rejects(native());const r=spawnSync(process.execPath,['scripts/acquire-cms-snf-pecos.mjs','--url=https://example.com'],{cwd:new URL('..',import.meta.url),encoding:'utf8',timeout:5000});assert.equal(r.status,1);assert.equal(r.stdout,'');});
test('manifest-last fixture acquires9 responses, copies docs, replays full rows and rejects native authenticity',async()=>{let r;try{r=await acquire(transport());assert.equal(r.inspectionRequired,false);const m=await verify(r.manifestPath,r.manifestSha256);assert.equal(m.requests.length,9);assert.ok(m.documentsCopied.every(d=>d.downloadedThisRun===false));assert.equal(m.counts.owners.sourceRows,1);assert.equal(m.claims.nativeTransportVerified,false);await assert.rejects(verifyNative(r.manifestPath,r.manifestSha256));await assert.rejects(lstat(leases.fixture),{code:'ENOENT'});}finally{await clean(r?.directory);}});
test('unrelated catalog entries may change, selected version drift cannot',async()=>{let r;try{r=await acquire(transport(({index,b})=>{if(index===6){const m=JSON.parse(b);m.dataset.push({title:'Unrelated changed metadata'});return new Response(json(m),{headers:{'content-type':'application/json'}});}}));const m=await verify(r.manifestPath,r.manifestSha256);assert.notEqual(m.metadataPlans.before.catalog.sha256,m.metadataPlans.after.catalog.sha256);}finally{await clean(r?.directory);}let failure;try{await acquire(transport(({index,b})=>{if(index===6){const m=JSON.parse(b);m.dataset[0].distribution[0].modified='2026-08-18';return new Response(json(m),{headers:{'content-type':'application/json'}});}}));assert.fail();}catch(e){failure=e;assert.ok(e.recovery);}finally{await clean(failure?.recovery.directory);}});
test('completed raw invalid schema is retained, partial/derived outputs removed, lease released',async()=>{let failure;try{await acquire(transport(({index})=>index===4?new Response('wrong\nrow\n',{headers:{'content-type':'text/csv'}}):undefined));assert.fail();}catch(e){failure=e;const dir=e.recovery.directory;const f=JSON.parse(await readFile(path.join(dir,'failure.json')));assert.equal(f.networkOwnershipUnresolved,false);assert.equal(f.completedRaw.length,9);assert.equal((await readFile(path.join(dir,'owners.csv'))).toString(),'wrong\nrow\n');assert.ok(!(await readdir(dir)).some(n=>n.endsWith('.jsonl')||n.startsWith('manifest')));await assert.rejects(lstat(leases.fixture),{code:'ENOENT'});}finally{await clean(failure?.recovery.directory);}});
test('completed bad HTTP/type retains body before rejecting',async()=>{let failure;try{await acquire(transport(({index})=>index===0?new Response('retained-error-body',{status:500,headers:{'content-type':'text/plain'}}):undefined));assert.fail();}catch(e){failure=e;assert.equal((await readFile(path.join(e.recovery.directory,'catalog-before.json'))).toString(),'retained-error-body');const f=JSON.parse(await readFile(path.join(e.recovery.directory,'failure.json')));assert.equal(f.requests[0].status,500);}finally{await clean(failure?.recovery.directory);}});
test('source lease excludes another caller and never steals marker',async()=>{await mkdir(path.dirname(leases.fixture),{recursive:true});const h=await open(leases.fixture,'wx');await h.writeFile('other CMS owner');await h.close();try{let calls=0;await assert.rejects(acquire(async()=>{calls++;throw Error();}));assert.equal(calls,0);assert.equal((await readFile(leases.fixture)).toString(),'other CMS owner');}finally{await leaseClear();}});
test('postpublication failure retains descriptor; same-inode changed lease remains quarantined',async()=>{let f;try{await acquire(transport(),{},stage=>{if(stage==='after-publication')throw Error('fixture');});assert.fail();}catch(e){f=e;assert.ok(e.recovery.manifestPath);assert.equal(e.recovery.inspectionRequired,true);await verify(e.recovery.manifestPath,e.recovery.manifestSha256);}finally{await clean(f?.recovery.directory);}let result;try{await acquire(transport(),{},async(stage,{leasePath})=>{if(stage==='before-lease-cleanup')await writeFile(leasePath,'changed-owner');});assert.fail();}catch(e){result=e;assert.ok(e.recovery.manifestPath);assert.equal(e.recovery.leaseCleanupFailed,true);assert.equal((await readFile(leases.fixture)).toString(),'changed-owner');}finally{await clean(result?.recovery.directory);await leaseClear();}});
test('unresolved noncooperative fetch returns bounded with lease retained, no retry',async()=>{const c=new AbortController();let f,calls=0;const start=Date.now();try{await acquire(async()=>{calls++;setTimeout(()=>c.abort(),5);return new Promise(()=>{});},{signal:c.signal});assert.fail();}catch(e){f=e;assert.equal(e.sourceLeaseRetained,true);assert.equal(calls,1);assert.ok(Date.now()-start<5000);assert.ok(await lstat(leases.fixture));}finally{await clean(f?.recovery.directory);await leaseClear();}});
test('independent replay rejects selected tamper even if manifest hash is recomputed',async()=>{let r;try{r=await acquire(transport());const selected=path.join(r.directory,'owners.jsonl');await writeFile(selected,'{}\n');const m=JSON.parse(await readFile(r.manifestPath)),a=m.artifacts.find(a=>a.path==='owners.jsonl');a.bytes=3;a.sha256=sha(Buffer.from('{}\n'));const bytes=json(m);await writeFile(r.manifestPath,bytes);await assert.rejects(verify(r.manifestPath,sha(bytes)));}finally{await clean(r?.directory);}});
test('noncooperative read/cancel remains bounded and quarantined',async()=>{let f;const c=new AbortController(),start=Date.now();try{await acquire(async()=>{setTimeout(()=>c.abort(),5);return {status:200,redirected:false,headers:new Headers({'content-type':'application/json'}),body:{getReader:()=>({read:()=>new Promise(()=>{}),cancel:()=>new Promise(()=>{}),releaseLock(){}})}};},{signal:c.signal});assert.fail();}catch(e){f=e;assert.equal(e.sourceLeaseRetained,true);assert.ok(Date.now()-start<5000);}finally{await clean(f?.recovery.directory);await leaseClear();}});
test('actual fixed30second request deadline settles noncooperative fetch with quarantine',async()=>{let f;const keepAlive=setInterval(()=>{},1000),start=Date.now();try{await acquire(async()=>new Promise(()=>{}));assert.fail();}catch(e){f=e;assert.equal(e.sourceLeaseRetained,true);assert.ok(Date.now()-start>=30000&&Date.now()-start<35000);}finally{clearInterval(keepAlive);await clean(f?.recovery.directory);await leaseClear();}});
test('policy change after projection at publication hook prevents success and preserves raw evidence',async()=>{const file=new URL('../config/source-policies/cms-snf-pecos-acquisition.json',import.meta.url),original=await readFile(file);let f;try{await acquire(transport(),{},async stage=>{if(stage==='before-publication')await writeFile(file,json({...policy,publicExportAuthorized:true}));});assert.fail();}catch(e){f=e;assert.equal(e.recovery.manifestPath,null);const names=await readdir(e.recovery.directory);assert.ok(names.includes('failure.json')&&names.includes('owners.csv'));assert.ok(!names.some(n=>n.startsWith('manifest')));}finally{await writeFile(file,original);await clean(f?.recovery.directory);}});
