import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { runInNewContext } from "node:vm";
import test from "node:test";
import ts from "typescript";

const source = await readFile(new URL("../app/document-only-inquiry-proposal-registry.tsx", import.meta.url), "utf8"); const code = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX } }).outputText;
function fixture(runnerJson) { const slots = [], refs = [], effects = [], calls = []; let index = 0; const exports = {}; runInNewContext(code, { exports, AbortController, window: globalThis, require: (name) => name === "./runner-client" ? { runnerJson: (...args) => { calls.push(args); return runnerJson(...args); } } : name === "react" ? { useState(initial) { const slot = index++; if (!(slot in slots)) slots[slot] = initial; return [slots[slot], (next) => { slots[slot] = typeof next === "function" ? next(slots[slot]) : next; }]; }, useRef(initial) { const slot = index++; if (!(slot in refs)) refs[slot] = { current: initial }; return refs[slot]; }, useCallback(callback) { index += 1; return callback; }, useEffect(effect) { index += 1; effects.push(effect); } } : name === "react/jsx-runtime" ? { jsx: (type, props) => ({ type, props }), jsxs: (type, props) => ({ type, props }), Fragment: "fragment" } : { __esModule: true, default: () => null } }); return { calls, mount() { const tree = this.render(); for (const effect of effects.splice(0)) effect(); return tree; }, render() { index = 0; return exports.default(); } }; }
const hashes = ["a", "b", "c", "d"].map((value) => value.repeat(64));
const view = () => ({ schema_version: "document-only-inquiry-proposal-registry-view@1.0.0", available: true, coverage: { actual_collected_data: { admitted_jurisdictions: 11, denominator: 51, unresolved_data_gaps: 40 }, authorization_packets: { covered_current_gap_states: 40, expected_current_gap_states: 40, packet_gaps: 0 }, document_only_proposals: { covered_current_gap_states: 40, expected_current_gap_states: 40, proposal_gaps: 0 } }, authority: { approval_granted: false }, proposals: hashes.map((hash, index) => ({ proposal_id: `wave-${index + 1}-document-only-inquiry-20260923-01`, wave_number: index + 1, status: "PROPOSED", approval_status: "NOT APPROVED", authority_status: "NO ACTION AUTHORIZED", document_sha256: hash, state_count: 10, states: [{ state_abbreviation: `S${index}`, state_name: `State ${index}` }], approval_syntax: `Approve wave-${index + 1}-document-only-inquiry-20260923-01 with document SHA-256 ${hash}.`, supersession: index === 0 ? { supersedes_only_prior_unapproved_document_sha256: "976369982eea4c8289acb4677a921ede6cd0fe7efacf8e0fa5de6c8afd3c2a50", prior_proposal_was_approved: false, prior_proposal_authorized_action: false } : null })) });
function nodes(tree) { if (!tree || typeof tree !== "object") return []; if (Array.isArray(tree)) return tree.flatMap(nodes); return [tree, ...nodes(tree.props?.children)]; } const textOf = (tree) => typeof tree === "string" ? tree : Array.isArray(tree) ? tree.map(textOf).join(" ") : tree && typeof tree === "object" ? textOf(tree.props?.children) : ""; const settle = () => new Promise((resolve) => setTimeout(resolve, 5));

test("panel renders four copy-only proposals and separates all three coverage measures", async () => { const f = fixture(async (url, options) => { assert.equal(url, "/api/data-operations/document-only-inquiry-proposals"); assert.ok(options.signal); return view(); }); f.mount(); await settle(); const tree = f.render(); assert.match(textOf(tree), /Actual collected coverage: 11\/51/); assert.match(textOf(tree), /Authorization-packet coverage: 40\/40/); assert.match(textOf(tree), /document-only proposal coverage: 40\/40/); assert.match(textOf(tree), /PROPOSED · NOT APPROVED · NO ACTION AUTHORIZED/); assert.match(textOf(tree), /supersedes only the prior unapproved document SHA-256/); assert.equal(nodes(tree).filter((node) => node.type === "article").length, 4); assert.equal(nodes(tree).filter((node) => node.type === "button").length, 1); assert.doesNotMatch(textOf(tree), /Approve now|Execute|Start inquiry/); });
test("panel cancels stale requests and clears proposal details on failure", async () => { const pending = []; const f = fixture((_url, options) => new Promise((resolve, reject) => pending.push({ resolve, reject, signal: options.signal }))); f.mount(); await settle(); let tree = f.render(); nodes(tree).find((node) => node.type === "button").props.onClick(); assert.equal(pending[0].signal.aborted, true); pending[1].resolve(view()); await settle(); pending[0].resolve({ ...view(), proposals: [] }); await settle(); tree = f.render(); assert.match(textOf(tree), /wave-1-document-only/); nodes(tree).find((node) => node.type === "button").props.onClick(); pending[2].reject(new Error("private")); await settle(); tree = f.render(); assert.match(textOf(tree), /unavailable or failed verification/); assert.doesNotMatch(textOf(tree), /wave-1-document-only|aaaaaaaa/); });
test("Data Operations places proposal registry next to current authorization chain", async () => { const dataOperations = await readFile(new URL("../app/data-operations.tsx", import.meta.url), "utf8"); assert.match(dataOperations, /import DocumentOnlyInquiryProposalRegistry/); assert.ok(dataOperations.indexOf("<DocumentOnlyInquiryProposalRegistry />") > dataOperations.indexOf("<BroadOrganizationCurrentAuthorizationChain />")); });
