import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {mkdir,readdir,readFile,writeFile,rm,unlink} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {APP_ROOT} from './paths.mjs';
import {flFoodGisRequests,projectFlFoodGisPreflight,FL_FOOD_GIS_ITEM} from './fl-food-gis-contract.mjs';
import {preflightFlFoodGisWithTestTransport as run,verifyFlFoodGisPreflightWithTestInput as verify,verifyFlFoodGisPreflight as nativeVerify,preflightFlFoodGis as native} from './fl-food-gis-preflight.mjs';
const ROOT=path.join(APP_ROOT,'data/tmp/fl-food-gis-preflight'),encode=v=>Buffer.from(JSON.stringify(v)),sha=v=>createHash('sha256').update(v).digest('hex');
function fixture(){const lengths={FOOD_ENTITY_NUM:8,FE_TYPE:5,FOOD_ENTITY_NAME:100,ADDRESS_LINE_1:100,CITY:50,ZIP:6,ZIP_PLUS4:4,COUNTY:2000,IS_RETAIL:1,IS_WHOLESALE:1,FE_DESCRIPTION:255,OPERATING_HOURS:150,FE_CONTACT_EMAILL:100,FE_CONTACT_PHONE:100,FE_CONTACT_NAME:127,OWNER_CONTACT_NAME:127,OWNER_CONTACT_EMAIL:100,OWNER_CONTACT_PHONE:100,FDA_WORKPLAN_IND:1};return [{serviceItemId:FL_FOOD_GIS_ITEM,capabilities:'Map,Query,Data',layers:[{id:0,name:'Food Entities - Retail'},{id:1,name:'Food Entities - Manufacturing'}],spatialReference:{wkid:4326}},{id:0,name:'Food Entities - Retail',serviceItemId:FL_FOOD_GIS_ITEM,type:'Feature Layer',geometryType:'esriGeometryPoint',spatialReference:{wkid:4326},sourceSpatialReference:{wkid:4326},maxRecordCount:2000,advancedQueryCapabilities:{supportsStatistics:true,supportsPagination:true,supportsOrderBy:true},fields:[{name:'OBJECTID',type:'esriFieldTypeOID'},{name:'Geolocation',type:'esriFieldTypeGeometry'},{name:'OWNERS_PK',type:'esriFieldTypeBigInteger'},...Object.entries(lengths).map(([name,length])=>({name,type:'esriFieldTypeString',length,domain:null}))],drawingInfo:{renderer:{field1:'FE_DESCRIPTION',uniqueValueInfos:['HIGH RISK','MEDIUM RISK','LOW RISK'].map(value=>({value}))}}},{licenseInfo:'',accessInformation:''}];}
async function track(t){await mkdir(ROOT,{recursive:true});const before=new Set(await readdir(ROOT)),file=path.join(ROOT,'.fixture-policy.json');assert.ok(!before.has('.fixture-policy.json'));await writeFile(file,await readFile(path.join(APP_ROOT,'config/source-policies/fl-food-gis-preflight.json')),{flag:'wx'});t.after(async()=>{await unlink(file);for(const name of await readdir(ROOT)){if(before.has(name))continue;assert.match(name,/^[a-f0-9-]{36}$/);const target=path.join(ROOT,name);assert.equal(path.dirname(target),ROOT);await rm(target,{recursive:true,force:true});}});}
function transport(values=fixture()){let i=0;const timestamps=[];const f=async(u,o)=>{timestamps.push(Date.now());assert.equal(u,flFoodGisRequests()[i].url);assert.equal(o.redirect,'manual');assert.equal(o.credentials,'omit');assert.equal(o.method,'GET');return new Response(encode(values[i++]),{headers:{'content-type':'text/plain; charset=UTF-8'}});};f.count=()=>i;f.timestamps=timestamps;return f;}
test('exact metadata itinerary has no establishment/count/export request and no restaurant/grocery equivalence',()=>{assert.equal(flFoodGisRequests().length,3);assert.ok(flFoodGisRequests().every(r=>!new URL(r.url).pathname.endsWith('/query')));const out=projectFlFoodGisPreflight(fixture().map(encode));assert.equal(out.metadataContractValidated,true);assert.equal(out.acquisitionReady,false);assert.equal(out.sourceRows,null);assert.equal(out.groceryClassification.mappingVerified,false);assert.equal(out.riskIsBusinessCategory,false);assert.equal(out.licenseStatus,null);assert.equal(out.publisherUpdateClock,null);assert.equal(out.postalFields.joined,false);assert.equal(out.postalFields.zip5SourceWidth,6);assert.ok(out.excludedFieldNames.includes('OWNER_CONTACT_EMAIL'));assert.equal(Object.hasOwn(out.selectedFieldSchema,'OWNER_CONTACT_EMAIL'),false);});
test('wrong layer, item, CRS, field width/domain, risk category, status schema and new notice reject',()=>{for(const edit of [v=>v[0].serviceItemId='wrong',v=>v[1].id=1,v=>v[1].sourceSpatialReference={wkid:3857},v=>v[1].fields.find(f=>f.name==='ZIP').length=9,v=>v[1].fields.find(f=>f.name==='FE_TYPE').domain={codedValues:[]},v=>v[1].drawingInfo.renderer.uniqueValueInfos[0].value='GROCERY',v=>v[1].fields.push({name:'LICENSE_STATUS',type:'esriFieldTypeString'}),v=>v[2].licenseInfo='New restriction',v=>v[1].features=[{attributes:{}}]]){const values=fixture();edit(values);assert.throws(()=>projectFlFoodGisPreflight(values.map(encode)));}assert.throws(()=>projectFlFoodGisPreflight([Buffer.from([0xff]),...fixture().slice(1).map(encode)]));});
test('three native-shaped fixture requests produce independently verified metadata-only receipt',async t=>{await track(t);const fetch=transport(),out=await run(fetch),m=await verify(out.manifestPath,out.manifestSha256);assert.equal(fetch.count(),3);assert.equal(m.requests.length,3);for(let i=1;i<3;i++)assert.ok(fetch.timestamps[i]-fetch.timestamps[i-1]>=990);assert.ok(m.requests.every(r=>r.responseMediaType==='text/plain'));assert.equal(m.claims.nativeTransportVerified,false);assert.equal(m.result.acquisitionReady,false);await assert.rejects(nativeVerify(out.manifestPath,out.manifestSha256));});
test('transport rejection retains bounded diagnostic and policy without retry',async t=>{await track(t);let calls=0,recovery;await assert.rejects(run(()=>{calls++;return new Response('unavailable',{status:503,headers:{'content-type':'text/html; x=SECRET'}});}),e=>{recovery=e.recovery;return true;});assert.equal(calls,1);const raw=await readFile(path.join(recovery.directory,'failure.json'),'utf8');assert.doesNotMatch(raw,/SECRET/);assert.equal(JSON.parse(raw).requests[0].responseMediaType,'text/html');assert.ok((await readdir(recovery.directory)).includes('service.json'));});
test('closed options/preabort and cancellation during spacing issue no next request',async t=>{await track(t);const c=new AbortController();c.abort();await assert.rejects(native({signal:c.signal}),{name:'AbortError'});await assert.rejects(run(()=>assert.fail(),{url:'https://example.invalid'}));const d=new AbortController();let calls=0,recovery;await assert.rejects(run(()=>{calls++;setTimeout(()=>d.abort(),30);return new Response(encode(fixture()[0]),{headers:{'content-type':'application/json'}});},{signal:d.signal}),e=>{recovery=e.recovery;return true;});assert.equal(calls,1);assert.equal(JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8')).status,'CANCELLED');assert.ok(!(await readdir(ROOT)).includes('.source-lease'));});
test('source lease excludes concurrency and detects changed payload on same inode',async t=>{await track(t);let entered,release;const begun=new Promise(r=>entered=r),held=new Promise(r=>release=r),normal=transport();const first=run(async(...args)=>{entered();await held;return normal(...args);},{},async(stage,{leasePath})=>{if(stage==='before-lease-cleanup')await writeFile(leasePath,'CHANGED');});await begun;await assert.rejects(run(()=>assert.fail()),/lease unavailable/);release();await assert.rejects(first,e=>e.recovery.inspectionRequired&&e.recovery.sourceLeaseRetained);assert.equal(await readFile(path.join(ROOT,'.source-lease'),'utf8'),'CHANGED');await unlink(path.join(ROOT,'.source-lease'));});
test('noncooperative response retains lease and late disposal never silently unlocks',async t=>{await track(t);let entered,resolve,disposed=false;const begun=new Promise(r=>entered=r),c=new AbortController(),job=run(()=>{entered();return new Promise(r=>resolve=r);},{signal:c.signal});await begun;c.abort();await assert.rejects(job,e=>e.recovery.sourceLeaseRetained);resolve({body:{cancel:async()=>{disposed=true;}}});await new Promise(r=>setImmediate(r));assert.equal(disposed,true);await assert.rejects(run(()=>assert.fail()),/lease unavailable/);await unlink(path.join(ROOT,'.source-lease'));});
test('policy drift before publication preserves evidence and prevents success manifest',async t=>{await track(t);const file=path.join(ROOT,'.fixture-policy.json'),before=await readFile(file);let recovery;await assert.rejects(run(transport(),{},async stage=>{if(stage==='before-publication')await writeFile(file,Buffer.concat([before,Buffer.from(' ')]));}),e=>{recovery=e.recovery;return true;});assert.ok(!(await readdir(recovery.directory)).includes('manifest.json'));assert.deepEqual(await readFile(path.join(recovery.directory,'policy.json')),before);});
test('postpublication failure retains inspection-required verifiable receipt',async t=>{await track(t);let recovery;await assert.rejects(run(transport(),{},stage=>{if(stage==='after-publication')throw Error('SECRET');}),e=>{recovery=e.recovery;assert.doesNotMatch(e.message,/SECRET/);return true;});assert.equal(recovery.inspectionRequired,true);assert.equal((await verify(recovery.manifestPath,recovery.manifestSha256)).result.acquisitionReady,false);});
test('rehashed timing and readiness tampering fail independent verifier',async t=>{await track(t);const out=await run(transport()),original=JSON.parse(await readFile(out.manifestPath,'utf8'));for(const edit of [m=>m.result.acquisitionReady=true,m=>m.requests[1].startedAt=m.requests[0].completedAt]){const m=structuredClone(original);edit(m);const raw=encode(m);await writeFile(out.manifestPath,raw);await assert.rejects(verify(out.manifestPath,sha(raw)));}});
test('standalone CLI help and invalid overrides stay offline',async()=>{const cli=path.join(APP_ROOT,'scripts/preflight-fl-food-gis.mjs'),result=await promisify(execFile)(process.execPath,[cli,'--help']);assert.match(result.stdout,/no establishment query/);await assert.rejects(promisify(execFile)(process.execPath,[cli,'--url','https://example.invalid']),e=>e.code===1);});
test('over-cap response is not retained as complete metadata and verifier options are closed',async t=>{await track(t);let calls=0,recovery;await assert.rejects(run(()=>{calls++;return new Response(Buffer.alloc(1048577),{headers:{'content-type':'application/json'}});}),e=>{recovery=e.recovery;return true;});assert.equal(calls,1);assert.ok(!(await readdir(recovery.directory)).includes('service.json'));await assert.rejects(nativeVerify('unused','0'.repeat(64),{hook(){}}));await assert.rejects(nativeVerify('unused',['0'.repeat(64)]));});
test('stalled body read/cleanup cannot hang cancellation or relinquish unknown ownership',async t=>{await track(t);const c=new AbortController();let timer;await assert.rejects(run(()=>{timer=setTimeout(()=>c.abort(),20);return{status:200,redirected:false,headers:new Headers({'content-type':'application/json'}),body:{getReader:()=>({read:()=>new Promise(()=>{}),cancel:()=>new Promise(()=>{}),releaseLock(){}})}};},{signal:c.signal}),e=>e.recovery.sourceLeaseRetained===true);clearTimeout(timer);await assert.rejects(run(()=>assert.fail()),/lease unavailable/);await unlink(path.join(ROOT,'.source-lease'));});
