import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { APP_ROOT } from "./paths.mjs";
import { readIllinoisBroadOrganizationAdmissionReadiness, readIllinoisBroadOrganizationAdmissionReadinessForTest } from "./illinois-broad-organization-admission-readiness.mjs";

async function isolated(t){const parent=path.join(APP_ROOT,"data","tmp");await mkdir(parent,{recursive:true});const root=await mkdtemp(path.join(parent,"il-readiness-"));t.after(()=>rm(root,{recursive:true,force:true}));return root;}
async function candidate(root,value){const directory=path.join(root,randomUUID());await mkdir(directory);await writeFile(path.join(directory,"receipt.json"),`${JSON.stringify(value)}\n`);return directory;}
async function verifier(receiptPath){const value=JSON.parse(await readFile(receiptPath,"utf8"));if(value.kind==="corrupt")throw Error("private verifier detail");if(value.kind==="terminal")return{receipt:{status:value.status,inspection_required:true,network_requests:0,source_pointer_changed:false,national_admission_performed:false}};return{receipt:{status:"SUCCEEDED",finished_at:value.finished_at,network_requests:0,source_pointer_changed:false,national_admission_performed:false,export_policy:"local-review-only"}};}

test("production reader exposes only cancellation and preserves all seven unresolved gates",async()=>{const source=await readFile(new URL("./illinois-broad-organization-admission-readiness.mjs",import.meta.url),"utf8"),server=await readFile(new URL("./server.mjs",import.meta.url),"utf8"),view=await readIllinoisBroadOrganizationAdmissionReadiness();assert.match(source,/readIllinoisBroadOrganizationAdmissionReadiness\(\{signal\}=\{\}\)/);assert.doesNotMatch(server,/readIllinoisBroadOrganizationAdmissionReadinessForTest/);assert.equal(view.gates.length,7);assert.ok(view.gates.every(gate=>gate.closure_state==="unresolved"&&!gate.authority_granted));assert.equal(view.claims.statewide_completeness,null);});
test("verified evidence affects only the two package-backed gates",async t=>{const root=await isolated(t);await candidate(root,{kind:"verified",finished_at:"2026-10-07T00:00:01.000Z"});const view=await readIllinoisBroadOrganizationAdmissionReadinessForTest({root,verifier});assert.equal(view.package_evidence.status,"verified");assert.equal(view.package_evidence.verified_operation_count,1);assert.deepEqual(view.gates.filter(gate=>gate.evidence_state==="evidenced-unresolved").map(gate=>gate.gate),["operator-supplied-complete-same-run-package","independent-package-verification"]);assert.ok(view.gates.every(gate=>gate.closure_state==="unresolved"&&!gate.authority_granted));});
test("valid failed and cancelled receipts stay separate from corrupt evidence",async t=>{const root=await isolated(t);await candidate(root,{kind:"terminal",status:"FAILED"});await candidate(root,{kind:"terminal",status:"CANCELLED"});await candidate(root,{kind:"corrupt"});const view=await readIllinoisBroadOrganizationAdmissionReadinessForTest({root,verifier}),serialized=JSON.stringify(view);assert.equal(view.package_evidence.status,"corrupt");assert.equal(view.package_evidence.terminal_non_success_operation_count,2);assert.equal(view.package_evidence.corrupt_operation_count,1);assert.doesNotMatch(serialized,/private verifier detail|receipt\.json|il-readiness/i);});
test("isolated reader bounds inventory and honors cancellation",async t=>{const root=await isolated(t);await candidate(root,{kind:"verified"});await assert.rejects(readIllinoisBroadOrganizationAdmissionReadinessForTest({root,verifier,maximumOperations:0}),/test options are invalid/);await assert.rejects(readIllinoisBroadOrganizationAdmissionReadinessForTest({root,verifier,signal:AbortSignal.abort()}),error=>error.name==="AbortError");});
