import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, rm, symlink, writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { APP_ROOT } from "./paths.mjs";
import { KY_BUSINESS_FIELDS } from "./kentucky-business-entity-bulk-offline.mjs";
import { runKentuckyBusinessEntityAppJob, verifyKentuckyBusinessEntityAppJob } from "./kentucky-business-entity-bulk-app.mjs";
const packagesRoot=path.join(APP_ROOT,"data","imports","kentucky-business-entity-bulk","packages"),operationsRoot=path.join(APP_ROOT,"data","imports","kentucky-business-entity-bulk","operations"),sha=bytes=>createHash("sha256").update(bytes).digest("hex");
const company=(id="0000123")=>Object.fromEntries(KY_BUSINESS_FIELDS.map(field=>[field,({ID:id,comptype:"06",compseq:"00001",Name:"Synthetic Market LLC",Standing:"G",Status:"A",Country:"US",State:"KY",Type:"LLC",raname:"PRIVATE PERSON",raaddr1:"PRIVATE",racity:"Frankfort",restate:"KY",razip:"40601",poaddr1:"100 Main St",pocity:"Cincinnati",postate:"OH",pozip:"45202-1234",filedate:"01/02/2020",recorddate:"10/03/2026",applname:"PRIVATE APPLICANT",recordnumber:"0000042"})[field]??""]));
const claims=()=>({network_requests:0,acquisition_performed:false,account_created:false,payment_made:false,terms_accepted:false,publisher_contacted:false,officer_files_included:false,source_authenticity_verified:false,statewide_complete:false,current_operation_verified:false,physical_site_verified:false,redistribution_authorized:false,national_admission_performed:false,production_enrollment:false,source_pointer_changed:false});
async function makePackage({rows=[company()],extra=false}={}){const id=`test-${randomUUID()}`,directory=path.join(packagesRoot,id);await mkdir(directory,{recursive:true});const bytes=Buffer.from(`${rows.map(row=>KY_BUSINESS_FIELDS.map(field=>row[field]).join("\t")).join("\n")}\n`),selection={schema_version:"kentucky-business-entity-package@1.0.0",package_id:id,observed_at:"2026-10-03T12:00:00.000Z",temporal_scope:"all-companies-monthly",source:"https://www.sos.ky.gov/bus/Pages/Bulk-Data-Service.aspx",source_file_has_header:false,transformation:{version:"fixture@1.0.0",method:"Synthetic fixture.",performed_by:"test"},raw_source_classification:"person-bearing-internal",files:{COMPANIES:{path:"companies.txt",bytes:bytes.length,sha256:sha(bytes),row_count:rows.length}},claims:claims()};await writeFile(path.join(directory,"companies.txt"),bytes);await writeFile(path.join(directory,"selection.json"),`${JSON.stringify(selection)}\n`);if(extra)await writeFile(path.join(directory,"officers.txt"),"forbidden\n");return{directory};}

test("runs and independently replays a private Kentucky release with separate ZIP5 and ZIP4",async t=>{const pkg=await makePackage();let operation;t.after(async()=>{await rm(pkg.directory,{recursive:true,force:true});if(operation)await rm(operation,{recursive:true,force:true});});const saved=globalThis.fetch;globalThis.fetch=()=>assert.fail("network request");try{const result=await runKentuckyBusinessEntityAppJob({packageDirectory:pkg.directory});operation=result.operationDirectory;assert.equal(result.receipt.status,"SUCCEEDED");assert.equal(result.receipt.network_requests,0);assert.equal(result.receipt.statewide_complete,false);assert.equal(result.receipt.public_export_authorized,false);const proof=await verifyKentuckyBusinessEntityAppJob(result.receiptPath);assert.equal(proof.receipt.source.record_count,1);const text=await readFile(path.join(operation,"release","organizations.jsonl"),"utf8");assert.match(text,/"zip5":"45202","zip4":"1234"/);assert.doesNotMatch(text,/PRIVATE PERSON|PRIVATE APPLICANT/);assert.deepEqual((await readdir(path.join(operation,"release"))).sort(),["manifest.json","organizations.jsonl"]);}finally{globalThis.fetch=saved;}});
test("cancellation retains CANCELLED and cleans only operation-owned unpublished data",async t=>{const pkg=await makePackage(),controller=new AbortController();let operation,calls=0,before=new Set(await readdir(operationsRoot).catch(error=>error.code==="ENOENT"?[]:Promise.reject(error)));t.after(async()=>{await rm(pkg.directory,{recursive:true,force:true});if(operation)await rm(operation,{recursive:true,force:true});});await assert.rejects(runKentuckyBusinessEntityAppJob({packageDirectory:pkg.directory,signal:controller.signal,now:()=>{calls++;if(calls===1)controller.abort();return new Date("2026-10-03T12:00:00.000Z");}}),error=>error.name==="AbortError");const added=(await readdir(operationsRoot)).filter(name=>!before.has(name));assert.equal(added.length,1);operation=path.join(operationsRoot,added[0]);assert.equal(JSON.parse(await readFile(path.join(operation,"receipt.json"))).status,"CANCELLED");await assert.rejects(readFile(path.join(operation,"release")),{code:"ENOENT"});await assert.rejects(readFile(path.join(operation,"input-snapshot")),{code:"ENOENT"});});
test("invalid inventory, duplicate identity, and linked package fail before operation creation",async t=>{const extra=await makePackage({extra:true}),duplicate=await makePackage({rows:[company(),company()]}),valid=await makePackage(),before=new Set(await readdir(operationsRoot).catch(error=>error.code==="ENOENT"?[]:Promise.reject(error)));t.after(()=>Promise.all([extra,duplicate,valid].map(item=>rm(item.directory,{recursive:true,force:true}))));await assert.rejects(runKentuckyBusinessEntityAppJob({packageDirectory:extra.directory}),/officer files are forbidden/);await assert.rejects(runKentuckyBusinessEntityAppJob({packageDirectory:duplicate.directory}),/duplicate/);const link=path.join(packagesRoot,`test-link-${randomUUID()}`);try{await symlink(valid.directory,link,"junction");t.after(()=>rm(link,{recursive:true,force:true}));await assert.rejects(runKentuckyBusinessEntityAppJob({packageDirectory:link}),/real directory/);}catch(error){if(error.code!=="EPERM")throw error;}assert.deepEqual(new Set(await readdir(operationsRoot).catch(error=>error.code==="ENOENT"?[]:Promise.reject(error))),before);});
test("verification rejects tampering and app source contains no transport",async t=>{const pkg=await makePackage(),result=await runKentuckyBusinessEntityAppJob({packageDirectory:pkg.directory});t.after(()=>Promise.all([rm(pkg.directory,{recursive:true,force:true}),rm(result.operationDirectory,{recursive:true,force:true})]));await writeFile(path.join(result.operationDirectory,"release","organizations.jsonl"),"{}\n");await assert.rejects(verifyKentuckyBusinessEntityAppJob(result.receiptPath),/Independent replay/);const source=await readFile(new URL("./kentucky-business-entity-bulk-app.mjs",import.meta.url),"utf8");assert.doesNotMatch(source,/\bfetch\s*\(/);assert.match(source,/geocode_claim:false/);assert.match(source,/public_export_authorized:false/);});
