import assert from 'node:assert/strict';
import {readFile,unlink} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import test from 'node:test';
import contract from '../config/connectors/md-childcare-preflight.json' with {type:'json'};
import {APP_ROOT} from './paths.mjs';
import {acquireMdChildcarePreflight,validateMdChildcarePreflight,writeMdChildcarePreflight,MD_CHILDCARE_URLS} from './md-childcare-preflight.mjs';
const C=contract.source_contract,hash=v=>createHash('sha256').update(v).digest('hex');
function fixture(mutate=()=>{}){const calls=[];const item={id:C.item_id,owner:C.owner,orgId:C.organization_id,title:C.title,name:C.item_name,type:C.item_type,access:C.access,url:C.service_url,description:C.description,licenseInfo:C.licenseInfo,created:1745014272000,modified:1779911329000,numViews:1,properties:null,tags:['Childcare']};const layer={id:0,name:C.layer_name,type:'Feature Layer',description:'',serviceItemId:C.item_id,objectIdField:'OBJECTID',geometryType:'esriGeometryPoint',capabilities:'Query',maxRecordCount:2000,extent:{spatialReference:{wkid:102100,latestWkid:3857}},advancedQueryCapabilities:{supportsPagination:true,supportsStatistics:true,supportsOrderBy:true},editingInfo:{lastEditDate:1779911324252,schemaLastEditDate:1779911324252,dataLastEditDate:1779911324252},fields:C.fields};return {calls,item,options:{now:()=>new Date('2026-09-08T19:00:00.000Z'),fetchImpl:async(url,request)=>{const kind=Object.keys(MD_CHILDCARE_URLS).find(k=>MD_CHILDCARE_URLS[k]===url);assert.ok(kind);assert.equal(request.redirect,'error');assert.equal(request.credentials,'omit');calls.push(kind);const payload=structuredClone(kind==='item'?item:kind==='layer'?layer:{count:1772});const response=await mutate(payload,kind,calls);return response instanceof Response?response:Response.json(payload);}}};}
let evidence;
test('MD exact metadata/count sequence retains full notices and publishes independent immutable receipts',async()=>{
 const f=fixture((v,k,c)=>{if(k==='item'&&c.length===6)v.numViews++;});evidence=await acquireMdChildcarePreflight(f.options);assert.deepEqual(f.calls,['item','layer','count','count','layer','item']);assert.equal(evidence.source.record_count,1772);assert.equal(evidence.source.publisher_cohort_date,'2026-02-13');assert.deepEqual(evidence.observations[0].payload,f.item);assert.equal(evidence.readiness.acquisition_ready,false);assert.equal(evidence.claims.source_records_requested,0);assert.equal(evidence.claims.full_item_metadata_retained,true);
 const saved=[];try{for(let i=0;i<2;i++)saved.push(await writeMdChildcarePreflight(evidence));assert.notEqual(saved[0].path,saved[1].path);for(const s of saved){const raw=await readFile(s.path);assert.equal(hash(raw),s.sha256);assert.deepEqual(validateMdChildcarePreflight(JSON.parse(raw)),evidence);}}finally{for(const s of saved)await unlink(s.path);}
});
test('MD rejects item, schema, privacy, count, protocol and paired evidence drift without retries',async()=>{
 const scenarios=[(v,k)=>{if(k==='item')v.owner='other';},(v,k)=>{if(k==='item')v.licenseInfo=v.licenseInfo.slice(0,100);},(v,k)=>{if(k==='item')v.features=[];},(v,k)=>{if(k==='item')v.properties={owner:'PRIVATE'};},(v,k)=>{if(k==='layer')v.fields[0].type='esriFieldTypeString';},(v,k)=>{if(k==='layer')v.fields[1].name='USER_Facility_Name';},(v,k)=>{if(k==='layer')v.extent.spatialReference.latestWkid=4326;},(v,k)=>{if(k==='count')v.features=[{attributes:{Phone:'PRIVATE'}}];},(v,k)=>{if(k==='count')v.count=20001;},(v,k,c)=>{if(k==='count'&&c.length===4)v.count++;},(v,k,c)=>{if(k==='layer'&&c.length===5)v.editingInfo.dataLastEditDate++;},(_v,k)=>{if(k==='item')return Response.json({error:{code:499}});},()=>new Response('PRIVATE',{status:429}),()=>new Response('x',{headers:{'content-type':'application/json','content-length':'2000001'}}),()=>new Response(Uint8Array.of(255),{headers:{'content-type':'application/json'}})];
 for(const key of ['error','features','objectIds','attributes','geometry'])scenarios.push((v,k)=>{if(k==='layer')v[key]=null;});
 scenarios.push((v,k)=>{if(k==='layer')v.editingInfo.dataLastEditDate=Date.parse('2027-01-01T00:00:00Z');});
 await Promise.all(scenarios.map(async mutate=>{const f=fixture(mutate);await assert.rejects(acquireMdChildcarePreflight(f.options),e=>!e.message.includes('PRIVATE'));assert.ok(f.calls.length<=6);}));
});
test('MD semantic replay rejects rehashed unsafe receipts and writer option bypasses',async()=>{
 assert.ok(evidence);for(const change of [e=>{e.observations[0].payload.licenseInfo+='changed';},e=>{e.observations[2].payload.count++;},e=>{e.observations[1].payload.fields[0].nullable=true;},e=>{e.claims.current_operations_verified=true;},e=>{e.source.publisher_cohort_date='2026-09-08';}]){const e=structuredClone(evidence);change(e);for(const o of e.observations)o.payload_sha256=hash(JSON.stringify(o.payload));assert.throws(()=>validateMdChildcarePreflight(e));await assert.rejects(writeMdChildcarePreflight(e));}
 await assert.rejects(writeMdChildcarePreflight(evidence,{outputRoot:APP_ROOT}));await assert.rejects(writeMdChildcarePreflight(evidence,{signal:AbortSignal.abort()}),{name:'AbortError'});
});
test('MD cancellation stops noncooperative headers, streaming bodies and pacing',async()=>{
 await Promise.all(['header','body','pacing'].map(async mode=>{const c=new AbortController();let late,cancelled=0;const f=fixture(()=>{if(mode==='header'){c.abort();return new Promise(resolve=>{late=resolve;});}if(mode==='body')return new Response(new ReadableStream({start(s){s.enqueue(new TextEncoder().encode('{'));setImmediate(()=>c.abort());},cancel(){cancelled++;}}),{headers:{'content-type':'application/json'}});setImmediate(()=>c.abort());});await assert.rejects(acquireMdChildcarePreflight({...f.options,signal:c.signal}),{name:'AbortError'});if(late){late(new Response(new ReadableStream({cancel(){cancelled++;}})));await new Promise(resolve=>setImmediate(resolve));}if(mode!=='pacing')assert.equal(cancelled,1);assert.equal(f.calls.length,1);}));
 const f=fixture();await assert.rejects(acquireMdChildcarePreflight({...f.options,signal:AbortSignal.abort()}));await assert.rejects(acquireMdChildcarePreflight({...f.options,url:'https://example.invalid'}));assert.equal(f.calls.length,0);
});
test('MD CLI rejects caller scope or endpoints without source requests',async()=>{for(const args of [['--url','https://example.invalid'],['--state','MD'],['--output','outside']])await assert.rejects(promisify(execFile)(process.execPath,['scripts/preflight-md-childcare.mjs',...args],{cwd:APP_ROOT,windowsHide:true}));});
test('MD offline replay binds imported contract and rejects rehashed layer payloads and future clocks',()=>{
 for(const key of ['error','features','objectIds','attributes','geometry','future-clock']){const e=structuredClone(evidence);for(const o of e.observations.filter(o=>o.kind==='layer')){if(key==='future-clock')o.payload.editingInfo.dataLastEditDate=Date.parse('2027-01-01T00:00:00Z');else o.payload[key]=null;o.payload_sha256=hash(JSON.stringify(o.payload));}assert.throws(()=>validateMdChildcarePreflight(e));}
 const before=contract.source_contract.licenseInfo;try{contract.source_contract.licenseInfo='modified';assert.throws(()=>validateMdChildcarePreflight(evidence));}finally{contract.source_contract.licenseInfo=before;}assert.equal(validateMdChildcarePreflight(evidence),evidence);
});
