import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import test from 'node:test';
import {acquireMdChildcareWithTransport,acquireMdChildcareNative,replayMdChildcareAcquisition,mdChildcarePageUrl} from './md-childcare-acquisition.mjs';
import {createMdChildcareFixture} from './md-childcare-test-fixtures.mjs';
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');let evidence;
test('MD explicit transport, hooks, safe batches and preabort reject before requests',async()=>{
 let n=0;const f=createMdChildcareFixture();f.options.fetchImpl=async()=>{n++;throw Error('unexpected');};for(const options of [{...f.options,url:'https://example.invalid'},{...f.options,fetchImpl:undefined},{...f.options,retainPrerequisite:undefined}])await assert.rejects(acquireMdChildcareWithTransport(options));await assert.rejects(acquireMdChildcareNative(f.options));await assert.rejects(acquireMdChildcareWithTransport({...f.options,signal:AbortSignal.abort()}),{name:'AbortError'});assert.equal(n,0);assert.throws(()=>mdChildcarePageUrl(Array(101).fill(1)));
});
test('MD synthetic acquisition preserves null points and repeated licenses across exact100 ID batches',async()=>{
 const f=createMdChildcareFixture({count:101,mutate:(p,k)=>{if(k==='page'&&p.features[0].attributes.OBJECTID===1)p.features[1].geometry={x:999,y:999};}});evidence=await acquireMdChildcareWithTransport(f.options);const replay=await replayMdChildcareAcquisition(evidence);assert.equal(replay.features.length,101);assert.equal(replay.features[0].geometry,null);assert.deepEqual(replay.features[1].geometry,{x:999,y:999});assert.equal(replay.features[0].attributes.Street_Address,null);assert.equal(replay.features[0].attributes.License_Number,replay.features[1].attributes.License_Number);assert.equal(f.calls.filter(c=>c.kind==='page').length,2);assert.equal(evidence.transport.requests,16);assert.deepEqual(f.persisted,['prerequisite','baseline-ids','page','page','final-ids']);assert.equal(replay.source.publisher_cohort_date,'2026-02-13');
 for(const c of f.calls.filter(c=>['page','baseline-ids','final-ids'].includes(c.kind)))assert.equal(new URL(c.url).searchParams.get('where'),"Provider_Type='Child Care Center'");
});
test('MD rejects private fields, membership, partial geometry, CRS, truncation and drift',async()=>{
 const changes=[(p,k)=>{if(k==='page')p.features[0].attributes.Phone='PRIVATE';},(p,k)=>{if(k==='page')p.features[0].attributes.Facility_Name={owner:'PRIVATE'};},(p,k)=>{if(k==='page')p.features[0].attributes.Provider_Type='Family Child Care';},(p,k)=>{if(k==='page')p.features[0].attributes.OBJECTID=999;},(p,k)=>{if(k==='page')p.features[0].geometry={x:1};},(p,k)=>{if(k==='page')p.features[0].geometry={x:1,y:2,spatialReference:{wkid:3857}};},(p,k)=>{if(k==='page')p.spatialReference.wkid=3857;},(p,k)=>{if(k==='page')p.exceededTransferLimit=true;},(p,k)=>{if(k==='final-ids')p.objectIds[0]=999;},(p,k)=>{if(k==='baseline-ids')p.objectIds[1]=p.objectIds[0];},(_p,k)=>{if(k==='page')return new Response('PRIVATE',{status:429});}];
 await Promise.all(changes.map(async mutate=>{const f=createMdChildcareFixture({mutate});await assert.rejects(acquireMdChildcareWithTransport(f.options),e=>!e.message.includes('PRIVATE'));}));
 await Promise.all([()=>new Response(Uint8Array.of(255),{headers:{'content-type':'application/json'}}),()=>new Response('[]',{headers:{'content-type':'application/json','content-length':'999999999'}}),()=>Response.json({error:{code:499}})].map(mutate=>assert.rejects(acquireMdChildcareWithTransport(createMdChildcareFixture({mutate}).options))));
 for(const mutate of changes.slice(0,8)){const e=structuredClone(evidence);for(const o of e.observations){mutate(o.payload,o.kind);o.payload_sha256=hash(o.payload);}await assert.rejects(replayMdChildcareAcquisition(e));}
 for(const mutate of [p=>{p.fields[1].length=1;},p=>{p.fields[1].alias={owner:'PRIVATE'};},p=>{p.uniqueIdField.isSystemMaintained=false;},p=>{p.spatialReference.latestWkid=3857;}]){const e=structuredClone(evidence);const o=e.observations.find(o=>o.kind==='page');mutate(o.payload);o.payload_sha256=hash(o.payload);await assert.rejects(replayMdChildcareAcquisition(e));}
});
test('MD cancellation drains hooks and cancels noncooperative transport',async()=>{
 const c=new AbortController();let enter,release;const entered=new Promise(r=>{enter=r;});const f=createMdChildcareFixture({prerequisite:async()=>{c.abort();enter();await new Promise(r=>{release=r;});}});let settled=false;const pending=acquireMdChildcareWithTransport({...f.options,signal:c.signal});pending.catch(()=>{settled=true;});await entered;await new Promise(r=>setImmediate(r));assert.equal(settled,false);release();await assert.rejects(pending,{name:'AbortError'});assert.equal(f.calls.filter(c=>c.kind==='baseline-ids').length,0);
 const a=new AbortController();let late,cancelled=0;const g=createMdChildcareFixture({mutate:()=>{a.abort();return new Promise(r=>{late=r;});}});await assert.rejects(acquireMdChildcareWithTransport({...g.options,signal:a.signal}),{name:'AbortError'});late(new Response(new ReadableStream({cancel(){cancelled++;}})));await new Promise(r=>setImmediate(r));assert.equal(cancelled,1);
});
