import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import test from 'node:test';
import {normalizeMdChildcareFeature,normalizeMdChildcareAcquisition} from './md-childcare-normalization.mjs';
import {acquireMdChildcareWithTransport} from './md-childcare-acquisition.mjs';
import {createMdChildcareFixture} from './md-childcare-test-fixtures.mjs';
import {assertNormalizedUsPostalFieldsDeep} from './normalized-us-postal-code.mjs';
const c={runId:'fixture-run',sourceReleaseId:'fixture-release',observedAt:'2026-09-08T19:00:00.000Z',processedAt:'2026-09-08T20:00:00.000Z',sourceUpdatedAt:new Date(1779911329000).toISOString(),sourceEditingInfo:{lastEditDate:1779911324252,schemaLastEditDate:1779911324252,dataLastEditDate:1779911324252}};
const ctx={runId:c.runId,sourceReleaseId:c.sourceReleaseId,processedAt:c.processedAt},hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const feature=()=>({attributes:{OBJECTID:1,Provider_Type:'Child Care Center',Facility_Name:' Center ',DBA_Name:' Alias ',License_Number:'00012',Street_Address:'123 Main Street',City:'Baltimore',State:'MD',Zip_Code:21201},geometry:{x:-76.6,y:39.3}});
test('MD source candidate preserves exact sparse inputs and dated lineage without identity claims',()=>{
 const f=feature(),r=normalizeMdChildcareFeature(f,c);assertNormalizedUsPostalFieldsDeep(r);assert.equal(r.business_name,'Center');assert.equal(r.dba_name,'Alias');assert.equal(r.reported_address.zip_code,'21201');assert.equal(r.reported_address.postal_code,'21201');assert.equal(r.reported_address.zip4,null);assert.equal(r.geocode.latitude,39.3);assert.equal(r.geocode.longitude,-76.6);assert.equal(Object.hasOwn(r,'geometry'),false);assert.deepEqual(r.source.selected_attributes,f.attributes);assert.deepEqual(r.source.point_geometry,f.geometry);assert.equal(r.provenance.input_feature_sha256,hash(f));assert.equal(r.provenance.publisher_cohort_date,'2026-02-13');assert.deepEqual(r.provenance.source_editing_info,c.sourceEditingInfo);assert.equal(r.provenance.source_updated_at,c.sourceUpdatedAt);assert.equal(r.provenance.observed_at,c.observedAt);assert.equal(r.provenance.processed_at,c.processedAt);assert.equal(r.external_identifiers[0].value,'00012');assert.ok(Object.values(r.claims).every(v=>v===false));
 const sparse={attributes:{OBJECTID:2,Provider_Type:'Child Care Center'}};const n=normalizeMdChildcareFeature(sparse,c);assert.deepEqual(n.source.selected_attributes,sparse.attributes);assert.equal(Object.hasOwn(n.source,'point_geometry'),false);assert.equal(n.reported_address.state,null);assert.equal(n.quality.state_unavailable_reason,'missing-source-state');assert.equal(n.quality.license_unavailable_reason,'missing-source-license');assert.equal(n.business_name,null);
});
test('MD integer postal conversion preserves leading zeroes and distinct invalid gaps',()=>{
 for(const [value,zip,reason]of [[100,'00100',null],[1,'00001',null],[99999,'99999',null],[0,null,'invalid-source-zip-placeholder'],[-1,null,'invalid-source-zip-range'],[100000,null,'invalid-source-zip-range'],[null,null,'missing-source-zip']]){const f=feature();f.attributes.Zip_Code=value;const r=normalizeMdChildcareFeature(f,c);assert.equal(r.reported_address.zip_code,zip);assert.equal(r.reported_address.zip4,null);assert.equal(r.quality.zip_unavailable_reason,reason);assert.equal(r.quality.zip4_unavailable_reason,'source-zip4-not-provided');}
});
test('MD invalid or missing points become gaps, structural point errors and private fields reject',()=>{
 for(const [point,reason]of [[null,'missing-source-point'],[{x:0,y:0},'source-point-zero-location'],[{x:999,y:999},'source-point-out-of-range']]){const r=normalizeMdChildcareFeature({...feature(),geometry:point},c);assert.equal(r.geocode.latitude,null);assert.equal(r.geocode.longitude,null);assert.equal(r.quality.point_unavailable_reason,reason);assert.deepEqual(r.source.point_geometry,point);}
 for(const point of [{x:1},{x:null,y:2},{x:{owner:'PRIVATE'},y:2},{x:1,y:2,spatialReference:{wkid:3857}}])assert.throws(()=>normalizeMdChildcareFeature({...feature(),geometry:point},c),{code:'MD_CHILDCARE_RECORD_REJECTED'});
 for(const change of [f=>{f.attributes.Phone='PRIVATE';},f=>{f.attributes.Facility_Name={owner:'PRIVATE'};},f=>{f.attributes.Zip_Code='21201';},f=>{f.attributes.Provider_Type='Family Child Care';}]){const f=feature();change(f);assert.throws(()=>normalizeMdChildcareFeature(f,c),e=>e.code==='MD_CHILDCARE_RECORD_REJECTED'&&!e.message.includes('PRIVATE'));}
 const f=feature();f.attributes.State='PA';f.attributes.Street_Address='PO Box 123';const r=normalizeMdChildcareFeature(f,c);assert.equal(r.reported_address.state,'PA');assert.equal(r.quality.state_scope_conflict,true);assert.equal(r.quality.address_unavailable_reason,'source-po-box-or-nonstreet-label');
});
test('MD chronology, options and cancellation reject independently',async()=>{
 for(const context of [{...c,processedAt:'2000-01-01T00:00:00.000Z'},{...c,sourceEditingInfo:{...c.sourceEditingInfo,lastEditDate:Date.parse('2027-01-01')}},{...c,runId:'../escape'}])assert.throws(()=>normalizeMdChildcareFeature(feature(),context));await assert.rejects(normalizeMdChildcareAcquisition({},ctx,{signal:AbortSignal.abort()}),{name:'AbortError'});await assert.rejects(normalizeMdChildcareAcquisition({},ctx,{url:'https://example.invalid'}));
});
test('MD bulk normalization conserves candidates and byte-limit quarantine with immutable evidence snapshot',async()=>{
 const fixture=createMdChildcareFixture({count:3,mutate:(p,k)=>{if(k==='page'){p.features[1].attributes.State='PA';for(const field of ['Facility_Name','DBA_Name','Street_Address','City'])p.features[2].attributes[field]='x'.repeat(8000);}}});const evidence=await acquireMdChildcareWithTransport(fixture.options);const r=await normalizeMdChildcareAcquisition(evidence,ctx);assert.equal(r.records.length,2);assert.equal(r.quarantine.length,1);assert.equal(r.summary.source_records,3);assert.equal(r.quarantine[0].reason,'normalized-record-byte-limit');assert.equal(r.summary.accepted_with_points,1);assert.equal(r.records[1].reported_address.state,'PA');assert.equal(r.summary.accepted_with_state_scope_conflict,1);assert.equal(r.summary.address_unavailable_reasons['missing-source-address'],1);assert.equal(JSON.stringify(r.quarantine).includes('x'.repeat(100)),false);assert.equal(r.records[0].external_identifiers[0].value,r.records[1].external_identifiers[0].value);assert.notEqual(r.records[0].source_record_id,r.records[1].source_record_id);
 const e=structuredClone(evidence),before=hash(e),pending=normalizeMdChildcareAcquisition(e,ctx);e.observations.find(o=>o.kind==='page').observed_at='2026-09-08T19:30:00.000Z';const result=await pending;assert.equal(result.summary.acquisition_evidence_sha256,before);assert.equal(result.records[0].provenance.observed_at,c.observedAt);const controller=new AbortController(),cancelled=normalizeMdChildcareAcquisition(evidence,ctx,{signal:controller.signal});setImmediate(()=>controller.abort());await assert.rejects(cancelled,{name:'AbortError'});
});
