import test from 'node:test';import assert from 'node:assert/strict';
import {projectMnConstructionExactZipEvidence as project,verifyMnConstructionExactZipAdmission as verify} from './mn-construction-exact-zip-evidence.mjs';
import {projectMnConstructionCredential} from './mn-construction-credential-reporting.mjs';

const source={release_id:'fixture',manifest_sha256:'a'.repeat(64),artifact_sha256:'b'.repeat(64)};
const row=(id,zip5,zip4=null,category='residential-roofer')=>projectMnConstructionCredential({schema_version:'1.0.0',dataset_id:'mn-dli-construction-business-credentials',source_record_id:`fixture:residential:row:${id}`,business_name:'Fixture LLC',dba_name:null,external_identifiers:[{type:'minnesota_dli_construction_credential',value:`RR${String(id).padStart(6,'0')}`}],credential:{kind:'license',category,status_source:'Issued',active_credential_basis:'publisher-status-at-observation',active_business_verified:false,original_date_source:null,expiration_date_source:null,date_semantics:'unparsed-publisher-values-not-business-lifecycle'},reported_address:{street:'1 Main',street2:null,city:'Town',state:'MN',country:'US',country_basis:'recognized-source-state-code-not-boundary-validation',zip_code:zip5,postal_code:zip5,zip4,address_role:'publisher-reported-role-unresolved',physical_location_verified:false},geocode:{latitude:null,longitude:null,status:'not-provided-by-source',address_role:'unresolved'},industry:{category:'construction',naics_code:null,basis:'credential-program-not-verified-establishment-classification'},affiliation:{parent_company:null,ownership_verified:false},provenance:{source_url:'https://secure.doli.state.mn.us/ccld/data/MNDLILicRegCertExport_Residential_Contractors.csv',source_release_id:'fixture',source_file_sha256:'c'.repeat(64),source_row_number:Number(id),selected_fields_sha256:'d'.repeat(64),ingest_run_id:'fixture',observed_at:'2026-09-08T13:11:41.678Z',transformation_version:'mn-construction-normalization@1.0.0',attribution:'Minnesota Department of Labor and Industry, Construction Codes and Licensing Division'},quality:{unique_business_identity_verified:false,current_usps_validity:'unverified',geographic_boundary_verified:false,postal_status:zip5===null?'missing':'format-only',physical_site_eligible:false,matching_eligible:false},export_policy:'local-review-only'});
test('projects nonadditive ZIP5 evidence and conserves missing and ZIP+4 separately',()=>{const p=project([row('1','55001','1234'),row('2','55001'),row('3',null)],{source,source_reference_at:'2026-09-08T13:11:41.678Z'});assert.equal(p.rows.length,1);assert.equal(p.rows[0].count,2);assert.equal(p.rows[0].zip4,null);assert.deepEqual(p.summary,{source_credential_rows:3,zip5_credential_rows:2,missing_reported_zip5_rows:1,reported_zip4_rows:1,positive_zip5_rows:1,projected_credential_rows:2});assert.equal(p.claims.current_operations_verified,false);assert.equal(p.claims.geocode_created,false);assert.equal(p.claims.all_business_completeness_percent,null);});
test('rejects duplicate identity and semantic inflation',()=>{const r=row('1','55001');assert.throws(()=>project([r,r],{source,source_reference_at:'2026-09-08T13:11:41.678Z'}));const inflated=structuredClone(r);inflated.record.quality.physical_site_eligible=true;assert.throws(()=>project([inflated],{source,source_reference_at:'2026-09-08T13:11:41.678Z'}));});
test('real retained admission replays immutable source and policy',async()=>{const result=await verify();assert.equal(result.status,'admission-ready-local-review-only');assert.equal(result.summary.source_credential_rows,11456);assert.equal(result.summary.zip5_credential_rows,11455);assert.equal(result.summary.missing_reported_zip5_rows,1);assert.equal(result.summary.reported_zip4_rows,0);assert.equal(result.claims.matrix_admission_performed,false);});
