import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {mnConstructionExactZipEvidenceStatusHttp} from './mn-construction-exact-zip-evidence-http.mjs';
import {readMnConstructionExactZipEvidenceStatus} from './mn-construction-exact-zip-evidence.mjs';

function exchange({method='GET',query='',headers={}}={}){const request=new EventEmitter();Object.assign(request,{method,headers,aborted:false,resume(){}});const response=new EventEmitter();Object.assign(response,{writableEnded:false,destroyed:false,headers:{},setHeader(k,v){this.headers[k]=v;}});const calls=[];const json=(res,status,value)=>{calls.push({status,value});res.writableEnded=true;};return{request,response,url:new URL(`http://127.0.0.1/api/business-map/mn-construction-exact-zip-evidence-status${query}`),json,calls};}

test('serves a bounded read-only exact-ZIP credential status envelope',async()=>{const x=exchange();await mnConstructionExactZipEvidenceStatusHttp(x.request,x.response,x.url,readMnConstructionExactZipEvidenceStatus,x.json);assert.equal(x.calls[0].status,200);assert.equal(x.calls[0].value.summary.source_credential_rows,11456);assert.equal(x.calls[0].value.summary.zip5_credential_rows,11455);assert.equal(x.calls[0].value.summary.positive_zip5_rows,961);assert.equal(x.calls[0].value.summary.missing_reported_zip5_rows,1);assert.equal(x.calls[0].value.summary.reported_zip4_rows,0);assert.equal(x.calls[0].value.claims.current_operations_verified,false);assert.equal(x.calls[0].value.claims.matrix_admission_performed,false);assert.equal(x.response.headers['Cache-Control'],'no-store');});
test('rejects methods, parameters, and request bodies before reading',async()=>{for(const options of[{method:'POST'},{query:'?zip=55101'},{headers:{'content-length':'1'}}]){const x=exchange(options);let read=false;await mnConstructionExactZipEvidenceStatusHttp(x.request,x.response,x.url,async()=>{read=true;},x.json);assert.equal(read,false);assert.equal(x.calls[0].status,400);}});
test('fails closed without leaking reader integrity details',async()=>{const x=exchange();await mnConstructionExactZipEvidenceStatusHttp(x.request,x.response,x.url,async()=>{throw Error('secret internal path and hash');},x.json);assert.deepEqual(x.calls,[{status:503,value:{error:'Minnesota construction exact-ZIP evidence status is unavailable or incompatible.'}}]);});
