import assert from 'node:assert/strict';
import { copyFile, mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import test from 'node:test';
import { APP_ROOT } from './paths.mjs';
import { buildNationalGoalCompletionMatrix, publishNationalGoalCompletionMatrix, verifyNationalGoalCompletionMatrix } from './national-goal-completion-matrix.mjs';
import { readNationalReportingCatalog } from './national-reporting-catalog.mjs';
import { BROAD_ORGANIZATION_SOURCES } from './broad-organization-evidence.mjs';
import { TEN_DIRECTORIES, TEN_VERSION } from './national-reporting-ten-catalog.mjs';

const states='AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY'.split(' ');
const source=(key,profile,sourceReleaseId=null,localReviewOnly=false)=>({schema_version:'1.0.0',view_type:'source',source_key:key,...(profile?{profile_source_id:profile}:{}),release_metadata:{source_release_id:sourceReleaseId??`release-${key}`,...(localReviewOnly?{record_level_distribution:'local-review-only'}:{}),...(key==='ak_active_business_licenses'?{source_observed_from:'2026-09-03T00:37:00Z',source_observed_through:'2026-09-03T00:37:03Z'}:{}),source_updated_at:'2026-09-01',source_rows_updated_at:'2026-09-01',source_modified_at:'2026-09-01'},zip_rows_with_contribution:4,zip_level_counts:{organization_address_count:10,provisional_physical_site_count:9},location_profile_geography:{profile_count:10,coordinate_assigned_single_count:5,latest_observed_at:'2026-09-01T00:00:00.000Z'},complete_source_for_all_businesses:false,lineage:{}});
async function deps(){const {catalog,sha256}=await readNationalReportingCatalog(),broad=Object.values(BROAD_ORGANIZATION_SOURCES),sources=[...catalog.sources.map(row=>source(row.sourceKey,row.profileId)),...broad.map(({sourceKey,profileSourceId,sourceReleaseId,localReviewOnly})=>source(sourceKey,profileSourceId,sourceReleaseId,localReviewOnly))],profileKeys=[...catalog.sources.filter(s=>s.profileId).map(s=>s.profileId),...broad.map(s=>s.sourceKey),...broad.flatMap(s=>s.profileSourceId?[s.profileSourceId]:[])];return{catalogReader:async()=>({catalog,sha256}),snapshotReader:async()=>({manifest:{},states:states.map((code,index)=>({postal_abbreviation:code,state_fips:String(index+1).padStart(2,'0'),state_name:code,is_50_states_or_dc:true,registry_evidence:{reported_address_profile_count:10,coordinate_assigned_profile_count:5,source_profile_counts_by_reported_address_state:Object.fromEntries(profileKeys.map(key=>[key,key==='alaska-dcced-active-business-licenses'&&code==='AK'?83_586:index===0?1:0]))}})),sources,evidence:{coverageReleaseId:'coverage-release',pointerSha256:'a'.repeat(64),manifestSha256:'b'.repeat(64),artifacts:{states:{sha256:'c'.repeat(64)},sources:{sha256:'d'.repeat(64)}}}}),irsReader:async()=>({status:'available',counts:Object.fromEntries(states.map((s,i)=>[s,i?0:1])),manifestSha256:'e'.repeat(64),summarySha256:'f'.repeat(64),sourceReleaseId:'irs-release'}),tenReader:async()=>({available:false,reason:'production-enrollment-absent'})};}
async function tenProjection(d){const {catalog}=await d.catalogReader();return{available:true,denominatorVersion:TEN_VERSION,exportPolicy:'local-review-only',allBusinessesPercent:null,mixedRecordUnitTotal:null,evidence:{coveragePointerSha256:'a'.repeat(64),coverageManifestSha256:'b'.repeat(64),enrollmentSha256:'1'.repeat(64),productionReceiptSha256:'2'.repeat(64),predecessorCatalogSha256:'3'.repeat(64)},states:states.map((code,index)=>({code,expected:10,datasets:[...catalog.sources.map(row=>({id:row.id,label:row.label,group:row.group,rowUnit:row.profileId?'location-profile records':'organization filing-address records',scope:row.scope,evidenceKind:'profile',sourceReleaseId:`release-${row.sourceKey}`,stateRecordCount:index?0:1,status:index?'no-state-records':'represented'})),...TEN_DIRECTORIES.map(row=>({id:row.id,label:row.label,group:row.group,rowUnit:row.rowUnit,scope:row.scope,evidenceKind:'directory',sourceReleaseId:`release-${row.id}`,sourceManifestSha256:row.manifestSha256,sourceDates:{released:'2026-08-26'},observedAt:'2026-09-12T00:00:00.000Z',stateRecordCount:index?0:row.stateDC,status:index?'no-state-records':'represented',geographicAssignmentPerformed:false,directoryDenominators:{allRetainedRows:row.all,stateDCRetainedRows:row.stateDC,territoryRows:row.territories,unknownStateRows:0},percentOfNationalDirectoryRows:index?0:row.stateDC/row.all*100,percentOfStateDCDirectoryRows:index?0:100,historicalAcquisitionFailed:row.id==='national-cms-nursing-homes'}))]}))};}

test('matrix distinguishes measured dataset availability from entirely unmeasured categories',async()=>{const d=await deps(),matrix=await buildNationalGoalCompletionMatrix({root:APP_ROOT,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-matrix',...d});assert.equal(matrix.schema_version,'national-goal-completion-matrix@1.1.0');assert.equal(matrix.jurisdictions.length,51);assert.equal(matrix.denominator.categories,8);assert.equal(matrix.all_business_completion_percent,null);for(const state of matrix.jurisdictions)for(const category of state.categories){assert.equal(category.all_business_completion_percent,null);assert.match(category.dataset_availability.measure,/measured-governed-dataset-presence/);assert.ok(category.datasets.every(row=>row.evidence.coverage_manifest_sha256==='b'.repeat(64)));}const al=matrix.jurisdictions[0],ak=matrix.jurisdictions[1],available=al.categories.find(c=>c.category_id==='retail-consumer').dataset_availability,unknown=al.categories.find(c=>c.category_id==='general-business').dataset_availability,zero=ak.categories.find(c=>c.category_id==='retail-consumer').dataset_availability;assert.equal(available.percent,100);assert.equal(available.measurement_status,'measured');assert.equal(unknown.available,0);assert.equal(unknown.measured,0);assert.equal(unknown.unmeasured,1);assert.equal(unknown.measurement_status,'unmeasured');assert.equal(unknown.percent,null);assert.equal(zero.available,0);assert.equal(zero.measured,zero.denominator);assert.equal(zero.measurement_status,'measured');assert.equal(zero.percent,0);});

test('geocode percentages preserve exact incomplete counts for FDIC and SNAP while availability keeps one decimal',async()=>{
  const d=await deps(),snapshotReader=async options=>{const snapshot=await d.snapshotReader(options);for(const row of snapshot.sources){if(row.source_key==='fdic_bankfind')row.location_profile_geography={profile_count:77285,coordinate_assigned_single_count:77272};if(row.source_key==='usda_snap_retailers')row.location_profile_geography={profile_count:252080,coordinate_assigned_single_count:252064};}return snapshot;};
  const matrix=await buildNationalGoalCompletionMatrix({root:APP_ROOT,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-geocode-precision',...d,snapshotReader});
  const dataset=id=>matrix.jurisdictions[0].categories.flatMap(category=>category.datasets).find(row=>row.dataset_id===id);
  for(const [id,assigned,eligible] of [['national-fdic-bankfind',77272,77285],['national-snap-retailers',252064,252080]]){
    const rate=dataset(id).geocode_rate;const expected=Number((BigInt(assigned)*100n*1_000_000_000_000n+BigInt(eligible)/2n)/BigInt(eligible))/1_000_000_000_000;
    assert.equal(rate.assigned,assigned);assert.equal(rate.eligible,eligible);assert.equal(rate.percent,expected);assert.ok(rate.percent<100);
  }
  for(const state of matrix.jurisdictions)for(const category of state.categories){const cell=category.dataset_availability;assert.equal(cell.percent,cell.measured===0?null:Math.round(cell.available/cell.measured*1000)/10);}
});

test('builder rejects impossible geocode counts and emits null percent for zero denominator',async()=>{
  const d=await deps(),run=async(profile_count,coordinate_assigned_single_count)=>{const snapshotReader=async options=>{const snapshot=await d.snapshotReader(options),row=snapshot.sources.find(item=>item.source_key==='fdic_bankfind');row.location_profile_geography={profile_count,coordinate_assigned_single_count};return snapshot;};return buildNationalGoalCompletionMatrix({root:APP_ROOT,createdAt:'2026-09-22T00:00:00.000Z',releaseId:`fixture-geocode-${profile_count}-${coordinate_assigned_single_count}`,...d,snapshotReader});};
  await assert.rejects(run(10,11),/assigned\/eligible counts are invalid/);await assert.rejects(run(-1,0),/assigned\/eligible counts are invalid/);await assert.rejects(run(Number.MAX_SAFE_INTEGER+1,0),/assigned\/eligible counts are invalid/);
  const matrix=await run(0,0),rate=matrix.jurisdictions[0].categories.flatMap(category=>category.datasets).find(row=>row.dataset_id==='national-fdic-bankfind').geocode_rate;assert.deepEqual({assigned:rate.assigned,eligible:rate.eligible,percent:rate.percent},{assigned:0,eligible:0,percent:null});
});

test('broad organization layers expose pinned policy evidence and never borrow jurisdiction geocodes',async()=>{const d=await deps(),matrix=await buildNationalGoalCompletionMatrix({root:APP_ROOT,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-broad-evidence',...d});for(const code of ['CO','CT','DE','FL','IA','NY','OR','PA','AK']){const dataset=matrix.jurisdictions.find(row=>row.code===code).categories.find(row=>row.category_id==='general-business').datasets[0];assert.equal(dataset.availability_status,'available');assert.equal(dataset.geocode_rate.status,'unmeasured-at-source-level');assert.equal(dataset.geocode_rate.percent,null);assert.equal(dataset.authorization.acquisition_authorized,false);assert.equal(dataset.broad_organization_evidence.state,code);assert.match(dataset.broad_organization_evidence.policy.sha256,/^[a-f0-9]{64}$/);if(code==='AK'){assert.equal(dataset.state_record_count,83_586);assert.equal(dataset.broad_organization_evidence.profile_source_id,'alaska-dcced-active-business-licenses');assert.equal(dataset.zip_contribution.rows,4);assert.match(dataset.row_unit,/organization-address evidence, separate from provisional site assertions/);}}});

test('Alaska broad licensing evidence is measured/available without making a completeness or site-count claim',async()=>{const d=await deps(),matrix=await buildNationalGoalCompletionMatrix({root:APP_ROOT,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-ak-transition',...d}),category=matrix.jurisdictions.find(row=>row.code==='AK').categories.find(row=>row.category_id==='general-business');assert.deepEqual(category.dataset_availability,{available:1,denominator:1,measured:1,unmeasured:0,measurement_status:'measured',percent:100,measure:'measured-governed-dataset-presence-not-business-completeness'});assert.equal(category.datasets[0].availability_status,'available');assert.equal(category.datasets[0].state_record_count,83_586);assert.equal(category.datasets[0].broad_organization_evidence.complete_all_businesses,false);assert.equal(category.datasets[0].broad_organization_evidence.geocode.percent,null);assert.equal(category.datasets[0].authorization.acquisition_authorized,false);});

test('valid ten-source enrollment adds both typed CMS directories together with exact proof hashes',async()=>{const d=await deps(),ten=await tenProjection(d),matrix=await buildNationalGoalCompletionMatrix({root:APP_ROOT,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-ten',...d,tenReader:async()=>ten});assert.equal(matrix.denominator.version,`${TEN_VERSION}+broad-jurisdiction-layer@1.1.0`);assert.equal(matrix.denominator.datasets,11);assert.equal(matrix.evidence.ten_source_enrollment_sha256,'1'.repeat(64));assert.equal(matrix.evidence.ten_source_production_receipt_sha256,'2'.repeat(64));for(const state of matrix.jurisdictions){const health=state.categories.find(row=>row.category_id==='health-care'),directories=health.datasets.filter(row=>row.directory_reporting);assert.equal(directories.length,2);for(const row of directories){assert.equal(row.all_business_completion_percent,undefined);assert.equal(row.directory_reporting.business_count,null);assert.equal(row.directory_reporting.physical_site_count,null);assert.equal(row.directory_reporting.national_completeness_percent,null);assert.equal(row.directory_reporting.geographic_assignment_performed,false);assert.equal(row.geocode_rate.percent,null);assert.equal(row.zip_contribution.rows,null);assert.equal(row.authorization.export_policy,'local-review-only');assert.match(row.evidence.source_manifest_sha256,/^[a-f0-9]{64}$/);}}});

test('only an explicitly absent ten-source enrollment preserves the eight-source reporting denominator with the nine-state broad layer',async()=>{const d=await deps(),options={root:APP_ROOT,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-fallback',...d},baseline=await buildNationalGoalCompletionMatrix({...options,tenReader:async()=>({available:false,reason:'production-enrollment-absent'})});assert.equal(baseline.denominator.datasets,9);assert.equal(baseline.denominator.version,'national-reporting-eight@1.0.0+broad-jurisdiction-layer@1.1.0');await assert.rejects(buildNationalGoalCompletionMatrix({...options,tenReader:async()=>({available:false,reason:'invalid-enrollment'})}),/invalid or stale/);await assert.rejects(buildNationalGoalCompletionMatrix({...options,tenReader:async()=>({available:true,denominatorVersion:TEN_VERSION,states:[]})}),/invalid or partial/);const partial=await tenProjection(d);partial.states[0].datasets.pop();await assert.rejects(buildNationalGoalCompletionMatrix({...options,tenReader:async()=>partial}),/invalid or partial/);await assert.rejects(buildNationalGoalCompletionMatrix({...options,tenReader:async()=>{throw Error('unreadable');}}),/could not be read safely/);const cancelled=Object.assign(Error('cancelled'),{name:'AbortError'});await assert.rejects(buildNationalGoalCompletionMatrix({...options,tenReader:async()=>{throw cancelled;}}),error=>error===cancelled);});

test('publisher is immutable and verifier rejects rehashed false geocode precision',async t=>{
  const root=await mkdtemp(path.join(APP_ROOT,'data/tmp/goal-matrix-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'data'),{recursive:true});
  for(const {policy} of Object.values(BROAD_ORGANIZATION_SOURCES)){const target=path.join(root,'config/source-policies',policy);await mkdir(path.dirname(target),{recursive:true});await copyFile(path.join(APP_ROOT,'config/source-policies',policy),target);}
  const d=await deps(),result=await publishNationalGoalCompletionMatrix({root,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-published',...d}),manifestPath=path.join(result.directory,'manifest.json');
  const verified=await verifyNationalGoalCompletionMatrix(manifestPath,{root,...d});assert.equal(verified.schema_version,'national-goal-completion-matrix@1.1.0');assert.equal(verified.network_requests,0);assert.equal(verified.production_pointers_changed,false);
  await assert.rejects(publishNationalGoalCompletionMatrix({root,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-published',...d}));await assert.rejects(readFile(path.join(root,'data/national-goal-completion-matrix/current.json')));
  const reportPath=path.join(result.directory,'report.json'),report=JSON.parse(await readFile(reportPath,'utf8')),fdic=report.jurisdictions.flatMap(state=>state.categories).flatMap(category=>category.datasets).find(dataset=>dataset.dataset_id==='national-fdic-bankfind');
  fdic.geocode_rate.percent=100;const reportBytes=Buffer.from(`${JSON.stringify(report,null,2)}\n`);await writeFile(reportPath,reportBytes);
  const manifest=JSON.parse(await readFile(manifestPath,'utf8'));manifest.artifacts[0].bytes=reportBytes.length;manifest.artifacts[0].sha256=createHash('sha256').update(reportBytes).digest('hex');await writeFile(manifestPath,`${JSON.stringify(manifest,null,2)}\n`);
  await assert.rejects(verifyNationalGoalCompletionMatrix(manifestPath,{root,...d}),/availability, geocode, or structural invariants are invalid/);
});

test('source replay detects semantic tamper and separates current-input drift',async t=>{
  const root=await mkdtemp(path.join(APP_ROOT,'data/tmp/goal-matrix-replay-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'data'),{recursive:true});
  for(const {policy} of Object.values(BROAD_ORGANIZATION_SOURCES)){const target=path.join(root,'config/source-policies',policy);await mkdir(path.dirname(target),{recursive:true});await copyFile(path.join(APP_ROOT,'config/source-policies',policy),target);}
  const d=await deps(),result=await publishNationalGoalCompletionMatrix({root,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-source-replay',...d}),manifestPath=path.join(result.directory,'manifest.json'),reportPath=path.join(result.directory,'report.json'),originalReport=structuredClone(result.report),originalManifest=structuredClone(result.manifest);
  const writeRelease=async(report,manifest=structuredClone(originalManifest))=>{const bytes=Buffer.from(`${JSON.stringify(report,null,2)}\n`);await writeFile(reportPath,bytes);manifest.artifacts[0].bytes=bytes.length;manifest.artifacts[0].sha256=createHash('sha256').update(bytes).digest('hex');await writeFile(manifestPath,`${JSON.stringify(manifest,null,2)}\n`);};
  const dataset=report=>report.jurisdictions[0].categories.find(row=>row.category_id==='retail-consumer').datasets[0],broad=report=>report.jurisdictions.find(row=>row.code==='AK').categories.find(row=>row.category_id==='general-business').datasets[0];
  const mutations=[
    report=>{dataset(report).state_record_count+=1;},report=>{dataset(report).temporal_status.status='tampered-status';},report=>{dataset(report).zip_contribution.rows+=1;},
    report=>{dataset(report).geocode_rate={assigned:4,eligible:10,percent:40,scope:'national-source-release'};},report=>{dataset(report).authorization.basis='tampered authorization';},
    report=>{dataset(report).gap_reason='tampered gap';},report=>{broad(report).broad_organization_evidence.policy.sha256='0'.repeat(64);}
  ];
  for(const mutate of mutations){const report=structuredClone(originalReport);mutate(report);await writeRelease(report);await assert.rejects(verifyNationalGoalCompletionMatrix(manifestPath,{root,...d}),error=>error.code==='GOAL_MATRIX_SEMANTIC_TAMPER');}
  const evidenceReport=structuredClone(originalReport),evidenceManifest=structuredClone(originalManifest);evidenceReport.evidence.coverage_pointer_sha256='9'.repeat(64);evidenceManifest.evidence=structuredClone(evidenceReport.evidence);await writeRelease(evidenceReport,evidenceManifest);await assert.rejects(verifyNationalGoalCompletionMatrix(manifestPath,{root,...d}),error=>error.code==='GOAL_MATRIX_EVIDENCE_REBUILD_REQUIRED');
  const createdManifest=structuredClone(originalManifest);createdManifest.created_at='2026-09-23T00:00:00.000Z';await writeRelease(originalReport,createdManifest);await assert.rejects(verifyNationalGoalCompletionMatrix(manifestPath,{root,...d}),error=>error.code==='GOAL_MATRIX_SEMANTIC_TAMPER');
  await writeRelease(originalReport);const driftSnapshot=async options=>{const snapshot=await d.snapshotReader(options);snapshot.evidence.pointerSha256='8'.repeat(64);return snapshot;};await assert.rejects(verifyNationalGoalCompletionMatrix(manifestPath,{root,...d,snapshotReader:driftSnapshot}),error=>error.code==='GOAL_MATRIX_EVIDENCE_REBUILD_REQUIRED');
});
