import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{runInNewContext}from'node:vm';import test from'node:test';import ts from'typescript';
const source=await readFile(new URL('../app/national-fdic-bankfind-coverage-status.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
function fixture(runnerJson){const slots=[],effects=[],cleanups=[];let index=0;const exports={};runInNewContext(code,{exports,AbortController,require:name=>name==='./runner-client'?{runnerJson}:name==='react'?{useState(initial){const i=index++;if(!(i in slots))slots[i]=initial;return[slots[i],next=>{slots[i]=typeof next==='function'?next(slots[i]):next}]},useEffect(effect){index++;effects.push(effect)}}:name==='react/jsx-runtime'?{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props}),Fragment:'fragment'}:{}});return{mount(){this.render();for(const effect of effects.splice(0))cleanups.push(effect())},unmount(){for(const cleanup of cleanups.splice(0))cleanup?.()},render(){index=0;return exports.default()}}}
const nodes=tree=>!tree||typeof tree!=='object'?[]:Array.isArray(tree)?tree.flatMap(nodes):[tree,...nodes(tree.props?.children)],textOf=tree=>typeof tree==='string'?tree:Array.isArray(tree)?tree.map(textOf).join(' '):tree&&typeof tree==='object'?textOf(tree.props?.children):'',settle=()=>new Promise(resolve=>setTimeout(resolve,5));
const view=()=>({available:true,release:{release_id:'fdic-r1'},product_label:'FDIC-insured active institutions and current indexed offices',coverage:{active_institutions:4238,current_indexed_offices:77285,source_locations:78087,foreign_location_exclusions:802,jurisdiction_rows:58,positive_zip5_rows:18018,zip5_union_rows:37856,denominator_only_zip5_rows:19838,reported_zip4_count:0,retained_coordinate_count:77283,missing_coordinate_count:2,record_zcta_count:77139,record_nonpolygon_count:146,positive_source_zip_outside_zbp_zcta:28,main_office_count:4235,active_institutions_without_accepted_office:3},claims:{},inclusion:{generic_business_totals:false,generic_entity_totals:false,generic_site_totals:false,generic_category_totals:false,generic_exports:false,production_enrollment:false,status:'excluded-non-additive-governed-layer'}});
test('FDIC panel renders separate aggregates, warnings, and no controls',async()=>{const f=fixture(async(url,options)=>{assert.equal(url,'/api/data-operations/national-fdic-bankfind-coverage-status');assert.ok(options.signal);return view()});f.mount();await settle();const tree=f.render(),text=textOf(tree);for(const expected of['4,238','77,285','802','18,018','19,838','77,283','2','28','different units','not all banks','FDIC attribution'])assert.match(text,new RegExp(expected,'i'));assert.equal(nodes(tree).filter(node=>['button','input','select'].includes(node.type)).length,0)});
test('FDIC panel rejects stale completion and clears cached evidence on failure',async()=>{let resolve,signal;const stale=fixture((_url,options)=>new Promise(done=>{resolve=()=>done(view());signal=options.signal}));stale.mount();stale.unmount();assert.equal(signal.aborted,true);resolve();await settle();assert.doesNotMatch(textOf(stale.render()),/77,285|fdic-r1/);let reject;const failed=fixture(()=>new Promise((_done,no)=>{reject=no}));failed.mount();reject(new Error('fail'));await settle();assert.match(textOf(failed.render()),/No cached evidence/)});
test('Data Operations includes separate FDIC status',async()=>{const data=await readFile(new URL('../app/data-operations.tsx',import.meta.url),'utf8');assert.match(data,/import NationalFdicBankfindCoverageStatus/);assert.match(data,/<NationalFdicBankfindCoverageStatus \/>/)});
test('exact ZIP Business Intelligence renders separate FDIC office evidence',async()=>{const data=await readFile(new URL('../app/business-intelligence.tsx',import.meta.url),'utf8');for(const expected of[/fdic_bankfind_office_evidence/,/FDIC-insured institution office evidence/,/Current indexed offices/,/Bounded service-type codes/,/Separate institution classifications/,/No website endorsement/,/not all banks, credit unions, financial businesses/])assert.match(data,expected)});
