import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { link, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { buildNationalZipBusinessEvidenceAlignment, publishNationalZipBusinessEvidenceAlignment, verifyNationalZipBusinessEvidenceAlignment } from "./national-zip-business-evidence-alignment.mjs";

const sha = value => createHash("sha256").update(value).digest("hex");
const stable = value => `${JSON.stringify(value, null, 2)}\n`;
const member = values => sha(values.length ? `${[...values].sort().join("\n")}\n` : "");
async function put(file, value) { await mkdir(path.dirname(file), { recursive: true }); const text = typeof value === "string" ? value : `${JSON.stringify(value)}\n`; await writeFile(file, text); return { bytes: Buffer.byteLength(text), sha256: sha(text) }; }

async function fixture(t) {
  const root = await mkdtemp(path.join(os.tmpdir(), "zip-business-alignment-")); t.after(() => rm(root, { recursive: true, force: true }));
  const zips = ["10001", "10002", "10003"], geo = "geo-r1";
  const summary = { schema_version: "national-zip-coverage-summary@1.0.0", dataset_id: "national-zip-coverage-summary", release_id: "national-zip-coverage-20260922000000-abcdef12", created_at: "2026-09-22T00:00:00.000Z", projection_mode: "immutable-release",
    bindings: { census_zcta_source_release_id: geo, census_zcta_member_set_sha256: member(zips.slice(0, 2)), registry_dataset_id: "national-business-registry", registry_release_id: "registry-r1", registry_manifest_sha256: "b".repeat(64), registry_publisher_version: "2.15.0" }, registry_zip5: { members: { count: 3, member_set_sha256: member(zips) }, record_level_source_contribution: { count: 2, member_set_sha256: member(zips.slice(0, 2)) }, denominator_only_no_record_level_contribution: { count: 1, member_set_sha256: member(zips.slice(2)) } },
    census_zcta: { same_code_governed_zcta_members: { count: 2, member_set_sha256: member(zips.slice(0, 2)) } }, usps_assignment: { governed_dependency_present: false, registry_unverified_members: { count: 3 } }, claim_boundary: { all_business_completion_percentage: null, active_business_completion_percentage: null } };
  const smDir = path.join(root, "data", "national-zip-coverage-summary", "releases", summary.release_id), sa = await put(path.join(smDir, "zip-coverage-summary.json"), stable(summary));
  const sm = { schema_version: "national-zip-coverage-summary@1.0.0", dataset_id: "national-zip-coverage-summary", release_id: summary.release_id, created_at: summary.created_at, status: "published-local-derived-report", network_requests: 0, production_pointers_changed: false, evidence: summary.bindings, artifacts: [{ path: "zip-coverage-summary.json", artifact_type: "national-zip-coverage-summary-json", record_count: 1, distribution_policy: "local-review-only", ...sa }] }; const smd = await put(path.join(smDir, "manifest.json"), sm);
  const published = { status: "published", source_id: "census-zbp-2023", reference_year: 2023, establishments: 5, provenance: { source_release_id: "census-zbp-2023" } };
  const missing = { status: "not-published-for-zip", source_id: "census-zbp-2023", reference_year: 2023, establishments: null, employment: null, annual_payroll_thousands_usd: null, first_quarter_payroll_thousands_usd: null, provenance: { source_release_id: "census-zbp-2023" } };
  const coverageRows = [
    { zip_code: "10001", complete_all_businesses: false, registry_coverage: { status: "record-level-source-contribution", complete_all_businesses: false }, spatial_zip_polygon_membership: { status: "included", geography_release_id: geo }, baseline_coverage_status: "zbp-and-zcta", employer_baseline: published },
    { zip_code: "10002", complete_all_businesses: false, registry_coverage: { status: "record-level-source-contribution", complete_all_businesses: false }, spatial_zip_polygon_membership: { status: "included", geography_release_id: geo }, baseline_coverage_status: "zcta-without-published-zbp", employer_baseline: missing },
    { zip_code: "10003", complete_all_businesses: false, registry_coverage: { status: "denominator-only-no-record-level-contribution", complete_all_businesses: false }, spatial_zip_polygon_membership: { status: "not-in-denominator", geography_release_id: geo }, baseline_coverage_status: "not-observed-in-integrated-census-coverage-union", employer_baseline: null },
  ];
  const cDir = path.join(root, "coverage", "releases", "coverage-r1"), ca = await put(path.join(cDir, "zips.jsonl"), coverageRows.map(JSON.stringify).join("\n") + "\n");
  const cm = { schema_version: "1.0.0", dataset_id: "national-business-coverage-views", release_id: "coverage-r1", status: "published-partial-local-aggregate", publisher: { id: "national-business-coverage-views", version: "2.11.0" }, dependencies: [{ dataset_id: "national-business-registry", release_id: "registry-r1", manifest_sha256: "b".repeat(64), publisher_version: "2.15.0" }], artifacts: [{ path: "zips.jsonl", artifact_type: "zip-coverage-view-jsonl", record_count: 3, export_policy: "local-review-only", ...ca }] }; const cmd = await put(path.join(cDir, "manifest.json"), cm);
  const cp = await put(path.join(root, "coverage", "current.json"), { dataset_id: cm.dataset_id, release_id: "coverage-r1", manifest: "releases/coverage-r1/manifest.json", updated_at: "2026-09-22T00:00:00.000Z" });
  const zbpRows = [{ zip_code: "10001", coverage_status: "zbp-and-zcta", geography: { status: "2020-zcta-polygon-available" }, employer_baseline: published }, { zip_code: "10002", coverage_status: "zcta-without-published-zbp", geography: { status: "2020-zcta-polygon-available" }, employer_baseline: missing }];
  const zDir = path.join(root, "zbp", "releases", "zbp-r1"), za = await put(path.join(zDir, "zips.jsonl"), zbpRows.map(JSON.stringify).join("\n") + "\n");
  const gDir = path.join(root, "geography", "releases", geo), ga = await put(path.join(gDir, "derived/index/zctas.jsonl"), zips.slice(0, 2).map(zip => JSON.stringify({ geo_type: "zcta", geoid: zip, zcta: zip, geo_id: `zcta:${zip}` })).join("\n") + "\n");
  const gm = { schema_version: "1.0.0", dataset_id: "us-census-geography", release_id: geo, status: "published", complete_national_release: true, artifacts: [{ path: "derived/index/zctas.jsonl", artifact_type: "normalized-index", record_count: 2, ...ga }] }, gmd = await put(path.join(gDir, "manifest.json"), gm);
  const gp = await put(path.join(root, "geography", "current.json"), { dataset_id: gm.dataset_id, release_id: geo, manifest: `releases/${geo}/manifest.json`, updated_at: "2026-09-22T00:00:00.000Z" });
  const zm = { schema_version: "1.0.0", dataset_id: "census-zbp-baseline", release_id: "zbp-r1", status: "published", reference_year: 2023, complete_national_release: true, coverage: { union_zip_codes: 2 }, geography_dependency: { dataset_id: gm.dataset_id, release_id: geo, manifest_sha256: gmd.sha256 }, artifacts: [{ path: "zips.jsonl", artifact_type: "zip-coverage-union-jsonl", record_count: 2, ...za }] }; const zmd = await put(path.join(zDir, "manifest.json"), zm);
  const zp = await put(path.join(root, "zbp", "current.json"), { dataset_id: zm.dataset_id, release_id: "zbp-r1", manifest: "releases/zbp-r1/manifest.json", updated_at: "2026-09-22T00:00:00.000Z" });
  const enrollment = { schema_version: "national-zip-business-evidence-alignment-enrollment@1.0.0", zip_summary_manifest_path: path.relative(root, path.join(smDir, "manifest.json")), zip_summary_manifest_sha256: smd.sha256, zip_summary_artifact_sha256: sa.sha256,
    coverage_pointer_path: "coverage/current.json", coverage_pointer_sha256: cp.sha256, coverage_manifest_sha256: cmd.sha256, zbp_pointer_path: "zbp/current.json", zbp_pointer_sha256: zp.sha256, zbp_manifest_sha256: zmd.sha256,
    geography_pointer_path: "geography/current.json", geography_pointer_sha256: gp.sha256, geography_manifest_sha256: gmd.sha256 };
  return { root, enrollment, coverageRows, coveragePath: path.join(cDir, "zips.jsonl"), coverageManifest: path.join(cDir, "manifest.json") };
}
const args = f => ({ root: f.root, enrollment: f.enrollment, releaseId: "national-zip-business-alignment-20260923000000-abcdef12", createdAt: "2026-09-23T00:00:00.000Z" });
test("build conserves exact retained ZIP, ZBP, and ZCTA classes without arrays", async t => { const f = await fixture(t), r = await buildNationalZipBusinessEvidenceAlignment(args(f)); assert.equal(r.zip_member_alignment.exact_match, true); assert.equal(r.employer_baseline.published.count, 1); assert.equal(r.employer_baseline.not_published_for_zip.count, 1); assert.equal(r.employer_baseline.outside_zbp_zcta_union.count, 1); assert.equal(r.claim_boundary.active_business_completion_percentage, null); assert.equal((function a(v){return Array.isArray(v)||Boolean(v&&typeof v==="object"&&Object.values(v).some(a));})(r), false); });
test("same-count swapped ZIP, duplicate, and null-to-zero semantics fail closed", async t => { const f = await fixture(t); for (const mutate of [rows => { rows[2].zip_code = "99999"; }, rows => { rows[2].zip_code = "10002"; }, rows => { rows[2].employer_baseline = { status: "published", establishments: 0 }; }]) { const rows = structuredClone(f.coverageRows); mutate(rows); const text = rows.map(JSON.stringify).join("\n") + "\n"; await writeFile(f.coveragePath, text); const m = JSON.parse(await readFile(f.coverageManifest)); Object.assign(m.artifacts[0], { bytes: Buffer.byteLength(text), sha256: sha(text) }); await writeFile(f.coverageManifest, `${JSON.stringify(m)}\n`); f.enrollment.coverage_manifest_sha256 = sha(`${JSON.stringify(m)}\n`); await assert.rejects(() => buildNationalZipBusinessEvidenceAlignment(args(f))); } });
test("immutable verifier distinguishes evidence drift from semantic tamper", async t => { const f = await fixture(t), p = await publishNationalZipBusinessEvidenceAlignment(args(f)), mp = path.join(p.directory, "manifest.json"); assert.equal((await verifyNationalZipBusinessEvidenceAlignment(mp, { root: f.root, enrollment: f.enrollment })).status, "verified"); f.enrollment.coverage_pointer_sha256 = "f".repeat(64); await assert.rejects(() => verifyNationalZipBusinessEvidenceAlignment(mp, { root: f.root, enrollment: f.enrollment }), { code: "ZIP_BUSINESS_ALIGNMENT_EVIDENCE_REBUILD_REQUIRED" }); f.enrollment.coverage_pointer_sha256 = p.report.bindings.coverage_pointer_sha256; await writeFile(path.join(p.directory, "alignment.json"), "{}\n"); await assert.rejects(() => verifyNationalZipBusinessEvidenceAlignment(mp, { root: f.root, enrollment: f.enrollment }), { code: "ZIP_BUSINESS_ALIGNMENT_SEMANTIC_TAMPER" }); });
test("canonical ID/time and release placement are enforced", async t => { const f = await fixture(t); await assert.rejects(() => publishNationalZipBusinessEvidenceAlignment({ ...args(f), createdAt: "not-a-time" }), /created_at/); await assert.rejects(() => publishNationalZipBusinessEvidenceAlignment({ ...args(f), releaseId: "alignment-r2" }), /canonical alignment release ID/); const p = await publishNationalZipBusinessEvidenceAlignment({ ...args(f), releaseId: "national-zip-business-alignment-20260923000001-abcdef12" }), relocated = path.join(f.root, "relocated-manifest.json"); await writeFile(relocated, await readFile(path.join(p.directory, "manifest.json"))); await assert.rejects(() => verifyNationalZipBusinessEvidenceAlignment(relocated, { root: f.root, enrollment: f.enrollment }), { code: "ZIP_BUSINESS_ALIGNMENT_SEMANTIC_TAMPER" }); });
test("closed ZBP status mapping rejects contradictory ZCTA semantics", async t => { const f = await fixture(t), zbpPath = path.join(f.root, "zbp/releases/zbp-r1/zips.jsonl"), manifestPath = path.join(f.root, "zbp/releases/zbp-r1/manifest.json"); const rows = [{ zip_code: "10001", coverage_status: "zbp-without-zcta", geography: { status: "2020-zcta-polygon-available" }, employer_baseline: f.coverageRows[0].employer_baseline }, { zip_code: "10002", coverage_status: "zcta-without-published-zbp", geography: { status: "2020-zcta-polygon-available" }, employer_baseline: f.coverageRows[1].employer_baseline }], text = rows.map(JSON.stringify).join("\n") + "\n"; await writeFile(zbpPath, text); const m = JSON.parse(await readFile(manifestPath)); Object.assign(m.artifacts[0], { bytes: Buffer.byteLength(text), sha256: sha(text) }); await writeFile(manifestPath, `${JSON.stringify(m)}\n`); f.enrollment.zbp_manifest_sha256 = sha(`${JSON.stringify(m)}\n`); await assert.rejects(() => buildNationalZipBusinessEvidenceAlignment(args(f)), /mapping is inconsistent/); });
test("rehashed member arrays are semantic tamper when source bindings are unchanged", async t => { const f = await fixture(t), p = await publishNationalZipBusinessEvidenceAlignment({ ...args(f), releaseId: "national-zip-business-alignment-20260923000002-abcdef12" }), ap = path.join(p.directory, "alignment.json"), mp = path.join(p.directory, "manifest.json"), report = JSON.parse(await readFile(ap)); report.injected_zip_members = ["10001"]; const text = stable(report); await writeFile(ap, text); const m = JSON.parse(await readFile(mp)); m.artifacts[0].bytes = Buffer.byteLength(text); m.artifacts[0].sha256 = sha(text); await writeFile(mp, stable(m)); await assert.rejects(() => verifyNationalZipBusinessEvidenceAlignment(mp, { root: f.root, enrollment: f.enrollment }), { code: "ZIP_BUSINESS_ALIGNMENT_SEMANTIC_TAMPER" }); });
test("unexpected entries, hardlinks, and missing files are wrapped as semantic tamper", async t => { const f = await fixture(t), p = await publishNationalZipBusinessEvidenceAlignment({ ...args(f), releaseId: "national-zip-business-alignment-20260923000003-abcdef12" }), mp = path.join(p.directory, "manifest.json"), ap = path.join(p.directory, "alignment.json"); await writeFile(path.join(p.directory, "extra.txt"), "x"); await assert.rejects(() => verifyNationalZipBusinessEvidenceAlignment(mp, { root: f.root, enrollment: f.enrollment }), { code: "ZIP_BUSINESS_ALIGNMENT_SEMANTIC_TAMPER" }); await rm(path.join(p.directory, "extra.txt")); await link(ap, path.join(f.root, "alignment-hardlink.json")); await assert.rejects(() => verifyNationalZipBusinessEvidenceAlignment(mp, { root: f.root, enrollment: f.enrollment }), { code: "ZIP_BUSINESS_ALIGNMENT_SEMANTIC_TAMPER" }); await rm(path.join(f.root, "alignment-hardlink.json")); await rm(ap); await assert.rejects(() => verifyNationalZipBusinessEvidenceAlignment(mp, { root: f.root, enrollment: f.enrollment }), { code: "ZIP_BUSINESS_ALIGNMENT_SEMANTIC_TAMPER" }); });
test("coverage requires one exact registry dependency even when ZIP members are identical", async t => { for (const mutate of [m => { m.dependencies = []; }, m => { m.dependencies.push({ ...m.dependencies[0] }); }, m => { m.dependencies[0].release_id = "registry-r2"; }, m => { m.dependencies[0].manifest_sha256 = "c".repeat(64); }]) { const f = await fixture(t), mp = f.coverageManifest, m = JSON.parse(await readFile(mp)); mutate(m); const text = `${JSON.stringify(m)}\n`; await writeFile(mp, text); f.enrollment.coverage_manifest_sha256 = sha(text); await assert.rejects(() => buildNationalZipBusinessEvidenceAlignment(args(f)), /registry dependency/); } });
test("alignment artifact declaration is exact and malformed declarations are semantic tamper", async t => { const mutations = [a => { a.artifact_type = "other"; }, a => { a.record_count = 2; }, a => { a.bytes = 0; }, a => { a.sha256 = "A".repeat(64); }]; for (let index = 0; index < mutations.length; index += 1) { const f = await fixture(t), releaseId = `national-zip-business-alignment-2026092300001${index}-abcdef12`, p = await publishNationalZipBusinessEvidenceAlignment({ ...args(f), releaseId }), mp = path.join(p.directory, "manifest.json"), m = JSON.parse(await readFile(mp)); mutations[index](m.artifacts[0]); await writeFile(mp, stable(m)); await assert.rejects(() => verifyNationalZipBusinessEvidenceAlignment(mp, { root: f.root, enrollment: f.enrollment }), { code: "ZIP_BUSINESS_ALIGNMENT_SEMANTIC_TAMPER" }); } });
