import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { APP_ROOT } from './paths.mjs';
import { buildNationalGoalCompletionMatrix, publishNationalGoalCompletionMatrix, verifyNationalGoalCompletionMatrix } from './national-goal-completion-matrix.mjs';
import { readNationalReportingCatalog } from './national-reporting-catalog.mjs';

const states='AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY'.split(' ');
const source=(key,profile)=>({schema_version:'1.0.0',view_type:'source',source_key:key,profile_source_id:profile,release_metadata:{source_release_id:`release-${key}`,source_updated_at:'2026-09-01'},zip_rows_with_contribution:4,location_profile_geography:{profile_count:10,coordinate_assigned_single_count:5,latest_observed_at:'2026-09-01T00:00:00.000Z'},complete_source_for_all_businesses:false,lineage:{}});
async function deps(){const {catalog,sha256}=await readNationalReportingCatalog(),sources=catalog.sources.map(row=>source(row.sourceKey,row.profileId));return{catalogReader:async()=>({catalog,sha256}),snapshotReader:async()=>({manifest:{},states:states.map((code,index)=>({postal_abbreviation:code,state_fips:String(index+1).padStart(2,'0'),state_name:code,registry_evidence:{source_profile_counts_by_reported_address_state:Object.fromEntries(catalog.sources.filter(s=>s.profileId).map(s=>[s.profileId,index?0:1]))}})),sources,evidence:{coverageReleaseId:'coverage-release',pointerSha256:'a'.repeat(64),manifestSha256:'b'.repeat(64),artifacts:{states:{sha256:'c'.repeat(64)},sources:{sha256:'d'.repeat(64)}}}}),irsReader:async()=>({status:'available',counts:Object.fromEntries(states.map((s,i)=>[s,i?0:1])),manifestSha256:'e'.repeat(64),summarySha256:'f'.repeat(64),sourceReleaseId:'irs-release'})};}

test('matrix has exactly 51 jurisdictions and denominator-qualified category cells',async()=>{const d=await deps(),matrix=await buildNationalGoalCompletionMatrix({root:APP_ROOT,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-matrix',...d});assert.equal(matrix.jurisdictions.length,51);assert.equal(matrix.denominator.categories,8);assert.equal(matrix.all_business_completion_percent,null);for(const state of matrix.jurisdictions)for(const category of state.categories){assert.equal(category.all_business_completion_percent,null);assert.match(category.dataset_availability.measure,/not-business-completeness/);assert.ok(category.datasets.every(row=>row.evidence.coverage_manifest_sha256==='b'.repeat(64)));}assert.equal(matrix.jurisdictions[0].categories.find(c=>c.category_id==='retail-consumer').dataset_availability.percent,100);assert.equal(matrix.jurisdictions[0].categories.find(c=>c.category_id==='general-business').dataset_availability.percent,0);});

test('publisher is immutable, independently verifiable, network-free and does not create a pointer',async t=>{const root=await mkdtemp(path.join(APP_ROOT,'data/tmp/goal-matrix-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'data'),{recursive:true});const d=await deps(),result=await publishNationalGoalCompletionMatrix({root,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-published',...d});const verified=await verifyNationalGoalCompletionMatrix(path.join(result.directory,'manifest.json'));assert.equal(verified.network_requests,0);assert.equal(verified.production_pointers_changed,false);await assert.rejects(publishNationalGoalCompletionMatrix({root,createdAt:'2026-09-22T00:00:00.000Z',releaseId:'fixture-published',...d}));assert.rejects(readFile(path.join(root,'data/national-goal-completion-matrix/current.json')));await writeFile(path.join(result.directory,'report.json'),'tampered');await assert.rejects(verifyNationalGoalCompletionMatrix(path.join(result.directory,'manifest.json')));});
