import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {readFile} from 'node:fs/promises';
import {readNationalZipGoalAcceptance} from './national-zip-goal-acceptance.mjs';
import {nationalZipReportOnlyObjectiveHttp,projectNationalZipReportOnlyObjective} from './national-zip-report-only-objective-http.mjs';

const actual=()=>readNationalZipGoalAcceptance({claim:'report-only'});
function harness(method='GET',headers={}){const request=new EventEmitter();Object.assign(request,{method,headers,aborted:false,resume(){}});const response=new EventEmitter();Object.assign(response,{writableEnded:false,destroyed:false,headers:{},setHeader(k,v){this.headers[k]=v}});const result={status:null,body:null,calls:0};const json=(r,s,b)=>{result.status=s;result.body=b;result.calls++;r.writableEnded=true};return{request,response,result,run:(url=new URL('http://local/api/business-map/national-zip-report-only-objective'),deps={})=>nationalZipReportOnlyObjectiveHttp(request,response,url,json,deps)}}

test('projects exact accepted report-only counts, pins, and null boundaries',async()=>{const value=projectNationalZipReportOnlyObjective(await actual());assert.equal(value.status,'accepted-report-only');assert.deepEqual(value.zip_membership,{total:48194,source_contributed:47995,denominator_only:199});assert.deepEqual(value.outside_selected_zcta,{total:14403,source_reported:14361,denominator_only:41,explicit_00000:1});assert.deepEqual(value.usps_operational_denominator,{value:null,candidate_admission_status:'not-admitted'});assert.deepEqual(value.claims,{all_business_completion_percent:null,current_operating_business_count:null,current_operation_verified:false})});

test('projection rejects balanced conservation drift, admission widening, null-claim widening, and pin drift',async()=>{const report=await actual();for(const mutate of [v=>{v.source_reported_zip_membership.with_record_level_source_contribution--;v.source_reported_zip_membership.denominator_only_count++},v=>{v.source_reported_zip_membership.source_contributed_outside_selected_zcta_count--;v.source_reported_zip_membership.denominator_only_outside_selected_zcta_count++},v=>{v.authoritative_current_operational_usps_zip_denominator.admission_status='admitted'},v=>{v.all_business_completion_percent=0},v=>{v.current_operating_business_count=0},v=>{v.bindings.registry_manifest.sha256='0'.repeat(64)},v=>{v.acceptance.accepted=false}]){const changed=structuredClone(report);mutate(changed);assert.throws(()=>projectNationalZipReportOnlyObjective(changed),/rejected/)}});

test('HTTP is bodyless GET-only, uses report-only reader, no-store, and redacts failures',async()=>{const report=await actual(),ok=harness();let args;await ok.run(undefined,{reader:async value=>{args=value;return report}});assert.equal(ok.result.status,200);assert.equal(args.claim,'report-only');assert.ok(args.signal instanceof AbortSignal);assert.equal(ok.response.headers['Cache-Control'],'no-store');for(const h of [harness('POST'),harness('GET',{'content-length':'1'}),harness('GET',{'transfer-encoding':'chunked'})]){await h.run(undefined,{reader:async()=>report});assert.equal(h.result.status,400)}const query=harness();await query.run(new URL('http://local/api/business-map/national-zip-report-only-objective?x=1'),{reader:async()=>report});assert.equal(query.result.status,400);const bad=harness();await bad.run(undefined,{reader:async()=>{throw Error('C:/private/secret')}});assert.equal(bad.result.status,503);assert.doesNotMatch(JSON.stringify(bad.result.body),/private|secret/)});

test('server registers protected report-only route after authorization',async()=>{const source=await readFile(new URL('./server.mjs',import.meta.url),'utf8'),auth=source.indexOf('controlPlane.authorize(request)'),route=source.indexOf("url.pathname === '/api/business-map/national-zip-report-only-objective'");assert.ok(auth>=0&&route>auth);assert.match(source,/nationalZipReportOnlyObjectiveHttp\(request, response, url, json\)/)});
