import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{runInNewContext}from'node:vm';import test from'node:test';import ts from'typescript';
const source=await readFile(new URL('../app/national-fmcsa-registrant-principal-office-coverage-status.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
function fixture(runnerJson){const slots=[],effects=[],cleanups=[];let index=0;const exports={};runInNewContext(code,{exports,AbortController,require:name=>name==='./runner-client'?{runnerJson}:name==='react'?{useState(initial){const i=index++;if(!(i in slots))slots[i]=initial;return[slots[i],next=>{slots[i]=typeof next==='function'?next(slots[i]):next}]},useEffect(effect){index++;effects.push(effect)}}:name==='react/jsx-runtime'?{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props}),Fragment:'fragment'}:{}});return{mount(){this.render();for(const effect of effects.splice(0))cleanups.push(effect())},unmount(){for(const cleanup of cleanups.splice(0))cleanup?.()},render(){index=0;return exports.default()}}}
const nodes=tree=>!tree||typeof tree!=='object'?[]:Array.isArray(tree)?tree.flatMap(nodes):[tree,...nodes(tree.props?.children)],textOf=tree=>typeof tree==='string'?tree:Array.isArray(tree)?tree.map(textOf).join(' '):tree&&typeof tree==='object'?textOf(tree.props?.children):'',settle=()=>new Promise(resolve=>setTimeout(resolve,5));
const view=()=>({available:true,release:{release_id:'fmcsa-r1'},product_label:'FMCSA source-active registrant principal-office coverage',coverage:{selected_source_records:2211982,accepted_records:2195563,quarantined_records:16419,jurisdiction_rows:56,state_dc_records:2189579,territory_records:5984,positive_zip5_rows:35648,zip5_union_rows:39151,denominator_only_zip5_rows:3503,reported_zip4_count:550920,retained_coordinate_count:0,record_zcta_count:2185555,record_nonpolygon_count:10008,positive_source_zip_outside_zbp_zcta:1323},claims:{unique_business:false,current_operation:false,nationwide_completeness:false,physical_site:false,additive_to_generic_totals:false,roles_and_classes_exclusive:false},inclusion:{generic_business_totals:false,generic_entity_totals:false,generic_site_totals:false,generic_category_totals:false,generic_exports:false,production_enrollment:false,status:'excluded-non-additive-governed-layer'}});
test('FMCSA panel renders bounded aggregates, warnings, and no controls',async()=>{const f=fixture(async(url,options)=>{assert.equal(url,'/api/data-operations/national-fmcsa-registrant-principal-office-coverage-status');assert.ok(options.signal);return view()});f.mount();await settle();const tree=f.render(),text=textOf(tree);for(const expected of['2,211,982','2,195,563','16,419','35,648','3,503','550,920','1,323','home offices','Zero source coordinates','nonexclusive','not all businesses','production enrollment'])assert.match(text,new RegExp(expected,'i'));assert.equal(nodes(tree).filter(node=>['button','input','select'].includes(node.type)).length,0)});
test('FMCSA panel rejects stale unmounted completion',async()=>{let resolve,signal;const f=fixture((_url,options)=>new Promise(done=>{resolve=()=>done(view());signal=options.signal}));f.mount();f.unmount();assert.equal(signal.aborted,true);resolve();await settle();assert.doesNotMatch(textOf(f.render()),/2,211,982|fmcsa-r1/)});
test('FMCSA panel clears cached evidence on failure',async()=>{let reject;const f=fixture(()=>new Promise((_done,no)=>{reject=no}));f.mount();reject(new Error('fail'));await settle();assert.match(textOf(f.render()),/No cached evidence/)});
test('Data Operations includes FMCSA status',async()=>{const data=await readFile(new URL('../app/data-operations.tsx',import.meta.url),'utf8');assert.match(data,/import NationalFmcsaRegistrantPrincipalOfficeCoverageStatus/);assert.match(data,/<NationalFmcsaRegistrantPrincipalOfficeCoverageStatus \/>/)});
test('exact ZIP Business Intelligence renders the separate non-additive FMCSA evidence block',async()=>{const data=await readFile(new URL('../app/business-intelligence.tsx',import.meta.url),'utf8');for(const expected of[/fmcsa_registrant_principal_office_evidence/,/FMCSA source-active registrant principal-office evidence/,/Principal-office records/,/Governed classes/,/privacy_warning/,/not unique companies, current operations, verified physical sites/])assert.match(data,expected);assert.match(data,/source_active_registrant_principal_office_count/);assert.match(data,/reported_zip4_count/);assert.match(data,/retained_coordinate_count/)});
test('server maps the governed FMCSA ZIP row into the public aggregate contract',async()=>{const data=await readFile(new URL('./server.mjs',import.meta.url),'utf8');for(const expected of[/zip_code: result\.row\.code/,/source_active_registrant_principal_office_count: result\.row\.accepted_principal_office_count/,/carrier_operation_counts: result\.row\.carrier_operation_counts/,/privacy_warning:/])assert.match(data,expected)});
