import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {handleNationalReportingTen as handle} from './national-reporting-ten-http.mjs';
function fixture(){const request=Object.assign(new EventEmitter(),{method:'GET',headers:{},resume(){}}),response=Object.assign(new EventEmitter(),{destroyed:false,setHeader(){}}),results=[];return{request,response,url:new URL('http://localhost/api/dataset-representation/ten'),json:(_r,status,body)=>results.push({status,body}),results};}
test('deadline returns503 even when reader resolves unavailable after abort',async t=>{t.mock.timers.enable({apis:['setTimeout']});const f=fixture();let signal;const run=handle(f.request,f.response,f.url,options=>{signal=options.signal;return new Promise(resolve=>signal.addEventListener('abort',()=>resolve({available:false}),{once:true}));},f.json);t.mock.timers.tick(30000);await run;assert.equal(signal.aborted,true);assert.deepEqual(f.results.map(r=>r.status),[503]);assert.equal(f.request.listenerCount('aborted'),0);assert.equal(f.response.listenerCount('close'),0);});
test('deadline bounds response when readonly reader never settles',async t=>{t.mock.timers.enable({apis:['setTimeout']});const f=fixture();const run=handle(f.request,f.response,f.url,()=>new Promise(()=>{}),f.json);t.mock.timers.tick(30000);await run;assert.equal(f.results[0].status,503);});
test('pre-aborted request never starts a reader or leaks a rejection',async()=>{const f=fixture();f.request.aborted=true;await handle(f.request,f.response,f.url,()=>assert.fail('no read'),f.json);assert.equal(f.results[0].status,503);await new Promise(resolve=>setImmediate(resolve));});
test('destroyed response starts no read and sends no response',async()=>{const f=fixture();f.response.destroyed=true;await handle(f.request,f.response,f.url,()=>assert.fail('no read'),f.json);assert.deepEqual(f.results,[]);assert.equal(f.response.listenerCount('close'),0);await new Promise(resolve=>setImmediate(resolve));});
test('pending enrollment succeeds while query/body/writes never invoke reader',async()=>{for(const change of [f=>f.url.search='?state=MN',f=>f.request.headers['content-length']='1',f=>f.request.headers['transfer-encoding']='chunked',f=>f.request.method='POST']){const f=fixture();change(f);await handle(f.request,f.response,f.url,()=>assert.fail('no read'),f.json);assert.ok([400,405].includes(f.results[0].status));}const f=fixture();await handle(f.request,f.response,f.url,async()=>({available:false,reason:'production-enrollment-absent'}),f.json);assert.equal(f.results[0].status,200);});
