import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {readFile} from 'node:fs/promises';
import {nationalBusinessTemporalClaimMatrixHttp} from './national-business-temporal-claim-matrix-http.mjs';

async function call({method='GET',query='',headers={},reader=()=>({available:true})}={}){let reply,reads=0;const request=Object.assign(new EventEmitter(),{method,headers,resume(){}}),response=Object.assign(new EventEmitter(),{writableEnded:false,destroyed:false,setHeader(){}});await nationalBusinessTemporalClaimMatrixHttp(request,response,new URL(`http://local/${query}`),async options=>{reads++;return reader(options);},(_r,status,body)=>reply={status,body});return {...reply,reads};}
test('accepts only an empty bodyless GET and fails closed',async()=>{assert.deepEqual(await call(),{status:200,body:{available:true},reads:1});for(const input of [{method:'POST'},{query:'?state=AK'},{headers:{'content-length':'1'}},{headers:{'transfer-encoding':'chunked'}}]){const result=await call(input);assert.equal(result.status,400);assert.equal(result.reads,0);}const failed=await call({reader:()=>{throw Error('C:/private/token');}});assert.equal(failed.status,503);assert.doesNotMatch(JSON.stringify(failed.body),/private|token/);});
test('disconnect cancellation suppresses output',async()=>{let signal,writes=0;const request=Object.assign(new EventEmitter(),{method:'GET',headers:{},resume(){}}),response=Object.assign(new EventEmitter(),{writableEnded:false,destroyed:false,setHeader(){}});const pending=nationalBusinessTemporalClaimMatrixHttp(request,response,new URL('http://local/'),async options=>{signal=options.signal;await new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('hidden')),{once:true}));},()=>writes++);request.emit('aborted');await pending;assert.equal(signal.aborted,true);assert.equal(writes,0);});
test('server route is protected by shared authorization',async()=>{const code=await readFile(new URL('./server.mjs',import.meta.url),'utf8'),authorization=code.indexOf('controlPlane.authorize(request)'),route=code.indexOf("url.pathname === '/api/business-map/temporal-claim-matrix'");assert.ok(authorization>=0&&route>authorization);assert.match(code,/nationalBusinessTemporalClaimMatrixHttp\(request,response,url,readNationalBusinessTemporalClaimMatrix,json\)/);});
