import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createHash } from "node:crypto";
import { verifyNationalGoalCompletionMatrix } from './national-goal-completion-matrix.mjs';
import { nationalGoalCompletionView } from "./national-goal-completion-view.mjs";

const hash = (value) => createHash("sha256").update(value).digest("hex");
const LEGACY_SCHEMA="national-goal-completion-matrix@1.0.0";
const categories = ["general-business", "retail-consumer"];
const stateCodes='AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY'.split(' ');
function report(id) { return { schema_version: LEGACY_SCHEMA, release_id: id, created_at: "2026-09-22T12:00:00.000Z", denominator: { version: "fixture@1", datasets: 2, categories: 2, meaning: "dataset presence, not business completeness" }, all_business_completion_percent: null, limitations: ["Not business completeness."], jurisdictions: Array.from({ length: 51 }, (_, index) => ({ code: stateCodes[index], name: index === 0 ? "Alabama" : `Area ${index}`, all_business_completion_percent: null, categories: categories.map((category, categoryIndex) => { const availabilityStatus=categoryIndex===0?(index===0?"available":"unmeasured"):(index===0?"available":"observed-zero"),available=availabilityStatus==='available'?1:0;return { category_id: category, dataset_availability: { available, denominator: 1, percent:available*100,measure:'governed-dataset-presence-not-business-completeness' }, all_business_completion_percent: null, datasets: [{ dataset_id: category, label: category, availability_status: availabilityStatus, state_record_count: availabilityStatus==='unmeasured'?null:available, authorization: { state: "retained" }, temporal_status: { status: "within-review-window" }, geocode_rate: { assigned: 1, eligible: 2, percent: 50 }, gap_reason: availabilityStatus==='unmeasured'?'missing':null }] }; }) })) }; }
function legacyReport(id){const value=report(id);value.schema_version=LEGACY_SCHEMA;for(const jurisdiction of value.jurisdictions)for(const category of jurisdiction.categories){const {available,denominator}=category.dataset_availability;category.dataset_availability={available,denominator,percent:denominator?Math.round(available/denominator*1000)/10:null,measure:'governed-dataset-presence-not-business-completeness'};for(const dataset of category.datasets){const rate=dataset.geocode_rate;if(rate.eligible!==null)rate.percent=rate.eligible?Math.round(rate.assigned/rate.eligible*1000)/10:null;}}return value;}
async function publish(root, id, value=report(id)) { const directory = path.join(root, "data/national-goal-completion-matrix/releases", id); await mkdir(directory, { recursive: true }); const body = Buffer.from(`${JSON.stringify(value, null, 2)}\n`); await writeFile(path.join(directory, "report.json"), body); await writeFile(path.join(directory, "manifest.json"), `${JSON.stringify({ schema_version: value.schema_version, dataset_id: "national-goal-completion-matrix", release_id: id, status: "published-local-derived-report", all_business_completion_percent: null, production_pointers_changed: false, network_requests: 0, artifacts: [{ path: "report.json", bytes: body.length, sha256: hash(body), record_count: 51 }] })}\n`); return directory; }

test("selects the newest immutable release and exposes measured/unmeasured availability", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "goal-view-")); t.after(() => rm(root, { recursive: true, force: true })); await publish(root, "national-goal-completion-20260922110000-aaaaaaaa"); await publish(root, "national-goal-completion-20260922120000-bbbbbbbb"); const view = await nationalGoalCompletionView({ root, state: "AL", category: "retail-consumer" }); assert.equal(view.release_id, "national-goal-completion-20260922120000-bbbbbbbb"); assert.equal(view.jurisdictions.length, 51); assert.equal(view.selected.category.datasets[0].temporal_status.status, "within-review-window"); assert.equal(view.all_business_completion_percent, null); const unknown=await nationalGoalCompletionView({root,state:'AK',category:'general-business'});assert.equal(unknown.selected.category.dataset_availability.measurement_status,'unmeasured');assert.equal(unknown.selected.category.dataset_availability.percent,null);assert.equal(unknown.jurisdictions[1].measurement_status,'unmeasured');assert.equal(unknown.jurisdictions[1].percent,null);const observedZero=await nationalGoalCompletionView({root,state:'AK',category:'retail-consumer'});assert.equal(observedZero.selected.category.dataset_availability.measurement_status,'measured');assert.equal(observedZero.selected.category.dataset_availability.percent,0);assert.equal(observedZero.jurisdictions[1].measured,1); });
test("fails closed when the newest release is tampered instead of falling back", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "goal-view-")); t.after(() => rm(root, { recursive: true, force: true })); await publish(root, "national-goal-completion-20260922110000-aaaaaaaa"); const newest = await publish(root, "national-goal-completion-20260922120000-bbbbbbbb"); await writeFile(path.join(newest, "report.json"), "tampered"); assert.equal((await nationalGoalCompletionView({ root })).status, "newest-release-verification-failed"); });
test("fails closed when source replay requires a rebuild", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "goal-view-")); t.after(() => rm(root, { recursive: true, force: true })); await publish(root, "national-goal-completion-20260922120000-bbbbbbbb"); const verifier=async()=>{throw Object.assign(Error('drift'),{code:'GOAL_MATRIX_EVIDENCE_REBUILD_REQUIRED'});}; assert.equal((await nationalGoalCompletionView({root,verifier})).status,"newest-release-verification-failed"); });
test("rejects state and category inputs outside the closed matrix", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "goal-view-")); t.after(() => rm(root, { recursive: true, force: true })); await publish(root, "national-goal-completion-20260922120000-bbbbbbbb"); await assert.rejects(nationalGoalCompletionView({ root, state: "PR" }), /State is not/); await assert.rejects(nationalGoalCompletionView({ root, category: "made-up" }), /not in the matrix/); });
test("legacy immutable 1.0 releases remain verifiable and the view normalizes their all-unmeasured cells",async t=>{const root=await mkdtemp(path.join(os.tmpdir(),'goal-view-'));t.after(()=>rm(root,{recursive:true,force:true}));const id='national-goal-completion-20260922120000-cccccccc',directory=await publish(root,id,legacyReport(id)),verified=await verifyNationalGoalCompletionMatrix(path.join(directory,'manifest.json'));assert.equal(verified.schema_version,LEGACY_SCHEMA);const view=await nationalGoalCompletionView({root,state:'AK',category:'general-business'});assert.equal(view.release_id,id);assert.equal(view.selected.category.dataset_availability.measurement_status,'unmeasured');assert.equal(view.selected.category.dataset_availability.percent,null);assert.equal(view.selected.category.dataset_availability.unmeasured,1);assert.equal(view.jurisdictions[1].percent,null);});
