import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createHash } from "node:crypto";
import { nationalGoalCompletionView } from "./national-goal-completion-view.mjs";

const hash = (value) => createHash("sha256").update(value).digest("hex");
const categories = ["general-business", "retail-consumer"];
function report(id) { return { schema_version: "national-goal-completion-matrix@1.0.0", release_id: id, created_at: "2026-09-22T12:00:00.000Z", denominator: { version: "fixture@1", datasets: 2, categories: 2, meaning: "dataset presence, not business completeness" }, all_business_completion_percent: null, limitations: ["Not business completeness."], jurisdictions: Array.from({ length: 51 }, (_, index) => ({ code: index === 0 ? "AL" : index === 50 ? "DC" : `X${String(index).padStart(2, "0")}`, name: index === 0 ? "Alabama" : `Area ${index}`, all_business_completion_percent: null, categories: categories.map((category, categoryIndex) => ({ category_id: category, dataset_availability: { available: categoryIndex ? 1 : index === 0 ? 1 : 0, denominator: 1, percent: categoryIndex ? 100 : index === 0 ? 100 : 0, measure: "governed-dataset-presence-not-business-completeness" }, all_business_completion_percent: null, datasets: [{ dataset_id: category, label: category, availability_status: categoryIndex || index === 0 ? "available" : "unmeasured", state_record_count: 1, authorization: { state: "retained" }, temporal_status: { status: "within-review-window" }, geocode_rate: { assigned: 1, eligible: 2, percent: 50 }, gap_reason: categoryIndex || index === 0 ? null : "missing" }] })) })) }; }
async function publish(root, id) { const directory = path.join(root, "data/national-goal-completion-matrix/releases", id); await mkdir(directory, { recursive: true }); const body = Buffer.from(`${JSON.stringify(report(id), null, 2)}\n`); await writeFile(path.join(directory, "report.json"), body); await writeFile(path.join(directory, "manifest.json"), `${JSON.stringify({ schema_version: "national-goal-completion-matrix@1.0.0", dataset_id: "national-goal-completion-matrix", release_id: id, status: "published-local-derived-report", all_business_completion_percent: null, production_pointers_changed: false, network_requests: 0, artifacts: [{ path: "report.json", bytes: body.length, sha256: hash(body), record_count: 51 }] })}\n`); return directory; }

test("selects the newest immutable release without a pointer and exposes qualified 51-jurisdiction cells", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "goal-view-")); t.after(() => rm(root, { recursive: true, force: true })); await publish(root, "national-goal-completion-20260922110000-aaaaaaaa"); await publish(root, "national-goal-completion-20260922120000-bbbbbbbb"); const view = await nationalGoalCompletionView({ root, state: "AL", category: "retail-consumer" }); assert.equal(view.release_id, "national-goal-completion-20260922120000-bbbbbbbb"); assert.equal(view.jurisdictions.length, 51); assert.equal(view.selected.category.datasets[0].temporal_status.status, "within-review-window"); assert.equal(view.all_business_completion_percent, null); });
test("fails closed when the newest release is tampered instead of falling back", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "goal-view-")); t.after(() => rm(root, { recursive: true, force: true })); await publish(root, "national-goal-completion-20260922110000-aaaaaaaa"); const newest = await publish(root, "national-goal-completion-20260922120000-bbbbbbbb"); await writeFile(path.join(newest, "report.json"), "tampered"); assert.equal((await nationalGoalCompletionView({ root })).status, "newest-release-verification-failed"); });
test("rejects state and category inputs outside the closed matrix", async (t) => { const root = await mkdtemp(path.join(os.tmpdir(), "goal-view-")); t.after(() => rm(root, { recursive: true, force: true })); await publish(root, "national-goal-completion-20260922120000-bbbbbbbb"); await assert.rejects(nationalGoalCompletionView({ root, state: "PR" }), /State is not/); await assert.rejects(nationalGoalCompletionView({ root, category: "made-up" }), /not in the matrix/); });
