import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{runInNewContext}from'node:vm';import test from'node:test';import ts from'typescript';
const source=await readFile(new URL('../app/national-snap-retailer-industry-coverage-status.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
function fixture(runnerJson){const slots=[],effects=[],cleanups=[];let index=0;const exports={};runInNewContext(code,{exports,AbortController,require:name=>name==='./runner-client'?{runnerJson}:name==='react'?{useState(initial){const i=index++;if(!(i in slots))slots[i]=initial;return[slots[i],next=>{slots[i]=typeof next==='function'?next(slots[i]):next}]},useEffect(effect){index++;effects.push(effect)}}:name==='react/jsx-runtime'?{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props}),Fragment:'fragment'}:{}});return{mount(){this.render();for(const effect of effects.splice(0))cleanups.push(effect())},unmount(){for(const cleanup of cleanups.splice(0))cleanup?.()},render(){index=0;return exports.default()}}}
const nodes=tree=>!tree||typeof tree!=='object'?[]:Array.isArray(tree)?tree.flatMap(nodes):[tree,...nodes(tree.props?.children)],textOf=tree=>typeof tree==='string'?tree:Array.isArray(tree)?tree.map(textOf).join(' '):tree&&typeof tree==='object'?textOf(tree.props?.children):'',settle=()=>new Promise(resolve=>setTimeout(resolve,5));
const view=()=>({available:true,release:{release_id:'snap-r1'},industry:{label:'SNAP-authorized retailer locations',classification_system:'USDA SNAP Store Type',store_types:['Grocery Store']},coverage:{authorized_retailer_location_count:252080,source_positive_zip5_count:23957,denominator_only_zip5_rows:13915,reported_zip4_count:224257,state_dc_location_count:250000,territory_location_count:2080,store_type_counts:{'Grocery Store':1}},claims:{snap_authorized_as_of_source_update:true,current_operation:null,all_grocery_retailers:false,unique_business:null,nationwide_completeness:false,additive_to_generic_totals:false},inclusion:{generic_business_totals:false,generic_entity_totals:false,generic_site_totals:false,generic_category_totals:false,generic_exports:false,production_enrollment:false,status:'excluded-non-additive-governed-layer'}});
test('SNAP panel renders verified scope and no execution controls',async()=>{const f=fixture(async(url,options)=>{assert.equal(url,'/api/data-operations/national-snap-retailer-industry-coverage-status');assert.ok(options.signal);return view()});f.mount();await settle();const tree=f.render(),text=textOf(tree);for(const expected of['252,080','23,957','13,915','224,257','USDA SNAP Store Type','Excluded, non-additive coverage','not all grocery retail','production enrollment'])assert.match(text,new RegExp(expected,'i'));assert.equal(nodes(tree).filter(node=>['button','input','select'].includes(node.type)).length,0)});
test('unmounted stale SNAP response cannot replace state',async()=>{let resolve,signal;const f=fixture((_url,options)=>new Promise(done=>{resolve=()=>done(view());signal=options.signal}));f.mount();f.unmount();assert.equal(signal.aborted,true);resolve();await settle();assert.doesNotMatch(textOf(f.render()),/252,080|snap-r1/)});
test('failed SNAP response clears cached evidence',async()=>{let reject;const f=fixture(()=>new Promise((_done,no)=>{reject=no}));f.mount();reject(new Error('failed'));await settle();const text=textOf(f.render());assert.match(text,/No cached evidence/);assert.doesNotMatch(text,/252,080|snap-r1/)});
test('Data Operations includes SNAP status',async()=>{const data=await readFile(new URL('../app/data-operations.tsx',import.meta.url),'utf8');assert.match(data,/import NationalSnapRetailerIndustryCoverageStatus/);assert.match(data,/<NationalSnapRetailerIndustryCoverageStatus \/>/)});
