import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { runInNewContext } from "node:vm";
import test from "node:test";
import ts from "typescript";
const source = await readFile(new URL("../app/national-geography-goal-status.tsx", import.meta.url), "utf8"); const code = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX } }).outputText;
function fixture(runnerJson) { const slots = [], refs = [], effects = []; let index = 0; const exports = {}; runInNewContext(code, { exports, AbortController, window: globalThis, require: (name) => name === "./runner-client" ? { runnerJson } : name === "react" ? { useState(initial) { const slot = index++; if (!(slot in slots)) slots[slot] = initial; return [slots[slot], (next) => { slots[slot] = typeof next === "function" ? next(slots[slot]) : next; }]; }, useRef(initial) { const slot = index++; if (!(slot in refs)) refs[slot] = { current: initial }; return refs[slot]; }, useCallback(callback) { index += 1; return callback; }, useEffect(effect) { index += 1; effects.push(effect); } } : name === "react/jsx-runtime" ? { jsx: (type, props) => ({ type, props }), jsxs: (type, props) => ({ type, props }), Fragment: "fragment" } : { __esModule: true, default: () => null } }); return { mount() { const tree = this.render(); for (const effect of effects.splice(0)) effect(); return tree; }, render() { index = 0; return exports.default(); } }; }
const view = () => ({ available: true, release: { release_id: "release", manifest_sha256: "a".repeat(64), artifact_sha256: "b".repeat(64), created_at: "2026-09-23T00:00:00.000Z" }, census_polygon_completeness: { complete_for_declared_layers_and_vintages: true, coordinate_reference_system: "EPSG:4326", generalized_geometry: true, nation_polygon_products: 2, state_equivalents: 56, states_and_district_of_columbia: 51, county_equivalents: 3235, zcta_2020_polygons: 33791 }, temporal_vintage: { aligned: false, state_and_county_vintage: "Current", zcta_vintage: "2020", limitation: "mismatch" }, overlay_diagnostics: { zctas_complete_within_tolerance: 33788, zctas_partial_or_overlapping: 3, zctas_unmatched: 0, counties_without_zcta_intersection: 2, zctas_materially_crossing_state_boundaries: 184, zctas_materially_crossing_county_boundaries: 10277 }, usps_operational_denominator: { complete: false, verified: false, registry_zip5_keys: 48194, unverified_registry_zip5_keys: 48194, same_code_census_zcta: 33791, source_reported_without_same_code_zcta: 14361, denominator_only_without_same_code_zcta: 41, explicit_00000_placeholder_count: 1, limitation: "incomplete" }, zip4: { stored_separately_from_zip5: true, geometric: false, limitation: "ZIP+4 separate" }, claim_boundaries: {}, execution: { network_requests: 0, production_pointer_changes: false, current_pointer_present: false, read_only: true } });
function nodes(tree) { if (!tree || typeof tree !== "object") return []; if (Array.isArray(tree)) return tree.flatMap(nodes); return [tree, ...nodes(tree.props?.children)]; } const textOf = (tree) => typeof tree === "string" ? tree : Array.isArray(tree) ? tree.map(textOf).join(" ") : tree && typeof tree === "object" ? textOf(tree.props?.children) : ""; const settle = () => new Promise((resolve) => setTimeout(resolve, 5));
test("panel renders separate dynamic claims with no execution controls", async () => { const f = fixture(async (url, options) => { assert.equal(url, "/api/data-operations/national-geography-goal-status"); assert.ok(options.signal); return view(); }); f.mount(); await settle(); const tree = f.render(), text = textOf(tree); for (const expected of ["33788 within tolerance", "3 partial/overlapping", "2 counties with no ZCTA intersection", "184 materially cross-state", "10277 materially cross-county", "48194 registry ZIP5 keys", "14361 source-reported", "41 denominator-only", "1 explicit 00000 placeholder", "there is no overall completion percentage", "Stored separately: yes", "geometric: no"]) assert.match(text, new RegExp(expected)); assert.equal(nodes(tree).filter((item) => item.type === "button").length, 1); assert.doesNotMatch(text, /Build|Execute|Download|Approve/); });
test("panel cancels stale requests and clears prior evidence on failure", async () => { const pending = []; const f = fixture((_url, options) => new Promise((resolve, reject) => pending.push({ resolve, reject, signal: options.signal }))); f.mount(); await settle(); let tree = f.render(); nodes(tree).find((item) => item.type === "button").props.onClick(); assert.equal(pending[0].signal.aborted, true); pending[1].resolve(view()); await settle(); pending[0].resolve({ ...view(), overlay_diagnostics: { ...view().overlay_diagnostics, zctas_complete_within_tolerance: 1 } }); await settle(); tree = f.render(); assert.match(textOf(tree), /33788 within tolerance/); nodes(tree).find((item) => item.type === "button").props.onClick(); pending[2].reject(new Error("private")); await settle(); tree = f.render(); assert.match(textOf(tree), /unavailable or failed verification/); assert.doesNotMatch(textOf(tree), /33788|48194/); });
test("Data Operations places geography status beside coverage/proposal views", async () => { const data = await readFile(new URL("../app/data-operations.tsx", import.meta.url), "utf8"); assert.match(data, /import NationalGeographyGoalStatus/); assert.ok(data.indexOf("<NationalGeographyGoalStatus />") > data.indexOf("<DocumentOnlyInquiryProposalRegistry />")); });
