import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {APP_ROOT} from './paths.mjs';
import {TEN_DIRECTORIES,TEN_STATES,TEN_TERRITORIES} from './national-reporting-ten-catalog.mjs';
import {publishNationalReportingTenEnrollmentWithFixtureRoot as publish} from './national-reporting-ten-enrollment-publisher.mjs';

const sha=value=>createHash('sha256').update(value).digest('hex'),fixed='a'.repeat(64);
async function makeFixture(t){
  const parent=path.join(APP_ROOT,'data','tmp');await mkdir(parent,{recursive:true});
  const root=await mkdtemp(path.join(parent,'ten-publisher-'));t.after(()=>rm(root,{recursive:true,force:true}));
  const write=async(relative,value)=>{const file=path.join(root,relative),body=Buffer.from(typeof value==='string'?value:`${JSON.stringify(value)}\n`);await mkdir(path.dirname(file),{recursive:true});await writeFile(file,body);return{sha256:sha(body),bytes:body.length};};
  const catalogValue=JSON.parse(await readFile(path.join(APP_ROOT,'config','national-reporting-sources.json'),'utf8'));
  const catalog=await write('config/national-reporting-sources.json',catalogValue);
  const registryPath='data/business-registry/releases/registry/manifest.json',registry=await write(registryPath,{dataset_id:'national-business-registry',release_id:'registry'});
  const lineage={registry_release_id:'registry',geography_release_id:'geo',zcta_jurisdiction_crosswalk_release_id:'zcta',entity_resolution_release_id:'resolution',entity_resolution_benchmark_release_id:'benchmark',census_nonemployer_release_id:'nonemployer',transformation_version:'national-business-coverage-views@2.11.0'};
  const manifest={schema_version:'1.0.0',dataset_id:'national-business-coverage-views',release_id:'coverage',status:'published-partial-local-aggregate',dependencies:[['national-business-registry','registry',registry.sha256],['us-census-geography','geo',fixed],['us-census-zcta-jurisdiction-crosswalk','zcta',fixed],['national-business-entity-resolution','resolution',fixed],['national-business-entity-resolution-benchmark','benchmark',fixed],['census-nonemployer-baseline','nonemployer',fixed]].map(([dataset_id,release_id,manifest_sha256])=>({dataset_id,release_id,manifest_sha256})),artifacts:[]};
  const states=[...TEN_STATES,...TEN_TERRITORIES].map(postal_abbreviation=>({schema_version:'1.0.0',view_type:'state',postal_abbreviation,complete_all_businesses:false,lineage,registry_evidence:{source_profile_counts_by_reported_address_state:{}}}));
  for(const source of TEN_DIRECTORIES){
    manifest[source.sourceKey]={schema_version:source.extensionVersion,registry_manifest_sha256:registry.sha256,registry_manifest_path:registryPath,source_registry_declaration:{source:{dataset_id:source.datasetId,release_id:'retained',manifest_sha256:source.manifestSha256,selected_artifact:{sha256:source.selectedSha256}}},record_unit:source.rowUnit,export_policy:'local-review-only',business_count:null,physical_site_count:null,national_completeness_percent:null,geographic_assignment_performed:false,counts:{all_retained_directory_rows:source.all,state_dc_retained_directory_rows:source.stateDC,territory_retained_directory_rows:source.territories,unknown_reported_state_rows:0}};
    for(const row of states){const count=row.postal_abbreviation==='AL'?source.stateDC:row.postal_abbreviation==='PR'?source.territories:0;row[source.sourceKey]={schema_version:source.extensionVersion,record_unit:source.rowUnit,business_count:null,physical_site_count:null,national_completeness_percent:null,geographic_assignment_performed:false,denominators:{all_retained_directory_rows:source.all,state_dc_retained_directory_rows:source.stateDC,territory_retained_directory_rows:source.territories,unknown_reported_state_rows:0},directory_rows:count,percent_of_all_retained_directory_rows:count/source.all*100,percent_of_state_dc_retained_directory_rows:TEN_STATES.includes(row.postal_abbreviation)?count/source.stateDC*100:count?null:0};}
  }
  const sources=[{schema_version:'1.0.0',view_type:'source',source_key:'fixture',complete_source_for_all_businesses:false,lineage}];
  for(const[name,type,rows]of[['states','state-coverage-view-jsonl',states],['sources','source-coverage-view-jsonl',sources]]){const relative=`data/business-coverage-views/releases/coverage/views/${name}.jsonl`,body=rows.map(row=>`${JSON.stringify(row)}\n`).join(''),meter=await write(relative,body);manifest.artifacts.push({path:`views/${name}.jsonl`,artifact_type:type,record_count:rows.length,export_policy:'local-review-only',...meter});}
  const coverageManifest=await write('data/business-coverage-views/releases/coverage/manifest.json',manifest),pointer=await write('data/business-coverage-views/current.json',{dataset_id:manifest.dataset_id,release_id:'coverage',manifest:'releases/coverage/manifest.json'});
  const runId='production-fixture-01',receipt={schemaVersion:1,mode:'production',runId,status:'SUCCEEDED',stopRequested:false,error:null,stages:['registry-build','registry-verify','resolution-build','resolution-verify','benchmark-build','benchmark-verify','coverage-build','coverage-verify'].map(id=>({id,status:'SUCCEEDED',exitCode:0,error:null})),outputs:{coverage:{datasetId:manifest.dataset_id,releaseId:'coverage',path:'data/business-coverage-views/current.json',sha256:pointer.sha256,manifestPath:'data/business-coverage-views/releases/coverage/manifest.json',manifestSha256:coverageManifest.sha256},registry:{datasetId:'national-business-registry',releaseId:'registry',manifestPath:registryPath,manifestSha256:registry.sha256}}};
  const receiptRelative=`data/reconciliations/production-runs/${runId}/receipt.json`;await write(receiptRelative,receipt);
  return{root,runId,write,receipt,receiptRelative,pointerPath:'data/business-coverage-views/current.json',target:path.join(root,'config','national-reporting-ten-enrollment.json'),catalog,coverageManifest,pointer};
}

test('publishes exact enrollment once after successful closed receipt verification',async t=>{const f=await makeFixture(t),result=await publish(f.root,f.runId);assert.equal(result.status,'PUBLISHED');const value=JSON.parse(await readFile(f.target,'utf8'));assert.equal(value.productionReceipt.path,f.receiptRelative);assert.equal(value.predecessorCatalogSha256,f.catalog.sha256);assert.equal(value.coveragePointerSha256,f.pointer.sha256);assert.equal(value.coverageManifestSha256,f.coverageManifest.sha256);await assert.rejects(publish(f.root,f.runId),/already exists/);});
test('rejects tampered or incomplete production receipt without writing',async t=>{const f=await makeFixture(t),bad=structuredClone(f.receipt);bad.stages[7].status='FAILED';await f.write(f.receiptRelative,bad);await assert.rejects(publish(f.root,f.runId),/rejected/);await assert.rejects(readFile(f.target),{code:'ENOENT'});});
test('rejects stale current coverage or catalog changed at final checkpoint without writing',async t=>{for(const stale of[async f=>f.write(f.pointerPath,{dataset_id:'national-business-coverage-views',release_id:'old',manifest:'releases/old/manifest.json'}),async f=>f.write('config/national-reporting-sources.json',{schemaVersion:'changed'})]){const f=await makeFixture(t);await assert.rejects(publish(f.root,f.runId,{checkpoint:()=>stale(f)}));await assert.rejects(readFile(f.target),{code:'ENOENT'});}});
test('cancellation is preserved and never publishes',async t=>{const f=await makeFixture(t),controller=new AbortController();controller.abort();await assert.rejects(publish(f.root,f.runId,{signal:controller.signal}),{name:'AbortError'});await assert.rejects(readFile(f.target),{code:'ENOENT'});});
test('run and fixture paths are closed',async t=>{const f=await makeFixture(t);for(const run of['../escape','a/b','', '.', '..'])await assert.rejects(publish(f.root,run),/closed run identifier/);await assert.rejects(publish(path.join(APP_ROOT,'config'),f.runId),/outside data\/tmp/);await assert.rejects(readFile(f.target),{code:'ENOENT'});});
