import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {mkdir,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {APP_ROOT} from './paths.mjs';
import {normalizeNonemployerRecord} from './census-nonemployer.mjs';
import {getNonemployerIndustrySelectionCatalog as catalog,validateNonemployerIndustrySelection as validate,readSelectedNonemployerIndustry as native,readSelectedNonemployerIndustryWithTestInput as read} from './nonemployer-industry-selection.mjs';
const opts={naicsVersion:'2022',referenceYear:2023,naics:'4451'},hash=v=>createHash('sha256').update(v).digest('hex');
async function fixture(t,flag=false){const parent=path.join(APP_ROOT,'data/tmp');await mkdir(parent,{recursive:true});const root=await mkdtemp(path.join(parent,'nes-selection-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'derived/industry'),{recursive:true});const row=(state,count)=>normalizeNonemployerRecord({GEOTYPE:state?'02':'01',ST:state??'00',COUNTY:'000',YEAR:'2023',NAICS2022:'4451',NAICS2022_LABEL:'Grocery and convenience retailers',LFO:'001',RCPSZES:'001',NESTAB:String(count)},2023,{source_release_id:'fixture',ingest_run_id:'fixture'}),groups={national:[row(null,100)],state:[row('01',20),row('02',0)]};if(flag)groups.state[0].measures.nonemployer_establishments_flag='D';const artifacts=[];for(const kind of ['national','state']){const raw=gzipSync(groups[kind].map(r=>JSON.stringify(r)+'\n').join(''));const file=`derived/industry/${kind}.jsonl.gz`;await writeFile(path.join(root,file),raw);artifacts.push({path:file,artifact_type:'normalized-nonemployer-industry-jsonl-gzip',geography_type:kind,bytes:raw.length,sha256:hash(raw),record_count:groups[kind].length});}const m={schema_version:'1.0.0',dataset_id:'census-nonemployer-baseline',release_id:'fixture',reference_year:2023,status:'published-annual-aggregate',complete_source_release:true,geography_scope:'50-states-and-district-of-columbia',coverage:{normalized_national_industry_rows:1,normalized_state_industry_rows:2},artifacts},raw=JSON.stringify(m),manifestPath=path.join(root,'manifest.json');await writeFile(manifestPath,raw);return{manifestPath,manifestSha256:hash(raw)};}
test('catalog exposes exact published levels and context-only relationships',()=>{assert.equal(catalog().entries.length,5);assert.equal(catalog().entries.find(e=>e.naics==='4451').level,'industry-group');assert.match(catalog().entries.find(e=>e.naics==='4451').scopeNotice,/vending/);assert.ok(catalog().entries.every(e=>e.categoryRelation==='context-only-not-equivalent'));assert.throws(()=>catalog().entries.push({}));assert.deepEqual(validate({...opts,states:[]}).states,[]);});
test('single exact code rejects app category aliases, absent six-digit variants and overlapping selections',()=>{for(const bad of [{...opts,naics:'retail-consumer'},{...opts,naics:'445110'},{...opts,naics:['44-45','4451']},{...opts,codes:['23','236']},{...opts,naicsVersion:'2017'},{...opts,referenceYear:2024},{...opts,categoryId:'childcare'},{...opts,loader:()=>{}}])assert.throws(()=>validate(bad));for(const naics of ['44-45','4451','45611','62441','23'])assert.equal(validate({...opts,naics}).naics,naics);});
test('closed dense selection rejects accessors, symbols, sparse arrays and wrong state scope',()=>{let invoked=false;const bad={...opts};Object.defineProperty(bad,'states',{get(){invoked=true;return[];}});assert.throws(()=>validate(bad));assert.equal(invoked,false);for(const states of [new Array(1),['01','01'],['72'],['AL'],[1],Object.assign(['01'],{extra:true})])assert.throws(()=>validate({...opts,states}));assert.throws(()=>validate({...opts,[Symbol('x')]:1}));});
test('adapter keeps official national denominator, missing and zero cells and full-state reconciliation',async t=>{const f=await fixture(t),all=await read(f,opts),filtered=await read(f,{...opts,states:['01','02','06']});assert.equal(filtered.alignment.verificationMode,'synthetic-test-input');assert.equal(filtered.alignment.national.count,100);assert.equal(filtered.alignment.states[0].percentOfNationalSameIndustry,20);assert.equal(filtered.alignment.states[1].percentOfNationalSameIndustry,0);assert.equal(filtered.alignment.states[2].status,'not-published');assert.deepEqual(filtered.alignment.stateReconciliation,all.alignment.stateReconciliation);assert.equal(filtered.claims.collectionCompletenessPercent,null);assert.equal((await read(f,{...opts,states:[]})).alignment.national.count,100);assert.throws(()=>{filtered.alignment.national.count=20;});});
test('flagged measures remain unknown, and selected source drift rejects',async t=>{const f=await fixture(t,true),r=await read(f,opts);assert.equal(r.alignment.states[0].count,null);assert.equal(r.alignment.states[0].status,'flagged-uninterpreted');assert.equal(r.alignment.states[0].flags.measure,'D');await assert.rejects(read({...f,manifestSha256:'0'.repeat(64)},opts));});
test('pre-abort native adapter cannot read retained evidence or acquire',async()=>{await assert.rejects(native({...opts,signal:AbortSignal.abort()}),{name:'AbortError'});await assert.rejects(native({...opts,source:'https://example.com'}));});
