import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {mkdir,mkdtemp,readFile,writeFile,rm,link,unlink} from 'node:fs/promises';
import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {APP_ROOT} from './paths.mjs';
import {normalizeNonemployerRecord} from './census-nonemployer.mjs';
import {readNonemployerIndustryAlignment as native,readNonemployerIndustryAlignmentWithTestInput as read} from './nonemployer-industry-alignment.mjs';
const hash=v=>createHash('sha256').update(v).digest('hex'),opts={naics:'23',referenceYear:2023};
function row(state,count,extra={}){return normalizeNonemployerRecord({GEOTYPE:state?'02':'01',ST:state??'00',COUNTY:'000',YEAR:'2023',NAICS2022:'23',LFO:'001',RCPSZES:'001',NESTAB:String(count),...extra},2023,{source_release_id:'fixture',ingest_run_id:'fixture'});}
async function fixture(t,change=()=>{}){const parent=path.join(APP_ROOT,'data/tmp');await mkdir(parent,{recursive:true});const root=await mkdtemp(path.join(parent,'nes-alignment-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'derived/industry'),{recursive:true});
 const groups={national:[row(null,100)],state:[row('01',25),row('02',0),row('04',75)]};change(groups);const artifacts=[];
 for(const kind of ['national','state']){const raw=gzipSync(groups[kind].map(r=>JSON.stringify(r)+'\n').join(''));await writeFile(path.join(root,`derived/industry/${kind}.jsonl.gz`),raw);artifacts.push({path:`derived/industry/${kind}.jsonl.gz`,artifact_type:'normalized-nonemployer-industry-jsonl-gzip',geography_type:kind,bytes:raw.length,sha256:hash(raw),record_count:groups[kind].length});}
 const m={schema_version:'1.0.0',dataset_id:'census-nonemployer-baseline',release_id:'fixture',reference_year:2023,status:'published-annual-aggregate',complete_source_release:true,geography_scope:'50-states-and-district-of-columbia',coverage:{normalized_national_industry_rows:groups.national.length,normalized_state_industry_rows:groups.state.length},artifacts};const raw=JSON.stringify(m);const manifestPath=path.join(root,'manifest.json');await writeFile(manifestPath,raw);return {manifestPath,manifestSha256:hash(raw)};}
test('official national denominator survives state filtering; published zero differs from absent',async t=>{const f=await fixture(t);const result=await read(f,{...opts,states:['01','02','06']});assert.equal(result.national.count,100);assert.equal(result.states[0].percentOfNationalSameIndustry,25);assert.equal(result.states[1].percentOfNationalSameIndustry,0);assert.equal(result.states[2].count,null);assert.equal(result.states[2].status,'not-published');assert.equal(result.stateReconciliation.knownStateCount,3);assert.equal(result.stateReconciliation.nationalMinusStateSum,null);assert.equal(result.claims.collectionCompletenessPercent,null);assert.equal(result.claims.employerUniverseIncluded,false);assert.equal(result.verificationMode,'synthetic-test-input');assert.throws(()=>{result.national.count=1;});});
test('subtotals and adjacent NAICS never enter numerator or denominator',async t=>{const f=await fixture(t,g=>{g.national.push(row(null,900,{LFO:'9101'}),row(null,700,{RCPSZES:'1411'}),row(null,800,{NAICS2022:'236'}));g.state.push(row('01',900,{LFO:'9111'}));});assert.equal((await read(f,opts)).states[0].count,25);assert.equal((await read(f,opts)).national.count,100);});
test('flagged, null and zero national cells yield unknown percentages without invented suppression values',async t=>{for(const mode of ['flag','null','zero','absent']){const f=await fixture(t,g=>{if(mode==='flag')g.national[0].measures.nonemployer_establishments_flag='D';if(mode==='null')g.national[0].measures.nonemployer_establishments=null;if(mode==='zero')g.national[0].measures.nonemployer_establishments=0;if(mode==='absent')g.national[0]=row(null,1,{NAICS2022:'99'});});const r=await read(f,opts);assert.equal(r.states[0].percentOfNationalSameIndustry,null);if(mode==='flag'){assert.equal(r.national.flags.measure,'D');assert.equal(r.national.status,'flagged-uninterpreted');}}const f=await fixture(t,g=>{g.state[0].naics.footnote='uninterpreted';});assert.equal((await read(f,opts)).states[0].count,null);});
test('rehashed duplicate, year, NAICS identity, provenance, negative and fractional defects reject',async t=>{for(const modify of [g=>g.state.push(g.state[0]),g=>g.state[0].reference_year=2024,g=>g.state[0].naics.code='23bad',g=>g.state[0].provenance.transformation_version='future',g=>g.state[0].measures.nonemployer_establishments=-1,g=>g.state[0].measures.nonemployer_establishments=0.5,g=>g.state[0].record_id='wrong']){const f=await fixture(t,modify);await assert.rejects(read(f,opts));}});
test('hash mismatch, corrupt gzip and hardlink inputs reject',async t=>{const f=await fixture(t);await assert.rejects(read({...f,manifestSha256:'0'.repeat(64)},opts));const file=path.join(path.dirname(f.manifestPath),'derived/industry/state.jsonl.gz');await writeFile(file,'corrupt');await assert.rejects(read(f,opts));const second=await fixture(t),alias=second.manifestPath+'.alias';await link(second.manifestPath,alias);await assert.rejects(read(second,opts));await unlink(alias);});
test('closed selection, sparse state arrays and preaborted native read reject before retained access',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(native({...opts,signal:controller.signal}),{name:'AbortError'});for(const bad of [{...opts,referenceYear:2024},{...opts,naics:'construction'},{...opts,states:['72']},{...opts,states:['01','01']},{...opts,states:new Array(1)},{...opts,source:'url'}])await assert.rejects(native(bad));});

test('rehashed corrupt gzip and gzip-contained malformed UTF8 reach decoder rejection',async t=>{for(const raw of [Buffer.from('not-gzip'),gzipSync(Buffer.from([0xff,0x0a]))]){const f=await fixture(t),m=JSON.parse(await readFile(f.manifestPath,'utf8')),a=m.artifacts.find(x=>x.geography_type==='state');await writeFile(path.join(path.dirname(f.manifestPath),a.path),raw);a.bytes=raw.length;a.sha256=hash(raw);const text=JSON.stringify(m);await writeFile(f.manifestPath,text);f.manifestSha256=hash(text);await assert.rejects(read(f,opts),error=>raw[0]===0x6e?error.code==='Z_DATA_ERROR':error.code==='ERR_ENCODING_INVALID_ENCODED_DATA');}});

test('all51 native-dimension fixture retains nonzero residual and unnormalized national shares',async t=>{const states='01 02 04 05 06 08 09 10 11 12 13 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 44 45 46 47 48 49 50 51 53 54 55 56'.split(' ');const f=await fixture(t,g=>{g.state=states.map(s=>row(s,1));});const result=await read(f,opts);assert.equal(result.stateReconciliation.knownStateCount,51);assert.equal(result.stateReconciliation.knownStateEstablishments,51);assert.equal(result.stateReconciliation.nationalMinusStateSum,49);assert.equal(result.states.reduce((n,s)=>n+s.percentOfNationalSameIndustry,0),51);const filtered=await read(f,{...opts,states:['01']});assert.equal(filtered.states[0].percentOfNationalSameIndustry,1);assert.deepEqual(filtered.stateReconciliation,result.stateReconciliation);});

test('rehashed overlong and unterminated decompressed lines reject',async t=>{for(const content of [JSON.stringify({...row('01',1),extra:'x'.repeat(17000)})+'\n',JSON.stringify(row('01',1))]){const f=await fixture(t),m=JSON.parse(await readFile(f.manifestPath,'utf8')),a=m.artifacts.find(x=>x.geography_type==='state'),raw=gzipSync(content);await writeFile(path.join(path.dirname(f.manifestPath),a.path),raw);a.bytes=raw.length;a.sha256=hash(raw);a.record_count=1;m.coverage.normalized_state_industry_rows=1;const manifest=JSON.stringify(m);await writeFile(f.manifestPath,manifest);await assert.rejects(read({...f,manifestSha256:hash(manifest)},opts),/alignment rejected/);}});

test('cooperative abort after decompression has consumed its first chunk returns no result',async t=>{const f=await fixture(t,g=>{g.national=Array.from({length:512},(_,i)=>row(null,1,{NAICS2022:String(1000+i)}));});const controller=new AbortController(),signal=controller.signal,originalAdd=signal.addEventListener.bind(signal),originalCheck=signal.throwIfAborted.bind(signal);let streaming=false,checks=0;
 // The helper registers its stream abort listener only after verified file reads.
 signal.addEventListener=(...args)=>{if(args[0]==='abort')streaming=true;return originalAdd(...args);};
 signal.throwIfAborted=()=>{if(streaming&&++checks===3)controller.abort();originalCheck();};
 await assert.rejects(read(f,{...opts,signal}),{name:'AbortError'});assert.equal(checks,3);assert.equal(signal.aborted,true);
});
