import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { projectOperationalIndustryEvidence, readOperationalIndustryEvidenceSummary } from "./operational-industry-evidence-summary.mjs";

const industries=["retail-consumer","health-care","financial-services","transportation","construction","tax-exempt-organizations","sales-tax-outlets","local-business-licenses","childcare"];
const counts=(present=0,zero=0,absent=0)=>({"evidence-present":present,"measured-zero":zero,"source-did-not-publish-for-zip":0,"outside-source-evidence-union":0,"outside-source-denominator":0,"absent-from-retained-source-rows":absent,"unavailable":0});
function fixture(){const dimensions=Array.from({length:51},(_,i)=>({id:`d${i}`,industries:i<9?[industries[i]]:[],...(i<9?{}:{unmapped_reason:"Not equivalent."})}));return{crosswalk:{schema_version:"exact-zip-operational-industry-crosswalk@1.0.0",matrix_schema_version:"national-exact-zip-industry-summary-view@3.1.0",operational_industries:industries,dimensions,claims:{cross_source_entity_counts_additive:false,business_completeness:null,industry_completeness:null,current_operation_verified:false,zip4_joined:false}},summary:{schema_version:"national-exact-zip-industry-summary-view@3.1.0",source_dimensions:51,zip5_rows:48194,industry_cells:2457894,dimensions:dimensions.map(row=>({id:row.id,temporal_qualification:{source_key:row.id,source_release_id:`release-${row.id}`,source_reference_at:null,review_due_at:null,review_qualification:"unmeasured",semantic_class:"non-active-reporting",source_status_term:"fixture"}}))},disposition:{state_name:"Test",state_fips:"01",zip5_rows:2,dimensions:Object.fromEntries(dimensions.map((row,i)=>[row.id,{dimension_id:row.id,derived_evidence_status_counts:i===0?counts(1,0,1):counts(0,2,0)}]))}}}

test("projects nonadditive dimension availability and ZIP-dimension measurement reach",()=>{const f=fixture(),value=projectOperationalIndustryEvidence({...f,state:"AL"}),retail=value.industries[0];assert.equal(retail.mapped_dimensions,1);assert.equal(retail.dimension_evidence_availability_percent,100);assert.equal(retail.measured_zip_dimension_cells,1);assert.equal(retail.zip_dimension_cell_denominator,2);assert.equal(retail.exact_zip_measurement_reach_percent,50);assert.equal(value.unmapped_dimensions.length,42);assert.equal(value.claims.business_completeness,null);assert.equal(value.claims.industry_completeness,null);assert.equal(value.claims.business_or_entity_counts_added,false);assert.equal(value.claims.zip4_joined,false)});
test("rejects missing, duplicate, unknown, and claim-widening crosswalk entries",()=>{for(const mutate of [f=>f.crosswalk.dimensions.pop(),f=>f.crosswalk.dimensions[1].id="d0",f=>f.crosswalk.dimensions[0].id="unknown",f=>f.crosswalk.dimensions[0].industries=["unknown"],f=>f.crosswalk.dimensions[9].unmapped_reason=undefined,f=>f.crosswalk.claims.industry_completeness=100]){const f=fixture();mutate(f);assert.throws(()=>projectOperationalIndustryEvidence({...f,state:"AL"}),/rejected/)}});
test("reads the registered retained state evidence and preserves provenance and nonclaims",async()=>{const value=await readOperationalIndustryEvidenceSummary({state:"NJ"});assert.equal(value.state.code,"NJ");assert.equal(value.industries.length,9);assert.equal(value.industries.find(row=>row.id==="childcare").mapped_dimensions,11);assert.equal(value.provenance.summary_release_id,"national-exact-zip-industry-evidence-matrix-e5287a4adc3f9b657499135d2f5641dac05b67359d9dbaf14ad4b72d598c97c9");assert.match(value.provenance.crosswalk_sha256,/^[a-f0-9]{64}$/);assert.equal(value.claims.network_requests,0);assert.equal(value.claims.runtime_writes,0);assert.equal(value.special_geography.included_in_state_denominator,false)});
test("crosswalk contains the exact retained v3.1 dimension roster once",async()=>{const config=JSON.parse(await readFile(new URL("../config/exact-zip-operational-industry-crosswalk.json",import.meta.url)));assert.equal(config.dimensions.length,51);assert.equal(new Set(config.dimensions.map(row=>row.id)).size,51);assert.equal(config.dimensions.filter(row=>row.industries.length===0).every(row=>row.unmapped_reason),true);assert.equal(config.dimensions.some(row=>row.id==="cross_source_entity_resolution_linkage_evidence"&&row.industries.length===0),true)});
