import test from 'node:test';
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { readFile } from 'node:fs/promises';
import { mkdtemp, rename, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { hashRegularFileStable, loadReportedOrganizationZipEvidenceStatusView } from './reported-organization-zip-evidence-status.mjs';
import { reportedOrganizationZipEvidenceStatusHttp } from './reported-organization-zip-evidence-status-http.mjs';

const verified={release_id:'broad-organization-zip-evidence-20260923-002630301Z-9cdbdcd319f2',manifest_sha256:'ee5896c32daf5b50a8b1ac44717ccd4a3005b91d1ca65dfc869c04490d441a7e',created_at:'2026-09-23T00:26:30.301Z',artifact_count:108,artifact_bytes:1572588359,conservation:{input_record_total:14340575,address_row_total:14340583,eligible_zip_row_total:9940777,missing_or_ineligible_row_total:4399806},sources:[{state:'DE',address_rows:66667,eligible_zip_rows:66502,missing_or_ineligible_rows:165,record_level_access:'local-review-only'}],claims:{}};
test('view projects only governed aggregates and keeps evidence non-additive',async()=>{const view=await loadReportedOrganizationZipEvidenceStatusView({verifier:async()=>verified});assert.equal(view.totals.address_rows,14340583);assert.equal(view.classification.contributes_to_general_business_or_site_totals,false);assert.equal(view.sources[0].record_level_access,'local-review-only');assert.equal(view.governance.ordinary_response_record_rows,0);assert.equal(JSON.stringify(view).includes('zip5'),false)});
function request(method='GET',headers={}){const value=new EventEmitter();value.method=method;value.headers=headers;value.readableEnded=true;value.readableLength=0;value.resume=()=>{};return value}
test('HTTP accepts only empty GET and redacts verifier failure',async()=>{const calls=[];const json=(_r,status,payload)=>calls.push({status,payload});await reportedOrganizationZipEvidenceStatusHttp(request(),{},new URL('http://x/status'),async()=>({ok:true}),json);assert.equal(calls[0].status,200);await reportedOrganizationZipEvidenceStatusHttp(request('POST'),{},new URL('http://x/status'),async()=>{},json);assert.equal(calls[1].status,405);await reportedOrganizationZipEvidenceStatusHttp(request(),{},new URL('http://x/status?q=1'),async()=>{},json);assert.equal(calls[2].status,400);await reportedOrganizationZipEvidenceStatusHttp(request('GET',{'content-length':'2'}),{},new URL('http://x/status'),async()=>{},json);assert.equal(calls[3].status,400);await reportedOrganizationZipEvidenceStatusHttp(request('GET',{'transfer-encoding':'chunked'}),{},new URL('http://x/status'),async()=>{},json);assert.equal(calls[4].status,400);await reportedOrganizationZipEvidenceStatusHttp(request(),{},new URL('http://x/status'),async()=>{throw Error('secret path')},json);assert.equal(calls[5].status,503);assert.equal(JSON.stringify(calls[5]).includes('secret'),false)});
test('selection schema pins every safety declaration and forbids extras',async()=>{const schema=JSON.parse(await readFile(new URL('../config/schemas/reported-organization-zip-evidence-status.schema.json',import.meta.url),'utf8'));assert.equal(schema.additionalProperties,false);for(const key of ['ordinary_response_record_rows','zip_member_lists_exposed','network_requests','production_pointer_changes','plan57_executed'])assert(schema.required.includes(key));});
test('verifier source enforces canonical single-link config schema manifest and artifact files',async()=>{const source=await readFile(new URL('./reported-organization-zip-evidence-status.mjs',import.meta.url),'utf8');assert.match(source,/realpath\(absolute\) !== absolute/);assert.match(source,/SCHEMA_SHA256/);assert.match(source,/stat\.nlink !== 1/);assert.match(source,/filesBelow\(releaseDirectory\)/)});
test('stable file hashing rejects a path replacement after bytes are read',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'reported-org-race-'));try{const target=path.join(directory,'artifact.gz');const replacement=path.join(directory,'replacement.gz');await writeFile(target,Buffer.alloc(1024,1));await writeFile(replacement,Buffer.alloc(1024,2));await assert.rejects(()=>hashRegularFileStable(target,{afterRead:async()=>{await rm(target);await rename(replacement,target)}}),/unavailable/)}finally{await rm(directory,{recursive:true,force:true})}});
test('UI is stale-safe and exposes no mutation controls',async()=>{const ui=await readFile(new URL('../app/reported-organization-zip-evidence-status.tsx',import.meta.url),'utf8');assert.match(ui,/AbortController/);assert.match(ui,/sequence\.current/);assert.doesNotMatch(ui,/>Download|>Build|>Approve|>Execute/);const server=await readFile(new URL('./server.mjs',import.meta.url),'utf8');assert.match(server,/reported-organization-zip-evidence-status/)});
