import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {readFile} from 'node:fs/promises';
import {retainedChildcareZipHttp} from './retained-childcare-zip-http.mjs';
import {readRetainedChildcareZipEvidence} from './retained-childcare-zip-evidence.mjs';
function fixture(){const request=Object.assign(new EventEmitter(),{method:'GET',headers:{}}),response=Object.assign(new EventEmitter(),{writableEnded:false,setHeader(){}}),out=[];return {request,response,out,json:(_r,status,value)=>out.push({status,value})};}
test('disconnect cancels in-flight lookup and never emits a late response',async()=>{const f=fixture();let seen;const pending=retainedChildcareZipHttp(f.request,f.response,new URL('http://local/?zip=00501'),{authorize:()=>true,reader:async({signal})=>{seen=signal;return new Promise(resolve=>signal.addEventListener('abort',()=>resolve({zip5:'00501'})));}},f.json);await Promise.resolve();await Promise.resolve();f.response.emit('close');await pending;assert.equal(seen.aborted,true);assert.equal(f.out.length,0);assert.equal(f.response.listenerCount('close'),0);});
test('same-ZIP malicious reader envelopes are rejected',async()=>{const base=await readRetainedChildcareZipEvidence({zip5:'00000'});for(const mutate of [v=>{v.claims.deduplicated_business_count=2;},v=>{v.status='retained-candidate-evidence-present';},v=>{v.extra=true;},v=>{v.manifest_sha256='0'.repeat(64);},v=>{v.sources.PA.extra=true;},v=>{v.summary.accepted_candidate_rows++;},v=>{v.row={zip5:'00000',zip4:null,hospital:{directory_rows:0,reported_states:{}},nursing_home:{directory_rows:0,reported_states:{}}};},v=>{v.available=false;}]){const value=structuredClone(base);mutate(value);const f=fixture();await retainedChildcareZipHttp(f.request,f.response,new URL('http://local/?zip=00000'),{authorize:()=>true,reader:async()=>value},f.json);assert.equal(f.out[0].status,503);}});
test('protected exact ZIP empty GET rejects unauthorized, duplicates, extra options and body before reading',async()=>{for(const mode of ['auth','duplicate','extra','body','zip4']){const f=fixture();if(mode==='body')f.request.headers['content-length']='1';let calls=0;await retainedChildcareZipHttp(f.request,f.response,new URL(`http://local/?zip=${mode==='zip4'?'00501-0001':'00501'}${mode==='duplicate'?'&zip=00501':mode==='extra'?'&build=1':''}`),{authorize:()=>mode!=='auth',reader:async()=>{calls++;} },f.json);assert.equal(calls,0);assert.equal(f.out[0].status,mode==='auth'?401:400);}});
test('returns source-bound ZIP and applies deadline/disconnect without late success',async t=>{const f=fixture();await retainedChildcareZipHttp(f.request,f.response,new URL('http://local/?zip=00501'),{authorize:()=>true,reader:async({zip5,signal})=>{assert.ok(signal);return readRetainedChildcareZipEvidence({zip5,signal});}},f.json);assert.equal(f.out[0].status,200);
 t.mock.timers.enable({apis:['setTimeout']});const timeout=fixture();let signal;const pending=retainedChildcareZipHttp(timeout.request,timeout.response,new URL('http://local/?zip=00501'),{authorize:()=>true,reader:async o=>{signal=o.signal;return new Promise(resolve=>o.signal.addEventListener('abort',()=>resolve({zip5:'00501'})));}},timeout.json);await Promise.resolve();await Promise.resolve();t.mock.timers.tick(30000);await pending;assert.equal(signal.aborted,true);assert.equal(timeout.out[0].status,503);assert.equal(timeout.request.listenerCount('aborted'),0);
});
test('runner wires the exact ZIP route only after the shared control-plane guard',async()=>{const source=await readFile(new URL('./server.mjs',import.meta.url),'utf8'),guard=source.indexOf('controlPlane.authorize(request);'),route=source.indexOf("url.pathname === '/api/business-map/retained-childcare-zip-evidence'");assert.ok(guard>=0&&route>guard);assert.match(source,/retainedChildcareZipHttp\(request,response,url,\{authorize:\(\)=>true\},json\)/);});
