import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {copyFile,mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {APP_ROOT} from './paths.mjs';
import {resetNationalIrsEoBmfCoverageRuntimeCacheForTest} from './national-irs-eo-bmf-organization-coverage.mjs';
import {readRetainedIrsStateAdjacentEvidence} from './retained-irs-state-adjacent-evidence.mjs';

const DATASET='national-irs-eo-bmf-organization-coverage',RELEASE='national-irs-eo-bmf-organization-coverage-cf09e08b19c01912';
const sha=value=>createHash('sha256').update(value).digest('hex');
async function fixture(t){await mkdir(path.join(APP_ROOT,'data','tmp'),{recursive:true});const root=await mkdtemp(path.join(APP_ROOT,'data','tmp','irs-adjacent-'));t.after(()=>rm(root,{recursive:true,force:true}));const source=path.join(APP_ROOT,'data',DATASET),target=path.join(root,'data',DATASET),release=path.join(target,'releases',RELEASE);await mkdir(release,{recursive:true});await copyFile(path.join(source,'current.json'),path.join(target,'current.json'));for(const name of ['manifest.json','coverage-summary.json','jurisdictions.jsonl','zip5-coverage.jsonl'])await copyFile(path.join(source,'releases',RELEASE,name),path.join(release,name));return{root,target,release};}
async function rewriteManifest(f,mutate){const file=path.join(f.release,'manifest.json'),manifest=JSON.parse(await readFile(file));mutate(manifest);const bytes=Buffer.from(`${JSON.stringify(manifest,null,2)}\n`);await writeFile(file,bytes);const pointerFile=path.join(f.target,'current.json'),pointer=JSON.parse(await readFile(pointerFile));pointer.manifest_sha256=sha(bytes);await writeFile(pointerFile,`${JSON.stringify(pointer,null,2)}\n`);resetNationalIrsEoBmfCoverageRuntimeCacheForTest();}

test('authoritative IRS reader conserves all 51 states/DC and selects one adjacent cohort',async()=>{resetNationalIrsEoBmfCoverageRuntimeCacheForTest();const states='AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY'.split(' ');let total=0;for(const state of states){const result=await readRetainedIrsStateAdjacentEvidence({state});assert.equal(result.state,state);assert.equal(result.included_in_broad_layer,false);assert.equal(result.included_in_dataset_availability,false);total+=result.organization_count;}const rows=(await readFile(path.join(APP_ROOT,'data',DATASET,'releases',RELEASE,'jurisdictions.jsonl'),'utf8')).trim().split(/\r?\n/).map(JSON.parse),territoryTotal=rows.filter(row=>!states.includes(row.code)).reduce((sum,row)=>sum+row.organization_count,0);assert.equal(total+territoryTotal,1_955_841);});
test('authoritative verifier rejects a self-consistent pointer, manifest and artifact rewrite',async t=>{const f=await fixture(t),summaryFile=path.join(f.release,'coverage-summary.json'),summary=JSON.parse(await readFile(summaryFile));summary.privacy_warning+=' Rewritten.';const bytes=Buffer.from(`${JSON.stringify(summary,null,2)}\n`);await writeFile(summaryFile,bytes);await rewriteManifest(f,manifest=>{manifest.privacy_warning=summary.privacy_warning;const descriptor=manifest.artifacts.find(row=>row.path==='coverage-summary.json');descriptor.bytes=bytes.length;descriptor.sha256=sha(bytes);});await assert.rejects(readRetainedIrsStateAdjacentEvidence({root:f.root,state:'AL'}),/authority changed|identity changed|release identity/);});
test('authoritative verifier rejects duplicate jurisdiction artifact descriptors',async t=>{const f=await fixture(t);await rewriteManifest(f,manifest=>manifest.artifacts.splice(2,0,structuredClone(manifest.artifacts.find(row=>row.path==='jurisdictions.jsonl'))));await assert.rejects(readRetainedIrsStateAdjacentEvidence({root:f.root,state:'AL'}),/artifact inventory changed|artifact metadata changed/);});
test('adjacent reader honors cancellation before authoritative retained I/O',async()=>{await assert.rejects(readRetainedIrsStateAdjacentEvidence({state:'AL',signal:AbortSignal.abort()}),error=>error.name==='AbortError');});
