import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {mkdir,readdir,readFile,writeFile,rm,unlink,rmdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {APP_ROOT} from './paths.mjs';
import {inspectUtChildcareEditionIndex as inspect,discoverUtChildcareEdition as native,discoverUtChildcareEditionWithTestTransport as run,verifyUtChildcareEditionDiscoveryWithTestInput as verify,verifyUtChildcareEditionDiscovery as nativeVerify} from './ut-childcare-edition-discovery.mjs';
const ROOT=path.join(APP_ROOT,'data/tmp/ut-childcare-edition-discovery'),edition='September-2026',opts={edition};
const url='https://dlbc.utah.gov/information-for-the-public/reports/',pdf=e=>'https://dlbc.utah.gov/wp-content/uploads/All-Child-Care-Licensing-Facilities-Report-'+e+'.pdf';
const html=e=>Buffer.from('<!doctype html><html><a href="'+pdf(e)+'">Regulated child care programs</a></html>'),sha=v=>createHash('sha256').update(v).digest('hex');
const response=(body=html(edition),type='text/html')=>new Response(body,{headers:{'content-type':type}});
async function track(t){await mkdir(ROOT,{recursive:true});const before=new Set(await readdir(ROOT));assert.ok(!before.has('.fixture-policy.json'));await writeFile(path.join(ROOT,'.fixture-policy.json'),await readFile(path.join(APP_ROOT,'config/source-policies/ut-childcare-edition-discovery.json')),{flag:'wx'});t.after(async()=>{await unlink(path.join(ROOT,'.fixture-policy.json'));for(const name of await readdir(ROOT)){if(before.has(name))continue;assert.match(name,/^[a-f0-9-]{36}$/);const target=path.join(ROOT,name);assert.equal(path.dirname(target),ROOT);await rm(target,{recursive:true,force:true});}});}
test('explicit linked edition separates retained reference from candidate, neither proves PDF freshness',()=>{
 const retained=inspect(html(edition),edition);assert.equal(retained.status,'retained-reference-still-listed');assert.equal(retained.sourceFreshnessVerified,false);
 const next=inspect(html('October-2026'),'October-2026');assert.equal(next.status,'different-edition-candidate');assert.equal(next.pdfContentsVerified,false);assert.equal(next.pdfBodyRequiredBeforeAdoption,true);
 assert.throws(()=>inspect(html(edition),'October-2026'));assert.throws(()=>inspect(html(edition),'latest'));assert.throws(()=>inspect(Buffer.from([0xff]),edition));assert.throws(()=>inspect(Buffer.alloc(1048577),edition));
});
test('index parser rejects hostile URLs and ignores scripts/comments',()=>{
 for(const href of [pdf(edition).replace('dlbc.utah.gov','evil.invalid'),pdf(edition)+'?secret=x',pdf(edition)+'#x',pdf(edition).replace('https://','https://user@')])assert.throws(()=>inspect(Buffer.from('<html><a href="'+href+'">x</a></html>'),edition));
 for(const wrapper of ['<!--<a href="'+pdf(edition)+'">x</a>-->','<script><a href="'+pdf(edition)+'">x</a></script>'])assert.throws(()=>inspect(Buffer.from('<html>'+wrapper+'</html>'),edition));
});
test('one fixed GET, immutable receipt and offline verifier preserve internal synthetic claims',async t=>{await track(t);let count=0;const out=await run(async(u,o)=>{count++;assert.equal(u,url);assert.equal(o.method,'GET');assert.equal(o.redirect,'manual');assert.equal(o.credentials,'omit');return response();},opts);const m=await verify(out.manifestPath,out.manifestSha256);assert.equal(count,1);assert.equal(m.claims.nativeTransportVerified,false);assert.equal(m.claims.pdfDownloaded,false);assert.equal(m.claims.selectedRowsPublished,false);assert.equal(m.result.status,'retained-reference-still-listed');assert.equal(m.requests.length,1);assert.ok(m.artifacts.every(a=>a.exportPolicy==='internal'));await assert.rejects(nativeVerify(out.manifestPath,out.manifestSha256));assert.ok(!(await readdir(ROOT)).includes('.source-lease'));});
test('wrong status/type, cap and invalid HTML fail once; complete index retained on conformance failure',async t=>{await track(t);for(const result of [()=>new Response(null,{status:302}),()=>response('x','application/pdf'),()=>response(Buffer.alloc(1048577)),()=>response('<html>Missing report</html>')]){let calls=0,recovery;await assert.rejects(run(()=>{calls++;return result();},opts),e=>{recovery=e.recovery;return true;});assert.equal(calls,1);const files=await readdir(recovery.directory);assert.ok(!files.includes('manifest.json'));const receipt=JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8'));assert.equal(receipt.status,'FAILED');if(files.includes('index.html'))assert.equal(receipt.completedRestrictedSourceArtifacts[0].sha256,sha(await readFile(path.join(recovery.directory,'index.html'))));}});
test('preabort and closed options make no request; cooperative cancellation releases lease',async t=>{await track(t);const c=new AbortController();c.abort();await assert.rejects(native({...opts,signal:c.signal}),{name:'AbortError'});await assert.rejects(run(()=>assert.fail(),{...opts,url}));const d=new AbortController();let recovery;await assert.rejects(run((u,o)=>{d.abort();o.signal.throwIfAborted();},{...opts,signal:d.signal}),e=>{recovery=e.recovery;return true;});assert.equal(JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8')).status,'CANCELLED');assert.ok(!(await readdir(ROOT)).includes('.source-lease'));});
test('shared lease excludes simultaneous and foreign owners without takeover',async t=>{await track(t);let entered,release;const begun=new Promise(r=>entered=r),held=new Promise(r=>release=r);const first=run(async()=>{entered();await held;return response();},opts);await begun;await assert.rejects(run(()=>assert.fail(),opts),/lease unavailable/);release();await first;const lease=path.join(ROOT,'.source-lease');await writeFile(lease,'FOREIGN');try{await assert.rejects(run(()=>assert.fail(),opts),/lease unavailable/);assert.equal(await readFile(lease,'utf8'),'FOREIGN');}finally{await unlink(lease);}});
test('noncooperative request retains lease, bounded abort and late disposal',async t=>{await track(t);const c=new AbortController();let entered,resolve,cancelled=false;const begun=new Promise(r=>entered=r);const pending=run(()=>{entered();return new Promise(r=>resolve=r);},{...opts,signal:c.signal});await begun;c.abort();await assert.rejects(pending,e=>e.recovery.sourceLeaseRetained===true);await assert.rejects(run(()=>assert.fail(),opts),/lease unavailable/);resolve({body:{cancel:async()=>{cancelled=true;}}});await new Promise(r=>setImmediate(r));assert.equal(cancelled,true);await unlink(path.join(ROOT,'.source-lease'));});
test('nonsettling response read and cleanup are bounded and retain unresolved lease',async t=>{await track(t);const c=new AbortController();let timer;const started=Date.now();await assert.rejects(run(()=>{timer=setTimeout(()=>c.abort(),20);return {status:200,redirected:false,headers:new Headers({'content-type':'text/html'}),body:{getReader:()=>({read:()=>new Promise(()=>{}),cancel:()=>new Promise(()=>{}),releaseLock(){}})}};},{...opts,signal:c.signal}),e=>e.recovery.sourceLeaseRetained===true);clearTimeout(timer);assert.ok(Date.now()-started<3000);await unlink(path.join(ROOT,'.source-lease'));});
test('postpublication failures preserve independently verifiable manifest with inspection required',async t=>{await track(t);let recovery;await assert.rejects(run(()=>response(),opts,stage=>{if(stage==='after-publication')throw Error('PRIVATE');}),e=>{recovery=e.recovery;assert.equal(e.code,'UT_EDITION_PUBLICATION_UNCERTAIN');assert.doesNotMatch(e.message,/PRIVATE/);return true;});assert.equal(recovery.inspectionRequired,true);await verify(recovery.manifestPath,recovery.manifestSha256);});
test('lease cleanup failure and changed owner preserve recovery without deleting changed lease',async t=>{await track(t);for(const changed of [false,true]){let recovery;await assert.rejects(run(()=>response(),opts,async(stage,{leasePath})=>{if(stage==='before-lease-cleanup'){if(changed){await unlink(leasePath);await mkdir(leasePath);}else throw Error('PRIVATE');}}),e=>{recovery=e.recovery;return true;});assert.equal(recovery.inspectionRequired,true);assert.equal(recovery.leaseCleanupFailed,true);await verify(recovery.manifestPath,recovery.manifestSha256);if(changed)await rmdir(path.join(ROOT,'.source-lease'));else await unlink(path.join(ROOT,'.source-lease'));}});
test('rehashed discovery result and changed source bytes fail independent verification',async t=>{await track(t);const out=await run(()=>response(),opts),m=JSON.parse(await readFile(out.manifestPath,'utf8'));m.result.sourceFreshnessVerified=true;const raw=JSON.stringify(m)+'\n';await writeFile(out.manifestPath,raw);await assert.rejects(verify(out.manifestPath,sha(raw)));});
test('verifier rejects unknown options, accessors and non-string hashes before reading',async()=>{
 await assert.rejects(nativeVerify('not-a-path','0'.repeat(64),{hook(){}}));
 await assert.rejects(nativeVerify('not-a-path',['0'.repeat(64)]));
 await assert.rejects(nativeVerify('not-a-path','0'.repeat(64),Object.defineProperty({},'signal',{get(){assert.fail('accessor executed');}})));
});
test('CLI help and invalid argument handling are offline and do not accept arbitrary source URLs',async()=>{
 const cli=path.join(APP_ROOT,'scripts/discover-ut-childcare-edition.mjs');
 const help=await promisify(execFile)(process.execPath,[cli,'--help']);assert.match(help.stdout,/no PDF download/);
 await assert.rejects(promisify(execFile)(process.execPath,[cli,'--url','https://example.invalid']),e=>e.code===1&&/no automatic retry/.test(e.stderr));
});
test('same-inode lease payload replacement is preserved with inspection recovery',async t=>{await track(t);await assert.rejects(run(()=>response(),opts,async(stage,{leasePath})=>{if(stage==='before-lease-cleanup')await writeFile(leasePath,'REPLACED SAME INODE');}),e=>e.recovery.inspectionRequired&&e.recovery.sourceLeaseRetained);const lease=path.join(ROOT,'.source-lease');assert.equal(await readFile(lease,'utf8'),'REPLACED SAME INODE');await unlink(lease);});
test('policy drift after request prevents publication and preserves original policy evidence',async t=>{await track(t);const file=path.join(ROOT,'.fixture-policy.json'),original=await readFile(file);let recovery;await assert.rejects(run(()=>response(),opts,async stage=>{if(stage==='before-publication')await writeFile(file,Buffer.concat([original,Buffer.from(' ')]));}),e=>{recovery=e.recovery;return true;});assert.ok(!(await readdir(recovery.directory)).includes('manifest.json'));assert.deepEqual(await readFile(path.join(recovery.directory,'policy.json')),original);});
test('complete HTTP rejection bodies and response status remain inspectable with policy bytes',async t=>{await track(t);let recovery;await assert.rejects(run(()=>new Response('Publisher temporarily unavailable',{status:503,headers:{'content-type':'text/plain'}}),opts),e=>{recovery=e.recovery;return true;});const failed=JSON.parse(await readFile(path.join(recovery.directory,'failure.json'),'utf8'));assert.equal(failed.requests[0].status,503);assert.equal(failed.requests[0].expectedContentTypeMatched,false);assert.equal(await readFile(path.join(recovery.directory,'index.html'),'utf8'),'Publisher temporarily unavailable');assert.ok((await readdir(recovery.directory)).includes('policy.json'));});
