import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
const require=createRequire(import.meta.url),code=await readFile(new URL('../app/workspace-views.tsx',import.meta.url),'utf8');
const pageCode=await readFile(new URL('../app/page.tsx',import.meta.url),'utf8');
const nodes=t=>!t||typeof t!=='object'?[]:Array.isArray(t)?t.flatMap(nodes):[t,...nodes(t.props?.children)];
const text=t=>t==null||typeof t==='boolean'?'':typeof t!=='object'?String(t):Array.isArray(t)?t.map(text).join(''):text(t.props?.children);
function harness(request,sourceCode=code){const values=[],effects=[],cleanup=[],deps=[];let cursor=0,effectCursor=0;const exports={},focused=[];runInNewContext(ts.transpileModule(sourceCode,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,AbortController,URLSearchParams,document:{getElementById:id=>({focus:()=>focused.push(id)})},require:name=>name==='./runner-client'?{runnerJson:request}:name==='./business-intelligence'?{StateAvailabilityChoropleth:()=>null}:name.startsWith('./census-')?{default:()=>null}:name.startsWith('./')?{}:name==='react'?{useMemo:fn=>fn(),useState:initial=>{const n=cursor++;if(!(n in values))values[n]=initial;return[values[n],v=>values[n]=v];},useEffect:(effect,nextDeps)=>{const n=effectCursor++;if(!deps[n]||nextDeps.some((value,index)=>value!==deps[n][index])){deps[n]=nextDeps;effects.push(()=>{cleanup[n]?.();cleanup[n]=effect();});}}}:require(name)});return{focused,render:(name,props={})=>{cursor=0;effectCursor=0;const tree=exports[name](props);effects.splice(0).forEach(effect=>effect());return tree;},close:()=>cleanup.forEach(fn=>fn?.())};}
function pageHarness(){const values=[];let cursor=0;const exports={};const marker=name=>Object.defineProperty(function(){return null;},'name',{value:name});const WorkspaceTabs=marker('WorkspaceTabs'),OperationsTabs=marker('OperationsTabs'),CoverageWorkspace=marker('CoverageWorkspace'),ZipEconomyWorkspace=marker('ZipEconomyWorkspace'),DataOperations=marker('DataOperations'),ConnectorCatalog=marker('ConnectorCatalog'),BusinessIntelligence=marker('BusinessIntelligence'),CoverageExplorer=marker('CoverageExplorer'),BenchmarkReview=marker('BenchmarkReview');const workspaceViews={workspaceTabs:['Coverage','Industries','ZIP Economy','Operations'],operationsTabs:['Jobs','Collection','Evidence','Connectors'],WorkspaceTabs,OperationsTabs,CoverageWorkspace,ZipEconomyWorkspace};const react={useCallback:fn=>fn,useMemo:fn=>fn(),useRef:initial=>({current:initial}),useState:initial=>{const n=cursor++;if(!(n in values))values[n]=typeof initial==='function'?initial():initial;return[values[n],next=>values[n]=typeof next==='function'?next(values[n]):next];},useEffect:()=>{}};runInNewContext(ts.transpileModule(pageCode,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,AbortController,Blob,URL,document:{createElement:()=>({click(){}})},window:{requestAnimationFrame:callback=>callback()},require:name=>name==='react'?react:name==='./workspace-views'?workspaceViews:name==='./data-operations'?{default:DataOperations}:name==='./connector-catalog'?{default:ConnectorCatalog}:name==='./business-intelligence'?{default:BusinessIntelligence}:name==='./coverage-explorer'?{default:CoverageExplorer}:name==='./benchmark-review'?{default:BenchmarkReview}:name==='./text-size-control'?{default:marker('TextSizeControl')}:name==='./runner-client'?{downloadRunnerArtifact:async()=>({}),runnerJson:async()=>({})}:require(name)});return{render:()=>{cursor=0;return exports.default();}};}
const flush=()=>new Promise(resolve=>setTimeout(resolve,0));

test('shared geography distinguishes unknown from measured nonmembership, preserves zero and exposes proof gaps accessibly',()=>{
 const h=harness(()=>assert.fail()),base={zip5:'00501',governed_zcta:{status:'not-in-denominator',geoid:null}};
 let tree=h.render('ZipGeographySummary',{view:base});assert.match(text(tree),/Unknown — no registry classification/);assert.doesNotMatch(text(tree),/Not in the selected governed/);assert.match(text(tree),/Unknown — not measured/);assert.equal(tree.props.style.fontSize,'1rem');assert.equal(tree.props.style.overflowWrap,'anywhere');assert.equal(tree.props.style.minWidth,0);assert.equal(nodes(tree).filter(n=>n.type==='summary').length,1);
 tree=h.render('ZipGeographySummary',{view:{...base,classification:{class:'valid-format-source-reported-no-same-code-zcta'},coverage_status:'record-level-source-contribution',selected_coverage_geography:{zcta_status:'missing',zcta_geoid:null,spatial_zip_polygon_membership_status:'not-included',material_county_count:0,county_assignment:'not-uniquely-assigned'},zip_quality:{usps_operational_evidence:{evidence_status:'unverified',operational_status:null},unresolved_proof_gap_codes:['gap-one']},coverage_gap_codes:['gap-one','gap-two']}});
 assert.match(text(tree),/Not in the selected governed ZCTA denominator/);assert.match(text(tree),/Material county intersections0/);assert.match(text(tree),/not uniquely assigned/);assert.match(text(tree),/USPS operational evidenceunverified/);assert.match(text(tree),/Current USPS operation is not verified/);assert.match(text(tree),/2 reported/);assert.equal(nodes(tree).filter(n=>n.type==='li').length,2);assert.match(text(tree),/not segment-filtered/);assert.match(text(tree),/neither resolves these geography gaps/);
 tree=h.render('ZipGeographySummary',{view:{...base,governed_zcta:{status:'included',geoid:'00501'},selected_coverage_geography:{material_county_count:2,county_assignment:'not-uniquely-assigned',spatial_zip_polygon_membership_status:'cross-boundary'}}});assert.match(text(tree),/included/);assert.match(text(tree),/cross boundary/);assert.match(text(tree),/Material county intersections2/);
});

test('geography is shared once across subtabs; observed overview precedes GDP and ordinary pending failures are not absence',async()=>{
 const pending=[],h=harness((url,{signal})=>new Promise((resolve,reject)=>pending.push({url,signal,resolve,reject})));
 let tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.props?.['aria-label']==='Economy ZIP5').props.onChange({target:{value:'00501'}});tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});nodes(tree).find(n=>n.props?.id==='economy-tab-1').props.onClick();tree=h.render('ZipEconomyWorkspace');assert.match(text(tree),/contributions are loading; absence has not been established/);assert.doesNotMatch(text(tree),/No verified positive segment evidence/);
 pending[0].reject(Error('fixture'));await flush();tree=h.render('ZipEconomyWorkspace');assert.match(text(tree),/contributions are unavailable/);assert.doesNotMatch(text(tree),/No verified positive segment evidence/);
 nodes(tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});h.render('ZipEconomyWorkspace');pending[1].resolve({zip5:'00501',evidence_status:'selected-evidence-present',governed_zcta:{status:'included',geoid:'00501'},bindings:{},counts:{physical_sites:3},category_evidence:{category_id:'all',status:'no-selected-positive-evidence',positive_source_contributions:[]}});await flush();tree=h.render('ZipEconomyWorkspace');assert.match(text(tree),/No verified positive segment evidence in the selected release/);
 const summary=tree=>nodes(tree).filter(n=>typeof n.type==='function'&&n.type.name==='ZipGeographySummary');assert.equal(summary(tree).length,1);
 nodes(tree).find(n=>n.props?.id==='economy-tab-0').props.onClick();tree=h.render('ZipEconomyWorkspace');assert.equal(summary(tree).length,1);assert.ok(text(tree).indexOf('Observed evidence · ZIP')<text(tree).indexOf('Total extrapolated ZIP GDP'));assert.match(text(tree),/not filtered by the business segment/);
 nodes(tree).find(n=>n.props?.['aria-label']==='Economy business segment').props.onChange({target:{value:'childcare'}});tree=h.render('ZipEconomyWorkspace');assert.equal(summary(tree).length,0);assert.equal(pending[1].signal.aborted,true);h.close();
});

test('reviewed segment options retain exact childcare selection through keyboard tab navigation and empty ordinary evidence',async()=>{
 const stub=code.replace("import ZipEvidenceQualificationPanel from './zip-evidence-qualification-panel';",'function ZipEvidenceQualificationPanel(){return null;}');
 const requests=[];const h=harness(async(url)=>{requests.push(url);return {zip5:'00501',evidence_status:'selected-evidence-present',governed_zcta:{geoid:null},bindings:{coverage_release_id:'coverage-fixture',registry_release_id:'registry-fixture'},category_evidence:{category_id:'childcare',status:'no-selected-positive-evidence',semantics:'No ordinary contribution is not qualification support.',positive_source_contributions:[]}};},stub);
 let tree=h.render('ZipEconomyWorkspace');const select=nodes(tree).find(n=>n.props?.['aria-label']==='Economy business segment');assert.equal(select.type,'select');assert.equal(select.props.onKeyDown,undefined);
 const options=nodes(select).filter(n=>n.type==='option').map(n=>n.props.value);for(const id of ['childcare','licensed-businesses','registrations-nonprofits'])assert.ok(options.includes(id));assert.ok(!options.includes('aggregate-baseline-context'));
 select.props.onChange({target:{value:'childcare'}});nodes(tree).find(n=>n.props?.['aria-label']==='Economy ZIP5').props.onChange({target:{value:'00501'}});tree=h.render('ZipEconomyWorkspace');assert.equal(requests.length,0);
 nodes(tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});tree=h.render('ZipEconomyWorkspace');await flush();
 nodes(tree).find(n=>n.props?.id==='economy-tab-0').props.onKeyDown({key:'ArrowRight',preventDefault(){}});tree=h.render('ZipEconomyWorkspace');assert.equal(h.focused.at(-1),'economy-tab-1');assert.equal(nodes(tree).find(n=>n.props?.id==='economy-tab-1').props.tabIndex,0);
 assert.deepEqual(requests,['/api/business-map/zip-inspector?zip=00501&category=childcare']);assert.match(text(tree),/Childcare · ZIP 00501/);assert.match(text(tree),/not a measured zero/);assert.match(text(tree),/missing contributions do not mean qualification is unsupported or zero/);
 assert.ok(nodes(tree).find(n=>typeof n.type==='function'&&n.type.name==='ZipEvidenceQualificationPanel').props.supplied,'mounted panel always uses the inspector envelope, including unknown responses');
 const panel=nodes(tree).find(n=>typeof n.type==='function'&&n.type.name==='ZipEvidenceQualificationPanel');assert.equal(panel.props.categoryId,'childcare');assert.equal(panel.props.coverageReleaseId,'coverage-fixture');assert.equal(panel.props.registryReleaseId,'registry-fixture');
 nodes(tree).find(n=>n.props?.id==='economy-tab-1').props.onKeyDown({key:'ArrowLeft',preventDefault(){}});tree=h.render('ZipEconomyWorkspace');assert.equal(nodes(tree).find(n=>n.props?.['aria-label']==='Economy business segment').props.value,'childcare');h.close();
});

test('ZIP qualification mounts only in Business segments with exact bound ordinary evidence and navigation state',async()=>{
 const stub=code.replace("import ZipEvidenceQualificationPanel from './zip-evidence-qualification-panel';",'function ZipEvidenceQualificationPanel(){return null;}');
 const pending=[];const h=harness((url,{signal})=>new Promise(resolve=>pending.push({url,signal,resolve})),stub);
 const panel=tree=>nodes(tree).find(n=>typeof n.type==='function'&&n.type.name==='ZipEvidenceQualificationPanel');
 let tree=h.render('ZipEconomyWorkspace',{stateCode:'PA'});assert.equal(panel(tree),undefined);
 nodes(tree).find(n=>n.props?.id==='economy-tab-1').props.onClick();tree=h.render('ZipEconomyWorkspace',{stateCode:'PA'});assert.equal(panel(tree).props.zip,'');assert.equal(pending.length,0);
 nodes(tree).find(n=>n.props?.['aria-label']==='Economy ZIP5').props.onChange({target:{value:'00501'}});tree=h.render('ZipEconomyWorkspace',{stateCode:'PA'});nodes(tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});tree=h.render('ZipEconomyWorkspace',{stateCode:'PA'});assert.equal(panel(tree).props.coverageReleaseId,'');
 pending[0].resolve({zip5:'00501',evidence_status:'selected-evidence-present',governed_zcta:{geoid:null},bindings:{coverage_release_id:'coverage-fixture',registry_release_id:'registry-fixture'},category_evidence:{category_id:'all',status:'positive-source-contribution',semantics:'Ordinary source evidence',positive_source_contributions:[{source_id:'ordinary-source',source_release_id:'r1',positive_counts:{record_count:7}}]}});await flush();
 tree=h.render('ZipEconomyWorkspace',{stateCode:'PA'});assert.equal(panel(tree).props.coverageReleaseId,'coverage-fixture');assert.equal(panel(tree).props.registryReleaseId,'registry-fixture');assert.equal(panel(tree).props.categoryId,'all');assert.match(text(tree),/ordinary-source/);
 tree=h.render('ZipEconomyWorkspace',{stateCode:'MD'});assert.equal(panel(tree).props.navigationState,'MD');assert.match(text(tree),/ordinary-source/);assert.equal(pending.length,1);
 nodes(tree).find(n=>n.props?.['aria-label']==='Economy business segment').props.onChange({target:{value:'health-care'}});tree=h.render('ZipEconomyWorkspace',{stateCode:'MD'});assert.equal(panel(tree).props.coverageReleaseId,'');assert.equal(panel(tree).props.categoryId,'health-care');assert.doesNotMatch(text(tree),/ordinary-source/);
 nodes(tree).find(n=>n.props?.id==='economy-tab-2').props.onClick();tree=h.render('ZipEconomyWorkspace',{stateCode:'MD'});assert.equal(panel(tree),undefined);h.close();
});
test('outside denominator panel separates configuration from measurements and is keyboard readable',()=>{
 const h=harness(()=>assert.fail()),comparison={available:true,denominator_version:'national-reporting-ten@1.0.0+broad',configuration:{path:'config/industry-segments.json',version:1,sha256:'a'.repeat(64)},catalog:{path:'config/national-reporting-sources.json',schema_version:'national-reporting-catalog@2.0.0',denominator_version:'national-reporting-ten@1.0.0',predecessor_sha256:'b'.repeat(64)},industries:['construction','sales-tax-outlets','local-business-licenses','childcare'].map(id=>({id,sources:[{id:`state-${id}`,scope:'state',publisher_states:['MN'],manual_selection_required:true}]}))};
 const tree=h.render('OutsideNationalReporting',{comparison}),value=text(tree);
 assert.match(value,/Outside national reporting denominator/);assert.match(value,/not evidence of acquisition or nationwide coverage/);assert.match(value,/totals above are unchanged/);assert.match(value,/State-only: MN/);assert.match(value,/manual selection required/);assert.match(value,/national-reporting-ten@1.0.0/);assert.match(value,/a{64}/);
 assert.equal(nodes(tree).find(row=>row.props?.role==='region').props.tabIndex,0);assert.equal(nodes(tree).filter(row=>row.type==='summary').length,1);assert.equal(nodes(tree).filter(row=>row.props?.scope==='row').length,4);assert.doesNotMatch(value,/\d+%/);
 for(const comparison of [undefined,{available:false,industries:null},{available:true,industries:null}]){const unavailable=text(h.render('OutsideNationalReporting',{comparison}));assert.match(unavailable,/Scope comparison unavailable/);assert.doesNotMatch(unavailable,/No excluded configured industry/);assert.doesNotMatch(unavailable,/\d+%/);}
});
test('both Coverage and Industries mount the same outside-denominator panel',()=>{
 for(const industries of [false,true]){const h=harness(async()=>({available:false,jurisdictions:[]})),tree=h.render('CoverageWorkspace',{industries});assert.equal(nodes(tree).filter(row=>typeof row.type==='function'&&row.type.name==='OutsideNationalReporting').length,1);h.close();}
});

test('simplified Coverage and Industries keep retained county evidence separate and follow the selected state',()=>{
 const stub=code.replace("import {RetainedCountyWorkspace} from './retained-county-panel';",'function RetainedCountyWorkspace(){return null;}');
 for(const industries of [false,true]){const h=harness(async()=>({available:false,jurisdictions:[]}),stub),tree=h.render('CoverageWorkspace',{industries,stateCode:'MD'});const panel=nodes(tree).find(row=>typeof row.type==='function'&&row.type.name==='RetainedCountyWorkspace');assert.equal(panel.props.stateCode,'MD');assert.equal(nodes(tree).filter(row=>row.type===panel.type).length,1);h.close();}
});
test('national expectation summary uses explicit dataset-state cells and null denominators',()=>{const h=harness(()=>assert.fail());const summary=h.render('summarizeAvailability',[{available:1,measured:2,denominator:3,unmeasured:1},{available:0,measured:0,denominator:3,unmeasured:3}]);assert.equal(summary.expected,6);assert.equal(summary.unmeasured,4);assert.equal(summary.availabilityPercent,50);assert.equal(summary.connectivityPercent,50);assert.equal(summary.connected,1);assert.equal(h.render('summarizeAvailability',[]).availabilityPercent,null);});
test('ZIP segment changes abort stale requests, reject mismatched scopes and allow same-ZIP retry',async()=>{const requests=[];const h=harness((url,options)=>new Promise((resolve,reject)=>requests.push({url,signal:options.signal,resolve,reject})));let tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.props?.['aria-label']==='Economy ZIP5').props.onChange({target:{value:'00501'}});tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});tree=h.render('ZipEconomyWorkspace');assert.match(requests[0].url,/zip=00501&category=all/);nodes(tree).find(n=>n.props?.['aria-label']==='Economy business segment').props.onChange({target:{value:'health-care'}});tree=h.render('ZipEconomyWorkspace');assert.equal(requests[0].signal.aborted,true);assert.match(requests[1].url,/category=health-care/);requests[0].resolve({zip5:'00501',category_evidence:{category_id:'all'},counts:{physical_sites:999}});requests[1].reject(Error('fixture'));await flush();tree=h.render('ZipEconomyWorkspace');assert.match(text(tree),/Exact ZIP evidence is unavailable/);assert.doesNotMatch(text(tree),/999/);nodes(tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});h.render('ZipEconomyWorkspace');assert.equal(requests.length,3);requests[2].resolve({zip5:'00501',category_evidence:{category_id:'all'}});await flush();assert.match(text(h.render('ZipEconomyWorkspace')),/did not match/);h.close();assert.equal(requests[2].signal.aborted,true);});
test('same-code governed ZCTA triggers exact readiness lookup and renders governed status, lineage and limitations',async()=>{
 const requests=[],h=harness((url,options)=>new Promise((resolve,reject)=>requests.push({url,signal:options.signal,resolve,reject})));let tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.props?.['aria-label']==='Economy ZIP5').props.onChange({target:{value:'00501'}});tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});h.render('ZipEconomyWorkspace');
 requests[0].resolve({zip5:'00501',evidence_status:'selected-evidence-present',governed_zcta:{status:'included',geoid:'00501'},bindings:{},counts:{physical_sites:0,establishments:0,employer_establishments:0},category_evidence:{category_id:'all',status:'no-selected-positive-evidence',positive_source_contributions:[]}});await flush();tree=h.render('ZipEconomyWorkspace');assert.equal(requests[1].url,'/api/business-map/zcta-economic-readiness?zcta=00501');
 const response={schema_version:'zcta-economic-readiness-view@1.0.0',zcta:'00501',available:true,status:'found',readiness:{population_2020:1200,housing_units_2020:500,zbp_publication_status:'zbp-and-zcta',relationship_count:2,material_relationship_count:1,state_fips:['36'],county_geoids:['36001','36003'],direct_county_gdp_count:1,missing_county_gdp_geoids:['36003'],direct_gdp_relationship_coverage:.5,model_status:'withheld',blockers:['no-official-zip-gdp','no-governed-allocation-model']},provenance:{release_id:'readiness-r1',manifest_sha256:'a'.repeat(64),artifact_sha256:'b'.repeat(64),created_at:'2026-10-02T00:00:00.000Z',geography_release_id:'geo-r1',input_releases:[{dataset_id:'bea-regional-gdp',release_id:'bea-r1',manifest_sha256:'c'.repeat(64)}]},limitations:['No ZIP GDP is produced.'],claims:{official_zip_code:false,active_businesses:false,numeric_gdp_or_demographic_allocation:false}};requests[1].resolve(response);await flush();tree=h.render('ZipEconomyWorkspace');assert.ok(nodes(tree).find(n=>typeof n.type==='function'&&n.type.name==='ZctaEconomicReadinessPanel'));const value=text(h.render('ZctaEconomicReadinessPanel',{view:response}));assert.match(value,/model_statuswithheld/);assert.match(value,/no-official-zip-gdp/);assert.match(value,/Direct county GDP coverage1 \/ 2 relationships · 50\.0%/);assert.match(value,/2020 Census population1,200 · aggregate context/);assert.match(value,/ZIP Business Patterns statuszbp-and-zcta/);assert.match(value,/readiness-r1/);assert.match(value,/bea-regional-gdp/);assert.match(value,/No ZIP GDP is produced/);
 nodes(tree).find(n=>n.props?.id==='economy-tab-2').props.onClick();tree=h.render('ZipEconomyWorkspace');assert.match(text(tree),/2020 Census housing units500 · aggregate context only/);assert.match(text(tree),/not a current estimate, demographic weight/);nodes(tree).find(n=>n.props?.id==='economy-tab-1').props.onClick();tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.props?.categoryId==='all'&&typeof n.props?.onRetry==='function').props.onRetry();tree=h.render('ZipEconomyWorkspace');assert.equal(requests[1].signal.aborted,true);assert.equal(nodes(tree).some(n=>typeof n.type==='function'&&n.type.name==='ZctaEconomicReadinessPanel'),false);requests[2].reject(Error('retry failed'));await flush();assert.match(text(h.render('ZipEconomyWorkspace')),/Exact ZIP evidence is unavailable/);assert.doesNotMatch(text(h.render('ZipEconomyWorkspace')),/readiness-r1/);h.close();
});
test('readiness is not applicable without same-code ZCTA and stale or mismatched responses cannot render',async()=>{
 const requests=[],h=harness((url,options)=>new Promise((resolve,reject)=>requests.push({url,signal:options.signal,resolve,reject})));let tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.props?.['aria-label']==='Economy ZIP5').props.onChange({target:{value:'99999'}});tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});h.render('ZipEconomyWorkspace');requests[0].resolve({zip5:'99999',governed_zcta:{status:'matched',geoid:'99999'},bindings:{},category_evidence:{category_id:'all',status:'no-selected-positive-evidence',positive_source_contributions:[]}});await flush();tree=h.render('ZipEconomyWorkspace');assert.equal(requests.length,1);assert.match(text(tree),/readiness: not applicable/);
 nodes(tree).find(n=>n.props?.['aria-label']==='Economy ZIP5').props.onChange({target:{value:'00501'}});tree=h.render('ZipEconomyWorkspace');nodes(tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});h.render('ZipEconomyWorkspace');requests[1].resolve({zip5:'00501',governed_zcta:{status:'included',geoid:'00501'},bindings:{},category_evidence:{category_id:'all',status:'no-selected-positive-evidence',positive_source_contributions:[]}});await flush();tree=h.render('ZipEconomyWorkspace');assert.equal(requests[2].url,'/api/business-map/zcta-economic-readiness?zcta=00501');
 nodes(tree).find(n=>n.props?.['aria-label']==='Economy business segment').props.onChange({target:{value:'health-care'}});tree=h.render('ZipEconomyWorkspace');assert.equal(requests[2].signal.aborted,true);requests[2].resolve({zcta:'00501',available:true,readiness:{model_status:'should-not-render'}});await flush();assert.doesNotMatch(text(h.render('ZipEconomyWorkspace')),/should-not-render/);
 requests[3].resolve({zip5:'00501',governed_zcta:{status:'included',geoid:'00501'},bindings:{},category_evidence:{category_id:'health-care',status:'no-selected-positive-evidence',positive_source_contributions:[]}});await flush();h.render('ZipEconomyWorkspace');requests[4].resolve({schema_version:'zcta-economic-readiness-view@1.0.0',zcta:'00501',available:false,status:'not-found',readiness:null,provenance:{release_id:'malformed-prohibited',manifest_sha256:'a'.repeat(64),artifact_sha256:'b'.repeat(64),created_at:'2026-10-02T00:00:00.000Z',geography_release_id:'geo-r1',input_releases:[]},limitations:[],claims:{official_zip_code:true,active_businesses:false,numeric_gdp_or_demographic_allocation:false}});await flush();assert.match(text(h.render('ZipEconomyWorkspace')),/Economic-model readiness is unavailable/);assert.doesNotMatch(text(h.render('ZipEconomyWorkspace')),/malformed-prohibited/);h.close();
});
test('readiness validator fails closed on malformed same-ZCTA envelopes and prohibited claims',()=>{const h=harness(()=>assert.fail()),base={schema_version:'zcta-economic-readiness-view@1.0.0',zcta:'00501',available:false,status:'not-found',readiness:null,provenance:{release_id:'r1',manifest_sha256:'a'.repeat(64),artifact_sha256:'b'.repeat(64),created_at:'2026-10-02T00:00:00.000Z',geography_release_id:'g1',input_releases:[]},limitations:[],claims:{official_zip_code:false,active_businesses:false,numeric_gdp_or_demographic_allocation:false}},row={population_2020:1,housing_units_2020:1,zbp_publication_status:'zbp-and-zcta',relationship_count:2,material_relationship_count:1,state_fips:['36'],county_geoids:['36001','36003'],direct_county_gdp_count:1,missing_county_gdp_geoids:['36003'],direct_gdp_relationship_coverage:.5,model_status:'withheld',blockers:['no-official-zip-gdp']},found={...base,available:true,status:'found',readiness:row};assert.equal(h.render('validZctaEconomicReadiness',base),true);assert.equal(h.render('validZctaEconomicReadiness',found),true);for(const value of [{...base,status:'found'},{...base,claims:{...base.claims,official_zip_code:true}},{...base,provenance:{...base.provenance,manifest_sha256:'bad'}},{...base,provenance:{...base.provenance,created_at:'2026-10-02'}},{...found,readiness:{...row,zbp_publication_status:'published'}},{...found,readiness:{...row,state_fips:['36','36']}},{...found,readiness:{...row,county_geoids:['36001','36001']}},{...found,readiness:{...row,missing_county_gdp_geoids:['36003','36003'],direct_county_gdp_count:0,direct_gdp_relationship_coverage:0}},{...found,readiness:{...row,blockers:['duplicate','duplicate']}},{...base,extra:true},null])assert.equal(h.render('validZctaEconomicReadiness',value),false);});
test('ZIP economy subtabs support keyboard navigation and show missing demographic inputs',()=>{const h=harness(()=>assert.fail());let tree=h.render('ZipEconomyWorkspace',{stateCode:'MN'});assert.match(text(tree),/A ZIP is not inferred/);const first=nodes(tree).find(n=>n.props?.id==='economy-tab-0');first.props.onKeyDown({key:'End',preventDefault(){}});tree=h.render('ZipEconomyWorkspace');assert.equal(h.focused.at(-1),'economy-tab-2');assert.match(text(tree),/Modeled output withheld; not observed/);assert.match(text(tree),/No governed demographic input/);assert.match(text(tree),/Missing inputs prevent modeling/);});
test('state choropleth uses scoped matrix availability only, hatches null and preserves browser wheel zoom',async()=>{const mapCode=await readFile(new URL('../app/business-intelligence.tsx',import.meta.url),'utf8');const h=harness(async()=>({available:true,features:['AK','DC'].map((code,index)=>({geometry:{type:'Polygon',coordinates:[[[-100,40],[-99,40],[-99,41],[-100,40]]]},properties:{geoid:String(index),postal_abbreviation:code,name:code,heat_value:999999,business_count:999999}}))}),mapCode);let selected;const props={rows:[{code:'AK',name:'Alaska',available:0,measured:2,unmeasured:1,percent:0},{code:'DC',name:'District',available:0,measured:0,unmeasured:3,percent:null}],selected:'',categoryLabel:'Health care',onSelect:code=>selected=code};h.render('StateAvailabilityChoropleth',props);await flush();const tree=h.render('StateAvailabilityChoropleth',props),paths=nodes(tree).filter(node=>node.type==='path'&&node.props.role==='button');assert.equal(paths.length,2);assert.match(paths[0].props['aria-label'],/Health care: 0.0% dataset availability/);assert.match(nodes(tree).find(node=>node.type==='svg').props['aria-label'],/Health care dataset availability/);assert.match(paths[1].props.fill,/availability-unmeasured/);assert.doesNotMatch(paths[0].props['aria-label'],/999999/);assert.equal(nodes(tree).find(node=>node.type==='svg').props.onWheel,undefined);paths[1].props.onKeyDown({key:'Enter',preventDefault(){}});assert.equal(selected,'DC');h.close();});
test('four primary tabs expose arrow Home End keyboard navigation',()=>{let selected;const h=harness(()=>assert.fail()),tree=h.render('WorkspaceTabs',{value:'Coverage',onChange:value=>selected=value}),tabs=nodes(tree).filter(n=>n.props?.role==='tab');assert.deepEqual(tabs.map(tab=>tab.props.children),['Coverage','Industries','ZIP Economy','Operations']);assert.equal(tabs[0].props['aria-selected'],true);for(const[key,index]of [['ArrowLeft',3],['ArrowRight',1],['End',3],['Home',0]]){let prevented=false;tabs[0].props.onKeyDown({key,preventDefault:()=>prevented=true});assert.equal(prevented,true);assert.equal(selected,tabs[index].props.children);assert.equal(h.focused.at(-1),`workspace-tab-${index}`);}});
test('operations subtabs group former workspaces and support keyboard navigation',()=>{let selected;const h=harness(()=>assert.fail()),tree=h.render('OperationsTabs',{value:'Jobs',onChange:value=>selected=value}),tabs=nodes(tree).filter(n=>n.props?.role==='tab');assert.deepEqual(tabs.map(tab=>tab.props.children),['Jobs','Collection','Evidence','Connectors']);tabs[0].props.onKeyDown({key:'End',preventDefault(){}});assert.equal(selected,'Connectors');assert.equal(h.focused.at(-1),'operations-tab-3');});
test('coverage exposes category scope and differentiates zero null and missing evidence',async()=>{let signal;const h=harness(async(url,options)=>{assert.match(url,/goal-completion\?category=general-business/);signal=options.signal;return{available:true,release_id:'fixture-release',denominator:{version:'fixture-v7'},categories:['general-business','health-care'],jurisdictions:[{code:'AK',name:'Alaska',available:0,measured:2,unmeasured:1,denominator:3,percent:0},{code:'DC',name:'District of Columbia',available:0,measured:0,unmeasured:3,denominator:3,percent:null}],selected:null};});h.render('CoverageWorkspace');await flush();const tree=h.render('CoverageWorkspace'),value=text(tree),selector=nodes(tree).find(n=>n.props?.['aria-label']==='Coverage category');assert.deepEqual(nodes(selector).filter(n=>n.type==='option').map(n=>text(n)),['Broad state organization layer','Health care']);assert.match(value,/Broad state organization layer availability/);assert.match(value,/0\.0%/);assert.match(value,/Unmeasured/);assert.match(value,/fixture-v7/);assert.match(value,/not completeness of all businesses/);assert.match(value,/3 unmeasured/);assert.match(value,/100% availability applies only to the selected category/);assert.equal(nodes(tree).filter(n=>n.props?.['aria-pressed']!==undefined).length,2);h.close();assert.equal(signal.aborted,true);});
test('industries leads with source summary and provides a consistent selected-state aside',async()=>{const h=harness(async url=>url.includes('state-summary')?{available:true,categories:[{id:'health-care',label:'Health care'}],national_category_counts:{'health-care':120},national_category_percent_of_collected_evidence:{'health-care':12.5},states:[{postal_abbreviation:'MD',state_name:'Maryland',category_counts:{'health-care':8},percent_of_category_nationwide:{'health-care':6.7}}]}:{available:true,release_id:'matrix',denominator:{version:'v1'},categories:['health-care'],jurisdictions:[{code:'MD',name:'Maryland',available:1,measured:2,unmeasured:1,denominator:3,percent:50,broad_layer_gap:false}],selected:{code:'MD',category:{datasets:[]}}});h.render('CoverageWorkspace',{industries:true,stateCode:'MD',categoryCode:'health-care'});await flush();const tree=h.render('CoverageWorkspace',{industries:true,stateCode:'MD',categoryCode:'health-care'}),value=text(tree);assert.ok(value.indexOf('Industry summary')<value.indexOf('Expected dataset × state cells'));assert.match(value,/National evidence rows120/);assert.match(value,/MD evidence rows8/);assert.equal(nodes(tree).find(n=>n.props?.['aria-label']==='Selected industry and state summary').type,'aside');assert.match(value,/All-business completeness: Unknown/);h.close();});
test('coverage aside shows the exact retained temporal boundary and fails closed',()=>{const h=harness(()=>assert.fail()),sha='a'.repeat(64),view={schema_version:'national-business-temporal-claim-matrix-view@1.0.0',available:true,scope:'retained-source-classification-only',summary:{source_count:30,source_defined_current_membership_sources:22,non_active_directory_registration_reporting_sources:7,annual_aggregate_sources:1,broad_state_dc_source_defined_active:11,broad_state_dc_total:51,broad_state_dc_gaps:40,verified_current_complete_jurisdictions:0,verified_current_complete_gaps:51,active_business_count:null,completeness_percentage:null},provenance:{release_id:`national-business-temporal-claim-matrix-${sha}`,manifest_sha256:sha,artifact_sha256:sha,created_at:'2026-10-03T00:00:00.000Z',registry_release_id:'registry-r1',registry_manifest_sha256:sha,coverage_release_id:'coverage-r1',coverage_manifest_sha256:sha},claims:{network_requests:0,current_pointer_written:false,production_enrollment:false,current_operations_verified:false,active_business_count:false,completeness_inferred:false}};assert.equal(h.render('validTemporalMatrix',view),true);const value=text(h.render('TemporalCoverageSummary',{view,error:false}));assert.match(value,/Source classifications30/);assert.match(value,/Source-defined current-membership cohorts22/);assert.match(value,/Broad state\/DC sources11 \/ 51/);assert.match(value,/Broad state\/DC gaps40/);assert.match(value,/Verified-current-complete jurisdictions0 \/ 51/);assert.match(value,/Active-business countUnknown/);assert.match(value,/All-business completenessUnknown/);assert.match(value,/does not independently verify current operation/);assert.match(value,new RegExp(sha));for(const malformed of [{...view,summary:{...view.summary,active_business_count:1}},{...view,claims:{...view.claims,current_operations_verified:true}},{...view,provenance:{...view.provenance,manifest_sha256:'bad'}},null])assert.equal(h.render('validTemporalMatrix',malformed),false);assert.doesNotMatch(text(h.render('TemporalCoverageSummary',{view:null,error:true})),/30|22|11 \/ 51/);});
test('coverage labels retained IRS evidence as adjacent and outside broad availability',async()=>{const payload={available:true,release_id:'matrix-release',denominator:{version:'matrix-v'},categories:['general-business'],jurisdictions:[{code:'AK',name:'Alaska',available:0,measured:0,unmeasured:1,denominator:1,percent:null,broad_layer_gap:true}],selected:{code:'AK',category:{datasets:[{dataset_id:'broad',label:'Broad jurisdiction organization layer',availability_status:'unmeasured',state_record_count:null,gap_reason:'missing'}]},adjacent_evidence:[{dataset_id:'national-irs-eo-bmf-organization-coverage',evidence_kind:'adjacent-retained-national-organization-cohort',included_in_broad_layer:false,included_in_dataset_availability:false,release_id:'irs-release',source_release_id:'source-release',source_date:'2026-08-11',state:'AK',row_semantics:'IRS EO BMF current-extract organization record grouped by reported filing-address state; not a physical site',organization_count:5822,record_zcta_count:4951,record_nonpolygon_count:871,limitations:['Tax-exempt filing-address evidence only; not a broad state organization layer.','Not all businesses, all nonprofits, unique businesses, current operations, or verified physical sites.','Same-code ZCTA evidence does not establish current USPS validity.','Excluded from generic totals, matrix datasets, availability, denominator, and broad-layer gap status.']}]}};const h=harness(async()=>payload);h.render('CoverageWorkspace',{stateCode:'AK'});await flush();const value=text(h.render('CoverageWorkspace',{stateCode:'AK'}));assert.match(value,/Adjacent retained evidence — outside availability/);assert.match(value,/5,822/);assert.match(value,/reported filing-address state/);assert.match(value,/Same-code ZCTA records4,951/);assert.match(value,/Nonpolygon records871/);assert.match(value,/not a broad state organization layer/);assert.match(value,/Excluded from generic totals, matrix datasets, availability, denominator, and broad-layer gap status/);assert.match(value,/Broad state organization layer: Gap/);h.close();});
test('unavailable coverage and unmounted late reads cannot display success counts',async()=>{let resolve;const h=harness(()=>new Promise(r=>resolve=r));h.render('CoverageWorkspace');h.close();resolve({available:true,jurisdictions:[{code:'XX'}]});await flush();assert.match(text(h.render('CoverageWorkspace')),/Verifying/);const missing=harness(async()=>({available:false,status:'missing-enrollment'}));missing.render('CoverageWorkspace');await flush();assert.match(text(missing.render('CoverageWorkspace')),/Completion is unmeasured/);});
test('ZIP economics explicitly withholds unsupported GDP and demographic allocations',()=>{const h=harness(()=>assert.fail('no request before valid ZIP')),tree=h.render('ZipEconomyWorkspace'),value=text(tree);assert.match(value,/Unavailable — no governed model/);assert.match(value,/explicitly prohibits ZIP\/ZCTA allocation/);assert.match(value,/not output or GDP weights/);nodes(tree).find(n=>n.props?.id==='economy-tab-2').props.onClick();const demographic=h.render('ZipEconomyWorkspace');assert.match(text(demographic),/Race: unavailable/);const select=nodes(demographic).find(n=>n.props?.['aria-label']==='Demographic dimension');assert.deepEqual(nodes(select).filter(n=>n.type==='option').map(n=>text(n)),['Race','Lineage / ancestry','Sex','Age']);select.props.onChange({target:{value:'Age'}});assert.match(text(h.render('ZipEconomyWorkspace')),/Age: unavailable/);});
test('readiness panels expose non-additive pharmacy status and exact ZIP blockers',async()=>{const sha='a'.repeat(64),view={schema_version:'business-intelligence-readiness-view@1.0.0',source_replay_performed:false,pharmacy_overlay:{status:'verified-retained-nonadditive-overlay',release_id:`national-nppes-pharmacy-registry-overlay-${sha}`,manifest_sha256:sha,created_at:'2026-10-03T10:38:45.404Z',summary:{pharmacy_rows:89077,exact_npi_membership_matches:89077,already_present_same_source_identity:89077,generic_business_additivity_delta:0,organization_additions:0,site_additions:0,establishment_additions:0,zip5_denominator_rows:48194,positive_zip5_rows:15376},claims:{active_npi_enumeration_as_of:'2026-08-09',nationwide_completeness:false,authoritative_current_usps_zip_denominator:null,current_operation:null,licensed_pharmacy:null,production_enrollment:false}},zip_denominator:{status:'blocked-on-authorized-authoritative-input',release_id:`zip-denominator-admission-readiness-${sha}`,manifest_sha256:sha,readiness_sha256:sha,observed_at:'2026-10-03T10:40:43.007Z',blockers:['missing-authorized-authoritative-usps-zip-artifact','authoritative-current-usps-denominator-unverified'],retained_zip_evidence:{rows:48194,usps_unverified:48194,same_code_census_zcta:33791,source_contributed_outside_zcta:14361},claims:{authoritative_current_usps_zip_denominator:null,valid_usps_zip_count:null,zip_validity_classified:false,production_execution:false}}},h=harness(async()=>view);assert.equal(h.render('validBiReadiness',view),true);h.render('BusinessIntelligenceReadiness',{mode:'industry'});await flush();assert.match(text(h.render('BusinessIntelligenceReadiness',{mode:'industry'})),/non-additive/);h.close();const zip=harness(async()=>view);zip.render('BusinessIntelligenceReadiness',{mode:'zip'});await flush();const output=text(zip.render('BusinessIntelligenceReadiness',{mode:'zip'}));assert.match(output,/missing-authorized-authoritative-usps-zip-artifact/);assert.match(output,/Valid USPS ZIP countUnknown/);zip.close();const invalid=[{...view,pharmacy_overlay:{...view.pharmacy_overlay,claims:{...view.pharmacy_overlay.claims,active_npi_enumeration_as_of:'2026-02-30'}}},{...view,pharmacy_overlay:{...view.pharmacy_overlay,summary:{...view.pharmacy_overlay.summary,positive_zip5_rows:48195}}},{...view,zip_denominator:{...view.zip_denominator,retained_zip_evidence:{...view.zip_denominator.retained_zip_evidence,same_code_census_zcta:-1}}},{...view,zip_denominator:{...view.zip_denominator,retained_zip_evidence:{...view.zip_denominator.retained_zip_evidence,source_contributed_outside_zcta:48195}}},{...view,zip_denominator:{...view.zip_denominator,retained_zip_evidence:{...view.zip_denominator.retained_zip_evidence,rows:Number.MAX_SAFE_INTEGER+1,usps_unverified:Number.MAX_SAFE_INTEGER+1}}}];for(const malformed of invalid)assert.equal(h.render('validBiReadiness',malformed),false);});
test('page navigation reaches every operations view, scopes job actions and preserves tab context',()=>{const h=pageHarness(),component=(tree,name)=>nodes(tree).find(node=>typeof node.type==='function'&&node.type.name===name),buttons=tree=>nodes(tree).filter(node=>node.type==='button').map(text);let tree=h.render();const coverage=component(tree,'CoverageWorkspace');assert.equal(coverage.props.industries,undefined);coverage.props.onStateChange('MD');coverage.props.onCategoryChange('health-care');component(tree,'WorkspaceTabs').props.onChange('Operations');tree=h.render();assert.equal(component(tree,'OperationsTabs').props.value,'Jobs');assert.match(text(tree),/Execution queue/);assert.ok(buttons(tree).some(label=>label.includes('Import')));assert.ok(buttons(tree).some(label=>label.includes('Export')));assert.ok(buttons(tree).some(label=>label.includes('New job')));
 for(const [tab,name] of [['Collection','DataOperations'],['Evidence','BusinessIntelligence'],['Connectors','ConnectorCatalog']]){component(tree,'OperationsTabs').props.onChange(tab);tree=h.render();assert.equal(component(tree,name).type.name,name);assert.ok(!buttons(tree).some(label=>label.includes('Import')));assert.ok(!buttons(tree).some(label=>label.includes('Export')));assert.ok(!buttons(tree).some(label=>label.includes('New job')));if(tab==='Evidence'){assert.equal(component(tree,'CoverageExplorer').type.name,'CoverageExplorer');assert.equal(component(tree,'BenchmarkReview').type.name,'BenchmarkReview');}}
 component(tree,'WorkspaceTabs').props.onChange('ZIP Economy');tree=h.render();assert.equal(component(tree,'ZipEconomyWorkspace').props.stateCode,'MD');component(tree,'WorkspaceTabs').props.onChange('Industries');tree=h.render();const industries=component(tree,'CoverageWorkspace');assert.equal(industries.props.industries,true);assert.equal(industries.props.stateCode,'MD');assert.equal(industries.props.categoryCode,'health-care');component(tree,'WorkspaceTabs').props.onChange('Operations');tree=h.render();assert.equal(component(tree,'OperationsTabs').props.value,'Connectors');assert.equal(component(tree,'ConnectorCatalog').type.name,'ConnectorCatalog');component(tree,'OperationsTabs').props.onChange('Jobs');tree=h.render();assert.match(text(tree),/Execution queue/);assert.ok(buttons(tree).some(label=>label.includes('New job')));});
