import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import {readRetainedChildcareZipEvidence} from './retained-childcare-zip-evidence.mjs';

const require=createRequire(import.meta.url),componentSource=await readFile(new URL('../app/workspace-views.tsx',import.meta.url),'utf8'),registration=JSON.parse(await readFile(new URL('../config/datasets/retained-childcare-zip-evidence.json',import.meta.url),'utf8'));
const text=value=>value==null||typeof value==='boolean'?'':typeof value!=='object'?String(value):Array.isArray(value)?value.map(text).join(''):text(value.props?.children);
function harness(request){const values=[],effects=[],cleanups=[],dependencies=[];let cursor=0,effectCursor=0;const exports={};runInNewContext(ts.transpileModule(componentSource,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,resolveJsonModule:true}}).outputText,{exports,AbortController,URLSearchParams,document:{getElementById:()=>null},require:name=>name==='../config/datasets/retained-childcare-zip-evidence.json'?registration:name==='./runner-client'?{runnerJson:request}:name==='./business-intelligence'?{StateAvailabilityChoropleth:()=>null}:name.startsWith('./census-')?{default:()=>null}:name.startsWith('./')?{}:name==='react'?{useMemo:fn=>fn(),useState:initial=>{const index=cursor++;if(!(index in values))values[index]=initial;return[values[index],next=>values[index]=next];},useEffect:(effect,next)=>{const index=effectCursor++;if(!dependencies[index]||next.some((value,item)=>value!==dependencies[index][item])){dependencies[index]=next;effects.push(()=>{cleanups[index]?.();cleanups[index]=effect();});}}}:require(name)});return{render:(name,...args)=>{cursor=0;effectCursor=0;const tree=exports[name](...args);effects.splice(0).forEach(run=>run());return tree;},close:()=>cleanups.forEach(cleanup=>cleanup?.())};}
const flush=()=>new Promise(resolve=>setTimeout(resolve,0));
function response(zip,status='retained-candidate-evidence-present'){const pin=registration.retained_release,source=pin.sources.PA;return{schema_version:'retained-childcare-zip-evidence@1.1.0',available:true,zip5:zip,status,row:status==='retained-candidate-evidence-present'?{zip5:zip,zip4:null,sources:[{publisher_scope:'PA',source_id:source.source_id,reported_state:'PA',candidate_rows:2}]}:null,release_id:pin.release_id,manifest_sha256:pin.manifest_sha256,created_at:pin.created_at,sources:structuredClone(pin.sources),summary:structuredClone(pin.summary),root_view_sha256:pin.root_view_sha256,claims:structuredClone(registration.claims),source_replay_performed:false,semantics:'Source-separated retained candidate rows only. Quality and provenance describe entire source cohorts, not this ZIP. Absent evidence is not zero businesses or invalid USPS membership.'};}

test('client accepts the protected endpoint native registered envelope',async()=>{const value=await readRetainedChildcareZipEvidence({zip5:'00603'}),h=harness(()=>assert.fail());assert.equal(h.render('validChildcareZipEvidence',value,'00603'),true);});
test('validator pins registered metadata and rejects forged or invalid nested evidence',()=>{const h=harness(()=>assert.fail()),valid=response('19103');assert.equal(h.render('validChildcareZipEvidence',valid,'19103'),true);const mutations=[value=>value.release_id=`retained-childcare-zip-evidence-${'f'.repeat(64)}`,value=>value.manifest_sha256='f'.repeat(64),value=>value.root_view_sha256='f'.repeat(64),value=>value.created_at='2026-10-03T04:27:00.196Z',value=>{value.sources.PA.accepted_candidate_rows++;value.summary.accepted_candidate_rows++;value.summary.zip_present_candidate_rows++;},value=>value.row.sources[0].candidate_rows=value.sources.PA.accepted_candidate_rows+1,value=>{value.row.sources=[{publisher_scope:'IA',source_id:value.sources.IA.source_id,reported_state:'IA',candidate_rows:1}];},value=>{value.sources.PA.quality.extra=0;},value=>{value.sources.PA.provenance.extra='x';},value=>{value.sources.PA.source_claims.extra=false;},value=>{value.sources.PA.by_reported_state[0].extra=0;},value=>{value.sources.PA.by_reported_state[0].percent_of_accepted_cohort=99;},value=>{value.row.sources[0].source_id='forged-source';},value=>{value.summary.invalid_zip_buckets=[];value.summary.invalid_zip_candidate_rows=0;value.summary.accepted_candidate_rows=12205;}];for(const mutate of mutations){const bad=structuredClone(valid);mutate(bad);assert.equal(h.render('validChildcareZipEvidence',bad,'19103'),false);}});
test('panel renders source-separated rows, lineage, quality and required limitations',()=>{const h=harness(()=>assert.fail()),tree=h.render('RetainedChildcareZipPanel',{view:response('19103')}),value=text(tree);assert.match(value,/Publisher cohortReported stateCandidate rowsCohort quality and lineage/);assert.match(value,/PApa-dhs-childcare-centersPA2/);assert.match(value,/cohort rows have ZIP5Observed/);for(const phrase of ['not unique businesses','verified physical sites','current operations','USPS ZIP validity','completeness measure'])assert.match(value,new RegExp(phrase));assert.equal(tree.props.style.minWidth,0);});
test('absent, unavailable and malformed remain distinct and never infer zero',async()=>{const absent=response('99999','absent-from-retained-candidate-evidence'),hAbsent=harness(()=>Promise.resolve(absent));hAbsent.render('RetainedChildcareZipLoader',{zip:'99999',attempt:0});await flush();const absentTree=hAbsent.render('RetainedChildcareZipLoader',{zip:'99999',attempt:0});assert.equal(absentTree.type.name,'RetainedChildcareZipPanel');assert.match(text(hAbsent.render('RetainedChildcareZipPanel',{view:absentTree.props.view})),/absence from this retained evidence only—not zero childcare businesses/);const hUnavailable=harness(()=>Promise.reject(Error('offline')));hUnavailable.render('RetainedChildcareZipLoader',{zip:'99998',attempt:0});await flush();assert.match(text(hUnavailable.render('RetainedChildcareZipLoader',{zip:'99998',attempt:0})),/evidence is unavailable.*Absence was not established/);const malformed=response('99997');malformed.claims.physical_site_count=1;const hMalformed=harness(()=>Promise.resolve(malformed));hMalformed.render('RetainedChildcareZipLoader',{zip:'99997',attempt:0});await flush();assert.match(text(hMalformed.render('RetainedChildcareZipLoader',{zip:'99997',attempt:0})),/malformed or unregistered contract.*No evidence state was accepted/);});
test('loader aborts stale exact-ZIP request and ignores its late response',async()=>{const pending=[],h=harness((url,{signal})=>new Promise(resolve=>pending.push({url,signal,resolve})));h.render('RetainedChildcareZipLoader',{zip:'19103',attempt:0});h.render('RetainedChildcareZipLoader',{zip:'00603',attempt:0});assert.equal(pending[0].signal.aborted,true);assert.match(pending[1].url,/zip=00603$/);pending[1].resolve(response('00603'));await flush();let tree=h.render('RetainedChildcareZipLoader',{zip:'00603',attempt:0});assert.equal(tree.type.name,'RetainedChildcareZipPanel');assert.equal(tree.props.view.zip5,'00603');pending[0].resolve(response('19103'));await flush();tree=h.render('RetainedChildcareZipLoader',{zip:'00603',attempt:0});assert.equal(tree.props.view.zip5,'00603');h.close();});
