import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
const require=createRequire(import.meta.url),code=await readFile(new URL('../app/workspace-views.tsx',import.meta.url),'utf8');
const nodes=t=>!t||typeof t!=='object'?[]:Array.isArray(t)?t.flatMap(nodes):[t,...nodes(t.props?.children)];
const text=t=>t==null||typeof t==='boolean'?'':typeof t!=='object'?String(t):Array.isArray(t)?t.map(text).join(''):text(t.props?.children);
function harness(request,sourceCode=code){const values=[],effects=[],cleanup=[];let cursor=0,first=true;const exports={},focused=[];runInNewContext(ts.transpileModule(sourceCode,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,AbortController,URLSearchParams,document:{getElementById:id=>({focus:()=>focused.push(id)})},require:name=>name==='./runner-client'?{runnerJson:request}:name==='./business-intelligence'?{StateAvailabilityChoropleth:()=>null}:name.startsWith('./census-')?{default:()=>null}:name.startsWith('./')?{}:name==='react'?{useMemo:fn=>fn(),useState:initial=>{const n=cursor++;if(!(n in values))values[n]=initial;return[values[n],v=>values[n]=v];},useEffect:effect=>{if(first)effects.push(effect);}}:require(name)});return{focused,render:(name,props={})=>{cursor=0;const tree=exports[name](props);if(first){first=false;effects.forEach(effect=>cleanup.push(effect()));}return tree;},close:()=>cleanup.forEach(fn=>fn?.())};}
const flush=()=>new Promise(resolve=>setTimeout(resolve,0));
test('state choropleth uses scoped matrix availability only, hatches null and preserves browser wheel zoom',async()=>{const mapCode=await readFile(new URL('../app/business-intelligence.tsx',import.meta.url),'utf8');const h=harness(async()=>({available:true,features:['AK','DC'].map((code,index)=>({geometry:{type:'Polygon',coordinates:[[[-100,40],[-99,40],[-99,41],[-100,40]]]},properties:{geoid:String(index),postal_abbreviation:code,name:code,heat_value:999999,business_count:999999}}))}),mapCode);let selected;const props={rows:[{code:'AK',name:'Alaska',available:0,measured:2,unmeasured:1,percent:0},{code:'DC',name:'District',available:0,measured:0,unmeasured:3,percent:null}],selected:'',categoryLabel:'Health care',onSelect:code=>selected=code};h.render('StateAvailabilityChoropleth',props);await flush();const tree=h.render('StateAvailabilityChoropleth',props),paths=nodes(tree).filter(node=>node.type==='path'&&node.props.role==='button');assert.equal(paths.length,2);assert.match(paths[0].props['aria-label'],/Health care: 0.0% dataset availability/);assert.match(nodes(tree).find(node=>node.type==='svg').props['aria-label'],/Health care dataset availability/);assert.match(paths[1].props.fill,/availability-unmeasured/);assert.doesNotMatch(paths[0].props['aria-label'],/999999/);assert.equal(nodes(tree).find(node=>node.type==='svg').props.onWheel,undefined);paths[1].props.onKeyDown({key:'Enter',preventDefault(){}});assert.equal(selected,'DC');h.close();});
test('primary tabs expose selected state and arrow Home End keyboard navigation',()=>{let selected;const h=harness(()=>assert.fail()),tree=h.render('WorkspaceTabs',{value:'Coverage',onChange:value=>selected=value}),tabs=nodes(tree).filter(n=>n.props?.role==='tab');assert.equal(tabs.length,7);assert.equal(tabs[0].props['aria-selected'],true);for(const[key,index]of [['ArrowLeft',6],['ArrowRight',1],['End',6],['Home',0]]){let prevented=false;tabs[0].props.onKeyDown({key,preventDefault:()=>prevented=true});assert.equal(prevented,true);assert.equal(selected,tabs[index].props.children);assert.equal(h.focused.at(-1),`workspace-tab-${index}`);}});
test('coverage exposes category scope and differentiates zero null and missing evidence',async()=>{let signal;const h=harness(async(url,options)=>{assert.match(url,/goal-completion\?category=general-business/);signal=options.signal;return{available:true,release_id:'fixture-release',denominator:{version:'fixture-v7'},categories:['general-business','health-care'],jurisdictions:[{code:'AK',name:'Alaska',available:0,measured:2,unmeasured:1,denominator:3,percent:0},{code:'DC',name:'District of Columbia',available:0,measured:0,unmeasured:3,denominator:3,percent:null}],selected:null};});h.render('CoverageWorkspace');await flush();const tree=h.render('CoverageWorkspace'),value=text(tree),selector=nodes(tree).find(n=>n.props?.['aria-label']==='Coverage category');assert.deepEqual(nodes(selector).filter(n=>n.type==='option').map(n=>text(n)),['Broad state organization layer','Health care']);assert.match(value,/Broad state organization layer availability/);assert.match(value,/0\.0%/);assert.match(value,/Unmeasured/);assert.match(value,/fixture-v7/);assert.match(value,/not completeness of all businesses/);assert.match(value,/3 unmeasured/);assert.match(value,/100% availability applies only to the selected category/);assert.equal(nodes(tree).filter(n=>n.props?.['aria-pressed']!==undefined).length,2);h.close();assert.equal(signal.aborted,true);});
test('unavailable coverage and unmounted late reads cannot display success counts',async()=>{let resolve;const h=harness(()=>new Promise(r=>resolve=r));h.render('CoverageWorkspace');h.close();resolve({available:true,jurisdictions:[{code:'XX'}]});await flush();assert.match(text(h.render('CoverageWorkspace')),/Verifying/);const missing=harness(async()=>({available:false,status:'missing-enrollment'}));missing.render('CoverageWorkspace');await flush();assert.match(text(missing.render('CoverageWorkspace')),/Completion is unmeasured/);});
test('ZIP economics explicitly withholds unsupported GDP and demographic allocations',()=>{const h=harness(()=>assert.fail('no request before valid ZIP')),tree=h.render('ZipEconomyWorkspace'),value=text(tree);assert.match(value,/Unavailable — no governed model/);assert.match(value,/explicitly prohibits ZIP\/ZCTA allocation/);assert.match(value,/not output or GDP weights/);assert.match(value,/Race: unavailable/);const select=nodes(tree).find(n=>n.props?.['aria-label']==='Demographic dimension');assert.deepEqual(nodes(select).filter(n=>n.type==='option').map(n=>text(n)),['Race','Lineage / ancestry','Sex','Age']);select.props.onChange({target:{value:'Age'}});assert.match(text(h.render('ZipEconomyWorkspace')),/Age: unavailable/);});
test('page preserves functional panels behind tabs and keeps text size global',async()=>{const page=await readFile(new URL('../app/page.tsx',import.meta.url),'utf8');assert.match(page,/useState<WorkspaceTab>\('Coverage'\)/);assert.match(page,/<TextSizeControl \/>/);assert.match(page,/hidden=\{workspaceTab!=='Jobs'\}/);for(const component of ['BusinessIntelligence','DataOperations','ConnectorCatalog','BenchmarkReview','CoverageExplorer'])assert.match(page,new RegExp(`<${component}\\s*\\/>`));assert.doesNotMatch(page,/href="#(?:queue|activity|coverage|business-intelligence|data-operations)"/);});
