import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {publishZctaDemographicInputReadiness as publish, validateZctaDemographicInputReadinessRow as validate, verifyZctaDemographicInputReadiness as verify} from './zcta-demographic-input-readiness.mjs';

const APP=path.resolve(import.meta.dirname,'..');
const SOURCE_RELEASE='us-census-geography-20260830-132803990Z-3629abc0';
const SOURCE_DIR=path.join(APP,'data/geography/releases',SOURCE_RELEASE);
const hash=(value)=>createHash('sha256').update(value).digest('hex');
const bytes=(value)=>Buffer.from(`${JSON.stringify(value)}\n`);
async function fixture(t){await fs.mkdir(path.join(APP,'tmp'),{recursive:true});const root=await fs.mkdtemp(path.join(APP,'tmp/zcta-demographic-readiness-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const destination=path.join(root,'data/geography/releases',SOURCE_RELEASE);await fs.mkdir(path.join(destination,'derived/index'),{recursive:true});await fs.copyFile(path.join(SOURCE_DIR,'manifest.json'),path.join(destination,'manifest.json'));await fs.copyFile(path.join(SOURCE_DIR,'derived/index/zctas.jsonl'),path.join(destination,'derived/index/zctas.jsonl'));await fs.mkdir(path.join(root,'config'),{recursive:true});await fs.copyFile(path.join(APP,'config/zcta-demographic-input-readiness.json'),path.join(root,'config/zcta-demographic-input-readiness.json'));return root;}

const row={schema_version:'1.0.0',zcta:'00601',geography_release_id:'geo',population_2020:17242,housing_units_2020:7605,availability:{population_2020:true,housing_units_2020:true,race:false,ancestry_lineage:false,sex:false,age:false},status:'partial-input-readiness',claims:{usps_zip_code:false,demographic_percentages:false,gdp:false}};
test('rows retain direct totals and explicit unavailable slices',()=>assert.equal(validate(row),row));
test('unavailable slices cannot be represented as values or claims',()=>{assert.throws(()=>validate({...row,availability:{...row.availability,race:true}}));assert.throws(()=>validate({...row,race:0}));assert.throws(()=>validate({...row,claims:{...row.claims,gdp:true}}));});
test('publish and independent replay conserve the exact registered cohort',async(t)=>{const root=await fixture(t);const result=await publish({root});assert.equal(result.record_count,33791);assert.equal(result.current_pointer_written,false);assert.deepEqual((await fs.readdir(path.join(root,'data/zcta-demographic-input-readiness'))).sort(),['.locks','.staging','releases']);assert.equal((await verify(path.join(result.directory,'manifest.json'),{root})).verified,true);});
test('tamper, rehashed tamper, extra inventory, and output hardlinks fail closed',async(t)=>{for(const mode of ['tamper','rehashed','extra','hardlink'])await t.test(mode,async(t)=>{const root=await fixture(t);const result=await publish({root});const file=path.join(result.directory,'zcta-demographic-input-readiness.jsonl');if(mode==='extra')await fs.writeFile(path.join(result.directory,'extra'),'x');else if(mode==='hardlink')await fs.link(file,path.join(root,'artifact-alias'));else{const raw=await fs.readFile(file);raw[100]=raw[100]===48?49:48;await fs.writeFile(file,raw);if(mode==='rehashed'){const mf=path.join(result.directory,'manifest.json');const m=JSON.parse(await fs.readFile(mf));m.artifacts[0].sha256=hash(raw);const {release_id,...body}=m;void release_id;m.release_id=`zcta-demographic-input-readiness-${hash(JSON.stringify(body))}`;await fs.writeFile(mf,bytes(m));const renamed=path.join(path.dirname(result.directory),m.release_id);await fs.rename(result.directory,renamed);result.directory=renamed;}}await assert.rejects(verify(path.join(result.directory,'manifest.json'),{root}));});});
test('source hardlinks, path escape, arbitrary timestamps, and pre-cancellation fail closed',async(t)=>{const root=await fixture(t);const source=path.join(root,'data/geography/releases',SOURCE_RELEASE,'derived/index/zctas.jsonl');await fs.link(source,path.join(root,'source-alias'));await assert.rejects(publish({root}),/unsafe source artifact identity/);await fs.rm(path.join(root,'source-alias'));await assert.rejects(verify(path.join(root,'..','outside','manifest.json'),{root}));await assert.rejects(publish({root,createdAt:'2000-01-01T00:00:00.000Z'}),/createdAt override/);const controller=new AbortController();controller.abort();await assert.rejects(publish({root,signal:controller.signal}),{name:'AbortError'});});
test('source and output symlinks fail closed',async(t)=>{const root=await fixture(t);const source=path.join(root,'data/geography/releases',SOURCE_RELEASE,'derived/index/zctas.jsonl');const sourceCopy=path.join(root,'source-copy.jsonl');await fs.copyFile(source,sourceCopy);await fs.rm(source);try{await fs.symlink(sourceCopy,source);}catch(error){if(error.code==='EPERM'){t.skip('host does not grant symlink creation');return;}throw error;}await assert.rejects(publish({root}),/unsafe source artifact identity/);await fs.rm(source);await fs.copyFile(sourceCopy,source);const result=await publish({root});const output=path.join(result.directory,'zcta-demographic-input-readiness.jsonl');const outputCopy=path.join(root,'output-copy.jsonl');await fs.copyFile(output,outputCopy);await fs.rm(output);await fs.symlink(outputCopy,output);await assert.rejects(verify(path.join(result.directory,'manifest.json'),{root}),/unsafe artifact identity/);});
test('source and output identity drift during reads fail closed',async(t)=>{const root=await fixture(t);const source=path.join(root,'data/geography/releases',SOURCE_RELEASE,'derived/index/zctas.jsonl');let timer=setInterval(()=>fs.utimes(source,new Date(),new Date()).catch(()=>{}),1);try{await assert.rejects(publish({root}),/source artifact changed during read/);}finally{clearInterval(timer);}const result=await publish({root});const output=path.join(result.directory,'zcta-demographic-input-readiness.jsonl');timer=setInterval(()=>fs.utimes(output,new Date(),new Date()).catch(()=>{}),1);try{await assert.rejects(verify(path.join(result.directory,'manifest.json'),{root}),/artifact changed during read/);}finally{clearInterval(timer);}});
test('mid-read cancellation leaves no publication or staging debris',async(t)=>{const root=await fixture(t);const controller=new AbortController();setTimeout(()=>controller.abort(),5);await assert.rejects(publish({root,signal:controller.signal}),{name:'AbortError'});assert.equal(await fs.stat(path.join(root,'data/zcta-demographic-input-readiness')).then(()=>true,error=>error.code==='ENOENT'?false:Promise.reject(error)),false);});
test('concurrent builders reject competing ownership and leave no staging debris',async(t)=>{const root=await fixture(t);const results=await Promise.allSettled([publish({root}),publish({root})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected').length,1);assert.deepEqual(await fs.readdir(path.join(root,'data/zcta-demographic-input-readiness/.staging')),[]);assert.deepEqual(await fs.readdir(path.join(root,'data/zcta-demographic-input-readiness/.locks')),[]);});
