import test from "node:test";
import assert from "node:assert/strict";
import { cp, link, lstat, mkdir, mkdtemp, readFile, readdir, rename, rm, symlink, unlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { APP_ROOT } from "./paths.mjs";
import { buildZipDenominatorGapCohort, deriveZipDenominatorGapCohort, verifyZipDenominatorGapCohort } from "./zip-denominator-gap-cohort.mjs";
const moduleUrl=new URL("./zip-denominator-gap-cohort.mjs",import.meta.url),moduleSource=(await readFile(moduleUrl,"utf8")).replace(/from "(\.\/[^\"]+)"/g,(_,p)=>`from "${new URL(p,moduleUrl).href}"`).replace('if(hooks&&root===APP_ROOT)fail("test hooks require isolated root");',''),zipCore=await import(`data:text/javascript;base64,${Buffer.from(moduleSource).toString("base64")}`);

test("registered release verifies exact conservation and claim boundaries", async()=>{
 const registration=JSON.parse(await readFile(path.join(APP_ROOT,"config/datasets/zip-denominator-gap-cohort.json"))),result=await verifyZipDenominatorGapCohort(path.join(APP_ROOT,registration.retained_release.manifest));
 assert.equal(result.manifest_sha256,registration.retained_release.manifest_sha256);assert.deepEqual(result.counts,{rows:48194,"same-code-census-zcta":33791,"source-contributed-outside-zcta":14361,"denominator-only-outside-zcta":41,"explicit-placeholder":1,production_only_vs_postal_candidate:4});assert.equal(result.claims.authoritative_current_usps_zip_denominator,null);assert.equal(result.claims.business_count,null);assert.equal(result.claims.production_enrollment,false);
});

test("derivation rejects classification drift",()=>assert.throws(()=>deriveZipDenominatorGapCohort({cohorts:[],comparison:{}},{},new Date().toISOString()),/rejected/));

test("pre-cancellation and output escape fail before publication",async()=>{
 await assert.rejects(buildZipDenominatorGapCohort({signal:AbortSignal.abort()}),{name:"AbortError"});
 await assert.rejects(buildZipDenominatorGapCohort({outputRoot:path.join(os.tmpdir(),"zip-gap-escape")}),/escapes repository data/);
});

test("verifier rejects tamper and closed-inventory violations",async t=>{
 const registration=JSON.parse(await readFile(path.join(APP_ROOT,"config/datasets/zip-denominator-gap-cohort.json"))),source=path.dirname(path.join(APP_ROOT,registration.retained_release.manifest));
 for(const mode of ["summary","rows","manifest","extra","missing","hardlink","manifest-hardlink","rehashed"]){const parent=await mkdtemp(path.join(APP_ROOT,"data",`${mode}-gap-test-`)),directory=path.join(parent,registration.retained_release.release_id);await cp(source,directory,{recursive:true});t.after(()=>rm(parent,{recursive:true,force:true}));if(mode==="summary")await writeFile(path.join(directory,"summary.json"),"{}\n");if(mode==="rows")await writeFile(path.join(directory,"cohort.jsonl"),"{}\n");if(mode==="manifest")await writeFile(path.join(directory,"manifest.json"),"{}\n");if(mode==="extra")await writeFile(path.join(directory,"extra"),"");if(mode==="missing")await unlink(path.join(directory,"summary.json"));if(mode==="hardlink")await link(path.join(directory,"cohort.jsonl"),path.join(parent,"linked"));if(mode==="manifest-hardlink")await link(path.join(directory,"manifest.json"),path.join(parent,"manifest-linked"));if(mode==="rehashed"){const f=path.join(directory,"summary.json"),raw=Buffer.from("{}\n"),m=JSON.parse(await readFile(path.join(directory,"manifest.json")));await writeFile(f,raw);m.artifacts[0].bytes=raw.length;m.artifacts[0].sha256=(await import("node:crypto")).createHash("sha256").update(raw).digest("hex");await writeFile(path.join(directory,"manifest.json"),`${JSON.stringify(m,null,2)}\n`);}await assert.rejects(verifyZipDenominatorGapCohort(path.join(directory,"manifest.json")),/rejected|Unexpected|ENOENT/);}
});
test("rehashed backdated, future, noncanonical and release-ID clock mutations fail",async t=>{const crypto=await import("node:crypto"),digest=b=>crypto.createHash("sha256").update(b).digest("hex"),registration=JSON.parse(await readFile(path.join(APP_ROOT,"config/datasets/zip-denominator-gap-cohort.json"))),source=path.dirname(path.join(APP_ROOT,registration.retained_release.manifest)),releases=path.join(APP_ROOT,"data/zip-denominator-gap-cohort/releases");for(const [mode,stamp]of [["backdated","2020-01-01T00:00:00.000Z"],["future","2099-01-01T00:00:00.000Z"],["noncanonical","2026-10-03T07:22:43Z"],["release-id-mismatch","2026-10-03T07:22:43.230Z"]]){const temp=await mkdtemp(path.join(releases,".clock-test-"));await cp(source,temp,{recursive:true});let summary=JSON.parse(await readFile(path.join(temp,"summary.json"))),manifest=JSON.parse(await readFile(path.join(temp,"manifest.json")));summary.created_at=stamp;const summaryBytes=Buffer.from(`${JSON.stringify(summary,null,2)}\n`),rowBytes=await readFile(path.join(temp,"cohort.jsonl")),content=digest(Buffer.concat([summaryBytes,rowBytes])),releaseId=`zip-denominator-gap-cohort-${stamp.replace(/[^0-9]/g,"").slice(0,17)}-${content.slice(0,12)}`;manifest.created_at=stamp;manifest.artifacts[0].bytes=summaryBytes.length;manifest.artifacts[0].sha256=digest(summaryBytes);manifest.release_id=mode==="release-id-mismatch"?`${releaseId.slice(0,-1)}0`:releaseId;await writeFile(path.join(temp,"summary.json"),summaryBytes);await writeFile(path.join(temp,"manifest.json"),`${JSON.stringify(manifest,null,2)}\n`);const directory=path.join(releases,manifest.release_id);await rename(temp,directory);t.after(()=>rm(directory,{recursive:true,force:true}));await assert.rejects(verifyZipDenominatorGapCohort(path.join(directory,"manifest.json")),/clock|identity|replay|rejected/);}});
test("reparse release ancestry is rejected where supported",async t=>{const registration=JSON.parse(await readFile(path.join(APP_ROOT,"config/datasets/zip-denominator-gap-cohort.json"))),target=path.dirname(path.join(APP_ROOT,registration.retained_release.manifest)),parent=await mkdtemp(path.join(APP_ROOT,"data","reparse-gap-test-")),linked=path.join(parent,registration.retained_release.release_id);t.after(()=>rm(parent,{recursive:true,force:true}));try{await symlink(target,linked,process.platform==="win32"?"junction":"dir");}catch(e){if(["EPERM","EACCES","ENOTSUP"].includes(e.code)){t.skip("host denies links");return;}throw e;}await assert.rejects(verifyZipDenominatorGapCohort(path.join(linked,"manifest.json")),/canonical|escapes/);});
test("mid-read, mid-write and post-rename cancellation are behavioral",async t=>{for(const phase of["afterInputRead","duringWrite","postRename"])await t.test(phase,async()=>{const outputRoot=await mkdtemp(path.join(APP_ROOT,"data","tmp",`zip-gap-${phase}-`)),controller=new AbortController(),hooks={[phase]:()=>controller.abort()};t.after(()=>rm(outputRoot,{recursive:true,force:true}));let error;try{await zipCore.buildZipDenominatorGapCohort({outputRoot,signal:controller.signal,_testHooks:hooks});}catch(e){error=e;}assert.equal(error?.name,"AbortError");if(phase==="postRename")assert.equal(error.inspection_required,true);const releases=path.join(outputRoot,"releases"),entries=await readdir(releases).catch(()=>[]);assert.equal(entries.some(name=>name.includes("staging")||name===".build.lock"),false);});});
test("concurrent contender, replaced lock and cleanup fault preserve ownership",async t=>{await t.test("concurrent",async()=>{const outputRoot=await mkdtemp(path.join(APP_ROOT,"data","tmp","zip-gap-concurrent-"));t.after(()=>rm(outputRoot,{recursive:true,force:true}));let release;const gate=new Promise(resolve=>{release=resolve;});const first=zipCore.buildZipDenominatorGapCohort({outputRoot,_testHooks:{afterLock:()=>gate}});while(!(await lstat(path.join(outputRoot,"releases",".build.lock")).then(()=>true,()=>false)))await new Promise(resolve=>setTimeout(resolve,5));await assert.rejects(zipCore.buildZipDenominatorGapCohort({outputRoot,_testHooks:{}}),/EEXIST/);release();await first;});await t.test("foreign lock",async()=>{const outputRoot=await mkdtemp(path.join(APP_ROOT,"data","tmp","zip-gap-foreign-"));t.after(()=>rm(outputRoot,{recursive:true,force:true}));let replacement;const hooks={afterLock:async({lock})=>{await rename(lock,`${lock}.owned`);await mkdir(lock);replacement=lock;throw Error("primary foreign fault");}};let error;try{await zipCore.buildZipDenominatorGapCohort({outputRoot,_testHooks:hooks});}catch(e){error=e;}assert.match(error.message,/primary foreign fault/);assert.equal(error.inspection_required,true);assert.equal((await lstat(replacement)).isDirectory(),true);});await t.test("cleanup",async()=>{const outputRoot=await mkdtemp(path.join(APP_ROOT,"data","tmp","zip-gap-cleanup-"));t.after(()=>rm(outputRoot,{recursive:true,force:true}));const hooks={duringWrite:()=>{throw Error("primary write fault");},beforeStageCleanup:()=>{throw Error("cleanup fault");}};let error;try{await zipCore.buildZipDenominatorGapCohort({outputRoot,_testHooks:hooks});}catch(e){error=e;}assert.match(error.message,/primary write fault/);assert.equal(error.inspection_required,true);});});
